<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class Broadcasttransaction2200ApplicationJSONData
{
	#[\JMS\Serializer\Annotation\SerializedName('txid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $txid = null;
    
	public function __construct()
	{
		$this->txid = null;
	}
}
