package openapisdk.models.shared;


public enum GoogleChromeManagementV1ThunderboltInfoSecurityLevelEnum {
    THUNDERBOLT_SECURITY_LEVEL_UNSPECIFIED("THUNDERBOLT_SECURITY_LEVEL_UNSPECIFIED"),
    THUNDERBOLT_SECURITY_NONE_LEVEL("THUNDERBOLT_SECURITY_NONE_LEVEL"),
    THUNDERBOLT_SECURITY_USER_LEVEL("THUNDERBOLT_SECURITY_USER_LEVEL"),
    THUNDERBOLT_SECURITY_SECURE_LEVEL("THUNDERBOLT_SECURITY_SECURE_LEVEL"),
    THUNDERBOLT_SECURITY_DP_ONLY_LEVEL("THUNDERBOLT_SECURITY_DP_ONLY_LEVEL"),
    THUNDERBOLT_SECURITY_USB_ONLY_LEVEL("THUNDERBOLT_SECURITY_USB_ONLY_LEVEL"),
    THUNDERBOLT_SECURITY_NO_PCIE_LEVEL("THUNDERBOLT_SECURITY_NO_PCIE_LEVEL");

    public final String value;

    private GoogleChromeManagementV1ThunderboltInfoSecurityLevelEnum(String value) {
        this.value = value;
    }
}
