package shared

type SmartPostHubEnum string

const (
	SmartPostHubEnumNone             SmartPostHubEnum = "none"
	SmartPostHubEnumAllentownPa      SmartPostHubEnum = "allentown_pa"
	SmartPostHubEnumAtlantaGa        SmartPostHubEnum = "atlanta_ga"
	SmartPostHubEnumBaltimoreMd      SmartPostHubEnum = "baltimore_md"
	SmartPostHubEnumCharlotteNc      SmartPostHubEnum = "charlotte_nc"
	SmartPostHubEnumChinoCa          SmartPostHubEnum = "chino_ca"
	SmartPostHubEnumDallasTx         SmartPostHubEnum = "dallas_tx"
	SmartPostHubEnumDenverCo         SmartPostHubEnum = "denver_co"
	SmartPostHubEnumDetroitMi        SmartPostHubEnum = "detroit_mi"
	SmartPostHubEnumEdisonNj         SmartPostHubEnum = "edison_nj"
	SmartPostHubEnumGroveCityOh      SmartPostHubEnum = "grove_city_oh"
	SmartPostHubEnumGroveportOh      SmartPostHubEnum = "groveport_oh"
	SmartPostHubEnumHoustonTx        SmartPostHubEnum = "houston_tx"
	SmartPostHubEnumIndianapolisIn   SmartPostHubEnum = "indianapolis_in"
	SmartPostHubEnumKansasCityKs     SmartPostHubEnum = "kansas_city_ks"
	SmartPostHubEnumLosAngelesCa     SmartPostHubEnum = "los_angeles_ca"
	SmartPostHubEnumMartinsburgWv    SmartPostHubEnum = "martinsburg_wv"
	SmartPostHubEnumMemphisTn        SmartPostHubEnum = "memphis_tn"
	SmartPostHubEnumMinneapolisMn    SmartPostHubEnum = "minneapolis_mn"
	SmartPostHubEnumNewBerlinWi      SmartPostHubEnum = "new_berlin_wi"
	SmartPostHubEnumNorthboroughMa   SmartPostHubEnum = "northborough_ma"
	SmartPostHubEnumOrlandoFl        SmartPostHubEnum = "orlando_fl"
	SmartPostHubEnumPhoneixAz        SmartPostHubEnum = "phoneix_az"
	SmartPostHubEnumPittsburghPa     SmartPostHubEnum = "pittsburgh_pa"
	SmartPostHubEnumRenoNv           SmartPostHubEnum = "reno_nv"
	SmartPostHubEnumSacramentoCa     SmartPostHubEnum = "sacramento_ca"
	SmartPostHubEnumSaltLakeCityUt   SmartPostHubEnum = "salt_lake_city_ut"
	SmartPostHubEnumSeattleWa        SmartPostHubEnum = "seattle_wa"
	SmartPostHubEnumStLouisMo        SmartPostHubEnum = "st_louis_mo"
	SmartPostHubEnumWindsorCt        SmartPostHubEnum = "windsor_ct"
	SmartPostHubEnumNewarkNy         SmartPostHubEnum = "newark_ny"
	SmartPostHubEnumSouthBrunswickNj SmartPostHubEnum = "south_brunswick_nj"
	SmartPostHubEnumScrantonPa       SmartPostHubEnum = "scranton_pa"
	SmartPostHubEnumWheelingIl       SmartPostHubEnum = "wheeling_il"
)
