"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import disableresult as shared_disableresult
from typing import Optional


@dataclasses.dataclass
class PostDisableResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    disable_result: Optional[shared_disableresult.DisableResult] = dataclasses.field(default=None)
    r"""OK - the request has succeeded."""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    