/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class SecuritycenterOrganizationsAssetsListRequest {
    
    public SecuritycenterOrganizationsAssetsListPathParams pathParams;
    public SecuritycenterOrganizationsAssetsListRequest withPathParams(SecuritycenterOrganizationsAssetsListPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    
    public SecuritycenterOrganizationsAssetsListQueryParams queryParams;
    public SecuritycenterOrganizationsAssetsListRequest withQueryParams(SecuritycenterOrganizationsAssetsListQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    
    public SecuritycenterOrganizationsAssetsListSecurity security;
    public SecuritycenterOrganizationsAssetsListRequest withSecurity(SecuritycenterOrganizationsAssetsListSecurity security) {
        this.security = security;
        return this;
    }
    
}
