/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class GetListPathwaysRequest {
    
    public GetListPathwaysQueryParams queryParams;
    public GetListPathwaysRequest withQueryParams(GetListPathwaysQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
