/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Contains details produced as a result of performing known fraudster risk analysis on a speaker.
 */
export class KnownFraudsterRisk extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "GeneratedFraudsterId" })
  generatedFraudsterId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "RiskScore" })
  riskScore: number;
}
