// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListDominantLanguageDetectionJobsResponse - Success
type ListDominantLanguageDetectionJobsResponse struct {
	DominantLanguageDetectionJobPropertiesList []DominantLanguageDetectionJobProperties `json:"DominantLanguageDetectionJobPropertiesList,omitempty"`
	NextToken                                  *string                                  `json:"NextToken,omitempty"`
}
