from .activity_check_repo_is_starred_by_authenticated_user import *
from .activity_delete_repo_subscription import *
from .activity_delete_thread_subscription import *
from .activity_get_feeds import *
from .activity_get_repo_subscription import *
from .activity_get_thread import *
from .activity_get_thread_subscription_for_authenticated_user import *
from .activity_list_events_for_authenticated_user import *
from .activity_list_notifications_for_authenticated_user import *
from .activity_list_org_events_for_authenticated_user import *
from .activity_list_public_events import *
from .activity_list_public_events_for_repo_network import *
from .activity_list_public_events_for_user import *
from .activity_list_public_org_events import *
from .activity_list_received_events_for_user import *
from .activity_list_received_public_events_for_user import *
from .activity_list_repo_events import *
from .activity_list_repo_notifications_for_authenticated_user import *
from .activity_list_repos_starred_by_authenticated_user import *
from .activity_list_repos_starred_by_user import *
from .activity_list_repos_watched_by_user import *
from .activity_list_stargazers_for_repo import *
from .activity_list_watched_repos_for_authenticated_user import *
from .activity_list_watchers_for_repo import *
from .activity_mark_notifications_as_read import *
from .activity_mark_repo_notifications_as_read import *
from .activity_mark_thread_as_read import *
from .activity_set_repo_subscription import *
from .activity_set_thread_subscription import *
from .activity_star_repo_for_authenticated_user import *
from .activity_unstar_repo_for_authenticated_user import *
from .apps_add_repo_to_installation import *
from .apps_check_authorization import *
from .apps_check_token import *
from .apps_create_content_attachment import *
from .apps_create_from_manifest import *
from .apps_create_installation_access_token import *
from .apps_delete_authorization import *
from .apps_delete_installation import *
from .apps_delete_token import *
from .apps_get_authenticated import *
from .apps_get_by_slug import *
from .apps_get_installation import *
from .apps_get_org_installation import *
from .apps_get_repo_installation import *
from .apps_get_user_installation import *
from .apps_list_installation_repos_for_authenticated_user import *
from .apps_list_installations import *
from .apps_list_installations_for_authenticated_user import *
from .apps_list_repos_accessible_to_installation import *
from .apps_remove_repo_from_installation import *
from .apps_reset_authorization import *
from .apps_reset_token import *
from .apps_revoke_authorization_for_application import *
from .apps_revoke_grant_for_application import *
from .apps_revoke_installation_access_token import *
from .checks_create import *
from .checks_create_suite import *
from .checks_get import *
from .checks_get_suite import *
from .checks_list_annotations import *
from .checks_list_for_ref import *
from .checks_list_for_suite import *
from .checks_list_suites_for_ref import *
from .checks_rerequest_suite import *
from .checks_set_suites_preferences import *
from .checks_update import *
from .codes_of_conduct_get_all_codes_of_conduct import *
from .codes_of_conduct_get_conduct_code import *
from .emojis_get import *
from .enterprise_admin_add_authorized_ssh_key import *
from .enterprise_admin_create_enterprise_server_license import *
from .enterprise_admin_create_global_webhook import *
from .enterprise_admin_create_impersonation_o_auth_token import *
from .enterprise_admin_create_org import *
from .enterprise_admin_create_pre_receive_environment import *
from .enterprise_admin_create_pre_receive_hook import *
from .enterprise_admin_create_user import *
from .enterprise_admin_delete_global_webhook import *
from .enterprise_admin_delete_impersonation_o_auth_token import *
from .enterprise_admin_delete_personal_access_token import *
from .enterprise_admin_delete_pre_receive_environment import *
from .enterprise_admin_delete_pre_receive_hook import *
from .enterprise_admin_delete_public_key import *
from .enterprise_admin_delete_user import *
from .enterprise_admin_demote_site_administrator import *
from .enterprise_admin_enable_or_disable_maintenance_mode import *
from .enterprise_admin_get_all_authorized_ssh_keys import *
from .enterprise_admin_get_configuration_status import *
from .enterprise_admin_get_download_status_for_pre_receive_environment import *
from .enterprise_admin_get_global_webhook import *
from .enterprise_admin_get_license_information import *
from .enterprise_admin_get_maintenance_status import *
from .enterprise_admin_get_pre_receive_environment import *
from .enterprise_admin_get_pre_receive_hook import *
from .enterprise_admin_get_pre_receive_hook_for_org import *
from .enterprise_admin_get_pre_receive_hook_for_repo import *
from .enterprise_admin_get_settings import *
from .enterprise_admin_get_type_stats import *
from .enterprise_admin_list_global_webhooks import *
from .enterprise_admin_list_personal_access_tokens import *
from .enterprise_admin_list_pre_receive_environments import *
from .enterprise_admin_list_pre_receive_hooks import *
from .enterprise_admin_list_pre_receive_hooks_for_org import *
from .enterprise_admin_list_pre_receive_hooks_for_repo import *
from .enterprise_admin_list_public_keys import *
from .enterprise_admin_ping_global_webhook import *
from .enterprise_admin_promote_user_to_be_site_administrator import *
from .enterprise_admin_remove_authorized_ssh_key import *
from .enterprise_admin_remove_pre_receive_hook_enforcement_for_org import *
from .enterprise_admin_remove_pre_receive_hook_enforcement_for_repo import *
from .enterprise_admin_set_settings import *
from .enterprise_admin_start_configuration_process import *
from .enterprise_admin_start_pre_receive_environment_download import *
from .enterprise_admin_suspend_user import *
from .enterprise_admin_sync_ldap_mapping_for_team import *
from .enterprise_admin_sync_ldap_mapping_for_user import *
from .enterprise_admin_unsuspend_user import *
from .enterprise_admin_update_global_webhook import *
from .enterprise_admin_update_ldap_mapping_for_team import *
from .enterprise_admin_update_ldap_mapping_for_user import *
from .enterprise_admin_update_org_name import *
from .enterprise_admin_update_pre_receive_environment import *
from .enterprise_admin_update_pre_receive_hook import *
from .enterprise_admin_update_pre_receive_hook_enforcement_for_org import *
from .enterprise_admin_update_pre_receive_hook_enforcement_for_repo import *
from .enterprise_admin_update_username_for_user import *
from .enterprise_admin_upgrade_license import *
from .gists_check_is_starred import *
from .gists_create import *
from .gists_create_comment import *
from .gists_delete import *
from .gists_delete_comment import *
from .gists_fork import *
from .gists_get import *
from .gists_get_comment import *
from .gists_get_revision import *
from .gists_list import *
from .gists_list_comments import *
from .gists_list_commits import *
from .gists_list_for_user import *
from .gists_list_forks import *
from .gists_list_public import *
from .gists_list_starred import *
from .gists_star import *
from .gists_unstar import *
from .gists_update import *
from .gists_update_comment import *
from .git_create_blob import *
from .git_create_commit import *
from .git_create_ref import *
from .git_create_tag import *
from .git_create_tree import *
from .git_delete_ref import *
from .git_get_blob import *
from .git_get_commit import *
from .git_get_ref import *
from .git_get_tag import *
from .git_get_tree import *
from .git_list_matching_refs import *
from .git_update_ref import *
from .gitignore_get_all_templates import *
from .gitignore_get_template import *
from .issues_add_assignees import *
from .issues_add_labels import *
from .issues_check_user_can_be_assigned import *
from .issues_create import *
from .issues_create_comment import *
from .issues_create_label import *
from .issues_create_milestone import *
from .issues_delete_comment import *
from .issues_delete_label import *
from .issues_delete_milestone import *
from .issues_get import *
from .issues_get_comment import *
from .issues_get_event import *
from .issues_get_label import *
from .issues_get_milestone import *
from .issues_list import *
from .issues_list_assignees import *
from .issues_list_comments import *
from .issues_list_comments_for_repo import *
from .issues_list_events import *
from .issues_list_events_for_repo import *
from .issues_list_events_for_timeline import *
from .issues_list_for_authenticated_user import *
from .issues_list_for_org import *
from .issues_list_for_repo import *
from .issues_list_labels_for_milestone import *
from .issues_list_labels_for_repo import *
from .issues_list_labels_on_issue import *
from .issues_list_milestones import *
from .issues_lock import *
from .issues_remove_all_labels import *
from .issues_remove_assignees import *
from .issues_remove_label import *
from .issues_set_labels import *
from .issues_unlock import *
from .issues_update import *
from .issues_update_comment import *
from .issues_update_label import *
from .issues_update_milestone import *
from .licenses_get import *
from .licenses_get_all_commonly_used import *
from .licenses_get_for_repo import *
from .markdown_render import *
from .markdown_render_raw import *
from .meta_get import *
from .meta_get_octocat import *
from .meta_get_zen import *
from .meta_root import *
from .oauth_authorizations_create_authorization import *
from .oauth_authorizations_delete_authorization import *
from .oauth_authorizations_delete_grant import *
from .oauth_authorizations_get_authorization import *
from .oauth_authorizations_get_grant import *
from .oauth_authorizations_get_or_create_authorization_for_app import *
from .oauth_authorizations_get_or_create_authorization_for_app_and_fingerprint import *
from .oauth_authorizations_list_authorizations import *
from .oauth_authorizations_list_grants import *
from .oauth_authorizations_update_authorization import *
from .orgs_check_membership_for_user import *
from .orgs_check_public_membership_for_user import *
from .orgs_convert_member_to_outside_collaborator import *
from .orgs_create_webhook import *
from .orgs_delete_webhook import *
from .orgs_get import *
from .orgs_get_membership_for_authenticated_user import *
from .orgs_get_membership_for_user import *
from .orgs_get_webhook import *
from .orgs_list import *
from .orgs_list_app_installations import *
from .orgs_list_for_authenticated_user import *
from .orgs_list_for_user import *
from .orgs_list_members import *
from .orgs_list_memberships_for_authenticated_user import *
from .orgs_list_outside_collaborators import *
from .orgs_list_public_members import *
from .orgs_list_webhooks import *
from .orgs_ping_webhook import *
from .orgs_remove_member import *
from .orgs_remove_membership_for_user import *
from .orgs_remove_outside_collaborator import *
from .orgs_remove_public_membership_for_authenticated_user import *
from .orgs_set_membership_for_user import *
from .orgs_set_public_membership_for_authenticated_user import *
from .orgs_update import *
from .orgs_update_membership_for_authenticated_user import *
from .orgs_update_webhook import *
from .projects_add_collaborator import *
from .projects_create_card import *
from .projects_create_column import *
from .projects_create_for_authenticated_user import *
from .projects_create_for_org import *
from .projects_create_for_repo import *
from .projects_delete import *
from .projects_delete_card import *
from .projects_delete_column import *
from .projects_get import *
from .projects_get_card import *
from .projects_get_column import *
from .projects_get_permission_for_user import *
from .projects_list_cards import *
from .projects_list_collaborators import *
from .projects_list_columns import *
from .projects_list_for_org import *
from .projects_list_for_repo import *
from .projects_list_for_user import *
from .projects_move_card import *
from .projects_move_column import *
from .projects_remove_collaborator import *
from .projects_update import *
from .projects_update_card import *
from .projects_update_column import *
from .pulls_check_if_merged import *
from .pulls_create import *
from .pulls_create_reply_for_review_comment import *
from .pulls_create_review import *
from .pulls_create_review_comment import *
from .pulls_delete_pending_review import *
from .pulls_delete_review_comment import *
from .pulls_dismiss_review import *
from .pulls_get import *
from .pulls_get_review import *
from .pulls_get_review_comment import *
from .pulls_list import *
from .pulls_list_comments_for_review import *
from .pulls_list_commits import *
from .pulls_list_files import *
from .pulls_list_requested_reviewers import *
from .pulls_list_review_comments import *
from .pulls_list_review_comments_for_repo import *
from .pulls_list_reviews import *
from .pulls_merge import *
from .pulls_remove_requested_reviewers import *
from .pulls_request_reviewers import *
from .pulls_submit_review import *
from .pulls_update import *
from .pulls_update_branch import *
from .pulls_update_review import *
from .pulls_update_review_comment import *
from .rate_limit_get import *
from .reactions_create_for_commit_comment import *
from .reactions_create_for_issue import *
from .reactions_create_for_issue_comment import *
from .reactions_create_for_pull_request_review_comment import *
from .reactions_create_for_team_discussion import *
from .reactions_create_for_team_discussion_comment import *
from .reactions_delete import *
from .reactions_list_for_commit_comment import *
from .reactions_list_for_issue import *
from .reactions_list_for_issue_comment import *
from .reactions_list_for_pull_request_review_comment import *
from .reactions_list_for_team_discussion import *
from .reactions_list_for_team_discussion_comment import *
from .repos_accept_invitation import *
from .repos_add_app_access_restrictions import *
from .repos_add_collaborator import *
from .repos_add_status_check_contexts import *
from .repos_add_team_access_restrictions import *
from .repos_add_user_access_restrictions import *
from .repos_check_collaborator import *
from .repos_compare_commits import *
from .repos_create_commit_comment import *
from .repos_create_commit_signature_protection import *
from .repos_create_commit_status import *
from .repos_create_deploy_key import *
from .repos_create_deployment import *
from .repos_create_deployment_status import *
from .repos_create_for_authenticated_user import *
from .repos_create_fork import *
from .repos_create_in_org import *
from .repos_create_or_update_file_contents import *
from .repos_create_pages_site import *
from .repos_create_release import *
from .repos_create_using_template import *
from .repos_create_webhook import *
from .repos_decline_invitation import *
from .repos_delete import *
from .repos_delete_access_restrictions import *
from .repos_delete_admin_branch_protection import *
from .repos_delete_branch_protection import *
from .repos_delete_commit_comment import *
from .repos_delete_commit_signature_protection import *
from .repos_delete_deploy_key import *
from .repos_delete_file import *
from .repos_delete_invitation import *
from .repos_delete_pages_site import *
from .repos_delete_pull_request_review_protection import *
from .repos_delete_release import *
from .repos_delete_release_asset import *
from .repos_delete_webhook import *
from .repos_download_tarball_archive import *
from .repos_download_zipball_archive import *
from .repos_get import *
from .repos_get_access_restrictions import *
from .repos_get_admin_branch_protection import *
from .repos_get_all_status_check_contexts import *
from .repos_get_all_topics import *
from .repos_get_apps_with_access_to_protected_branch import *
from .repos_get_branch import *
from .repos_get_branch_protection import *
from .repos_get_code_frequency_stats import *
from .repos_get_collaborator_permission_level import *
from .repos_get_combined_status_for_ref import *
from .repos_get_commit import *
from .repos_get_commit_activity_stats import *
from .repos_get_commit_comment import *
from .repos_get_commit_signature_protection import *
from .repos_get_content import *
from .repos_get_contributors_stats import *
from .repos_get_deploy_key import *
from .repos_get_deployment import *
from .repos_get_deployment_status import *
from .repos_get_latest_pages_build import *
from .repos_get_latest_release import *
from .repos_get_pages import *
from .repos_get_pages_build import *
from .repos_get_participation_stats import *
from .repos_get_pull_request_review_protection import *
from .repos_get_punch_card_stats import *
from .repos_get_readme import *
from .repos_get_readme_in_directory import *
from .repos_get_release import *
from .repos_get_release_asset import *
from .repos_get_release_by_tag import *
from .repos_get_status_checks_protection import *
from .repos_get_teams_with_access_to_protected_branch import *
from .repos_get_users_with_access_to_protected_branch import *
from .repos_get_webhook import *
from .repos_list_branches import *
from .repos_list_branches_for_head_commit import *
from .repos_list_collaborators import *
from .repos_list_comments_for_commit import *
from .repos_list_commit_comments_for_repo import *
from .repos_list_commit_statuses_for_ref import *
from .repos_list_commits import *
from .repos_list_contributors import *
from .repos_list_deploy_keys import *
from .repos_list_deployment_statuses import *
from .repos_list_deployments import *
from .repos_list_for_authenticated_user import *
from .repos_list_for_org import *
from .repos_list_for_user import *
from .repos_list_forks import *
from .repos_list_invitations import *
from .repos_list_invitations_for_authenticated_user import *
from .repos_list_languages import *
from .repos_list_pages_builds import *
from .repos_list_public import *
from .repos_list_pull_requests_associated_with_commit import *
from .repos_list_release_assets import *
from .repos_list_releases import *
from .repos_list_tags import *
from .repos_list_teams import *
from .repos_list_webhooks import *
from .repos_merge import *
from .repos_ping_webhook import *
from .repos_remove_app_access_restrictions import *
from .repos_remove_collaborator import *
from .repos_remove_status_check_contexts import *
from .repos_remove_status_check_protection import *
from .repos_remove_team_access_restrictions import *
from .repos_remove_user_access_restrictions import *
from .repos_replace_all_topics import *
from .repos_request_pages_build import *
from .repos_set_admin_branch_protection import *
from .repos_set_app_access_restrictions import *
from .repos_set_status_check_contexts import *
from .repos_set_team_access_restrictions import *
from .repos_set_user_access_restrictions import *
from .repos_test_push_webhook import *
from .repos_transfer import *
from .repos_update import *
from .repos_update_branch_protection import *
from .repos_update_commit_comment import *
from .repos_update_information_about_pages_site import *
from .repos_update_invitation import *
from .repos_update_pull_request_review_protection import *
from .repos_update_release import *
from .repos_update_release_asset import *
from .repos_update_status_check_protection import *
from .repos_update_webhook import *
from .repos_upload_release_asset import *
from .search_code import *
from .search_commits import *
from .search_issues_and_pull_requests import *
from .search_labels import *
from .search_repos import *
from .search_topics import *
from .search_users import *
from .teams_add_member_legacy import *
from .teams_add_or_update_membership_for_user import *
from .teams_add_or_update_project_permissions import *
from .teams_add_or_update_repo_permissions import *
from .teams_check_permissions_for_project import *
from .teams_check_permissions_for_repo import *
from .teams_create import *
from .teams_create_discussion import *
from .teams_create_discussion_comment import *
from .teams_delete import *
from .teams_delete_discussion import *
from .teams_delete_discussion_comment import *
from .teams_get import *
from .teams_get_by_name import *
from .teams_get_discussion import *
from .teams_get_discussion_comment import *
from .teams_get_member_legacy import *
from .teams_get_membership_for_user import *
from .teams_list import *
from .teams_list_child import *
from .teams_list_discussion_comments import *
from .teams_list_discussions import *
from .teams_list_for_authenticated_user import *
from .teams_list_members import *
from .teams_list_projects import *
from .teams_list_repos import *
from .teams_remove_member_legacy import *
from .teams_remove_membership_for_user import *
from .teams_remove_project import *
from .teams_remove_repo import *
from .teams_update import *
from .teams_update_discussion import *
from .teams_update_discussion_comment import *
from .users_add_email_for_authenticated import *
from .users_check_following_for_user import *
from .users_check_person_is_followed_by_authenticated import *
from .users_create_gpg_key_for_authenticated import *
from .users_create_public_ssh_key_for_authenticated import *
from .users_delete_email_for_authenticated import *
from .users_delete_gpg_key_for_authenticated import *
from .users_delete_public_ssh_key_for_authenticated import *
from .users_follow import *
from .users_get_authenticated import *
from .users_get_by_username import *
from .users_get_context_for_user import *
from .users_get_gpg_key_for_authenticated import *
from .users_get_public_ssh_key_for_authenticated import *
from .users_list import *
from .users_list_emails_for_authenticated import *
from .users_list_followed_by_authenticated import *
from .users_list_followers_for_authenticated_user import *
from .users_list_followers_for_user import *
from .users_list_following_for_user import *
from .users_list_gpg_keys_for_authenticated import *
from .users_list_gpg_keys_for_user import *
from .users_list_public_emails_for_authenticated import *
from .users_list_public_keys_for_user import *
from .users_list_public_ssh_keys_for_authenticated import *
from .users_unfollow import *
from .users_update_authenticated import *

__all__ = ["ActivityCheckRepoIsStarredByAuthenticatedUserPathParams","ActivityCheckRepoIsStarredByAuthenticatedUserRequest","ActivityCheckRepoIsStarredByAuthenticatedUserResponse","ActivityDeleteRepoSubscriptionPathParams","ActivityDeleteRepoSubscriptionRequest","ActivityDeleteRepoSubscriptionResponse","ActivityDeleteThreadSubscriptionPathParams","ActivityDeleteThreadSubscriptionRequest","ActivityDeleteThreadSubscriptionResponse","ActivityGetFeedsResponse","ActivityGetRepoSubscriptionPathParams","ActivityGetRepoSubscriptionRequest","ActivityGetRepoSubscriptionResponse","ActivityGetThreadPathParams","ActivityGetThreadRequest","ActivityGetThreadResponse","ActivityGetThreadSubscriptionForAuthenticatedUserPathParams","ActivityGetThreadSubscriptionForAuthenticatedUserRequest","ActivityGetThreadSubscriptionForAuthenticatedUserResponse","ActivityListEventsForAuthenticatedUserPathParams","ActivityListEventsForAuthenticatedUserQueryParams","ActivityListEventsForAuthenticatedUserRequest","ActivityListEventsForAuthenticatedUserResponse","ActivityListNotificationsForAuthenticatedUserQueryParams","ActivityListNotificationsForAuthenticatedUserRequest","ActivityListNotificationsForAuthenticatedUserResponse","ActivityListOrgEventsForAuthenticatedUserPathParams","ActivityListOrgEventsForAuthenticatedUserQueryParams","ActivityListOrgEventsForAuthenticatedUserRequest","ActivityListOrgEventsForAuthenticatedUserResponse","ActivityListPublicEventsQueryParams","ActivityListPublicEventsRequest","ActivityListPublicEvents503ApplicationJSON","ActivityListPublicEventsResponse","ActivityListPublicEventsForRepoNetworkPathParams","ActivityListPublicEventsForRepoNetworkQueryParams","ActivityListPublicEventsForRepoNetworkRequest","ActivityListPublicEventsForRepoNetworkResponse","ActivityListPublicEventsForUserPathParams","ActivityListPublicEventsForUserQueryParams","ActivityListPublicEventsForUserRequest","ActivityListPublicEventsForUserResponse","ActivityListPublicOrgEventsPathParams","ActivityListPublicOrgEventsQueryParams","ActivityListPublicOrgEventsRequest","ActivityListPublicOrgEventsResponse","ActivityListReceivedEventsForUserPathParams","ActivityListReceivedEventsForUserQueryParams","ActivityListReceivedEventsForUserRequest","ActivityListReceivedEventsForUserResponse","ActivityListReceivedPublicEventsForUserPathParams","ActivityListReceivedPublicEventsForUserQueryParams","ActivityListReceivedPublicEventsForUserRequest","ActivityListReceivedPublicEventsForUserResponse","ActivityListRepoEventsPathParams","ActivityListRepoEventsQueryParams","ActivityListRepoEventsRequest","ActivityListRepoEventsResponse","ActivityListRepoNotificationsForAuthenticatedUserPathParams","ActivityListRepoNotificationsForAuthenticatedUserQueryParams","ActivityListRepoNotificationsForAuthenticatedUserRequest","ActivityListRepoNotificationsForAuthenticatedUserResponse","ActivityListReposStarredByAuthenticatedUserQueryParams","ActivityListReposStarredByAuthenticatedUserRequest","ActivityListReposStarredByAuthenticatedUserResponse","ActivityListReposStarredByUserPathParams","ActivityListReposStarredByUserQueryParams","ActivityListReposStarredByUserRequest","ActivityListReposStarredByUserResponse","ActivityListReposWatchedByUserPathParams","ActivityListReposWatchedByUserQueryParams","ActivityListReposWatchedByUserRequest","ActivityListReposWatchedByUserResponse","ActivityListStargazersForRepoPathParams","ActivityListStargazersForRepoQueryParams","ActivityListStargazersForRepoRequest","ActivityListStargazersForRepoResponse","ActivityListWatchedReposForAuthenticatedUserQueryParams","ActivityListWatchedReposForAuthenticatedUserRequest","ActivityListWatchedReposForAuthenticatedUserResponse","ActivityListWatchersForRepoPathParams","ActivityListWatchersForRepoQueryParams","ActivityListWatchersForRepoRequest","ActivityListWatchersForRepoResponse","ActivityMarkNotificationsAsReadRequestBody","ActivityMarkNotificationsAsReadRequest","ActivityMarkNotificationsAsRead202ApplicationJSON","ActivityMarkNotificationsAsReadResponse","ActivityMarkRepoNotificationsAsReadPathParams","ActivityMarkRepoNotificationsAsReadRequestBody","ActivityMarkRepoNotificationsAsReadRequest","ActivityMarkRepoNotificationsAsRead202ApplicationJSON","ActivityMarkRepoNotificationsAsReadResponse","ActivityMarkThreadAsReadPathParams","ActivityMarkThreadAsReadRequest","ActivityMarkThreadAsReadResponse","ActivitySetRepoSubscriptionPathParams","ActivitySetRepoSubscriptionRequestBody","ActivitySetRepoSubscriptionRequest","ActivitySetRepoSubscriptionResponse","ActivitySetThreadSubscriptionPathParams","ActivitySetThreadSubscriptionRequestBody","ActivitySetThreadSubscriptionRequest","ActivitySetThreadSubscriptionResponse","ActivityStarRepoForAuthenticatedUserPathParams","ActivityStarRepoForAuthenticatedUserRequest","ActivityStarRepoForAuthenticatedUserResponse","ActivityUnstarRepoForAuthenticatedUserPathParams","ActivityUnstarRepoForAuthenticatedUserRequest","ActivityUnstarRepoForAuthenticatedUserResponse","AppsAddRepoToInstallationPathParams","AppsAddRepoToInstallationRequest","AppsAddRepoToInstallationResponse","AppsCheckAuthorizationPathParams","AppsCheckAuthorizationRequest","AppsCheckAuthorizationAuthorizationApp","AppsCheckAuthorizationAuthorizationScopedInstallationRepositorySelectionEnum","AppsCheckAuthorizationAuthorizationScopedInstallation","AppsCheckAuthorizationAuthorizationSimpleUser","AppsCheckAuthorizationAuthorization","AppsCheckAuthorizationResponse","AppsCheckTokenPathParams","AppsCheckTokenRequestBody","AppsCheckTokenRequest","AppsCheckTokenResponse","AppsCreateContentAttachmentPathParams","AppsCreateContentAttachmentRequestBody","AppsCreateContentAttachmentRequest","AppsCreateContentAttachment415ApplicationJSON","AppsCreateContentAttachmentResponse","AppsCreateFromManifestPathParams","AppsCreateFromManifestRequest","AppsCreateFromManifestResponse","AppsCreateInstallationAccessTokenPathParams","AppsCreateInstallationAccessTokenHeaders","AppsCreateInstallationAccessTokenRequestBody","AppsCreateInstallationAccessTokenRequest","AppsCreateInstallationAccessToken415ApplicationJSON","AppsCreateInstallationAccessTokenResponse","AppsDeleteAuthorizationPathParams","AppsDeleteAuthorizationRequestBody","AppsDeleteAuthorizationRequest","AppsDeleteAuthorizationResponse","AppsDeleteInstallationPathParams","AppsDeleteInstallationHeaders","AppsDeleteInstallationRequest","AppsDeleteInstallationResponse","AppsDeleteTokenPathParams","AppsDeleteTokenRequestBody","AppsDeleteTokenRequest","AppsDeleteTokenResponse","AppsGetAuthenticatedResponse","AppsGetBySlugPathParams","AppsGetBySlugRequest","AppsGetBySlug415ApplicationJSON","AppsGetBySlugResponse","AppsGetInstallationPathParams","AppsGetInstallationHeaders","AppsGetInstallationRequest","AppsGetInstallation415ApplicationJSON","AppsGetInstallationResponse","AppsGetOrgInstallationPathParams","AppsGetOrgInstallationHeaders","AppsGetOrgInstallationRequest","AppsGetOrgInstallationResponse","AppsGetRepoInstallationPathParams","AppsGetRepoInstallationHeaders","AppsGetRepoInstallationRequest","AppsGetRepoInstallationResponse","AppsGetUserInstallationPathParams","AppsGetUserInstallationHeaders","AppsGetUserInstallationRequest","AppsGetUserInstallationResponse","AppsListInstallationReposForAuthenticatedUserPathParams","AppsListInstallationReposForAuthenticatedUserQueryParams","AppsListInstallationReposForAuthenticatedUserHeaders","AppsListInstallationReposForAuthenticatedUserRequest","AppsListInstallationReposForAuthenticatedUser200ApplicationJSON","AppsListInstallationReposForAuthenticatedUserResponse","AppsListInstallationsQueryParams","AppsListInstallationsHeaders","AppsListInstallationsRequest","AppsListInstallationsResponse","AppsListInstallationsForAuthenticatedUserQueryParams","AppsListInstallationsForAuthenticatedUserHeaders","AppsListInstallationsForAuthenticatedUserRequest","AppsListInstallationsForAuthenticatedUser200ApplicationJSON","AppsListInstallationsForAuthenticatedUser415ApplicationJSON","AppsListInstallationsForAuthenticatedUserResponse","AppsListReposAccessibleToInstallationQueryParams","AppsListReposAccessibleToInstallationHeaders","AppsListReposAccessibleToInstallationRequest","AppsListReposAccessibleToInstallation200ApplicationJSON","AppsListReposAccessibleToInstallationResponse","AppsRemoveRepoFromInstallationPathParams","AppsRemoveRepoFromInstallationRequest","AppsRemoveRepoFromInstallationResponse","AppsResetAuthorizationPathParams","AppsResetAuthorizationRequest","AppsResetAuthorizationResponse","AppsResetTokenPathParams","AppsResetTokenRequestBody","AppsResetTokenRequest","AppsResetTokenResponse","AppsRevokeAuthorizationForApplicationPathParams","AppsRevokeAuthorizationForApplicationRequest","AppsRevokeAuthorizationForApplicationResponse","AppsRevokeGrantForApplicationPathParams","AppsRevokeGrantForApplicationRequest","AppsRevokeGrantForApplicationResponse","AppsRevokeInstallationAccessTokenResponse","ChecksCreatePathParams","ChecksCreateRequestBodyActions","ChecksCreateRequestBodyConclusionEnum","ChecksCreateRequestBodyOutputAnnotationsAnnotationLevelEnum","ChecksCreateRequestBodyOutputAnnotations","ChecksCreateRequestBodyOutputImages","ChecksCreateRequestBodyOutput","ChecksCreateRequestBodyStatusEnum","ChecksCreateRequestBody","ChecksCreateRequest","ChecksCreateResponse","ChecksCreateSuitePathParams","ChecksCreateSuiteRequestBody","ChecksCreateSuiteRequest","ChecksCreateSuiteResponse","ChecksGetPathParams","ChecksGetRequest","ChecksGetResponse","ChecksGetSuitePathParams","ChecksGetSuiteRequest","ChecksGetSuiteResponse","ChecksListAnnotationsPathParams","ChecksListAnnotationsQueryParams","ChecksListAnnotationsRequest","ChecksListAnnotationsResponse","ChecksListForRefPathParams","ChecksListForRefQueryParams","ChecksListForRefRequest","ChecksListForRef200ApplicationJSON","ChecksListForRefResponse","ChecksListForSuitePathParams","ChecksListForSuiteQueryParams","ChecksListForSuiteRequest","ChecksListForSuite200ApplicationJSON","ChecksListForSuiteResponse","ChecksListSuitesForRefPathParams","ChecksListSuitesForRefQueryParams","ChecksListSuitesForRefRequest","ChecksListSuitesForRef200ApplicationJSON","ChecksListSuitesForRefResponse","ChecksRerequestSuitePathParams","ChecksRerequestSuiteRequest","ChecksRerequestSuiteResponse","ChecksSetSuitesPreferencesPathParams","ChecksSetSuitesPreferencesRequestBodyAutoTriggerChecks","ChecksSetSuitesPreferencesRequestBody","ChecksSetSuitesPreferencesRequest","ChecksSetSuitesPreferencesResponse","ChecksUpdatePathParams","ChecksUpdateRequestBodyActions","ChecksUpdateRequestBodyConclusionEnum","ChecksUpdateRequestBodyOutputAnnotationsAnnotationLevelEnum","ChecksUpdateRequestBodyOutputAnnotations","ChecksUpdateRequestBodyOutputImages","ChecksUpdateRequestBodyOutput","ChecksUpdateRequestBodyStatusEnum","ChecksUpdateRequestBody","ChecksUpdateRequest","ChecksUpdateResponse","CodesOfConductGetAllCodesOfConduct415ApplicationJSON","CodesOfConductGetAllCodesOfConductResponse","CodesOfConductGetConductCodePathParams","CodesOfConductGetConductCodeRequest","CodesOfConductGetConductCode415ApplicationJSON","CodesOfConductGetConductCodeResponse","EmojisGetResponse","EnterpriseAdminAddAuthorizedSSHKeyRequestBody","EnterpriseAdminAddAuthorizedSSHKeyRequest","EnterpriseAdminAddAuthorizedSSHKeyResponse","EnterpriseAdminCreateEnterpriseServerLicenseRequestBody","EnterpriseAdminCreateEnterpriseServerLicenseRequest","EnterpriseAdminCreateEnterpriseServerLicenseResponse","EnterpriseAdminCreateGlobalWebhookHeaders","EnterpriseAdminCreateGlobalWebhookRequestBodyConfig","EnterpriseAdminCreateGlobalWebhookRequestBody","EnterpriseAdminCreateGlobalWebhookRequest","EnterpriseAdminCreateGlobalWebhookResponse","EnterpriseAdminCreateImpersonationOAuthTokenPathParams","EnterpriseAdminCreateImpersonationOAuthTokenRequestBody","EnterpriseAdminCreateImpersonationOAuthTokenRequest","EnterpriseAdminCreateImpersonationOAuthTokenResponse","EnterpriseAdminCreateOrgRequestBody","EnterpriseAdminCreateOrgRequest","EnterpriseAdminCreateOrgResponse","EnterpriseAdminCreatePreReceiveEnvironmentRequestBody","EnterpriseAdminCreatePreReceiveEnvironmentRequest","EnterpriseAdminCreatePreReceiveEnvironmentResponse","EnterpriseAdminCreatePreReceiveHookRequestBody","EnterpriseAdminCreatePreReceiveHookRequest","EnterpriseAdminCreatePreReceiveHookResponse","EnterpriseAdminCreateUserRequestBody","EnterpriseAdminCreateUserRequest","EnterpriseAdminCreateUserResponse","EnterpriseAdminDeleteGlobalWebhookPathParams","EnterpriseAdminDeleteGlobalWebhookHeaders","EnterpriseAdminDeleteGlobalWebhookRequest","EnterpriseAdminDeleteGlobalWebhookResponse","EnterpriseAdminDeleteImpersonationOAuthTokenPathParams","EnterpriseAdminDeleteImpersonationOAuthTokenRequest","EnterpriseAdminDeleteImpersonationOAuthTokenResponse","EnterpriseAdminDeletePersonalAccessTokenPathParams","EnterpriseAdminDeletePersonalAccessTokenRequest","EnterpriseAdminDeletePersonalAccessTokenResponse","EnterpriseAdminDeletePreReceiveEnvironmentPathParams","EnterpriseAdminDeletePreReceiveEnvironmentRequest","EnterpriseAdminDeletePreReceiveEnvironment422ApplicationJSONErrors","EnterpriseAdminDeletePreReceiveEnvironment422ApplicationJSON","EnterpriseAdminDeletePreReceiveEnvironmentResponse","EnterpriseAdminDeletePreReceiveHookPathParams","EnterpriseAdminDeletePreReceiveHookRequest","EnterpriseAdminDeletePreReceiveHookResponse","EnterpriseAdminDeletePublicKeyPathParams","EnterpriseAdminDeletePublicKeyRequest","EnterpriseAdminDeletePublicKeyResponse","EnterpriseAdminDeleteUserPathParams","EnterpriseAdminDeleteUserRequest","EnterpriseAdminDeleteUserResponse","EnterpriseAdminDemoteSiteAdministratorPathParams","EnterpriseAdminDemoteSiteAdministratorRequest","EnterpriseAdminDemoteSiteAdministratorResponse","EnterpriseAdminEnableOrDisableMaintenanceModeRequestBody","EnterpriseAdminEnableOrDisableMaintenanceModeRequest","EnterpriseAdminEnableOrDisableMaintenanceModeResponse","EnterpriseAdminGetAllAuthorizedSSHKeysResponse","EnterpriseAdminGetConfigurationStatusResponse","EnterpriseAdminGetDownloadStatusForPreReceiveEnvironmentPathParams","EnterpriseAdminGetDownloadStatusForPreReceiveEnvironmentRequest","EnterpriseAdminGetDownloadStatusForPreReceiveEnvironmentResponse","EnterpriseAdminGetGlobalWebhookPathParams","EnterpriseAdminGetGlobalWebhookHeaders","EnterpriseAdminGetGlobalWebhookRequest","EnterpriseAdminGetGlobalWebhookResponse","EnterpriseAdminGetLicenseInformationResponse","EnterpriseAdminGetMaintenanceStatusResponse","EnterpriseAdminGetPreReceiveEnvironmentPathParams","EnterpriseAdminGetPreReceiveEnvironmentRequest","EnterpriseAdminGetPreReceiveEnvironmentResponse","EnterpriseAdminGetPreReceiveHookPathParams","EnterpriseAdminGetPreReceiveHookRequest","EnterpriseAdminGetPreReceiveHookResponse","EnterpriseAdminGetPreReceiveHookForOrgPathParams","EnterpriseAdminGetPreReceiveHookForOrgRequest","EnterpriseAdminGetPreReceiveHookForOrgResponse","EnterpriseAdminGetPreReceiveHookForRepoPathParams","EnterpriseAdminGetPreReceiveHookForRepoRequest","EnterpriseAdminGetPreReceiveHookForRepoResponse","EnterpriseAdminGetSettingsResponse","EnterpriseAdminGetTypeStatsPathParams","EnterpriseAdminGetTypeStatsRequest","EnterpriseAdminGetTypeStatsResponse","EnterpriseAdminListGlobalWebhooksQueryParams","EnterpriseAdminListGlobalWebhooksHeaders","EnterpriseAdminListGlobalWebhooksRequest","EnterpriseAdminListGlobalWebhooksResponse","EnterpriseAdminListPersonalAccessTokensQueryParams","EnterpriseAdminListPersonalAccessTokensRequest","EnterpriseAdminListPersonalAccessTokensResponse","EnterpriseAdminListPreReceiveEnvironmentsQueryParams","EnterpriseAdminListPreReceiveEnvironmentsRequest","EnterpriseAdminListPreReceiveEnvironmentsResponse","EnterpriseAdminListPreReceiveHooksQueryParams","EnterpriseAdminListPreReceiveHooksRequest","EnterpriseAdminListPreReceiveHooksResponse","EnterpriseAdminListPreReceiveHooksForOrgPathParams","EnterpriseAdminListPreReceiveHooksForOrgQueryParams","EnterpriseAdminListPreReceiveHooksForOrgRequest","EnterpriseAdminListPreReceiveHooksForOrgResponse","EnterpriseAdminListPreReceiveHooksForRepoPathParams","EnterpriseAdminListPreReceiveHooksForRepoQueryParams","EnterpriseAdminListPreReceiveHooksForRepoRequest","EnterpriseAdminListPreReceiveHooksForRepoResponse","EnterpriseAdminListPublicKeysQueryParams","EnterpriseAdminListPublicKeysRequest","EnterpriseAdminListPublicKeysResponse","EnterpriseAdminPingGlobalWebhookPathParams","EnterpriseAdminPingGlobalWebhookHeaders","EnterpriseAdminPingGlobalWebhookRequest","EnterpriseAdminPingGlobalWebhookResponse","EnterpriseAdminPromoteUserToBeSiteAdministratorPathParams","EnterpriseAdminPromoteUserToBeSiteAdministratorRequest","EnterpriseAdminPromoteUserToBeSiteAdministratorResponse","EnterpriseAdminRemoveAuthorizedSSHKeyRequestBody","EnterpriseAdminRemoveAuthorizedSSHKeyRequest","EnterpriseAdminRemoveAuthorizedSSHKeyResponse","EnterpriseAdminRemovePreReceiveHookEnforcementForOrgPathParams","EnterpriseAdminRemovePreReceiveHookEnforcementForOrgRequest","EnterpriseAdminRemovePreReceiveHookEnforcementForOrgResponse","EnterpriseAdminRemovePreReceiveHookEnforcementForRepoPathParams","EnterpriseAdminRemovePreReceiveHookEnforcementForRepoRequest","EnterpriseAdminRemovePreReceiveHookEnforcementForRepoResponse","EnterpriseAdminSetSettingsRequestBody","EnterpriseAdminSetSettingsRequest","EnterpriseAdminSetSettingsResponse","EnterpriseAdminStartConfigurationProcessResponse","EnterpriseAdminStartPreReceiveEnvironmentDownloadPathParams","EnterpriseAdminStartPreReceiveEnvironmentDownloadRequest","EnterpriseAdminStartPreReceiveEnvironmentDownload422ApplicationJSONErrors","EnterpriseAdminStartPreReceiveEnvironmentDownload422ApplicationJSON","EnterpriseAdminStartPreReceiveEnvironmentDownloadResponse","EnterpriseAdminSuspendUserPathParams","EnterpriseAdminSuspendUserRequestBody","EnterpriseAdminSuspendUserRequest","EnterpriseAdminSuspendUserResponse","EnterpriseAdminSyncLdapMappingForTeamPathParams","EnterpriseAdminSyncLdapMappingForTeamRequest","EnterpriseAdminSyncLdapMappingForTeam201ApplicationJSON","EnterpriseAdminSyncLdapMappingForTeamResponse","EnterpriseAdminSyncLdapMappingForUserPathParams","EnterpriseAdminSyncLdapMappingForUserRequest","EnterpriseAdminSyncLdapMappingForUser201ApplicationJSON","EnterpriseAdminSyncLdapMappingForUserResponse","EnterpriseAdminUnsuspendUserPathParams","EnterpriseAdminUnsuspendUserRequestBody","EnterpriseAdminUnsuspendUserRequest","EnterpriseAdminUnsuspendUserResponse","EnterpriseAdminUpdateGlobalWebhookPathParams","EnterpriseAdminUpdateGlobalWebhookHeaders","EnterpriseAdminUpdateGlobalWebhookRequestBodyConfig","EnterpriseAdminUpdateGlobalWebhookRequestBody","EnterpriseAdminUpdateGlobalWebhookRequest","EnterpriseAdminUpdateGlobalWebhookResponse","EnterpriseAdminUpdateLdapMappingForTeamPathParams","EnterpriseAdminUpdateLdapMappingForTeamRequestBody","EnterpriseAdminUpdateLdapMappingForTeamRequest","EnterpriseAdminUpdateLdapMappingForTeamResponse","EnterpriseAdminUpdateLdapMappingForUserPathParams","EnterpriseAdminUpdateLdapMappingForUserRequestBody","EnterpriseAdminUpdateLdapMappingForUserRequest","EnterpriseAdminUpdateLdapMappingForUserResponse","EnterpriseAdminUpdateOrgNamePathParams","EnterpriseAdminUpdateOrgNameRequestBody","EnterpriseAdminUpdateOrgNameRequest","EnterpriseAdminUpdateOrgName202ApplicationJSON","EnterpriseAdminUpdateOrgNameResponse","EnterpriseAdminUpdatePreReceiveEnvironmentPathParams","EnterpriseAdminUpdatePreReceiveEnvironmentRequestBody","EnterpriseAdminUpdatePreReceiveEnvironmentRequest","EnterpriseAdminUpdatePreReceiveEnvironment422ApplicationJSONErrors","EnterpriseAdminUpdatePreReceiveEnvironment422ApplicationJSON","EnterpriseAdminUpdatePreReceiveEnvironmentResponse","EnterpriseAdminUpdatePreReceiveHookPathParams","EnterpriseAdminUpdatePreReceiveHookRequestBody","EnterpriseAdminUpdatePreReceiveHookRequest","EnterpriseAdminUpdatePreReceiveHookResponse","EnterpriseAdminUpdatePreReceiveHookEnforcementForOrgPathParams","EnterpriseAdminUpdatePreReceiveHookEnforcementForOrgRequestBody","EnterpriseAdminUpdatePreReceiveHookEnforcementForOrgRequest","EnterpriseAdminUpdatePreReceiveHookEnforcementForOrgResponse","EnterpriseAdminUpdatePreReceiveHookEnforcementForRepoPathParams","EnterpriseAdminUpdatePreReceiveHookEnforcementForRepoRequestBodyEnforcementEnum","EnterpriseAdminUpdatePreReceiveHookEnforcementForRepoRequestBody","EnterpriseAdminUpdatePreReceiveHookEnforcementForRepoRequest","EnterpriseAdminUpdatePreReceiveHookEnforcementForRepoResponse","EnterpriseAdminUpdateUsernameForUserPathParams","EnterpriseAdminUpdateUsernameForUserRequestBody","EnterpriseAdminUpdateUsernameForUserRequest","EnterpriseAdminUpdateUsernameForUser202ApplicationJSON","EnterpriseAdminUpdateUsernameForUserResponse","EnterpriseAdminUpgradeLicenseRequestBody","EnterpriseAdminUpgradeLicenseRequest","EnterpriseAdminUpgradeLicenseResponse","GistsCheckIsStarredPathParams","GistsCheckIsStarredRequest","GistsCheckIsStarredResponse","GistsCreateRequestBodyFiles","GistsCreateRequestBodyPublic2Enum","GistsCreateRequestBody","GistsCreateRequest","GistsCreateResponse","GistsCreateCommentPathParams","GistsCreateCommentRequestBody","GistsCreateCommentRequest","GistsCreateCommentResponse","GistsDeletePathParams","GistsDeleteRequest","GistsDeleteResponse","GistsDeleteCommentPathParams","GistsDeleteCommentRequest","GistsDeleteCommentResponse","GistsForkPathParams","GistsForkRequest","GistsForkResponse","GistsGetPathParams","GistsGetRequest","GistsGet403ApplicationJSONBlock","GistsGet403ApplicationJSON","GistsGetResponse","GistsGetCommentPathParams","GistsGetCommentRequest","GistsGetComment403ApplicationJSONBlock","GistsGetComment403ApplicationJSON","GistsGetCommentResponse","GistsGetRevisionPathParams","GistsGetRevisionRequest","GistsGetRevisionResponse","GistsListQueryParams","GistsListRequest","GistsListResponse","GistsListCommentsPathParams","GistsListCommentsQueryParams","GistsListCommentsRequest","GistsListCommentsResponse","GistsListCommitsPathParams","GistsListCommitsQueryParams","GistsListCommitsRequest","GistsListCommitsResponse","GistsListForUserPathParams","GistsListForUserQueryParams","GistsListForUserRequest","GistsListForUserResponse","GistsListForksPathParams","GistsListForksQueryParams","GistsListForksRequest","GistsListForksResponse","GistsListPublicQueryParams","GistsListPublicRequest","GistsListPublicResponse","GistsListStarredQueryParams","GistsListStarredRequest","GistsListStarredResponse","GistsStarPathParams","GistsStarRequest","GistsStarResponse","GistsUnstarPathParams","GistsUnstarRequest","GistsUnstarResponse","GistsUpdatePathParams","GistsUpdateRequestBodyFiles","GistsUpdateRequestBody","GistsUpdateRequest","GistsUpdateResponse","GistsUpdateCommentPathParams","GistsUpdateCommentRequestBody","GistsUpdateCommentRequest","GistsUpdateCommentResponse","GitCreateBlobPathParams","GitCreateBlobRequestBody","GitCreateBlobRequest","GitCreateBlobResponse","GitCreateCommitPathParams","GitCreateCommitRequestBodyAuthor","GitCreateCommitRequestBodyCommitter","GitCreateCommitRequestBody","GitCreateCommitRequest","GitCreateCommitResponse","GitCreateRefPathParams","GitCreateRefRequestBody","GitCreateRefRequest","GitCreateRefResponse","GitCreateTagPathParams","GitCreateTagRequestBodyTagger","GitCreateTagRequestBodyTypeEnum","GitCreateTagRequestBody","GitCreateTagRequest","GitCreateTagResponse","GitCreateTreePathParams","GitCreateTreeRequestBodyTreeModeEnum","GitCreateTreeRequestBodyTreeTypeEnum","GitCreateTreeRequestBodyTree","GitCreateTreeRequestBody","GitCreateTreeRequest","GitCreateTreeResponse","GitDeleteRefPathParams","GitDeleteRefRequest","GitDeleteRefResponse","GitGetBlobPathParams","GitGetBlobRequest","GitGetBlobResponse","GitGetCommitPathParams","GitGetCommitRequest","GitGetCommitResponse","GitGetRefPathParams","GitGetRefRequest","GitGetRefResponse","GitGetTagPathParams","GitGetTagRequest","GitGetTagResponse","GitGetTreePathParams","GitGetTreeQueryParams","GitGetTreeRequest","GitGetTreeResponse","GitListMatchingRefsPathParams","GitListMatchingRefsQueryParams","GitListMatchingRefsRequest","GitListMatchingRefsResponse","GitUpdateRefPathParams","GitUpdateRefRequestBody","GitUpdateRefRequest","GitUpdateRefResponse","GitignoreGetAllTemplatesResponse","GitignoreGetTemplatePathParams","GitignoreGetTemplateRequest","GitignoreGetTemplateResponse","IssuesAddAssigneesPathParams","IssuesAddAssigneesRequestBody","IssuesAddAssigneesRequest","IssuesAddAssigneesResponse","IssuesAddLabelsPathParams","IssuesAddLabelsRequestBody1","IssuesAddLabelsRequestBody3Labels","IssuesAddLabelsRequestBody3","IssuesAddLabelsRequestBody4","IssuesAddLabelsRequest","IssuesAddLabelsResponse","IssuesCheckUserCanBeAssignedPathParams","IssuesCheckUserCanBeAssignedRequest","IssuesCheckUserCanBeAssignedResponse","IssuesCreatePathParams","IssuesCreateRequestBodyLabels2","IssuesCreateRequestBody","IssuesCreateRequest","IssuesCreate503ApplicationJSON","IssuesCreateResponse","IssuesCreateCommentPathParams","IssuesCreateCommentRequestBody","IssuesCreateCommentRequest","IssuesCreateCommentResponse","IssuesCreateLabelPathParams","IssuesCreateLabelRequestBody","IssuesCreateLabelRequest","IssuesCreateLabelResponse","IssuesCreateMilestonePathParams","IssuesCreateMilestoneRequestBodyStateEnum","IssuesCreateMilestoneRequestBody","IssuesCreateMilestoneRequest","IssuesCreateMilestoneResponse","IssuesDeleteCommentPathParams","IssuesDeleteCommentRequest","IssuesDeleteCommentResponse","IssuesDeleteLabelPathParams","IssuesDeleteLabelRequest","IssuesDeleteLabelResponse","IssuesDeleteMilestonePathParams","IssuesDeleteMilestoneRequest","IssuesDeleteMilestoneResponse","IssuesGetPathParams","IssuesGetRequest","IssuesGetResponse","IssuesGetCommentPathParams","IssuesGetCommentRequest","IssuesGetCommentResponse","IssuesGetEventPathParams","IssuesGetEventRequest","IssuesGetEventResponse","IssuesGetLabelPathParams","IssuesGetLabelRequest","IssuesGetLabelResponse","IssuesGetMilestonePathParams","IssuesGetMilestoneRequest","IssuesGetMilestoneResponse","IssuesListFilterEnum","IssuesListStateEnum","IssuesListQueryParams","IssuesListRequest","IssuesListResponse","IssuesListAssigneesPathParams","IssuesListAssigneesQueryParams","IssuesListAssigneesRequest","IssuesListAssigneesResponse","IssuesListCommentsPathParams","IssuesListCommentsQueryParams","IssuesListCommentsRequest","IssuesListCommentsResponse","IssuesListCommentsForRepoPathParams","IssuesListCommentsForRepoQueryParams","IssuesListCommentsForRepoRequest","IssuesListCommentsForRepoResponse","IssuesListEventsPathParams","IssuesListEventsQueryParams","IssuesListEventsRequest","IssuesListEventsResponse","IssuesListEventsForRepoPathParams","IssuesListEventsForRepoQueryParams","IssuesListEventsForRepoRequest","IssuesListEventsForRepoResponse","IssuesListEventsForTimelinePathParams","IssuesListEventsForTimelineQueryParams","IssuesListEventsForTimelineRequest","IssuesListEventsForTimeline415ApplicationJSON","IssuesListEventsForTimelineResponse","IssuesListForAuthenticatedUserFilterEnum","IssuesListForAuthenticatedUserStateEnum","IssuesListForAuthenticatedUserQueryParams","IssuesListForAuthenticatedUserRequest","IssuesListForAuthenticatedUserResponse","IssuesListForOrgPathParams","IssuesListForOrgQueryParams","IssuesListForOrgRequest","IssuesListForOrgResponse","IssuesListForRepoPathParams","IssuesListForRepoQueryParams","IssuesListForRepoRequest","IssuesListForRepoResponse","IssuesListLabelsForMilestonePathParams","IssuesListLabelsForMilestoneQueryParams","IssuesListLabelsForMilestoneRequest","IssuesListLabelsForMilestoneResponse","IssuesListLabelsForRepoPathParams","IssuesListLabelsForRepoQueryParams","IssuesListLabelsForRepoRequest","IssuesListLabelsForRepoResponse","IssuesListLabelsOnIssuePathParams","IssuesListLabelsOnIssueQueryParams","IssuesListLabelsOnIssueRequest","IssuesListLabelsOnIssueResponse","IssuesListMilestonesPathParams","IssuesListMilestonesQueryParams","IssuesListMilestonesRequest","IssuesListMilestonesResponse","IssuesLockPathParams","IssuesLockRequestBodyLockReasonEnum","IssuesLockRequestBody","IssuesLockRequest","IssuesLockResponse","IssuesRemoveAllLabelsPathParams","IssuesRemoveAllLabelsRequest","IssuesRemoveAllLabelsResponse","IssuesRemoveAssigneesPathParams","IssuesRemoveAssigneesRequestBody","IssuesRemoveAssigneesRequest","IssuesRemoveAssigneesResponse","IssuesRemoveLabelPathParams","IssuesRemoveLabelRequest","IssuesRemoveLabelResponse","IssuesSetLabelsPathParams","IssuesSetLabelsRequestBody1","IssuesSetLabelsRequestBody3Labels","IssuesSetLabelsRequestBody3","IssuesSetLabelsRequestBody4","IssuesSetLabelsRequest","IssuesSetLabelsResponse","IssuesUnlockPathParams","IssuesUnlockRequest","IssuesUnlockResponse","IssuesUpdatePathParams","IssuesUpdateRequestBodyLabels2","IssuesUpdateRequestBodyStateEnum","IssuesUpdateRequestBody","IssuesUpdateRequest","IssuesUpdate503ApplicationJSON","IssuesUpdateResponse","IssuesUpdateCommentPathParams","IssuesUpdateCommentRequestBody","IssuesUpdateCommentRequest","IssuesUpdateCommentResponse","IssuesUpdateLabelPathParams","IssuesUpdateLabelRequestBody","IssuesUpdateLabelRequest","IssuesUpdateLabelResponse","IssuesUpdateMilestonePathParams","IssuesUpdateMilestoneRequestBodyStateEnum","IssuesUpdateMilestoneRequestBody","IssuesUpdateMilestoneRequest","IssuesUpdateMilestoneResponse","LicensesGetPathParams","LicensesGetRequest","LicensesGetResponse","LicensesGetAllCommonlyUsedQueryParams","LicensesGetAllCommonlyUsedRequest","LicensesGetAllCommonlyUsedResponse","LicensesGetForRepoPathParams","LicensesGetForRepoRequest","LicensesGetForRepoResponse","MarkdownRenderRequestBodyModeEnum","MarkdownRenderRequestBody","MarkdownRenderRequest","MarkdownRenderResponse","MarkdownRenderRawRequests","MarkdownRenderRawRequest","MarkdownRenderRawResponse","MetaGetResponse","MetaGetOctocatQueryParams","MetaGetOctocatRequest","MetaGetOctocatResponse","MetaGetZenResponse","MetaRoot200ApplicationJSON","MetaRootResponse","OauthAuthorizationsCreateAuthorizationRequestBody","OauthAuthorizationsCreateAuthorizationRequest","OauthAuthorizationsCreateAuthorizationResponse","OauthAuthorizationsDeleteAuthorizationPathParams","OauthAuthorizationsDeleteAuthorizationRequest","OauthAuthorizationsDeleteAuthorizationResponse","OauthAuthorizationsDeleteGrantPathParams","OauthAuthorizationsDeleteGrantRequest","OauthAuthorizationsDeleteGrantResponse","OauthAuthorizationsGetAuthorizationPathParams","OauthAuthorizationsGetAuthorizationRequest","OauthAuthorizationsGetAuthorizationResponse","OauthAuthorizationsGetGrantPathParams","OauthAuthorizationsGetGrantRequest","OauthAuthorizationsGetGrantResponse","OauthAuthorizationsGetOrCreateAuthorizationForAppPathParams","OauthAuthorizationsGetOrCreateAuthorizationForAppRequestBody","OauthAuthorizationsGetOrCreateAuthorizationForAppRequest","OauthAuthorizationsGetOrCreateAuthorizationForAppResponse","OauthAuthorizationsGetOrCreateAuthorizationForAppAndFingerprintPathParams","OauthAuthorizationsGetOrCreateAuthorizationForAppAndFingerprintRequestBody","OauthAuthorizationsGetOrCreateAuthorizationForAppAndFingerprintRequest","OauthAuthorizationsGetOrCreateAuthorizationForAppAndFingerprintResponse","OauthAuthorizationsListAuthorizationsQueryParams","OauthAuthorizationsListAuthorizationsRequest","OauthAuthorizationsListAuthorizationsResponse","OauthAuthorizationsListGrantsQueryParams","OauthAuthorizationsListGrantsRequest","OauthAuthorizationsListGrantsResponse","OauthAuthorizationsUpdateAuthorizationPathParams","OauthAuthorizationsUpdateAuthorizationRequestBody","OauthAuthorizationsUpdateAuthorizationRequest","OauthAuthorizationsUpdateAuthorizationResponse","OrgsCheckMembershipForUserPathParams","OrgsCheckMembershipForUserRequest","OrgsCheckMembershipForUserResponse","OrgsCheckPublicMembershipForUserPathParams","OrgsCheckPublicMembershipForUserRequest","OrgsCheckPublicMembershipForUserResponse","OrgsConvertMemberToOutsideCollaboratorPathParams","OrgsConvertMemberToOutsideCollaboratorRequest","OrgsConvertMemberToOutsideCollaboratorResponse","OrgsCreateWebhookPathParams","OrgsCreateWebhookRequestBodyConfig","OrgsCreateWebhookRequestBody","OrgsCreateWebhookRequest","OrgsCreateWebhookResponse","OrgsDeleteWebhookPathParams","OrgsDeleteWebhookRequest","OrgsDeleteWebhookResponse","OrgsGetPathParams","OrgsGetRequest","OrgsGetResponse","OrgsGetMembershipForAuthenticatedUserPathParams","OrgsGetMembershipForAuthenticatedUserRequest","OrgsGetMembershipForAuthenticatedUserResponse","OrgsGetMembershipForUserPathParams","OrgsGetMembershipForUserRequest","OrgsGetMembershipForUserResponse","OrgsGetWebhookPathParams","OrgsGetWebhookRequest","OrgsGetWebhookResponse","OrgsListQueryParams","OrgsListRequest","OrgsListResponse","OrgsListAppInstallationsPathParams","OrgsListAppInstallationsQueryParams","OrgsListAppInstallationsHeaders","OrgsListAppInstallationsRequest","OrgsListAppInstallations200ApplicationJSON","OrgsListAppInstallationsResponse","OrgsListForAuthenticatedUserQueryParams","OrgsListForAuthenticatedUserRequest","OrgsListForAuthenticatedUserResponse","OrgsListForUserPathParams","OrgsListForUserQueryParams","OrgsListForUserRequest","OrgsListForUserResponse","OrgsListMembersPathParams","OrgsListMembersQueryParams","OrgsListMembersRequest","OrgsListMembersResponse","OrgsListMembershipsForAuthenticatedUserStateEnum","OrgsListMembershipsForAuthenticatedUserQueryParams","OrgsListMembershipsForAuthenticatedUserRequest","OrgsListMembershipsForAuthenticatedUserResponse","OrgsListOutsideCollaboratorsPathParams","OrgsListOutsideCollaboratorsQueryParams","OrgsListOutsideCollaboratorsRequest","OrgsListOutsideCollaboratorsResponse","OrgsListPublicMembersPathParams","OrgsListPublicMembersQueryParams","OrgsListPublicMembersRequest","OrgsListPublicMembersResponse","OrgsListWebhooksPathParams","OrgsListWebhooksQueryParams","OrgsListWebhooksRequest","OrgsListWebhooksResponse","OrgsPingWebhookPathParams","OrgsPingWebhookRequest","OrgsPingWebhookResponse","OrgsRemoveMemberPathParams","OrgsRemoveMemberRequest","OrgsRemoveMemberResponse","OrgsRemoveMembershipForUserPathParams","OrgsRemoveMembershipForUserRequest","OrgsRemoveMembershipForUserResponse","OrgsRemoveOutsideCollaboratorPathParams","OrgsRemoveOutsideCollaboratorRequest","OrgsRemoveOutsideCollaborator422ApplicationJSON","OrgsRemoveOutsideCollaboratorResponse","OrgsRemovePublicMembershipForAuthenticatedUserPathParams","OrgsRemovePublicMembershipForAuthenticatedUserRequest","OrgsRemovePublicMembershipForAuthenticatedUserResponse","OrgsSetMembershipForUserPathParams","OrgsSetMembershipForUserRequestBodyRoleEnum","OrgsSetMembershipForUserRequestBody","OrgsSetMembershipForUserRequest","OrgsSetMembershipForUserResponse","OrgsSetPublicMembershipForAuthenticatedUserPathParams","OrgsSetPublicMembershipForAuthenticatedUserRequest","OrgsSetPublicMembershipForAuthenticatedUserResponse","OrgsUpdatePathParams","OrgsUpdateRequestBodyDefaultRepositoryPermissionEnum","OrgsUpdateRequestBodyMembersAllowedRepositoryCreationTypeEnum","OrgsUpdateRequestBody","OrgsUpdateRequest","OrgsUpdate415ApplicationJSON","OrgsUpdateResponse","OrgsUpdateMembershipForAuthenticatedUserPathParams","OrgsUpdateMembershipForAuthenticatedUserRequestBodyStateEnum","OrgsUpdateMembershipForAuthenticatedUserRequestBody","OrgsUpdateMembershipForAuthenticatedUserRequest","OrgsUpdateMembershipForAuthenticatedUserResponse","OrgsUpdateWebhookPathParams","OrgsUpdateWebhookRequestBodyConfig","OrgsUpdateWebhookRequestBody","OrgsUpdateWebhookRequest","OrgsUpdateWebhookResponse","ProjectsAddCollaboratorPathParams","ProjectsAddCollaboratorRequestBodyPermissionEnum","ProjectsAddCollaboratorRequestBody","ProjectsAddCollaboratorRequest","ProjectsAddCollaborator415ApplicationJSON","ProjectsAddCollaboratorResponse","ProjectsCreateCardPathParams","ProjectsCreateCardRequestBody1","ProjectsCreateCardRequestBody2","ProjectsCreateCardRequest","ProjectsCreateCard503ApplicationJSONErrors","ProjectsCreateCard503ApplicationJSON","ProjectsCreateCardResponse","ProjectsCreateColumnPathParams","ProjectsCreateColumnRequestBody","ProjectsCreateColumnRequest","ProjectsCreateColumnResponse","ProjectsCreateForAuthenticatedUserRequestBody","ProjectsCreateForAuthenticatedUserRequest","ProjectsCreateForAuthenticatedUser415ApplicationJSON","ProjectsCreateForAuthenticatedUserResponse","ProjectsCreateForOrgPathParams","ProjectsCreateForOrgRequestBody","ProjectsCreateForOrgRequest","ProjectsCreateForOrgResponse","ProjectsCreateForRepoPathParams","ProjectsCreateForRepoRequestBody","ProjectsCreateForRepoRequest","ProjectsCreateForRepoResponse","ProjectsDeletePathParams","ProjectsDeleteRequest","ProjectsDelete403ApplicationJSON","ProjectsDeleteResponse","ProjectsDeleteCardPathParams","ProjectsDeleteCardRequest","ProjectsDeleteCard403ApplicationJSON","ProjectsDeleteCardResponse","ProjectsDeleteColumnPathParams","ProjectsDeleteColumnRequest","ProjectsDeleteColumnResponse","ProjectsGetPathParams","ProjectsGetRequest","ProjectsGetResponse","ProjectsGetCardPathParams","ProjectsGetCardRequest","ProjectsGetCardResponse","ProjectsGetColumnPathParams","ProjectsGetColumnRequest","ProjectsGetColumnResponse","ProjectsGetPermissionForUserPathParams","ProjectsGetPermissionForUserRequest","ProjectsGetPermissionForUser415ApplicationJSON","ProjectsGetPermissionForUserResponse","ProjectsListCardsPathParams","ProjectsListCardsQueryParams","ProjectsListCardsRequest","ProjectsListCardsResponse","ProjectsListCollaboratorsPathParams","ProjectsListCollaboratorsQueryParams","ProjectsListCollaboratorsRequest","ProjectsListCollaborators415ApplicationJSON","ProjectsListCollaboratorsResponse","ProjectsListColumnsPathParams","ProjectsListColumnsQueryParams","ProjectsListColumnsRequest","ProjectsListColumnsResponse","ProjectsListForOrgPathParams","ProjectsListForOrgQueryParams","ProjectsListForOrgRequest","ProjectsListForOrgResponse","ProjectsListForRepoPathParams","ProjectsListForRepoQueryParams","ProjectsListForRepoRequest","ProjectsListForRepoResponse","ProjectsListForUserPathParams","ProjectsListForUserQueryParams","ProjectsListForUserRequest","ProjectsListForUser415ApplicationJSON","ProjectsListForUserResponse","ProjectsMoveCardPathParams","ProjectsMoveCardRequestBody","ProjectsMoveCardRequest","ProjectsMoveCard403ApplicationJSONErrors","ProjectsMoveCard403ApplicationJSON","ProjectsMoveCard503ApplicationJSONErrors","ProjectsMoveCard503ApplicationJSON","ProjectsMoveCardResponse","ProjectsMoveColumnPathParams","ProjectsMoveColumnRequestBody","ProjectsMoveColumnRequest","ProjectsMoveColumnResponse","ProjectsRemoveCollaboratorPathParams","ProjectsRemoveCollaboratorRequest","ProjectsRemoveCollaborator415ApplicationJSON","ProjectsRemoveCollaboratorResponse","ProjectsUpdatePathParams","ProjectsUpdateRequestBodyOrganizationPermissionEnum","ProjectsUpdateRequestBody","ProjectsUpdateRequest","ProjectsUpdate403ApplicationJSON","ProjectsUpdateResponse","ProjectsUpdateCardPathParams","ProjectsUpdateCardRequestBody","ProjectsUpdateCardRequest","ProjectsUpdateCardResponse","ProjectsUpdateColumnPathParams","ProjectsUpdateColumnRequestBody","ProjectsUpdateColumnRequest","ProjectsUpdateColumnResponse","PullsCheckIfMergedPathParams","PullsCheckIfMergedRequest","PullsCheckIfMergedResponse","PullsCreatePathParams","PullsCreateRequestBody","PullsCreateRequest","PullsCreateResponse","PullsCreateReplyForReviewCommentPathParams","PullsCreateReplyForReviewCommentRequestBody","PullsCreateReplyForReviewCommentRequest","PullsCreateReplyForReviewCommentResponse","PullsCreateReviewPathParams","PullsCreateReviewRequestBodyComments","PullsCreateReviewRequestBodyEventEnum","PullsCreateReviewRequestBody","PullsCreateReviewRequest","PullsCreateReviewResponse","PullsCreateReviewCommentPathParams","PullsCreateReviewCommentRequestBodySideEnum","PullsCreateReviewCommentRequestBodyStartSideEnum","PullsCreateReviewCommentRequestBody","PullsCreateReviewCommentRequest","PullsCreateReviewCommentResponse","PullsDeletePendingReviewPathParams","PullsDeletePendingReviewRequest","PullsDeletePendingReviewResponse","PullsDeleteReviewCommentPathParams","PullsDeleteReviewCommentRequest","PullsDeleteReviewCommentResponse","PullsDismissReviewPathParams","PullsDismissReviewRequestBody","PullsDismissReviewRequest","PullsDismissReviewResponse","PullsGetPathParams","PullsGetRequest","PullsGetResponse","PullsGetReviewPathParams","PullsGetReviewRequest","PullsGetReviewResponse","PullsGetReviewCommentPathParams","PullsGetReviewCommentRequest","PullsGetReviewCommentResponse","PullsListPathParams","PullsListQueryParams","PullsListRequest","PullsListResponse","PullsListCommentsForReviewPathParams","PullsListCommentsForReviewQueryParams","PullsListCommentsForReviewRequest","PullsListCommentsForReviewResponse","PullsListCommitsPathParams","PullsListCommitsQueryParams","PullsListCommitsRequest","PullsListCommitsResponse","PullsListFilesPathParams","PullsListFilesQueryParams","PullsListFilesRequest","PullsListFilesResponse","PullsListRequestedReviewersPathParams","PullsListRequestedReviewersQueryParams","PullsListRequestedReviewersRequest","PullsListRequestedReviewersResponse","PullsListReviewCommentsPathParams","PullsListReviewCommentsQueryParams","PullsListReviewCommentsRequest","PullsListReviewCommentsResponse","PullsListReviewCommentsForRepoPathParams","PullsListReviewCommentsForRepoQueryParams","PullsListReviewCommentsForRepoRequest","PullsListReviewCommentsForRepoResponse","PullsListReviewsPathParams","PullsListReviewsQueryParams","PullsListReviewsRequest","PullsListReviewsResponse","PullsMergePathParams","PullsMergeRequestBodyMergeMethodEnum","PullsMergeRequestBody","PullsMergeRequest","PullsMerge405ApplicationJSON","PullsMerge409ApplicationJSON","PullsMergeResponse","PullsRemoveRequestedReviewersPathParams","PullsRemoveRequestedReviewersRequestBody","PullsRemoveRequestedReviewersRequest","PullsRemoveRequestedReviewersResponse","PullsRequestReviewersPathParams","PullsRequestReviewersRequestBody","PullsRequestReviewersRequest","PullsRequestReviewersResponse","PullsSubmitReviewPathParams","PullsSubmitReviewRequestBodyEventEnum","PullsSubmitReviewRequestBody","PullsSubmitReviewRequest","PullsSubmitReviewResponse","PullsUpdatePathParams","PullsUpdateRequestBodyStateEnum","PullsUpdateRequestBody","PullsUpdateRequest","PullsUpdateResponse","PullsUpdateBranchPathParams","PullsUpdateBranchRequestBody","PullsUpdateBranchRequest","PullsUpdateBranch202ApplicationJSON","PullsUpdateBranch415ApplicationJSON","PullsUpdateBranchResponse","PullsUpdateReviewPathParams","PullsUpdateReviewRequestBody","PullsUpdateReviewRequest","PullsUpdateReviewResponse","PullsUpdateReviewCommentPathParams","PullsUpdateReviewCommentRequestBody","PullsUpdateReviewCommentRequest","PullsUpdateReviewCommentResponse","RateLimitGetResponse","ReactionsCreateForCommitCommentPathParams","ReactionsCreateForCommitCommentRequestBodyContentEnum","ReactionsCreateForCommitCommentRequestBody","ReactionsCreateForCommitCommentRequest","ReactionsCreateForCommitComment415ApplicationJSON","ReactionsCreateForCommitCommentResponse","ReactionsCreateForIssuePathParams","ReactionsCreateForIssueRequestBodyContentEnum","ReactionsCreateForIssueRequestBody","ReactionsCreateForIssueRequest","ReactionsCreateForIssue415ApplicationJSON","ReactionsCreateForIssueResponse","ReactionsCreateForIssueCommentPathParams","ReactionsCreateForIssueCommentRequestBodyContentEnum","ReactionsCreateForIssueCommentRequestBody","ReactionsCreateForIssueCommentRequest","ReactionsCreateForIssueComment415ApplicationJSON","ReactionsCreateForIssueCommentResponse","ReactionsCreateForPullRequestReviewCommentPathParams","ReactionsCreateForPullRequestReviewCommentRequestBodyContentEnum","ReactionsCreateForPullRequestReviewCommentRequestBody","ReactionsCreateForPullRequestReviewCommentRequest","ReactionsCreateForPullRequestReviewComment415ApplicationJSON","ReactionsCreateForPullRequestReviewCommentResponse","ReactionsCreateForTeamDiscussionPathParams","ReactionsCreateForTeamDiscussionHeaders","ReactionsCreateForTeamDiscussionRequestBodyContentEnum","ReactionsCreateForTeamDiscussionRequestBody","ReactionsCreateForTeamDiscussionRequest","ReactionsCreateForTeamDiscussionResponse","ReactionsCreateForTeamDiscussionCommentPathParams","ReactionsCreateForTeamDiscussionCommentHeaders","ReactionsCreateForTeamDiscussionCommentRequestBodyContentEnum","ReactionsCreateForTeamDiscussionCommentRequestBody","ReactionsCreateForTeamDiscussionCommentRequest","ReactionsCreateForTeamDiscussionCommentResponse","ReactionsDeletePathParams","ReactionsDeleteHeaders","ReactionsDeleteRequest","ReactionsDeleteResponse","ReactionsListForCommitCommentPathParams","ReactionsListForCommitCommentQueryParams","ReactionsListForCommitCommentRequest","ReactionsListForCommitComment415ApplicationJSON","ReactionsListForCommitCommentResponse","ReactionsListForIssuePathParams","ReactionsListForIssueQueryParams","ReactionsListForIssueRequest","ReactionsListForIssue415ApplicationJSON","ReactionsListForIssueResponse","ReactionsListForIssueCommentPathParams","ReactionsListForIssueCommentQueryParams","ReactionsListForIssueCommentRequest","ReactionsListForIssueComment415ApplicationJSON","ReactionsListForIssueCommentResponse","ReactionsListForPullRequestReviewCommentPathParams","ReactionsListForPullRequestReviewCommentQueryParams","ReactionsListForPullRequestReviewCommentRequest","ReactionsListForPullRequestReviewComment415ApplicationJSON","ReactionsListForPullRequestReviewCommentResponse","ReactionsListForTeamDiscussionPathParams","ReactionsListForTeamDiscussionQueryParams","ReactionsListForTeamDiscussionHeaders","ReactionsListForTeamDiscussionRequest","ReactionsListForTeamDiscussionResponse","ReactionsListForTeamDiscussionCommentPathParams","ReactionsListForTeamDiscussionCommentQueryParams","ReactionsListForTeamDiscussionCommentHeaders","ReactionsListForTeamDiscussionCommentRequest","ReactionsListForTeamDiscussionCommentResponse","ReposAcceptInvitationPathParams","ReposAcceptInvitationRequest","ReposAcceptInvitationResponse","ReposAddAppAccessRestrictionsPathParams","ReposAddAppAccessRestrictionsRequestBody1","ReposAddAppAccessRestrictionsRequest","ReposAddAppAccessRestrictionsResponse","ReposAddCollaboratorPathParams","ReposAddCollaboratorRequestBodyPermissionEnum","ReposAddCollaboratorRequestBody","ReposAddCollaboratorRequest","ReposAddCollaboratorResponse","ReposAddStatusCheckContextsPathParams","ReposAddStatusCheckContextsRequestBody1","ReposAddStatusCheckContextsRequest","ReposAddStatusCheckContextsResponse","ReposAddTeamAccessRestrictionsPathParams","ReposAddTeamAccessRestrictionsRequestBody1","ReposAddTeamAccessRestrictionsRequest","ReposAddTeamAccessRestrictionsResponse","ReposAddUserAccessRestrictionsPathParams","ReposAddUserAccessRestrictionsRequestBody1","ReposAddUserAccessRestrictionsRequest","ReposAddUserAccessRestrictionsResponse","ReposCheckCollaboratorPathParams","ReposCheckCollaboratorRequest","ReposCheckCollaboratorResponse","ReposCompareCommitsPathParams","ReposCompareCommitsRequest","ReposCompareCommitsResponse","ReposCreateCommitCommentPathParams","ReposCreateCommitCommentRequestBody","ReposCreateCommitCommentRequest","ReposCreateCommitCommentResponse","ReposCreateCommitSignatureProtectionPathParams","ReposCreateCommitSignatureProtectionRequest","ReposCreateCommitSignatureProtectionResponse","ReposCreateCommitStatusPathParams","ReposCreateCommitStatusRequestBodyStateEnum","ReposCreateCommitStatusRequestBody","ReposCreateCommitStatusRequest","ReposCreateCommitStatusResponse","ReposCreateDeployKeyPathParams","ReposCreateDeployKeyRequestBody","ReposCreateDeployKeyRequest","ReposCreateDeployKeyResponse","ReposCreateDeploymentPathParams","ReposCreateDeploymentRequestBody","ReposCreateDeploymentRequest","ReposCreateDeployment202ApplicationJSON","ReposCreateDeploymentResponse","ReposCreateDeploymentStatusPathParams","ReposCreateDeploymentStatusRequestBodyEnvironmentEnum","ReposCreateDeploymentStatusRequestBodyStateEnum","ReposCreateDeploymentStatusRequestBody","ReposCreateDeploymentStatusRequest","ReposCreateDeploymentStatusResponse","ReposCreateForAuthenticatedUserRequestBody","ReposCreateForAuthenticatedUserRequest","ReposCreateForAuthenticatedUserResponse","ReposCreateForkPathParams","ReposCreateForkRequestBody","ReposCreateForkRequest","ReposCreateForkResponse","ReposCreateInOrgPathParams","ReposCreateInOrgRequestBodyVisibilityEnum","ReposCreateInOrgRequestBody","ReposCreateInOrgRequest","ReposCreateInOrgResponse","ReposCreateOrUpdateFileContentsPathParams","ReposCreateOrUpdateFileContentsRequestBodyAuthor","ReposCreateOrUpdateFileContentsRequestBodyCommitter","ReposCreateOrUpdateFileContentsRequestBody","ReposCreateOrUpdateFileContentsRequest","ReposCreateOrUpdateFileContentsResponse","ReposCreatePagesSitePathParams","ReposCreatePagesSiteRequestBodySourceBranchEnum","ReposCreatePagesSiteRequestBodySourcePathEnum","ReposCreatePagesSiteRequestBodySource","ReposCreatePagesSiteRequestBody","ReposCreatePagesSiteRequest","ReposCreatePagesSite415ApplicationJSON","ReposCreatePagesSiteResponse","ReposCreateReleasePathParams","ReposCreateReleaseRequestBody","ReposCreateReleaseRequest","ReposCreateReleaseResponse","ReposCreateUsingTemplatePathParams","ReposCreateUsingTemplateRequestBody","ReposCreateUsingTemplateRequest","ReposCreateUsingTemplateResponse","ReposCreateWebhookPathParams","ReposCreateWebhookRequestBodyConfig","ReposCreateWebhookRequestBody","ReposCreateWebhookRequest","ReposCreateWebhookResponse","ReposDeclineInvitationPathParams","ReposDeclineInvitationRequest","ReposDeclineInvitationResponse","ReposDeletePathParams","ReposDeleteRequest","ReposDelete403ApplicationJSON","ReposDeleteResponse","ReposDeleteAccessRestrictionsPathParams","ReposDeleteAccessRestrictionsRequest","ReposDeleteAccessRestrictionsResponse","ReposDeleteAdminBranchProtectionPathParams","ReposDeleteAdminBranchProtectionRequest","ReposDeleteAdminBranchProtectionResponse","ReposDeleteBranchProtectionPathParams","ReposDeleteBranchProtectionRequest","ReposDeleteBranchProtectionResponse","ReposDeleteCommitCommentPathParams","ReposDeleteCommitCommentRequest","ReposDeleteCommitCommentResponse","ReposDeleteCommitSignatureProtectionPathParams","ReposDeleteCommitSignatureProtectionRequest","ReposDeleteCommitSignatureProtectionResponse","ReposDeleteDeployKeyPathParams","ReposDeleteDeployKeyRequest","ReposDeleteDeployKeyResponse","ReposDeleteFilePathParams","ReposDeleteFileRequestBodyAuthor","ReposDeleteFileRequestBodyCommitter","ReposDeleteFileRequestBody","ReposDeleteFileRequest","ReposDeleteFile503ApplicationJSON","ReposDeleteFileResponse","ReposDeleteInvitationPathParams","ReposDeleteInvitationRequest","ReposDeleteInvitationResponse","ReposDeletePagesSitePathParams","ReposDeletePagesSiteRequest","ReposDeletePagesSite415ApplicationJSON","ReposDeletePagesSiteResponse","ReposDeletePullRequestReviewProtectionPathParams","ReposDeletePullRequestReviewProtectionRequest","ReposDeletePullRequestReviewProtectionResponse","ReposDeleteReleasePathParams","ReposDeleteReleaseRequest","ReposDeleteReleaseResponse","ReposDeleteReleaseAssetPathParams","ReposDeleteReleaseAssetRequest","ReposDeleteReleaseAssetResponse","ReposDeleteWebhookPathParams","ReposDeleteWebhookRequest","ReposDeleteWebhookResponse","ReposDownloadTarballArchivePathParams","ReposDownloadTarballArchiveRequest","ReposDownloadTarballArchiveResponse","ReposDownloadZipballArchivePathParams","ReposDownloadZipballArchiveRequest","ReposDownloadZipballArchiveResponse","ReposGetPathParams","ReposGetRequest","ReposGetResponse","ReposGetAccessRestrictionsPathParams","ReposGetAccessRestrictionsRequest","ReposGetAccessRestrictionsResponse","ReposGetAdminBranchProtectionPathParams","ReposGetAdminBranchProtectionRequest","ReposGetAdminBranchProtectionResponse","ReposGetAllStatusCheckContextsPathParams","ReposGetAllStatusCheckContextsRequest","ReposGetAllStatusCheckContextsResponse","ReposGetAllTopicsPathParams","ReposGetAllTopicsQueryParams","ReposGetAllTopicsRequest","ReposGetAllTopics415ApplicationJSON","ReposGetAllTopicsResponse","ReposGetAppsWithAccessToProtectedBranchPathParams","ReposGetAppsWithAccessToProtectedBranchRequest","ReposGetAppsWithAccessToProtectedBranchResponse","ReposGetBranchPathParams","ReposGetBranchRequest","ReposGetBranch415ApplicationJSON","ReposGetBranchResponse","ReposGetBranchProtectionPathParams","ReposGetBranchProtectionRequest","ReposGetBranchProtectionResponse","ReposGetCodeFrequencyStatsPathParams","ReposGetCodeFrequencyStatsRequest","ReposGetCodeFrequencyStatsResponse","ReposGetCollaboratorPermissionLevelPathParams","ReposGetCollaboratorPermissionLevelRequest","ReposGetCollaboratorPermissionLevelResponse","ReposGetCombinedStatusForRefPathParams","ReposGetCombinedStatusForRefQueryParams","ReposGetCombinedStatusForRefRequest","ReposGetCombinedStatusForRefResponse","ReposGetCommitPathParams","ReposGetCommitQueryParams","ReposGetCommitRequest","ReposGetCommitResponse","ReposGetCommitActivityStatsPathParams","ReposGetCommitActivityStatsRequest","ReposGetCommitActivityStatsResponse","ReposGetCommitCommentPathParams","ReposGetCommitCommentRequest","ReposGetCommitCommentResponse","ReposGetCommitSignatureProtectionPathParams","ReposGetCommitSignatureProtectionRequest","ReposGetCommitSignatureProtectionResponse","ReposGetContentPathParams","ReposGetContentQueryParams","ReposGetContentRequest","ReposGetContentResponse","ReposGetContributorsStatsPathParams","ReposGetContributorsStatsRequest","ReposGetContributorsStatsResponse","ReposGetDeployKeyPathParams","ReposGetDeployKeyRequest","ReposGetDeployKeyResponse","ReposGetDeploymentPathParams","ReposGetDeploymentRequest","ReposGetDeploymentResponse","ReposGetDeploymentStatusPathParams","ReposGetDeploymentStatusRequest","ReposGetDeploymentStatus415ApplicationJSON","ReposGetDeploymentStatusResponse","ReposGetLatestPagesBuildPathParams","ReposGetLatestPagesBuildRequest","ReposGetLatestPagesBuildResponse","ReposGetLatestReleasePathParams","ReposGetLatestReleaseRequest","ReposGetLatestReleaseResponse","ReposGetPagesPathParams","ReposGetPagesRequest","ReposGetPagesResponse","ReposGetPagesBuildPathParams","ReposGetPagesBuildRequest","ReposGetPagesBuildResponse","ReposGetParticipationStatsPathParams","ReposGetParticipationStatsRequest","ReposGetParticipationStatsResponse","ReposGetPullRequestReviewProtectionPathParams","ReposGetPullRequestReviewProtectionRequest","ReposGetPullRequestReviewProtectionResponse","ReposGetPunchCardStatsPathParams","ReposGetPunchCardStatsRequest","ReposGetPunchCardStatsResponse","ReposGetReadmePathParams","ReposGetReadmeQueryParams","ReposGetReadmeRequest","ReposGetReadmeResponse","ReposGetReadmeInDirectoryPathParams","ReposGetReadmeInDirectoryQueryParams","ReposGetReadmeInDirectoryRequest","ReposGetReadmeInDirectoryResponse","ReposGetReleasePathParams","ReposGetReleaseRequest","ReposGetReleaseResponse","ReposGetReleaseAssetPathParams","ReposGetReleaseAssetRequest","ReposGetReleaseAsset415ApplicationJSON","ReposGetReleaseAssetResponse","ReposGetReleaseByTagPathParams","ReposGetReleaseByTagRequest","ReposGetReleaseByTagResponse","ReposGetStatusChecksProtectionPathParams","ReposGetStatusChecksProtectionRequest","ReposGetStatusChecksProtectionResponse","ReposGetTeamsWithAccessToProtectedBranchPathParams","ReposGetTeamsWithAccessToProtectedBranchRequest","ReposGetTeamsWithAccessToProtectedBranchResponse","ReposGetUsersWithAccessToProtectedBranchPathParams","ReposGetUsersWithAccessToProtectedBranchRequest","ReposGetUsersWithAccessToProtectedBranchResponse","ReposGetWebhookPathParams","ReposGetWebhookRequest","ReposGetWebhookResponse","ReposListBranchesPathParams","ReposListBranchesQueryParams","ReposListBranchesRequest","ReposListBranchesResponse","ReposListBranchesForHeadCommitPathParams","ReposListBranchesForHeadCommitRequest","ReposListBranchesForHeadCommit415ApplicationJSON","ReposListBranchesForHeadCommitResponse","ReposListCollaboratorsPathParams","ReposListCollaboratorsQueryParams","ReposListCollaboratorsRequest","ReposListCollaboratorsResponse","ReposListCommentsForCommitPathParams","ReposListCommentsForCommitQueryParams","ReposListCommentsForCommitRequest","ReposListCommentsForCommitResponse","ReposListCommitCommentsForRepoPathParams","ReposListCommitCommentsForRepoQueryParams","ReposListCommitCommentsForRepoRequest","ReposListCommitCommentsForRepoResponse","ReposListCommitStatusesForRefPathParams","ReposListCommitStatusesForRefQueryParams","ReposListCommitStatusesForRefRequest","ReposListCommitStatusesForRefResponse","ReposListCommitsPathParams","ReposListCommitsQueryParams","ReposListCommitsRequest","ReposListCommitsResponse","ReposListContributorsPathParams","ReposListContributorsQueryParams","ReposListContributorsRequest","ReposListContributorsResponse","ReposListDeployKeysPathParams","ReposListDeployKeysQueryParams","ReposListDeployKeysRequest","ReposListDeployKeysResponse","ReposListDeploymentStatusesPathParams","ReposListDeploymentStatusesQueryParams","ReposListDeploymentStatusesRequest","ReposListDeploymentStatusesResponse","ReposListDeploymentsPathParams","ReposListDeploymentsQueryParams","ReposListDeploymentsRequest","ReposListDeploymentsResponse","ReposListForAuthenticatedUserDirectionEnum","ReposListForAuthenticatedUserSortEnum","ReposListForAuthenticatedUserTypeEnum","ReposListForAuthenticatedUserVisibilityEnum","ReposListForAuthenticatedUserQueryParams","ReposListForAuthenticatedUserRequest","ReposListForAuthenticatedUserResponse","ReposListForOrgPathParams","ReposListForOrgQueryParams","ReposListForOrgRequest","ReposListForOrgResponse","ReposListForUserPathParams","ReposListForUserQueryParams","ReposListForUserRequest","ReposListForUserResponse","ReposListForksPathParams","ReposListForksQueryParams","ReposListForksRequest","ReposListForksResponse","ReposListInvitationsPathParams","ReposListInvitationsQueryParams","ReposListInvitationsRequest","ReposListInvitationsResponse","ReposListInvitationsForAuthenticatedUserQueryParams","ReposListInvitationsForAuthenticatedUserRequest","ReposListInvitationsForAuthenticatedUserResponse","ReposListLanguagesPathParams","ReposListLanguagesRequest","ReposListLanguagesResponse","ReposListPagesBuildsPathParams","ReposListPagesBuildsQueryParams","ReposListPagesBuildsRequest","ReposListPagesBuildsResponse","ReposListPublicQueryParams","ReposListPublicRequest","ReposListPublicResponse","ReposListPullRequestsAssociatedWithCommitPathParams","ReposListPullRequestsAssociatedWithCommitQueryParams","ReposListPullRequestsAssociatedWithCommitRequest","ReposListPullRequestsAssociatedWithCommit415ApplicationJSON","ReposListPullRequestsAssociatedWithCommitResponse","ReposListReleaseAssetsPathParams","ReposListReleaseAssetsQueryParams","ReposListReleaseAssetsRequest","ReposListReleaseAssetsResponse","ReposListReleasesPathParams","ReposListReleasesQueryParams","ReposListReleasesRequest","ReposListReleasesResponse","ReposListTagsPathParams","ReposListTagsQueryParams","ReposListTagsRequest","ReposListTagsResponse","ReposListTeamsPathParams","ReposListTeamsQueryParams","ReposListTeamsRequest","ReposListTeamsResponse","ReposListWebhooksPathParams","ReposListWebhooksQueryParams","ReposListWebhooksRequest","ReposListWebhooksResponse","ReposMergePathParams","ReposMergeRequestBody","ReposMergeRequest","ReposMergeResponse","ReposPingWebhookPathParams","ReposPingWebhookRequest","ReposPingWebhookResponse","ReposRemoveAppAccessRestrictionsPathParams","ReposRemoveAppAccessRestrictionsRequestBody1","ReposRemoveAppAccessRestrictionsRequest","ReposRemoveAppAccessRestrictionsResponse","ReposRemoveCollaboratorPathParams","ReposRemoveCollaboratorRequest","ReposRemoveCollaboratorResponse","ReposRemoveStatusCheckContextsPathParams","ReposRemoveStatusCheckContextsRequestBody1","ReposRemoveStatusCheckContextsRequest","ReposRemoveStatusCheckContextsResponse","ReposRemoveStatusCheckProtectionPathParams","ReposRemoveStatusCheckProtectionRequest","ReposRemoveStatusCheckProtectionResponse","ReposRemoveTeamAccessRestrictionsPathParams","ReposRemoveTeamAccessRestrictionsRequestBody1","ReposRemoveTeamAccessRestrictionsRequest","ReposRemoveTeamAccessRestrictionsResponse","ReposRemoveUserAccessRestrictionsPathParams","ReposRemoveUserAccessRestrictionsRequestBody1","ReposRemoveUserAccessRestrictionsRequest","ReposRemoveUserAccessRestrictionsResponse","ReposReplaceAllTopicsPathParams","ReposReplaceAllTopicsRequestBody","ReposReplaceAllTopicsRequest","ReposReplaceAllTopics415ApplicationJSON","ReposReplaceAllTopicsResponse","ReposRequestPagesBuildPathParams","ReposRequestPagesBuildRequest","ReposRequestPagesBuildResponse","ReposSetAdminBranchProtectionPathParams","ReposSetAdminBranchProtectionRequest","ReposSetAdminBranchProtectionResponse","ReposSetAppAccessRestrictionsPathParams","ReposSetAppAccessRestrictionsRequestBody1","ReposSetAppAccessRestrictionsRequest","ReposSetAppAccessRestrictionsResponse","ReposSetStatusCheckContextsPathParams","ReposSetStatusCheckContextsRequestBody1","ReposSetStatusCheckContextsRequest","ReposSetStatusCheckContextsResponse","ReposSetTeamAccessRestrictionsPathParams","ReposSetTeamAccessRestrictionsRequestBody1","ReposSetTeamAccessRestrictionsRequest","ReposSetTeamAccessRestrictionsResponse","ReposSetUserAccessRestrictionsPathParams","ReposSetUserAccessRestrictionsRequestBody1","ReposSetUserAccessRestrictionsRequest","ReposSetUserAccessRestrictionsResponse","ReposTestPushWebhookPathParams","ReposTestPushWebhookRequest","ReposTestPushWebhookResponse","ReposTransferPathParams","ReposTransferRequestBody","ReposTransferRequest","ReposTransferResponse","ReposUpdatePathParams","ReposUpdateRequestBodyVisibilityEnum","ReposUpdateRequestBody","ReposUpdateRequest","ReposUpdateResponse","ReposUpdateBranchProtectionPathParams","ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviewsDismissalRestrictions","ReposUpdateBranchProtectionRequestBodyRequiredPullRequestReviews","ReposUpdateBranchProtectionRequestBodyRequiredStatusChecks","ReposUpdateBranchProtectionRequestBodyRestrictions","ReposUpdateBranchProtectionRequestBody","ReposUpdateBranchProtectionRequest","ReposUpdateBranchProtection415ApplicationJSON","ReposUpdateBranchProtectionResponse","ReposUpdateCommitCommentPathParams","ReposUpdateCommitCommentRequestBody","ReposUpdateCommitCommentRequest","ReposUpdateCommitCommentResponse","ReposUpdateInformationAboutPagesSitePathParams","ReposUpdateInformationAboutPagesSiteRequestBodySourceEnum","ReposUpdateInformationAboutPagesSiteRequestBody","ReposUpdateInformationAboutPagesSiteRequest","ReposUpdateInformationAboutPagesSiteResponse","ReposUpdateInvitationPathParams","ReposUpdateInvitationRequestBodyPermissionsEnum","ReposUpdateInvitationRequestBody","ReposUpdateInvitationRequest","ReposUpdateInvitationResponse","ReposUpdatePullRequestReviewProtectionPathParams","ReposUpdatePullRequestReviewProtectionRequestBodyDismissalRestrictions","ReposUpdatePullRequestReviewProtectionRequestBody","ReposUpdatePullRequestReviewProtectionRequest","ReposUpdatePullRequestReviewProtectionResponse","ReposUpdateReleasePathParams","ReposUpdateReleaseRequestBody","ReposUpdateReleaseRequest","ReposUpdateReleaseResponse","ReposUpdateReleaseAssetPathParams","ReposUpdateReleaseAssetRequestBody","ReposUpdateReleaseAssetRequest","ReposUpdateReleaseAssetResponse","ReposUpdateStatusCheckProtectionPathParams","ReposUpdateStatusCheckProtectionRequestBody","ReposUpdateStatusCheckProtectionRequest","ReposUpdateStatusCheckProtectionResponse","ReposUpdateWebhookPathParams","ReposUpdateWebhookRequestBodyConfig","ReposUpdateWebhookRequestBody","ReposUpdateWebhookRequest","ReposUpdateWebhookResponse","ReposUploadReleaseAssetPathParams","ReposUploadReleaseAssetQueryParams","ReposUploadReleaseAssetRequest","ReposUploadReleaseAssetResponse","SearchCodeSortEnum","SearchCodeQueryParams","SearchCodeRequest","SearchCode200ApplicationJSON","SearchCode503ApplicationJSON","SearchCodeResponse","SearchCommitsSortEnum","SearchCommitsQueryParams","SearchCommitsRequest","SearchCommits200ApplicationJSON","SearchCommits415ApplicationJSON","SearchCommitsResponse","SearchIssuesAndPullRequestsSortEnum","SearchIssuesAndPullRequestsQueryParams","SearchIssuesAndPullRequestsRequest","SearchIssuesAndPullRequests200ApplicationJSON","SearchIssuesAndPullRequests503ApplicationJSON","SearchIssuesAndPullRequestsResponse","SearchLabelsSortEnum","SearchLabelsQueryParams","SearchLabelsRequest","SearchLabels200ApplicationJSON","SearchLabelsResponse","SearchReposSortEnum","SearchReposQueryParams","SearchReposRequest","SearchRepos200ApplicationJSON","SearchRepos503ApplicationJSON","SearchReposResponse","SearchTopicsQueryParams","SearchTopicsRequest","SearchTopics200ApplicationJSON","SearchTopics415ApplicationJSON","SearchTopicsResponse","SearchUsersSortEnum","SearchUsersQueryParams","SearchUsersRequest","SearchUsers200ApplicationJSON","SearchUsers503ApplicationJSON","SearchUsersResponse","TeamsAddMemberLegacyPathParams","TeamsAddMemberLegacyRequest","TeamsAddMemberLegacyResponse","TeamsAddOrUpdateMembershipForUserPathParams","TeamsAddOrUpdateMembershipForUserRequestBodyRoleEnum","TeamsAddOrUpdateMembershipForUserRequestBody","TeamsAddOrUpdateMembershipForUserRequest","TeamsAddOrUpdateMembershipForUserResponse","TeamsAddOrUpdateProjectPermissionsPathParams","TeamsAddOrUpdateProjectPermissionsHeaders","TeamsAddOrUpdateProjectPermissionsRequestBodyPermissionEnum","TeamsAddOrUpdateProjectPermissionsRequestBody","TeamsAddOrUpdateProjectPermissionsRequest","TeamsAddOrUpdateProjectPermissions403ApplicationJSON","TeamsAddOrUpdateProjectPermissionsResponse","TeamsAddOrUpdateRepoPermissionsPathParams","TeamsAddOrUpdateRepoPermissionsRequestBodyPermissionEnum","TeamsAddOrUpdateRepoPermissionsRequestBody","TeamsAddOrUpdateRepoPermissionsRequest","TeamsAddOrUpdateRepoPermissionsResponse","TeamsCheckPermissionsForProjectPathParams","TeamsCheckPermissionsForProjectHeaders","TeamsCheckPermissionsForProjectRequest","TeamsCheckPermissionsForProjectResponse","TeamsCheckPermissionsForRepoPathParams","TeamsCheckPermissionsForRepoRequest","TeamsCheckPermissionsForRepoResponse","TeamsCreatePathParams","TeamsCreateRequestBodyPermissionEnum","TeamsCreateRequestBodyPrivacyEnum","TeamsCreateRequestBody","TeamsCreateRequest","TeamsCreateResponse","TeamsCreateDiscussionPathParams","TeamsCreateDiscussionRequestBody","TeamsCreateDiscussionRequest","TeamsCreateDiscussionResponse","TeamsCreateDiscussionCommentPathParams","TeamsCreateDiscussionCommentRequestBody","TeamsCreateDiscussionCommentRequest","TeamsCreateDiscussionCommentResponse","TeamsDeletePathParams","TeamsDeleteRequest","TeamsDeleteResponse","TeamsDeleteDiscussionPathParams","TeamsDeleteDiscussionRequest","TeamsDeleteDiscussionResponse","TeamsDeleteDiscussionCommentPathParams","TeamsDeleteDiscussionCommentRequest","TeamsDeleteDiscussionCommentResponse","TeamsGetPathParams","TeamsGetRequest","TeamsGetResponse","TeamsGetByNamePathParams","TeamsGetByNameRequest","TeamsGetByNameResponse","TeamsGetDiscussionPathParams","TeamsGetDiscussionRequest","TeamsGetDiscussionResponse","TeamsGetDiscussionCommentPathParams","TeamsGetDiscussionCommentRequest","TeamsGetDiscussionCommentResponse","TeamsGetMemberLegacyPathParams","TeamsGetMemberLegacyRequest","TeamsGetMemberLegacyResponse","TeamsGetMembershipForUserPathParams","TeamsGetMembershipForUserRequest","TeamsGetMembershipForUserResponse","TeamsListPathParams","TeamsListQueryParams","TeamsListRequest","TeamsListResponse","TeamsListChildPathParams","TeamsListChildQueryParams","TeamsListChildRequest","TeamsListChildResponse","TeamsListDiscussionCommentsPathParams","TeamsListDiscussionCommentsQueryParams","TeamsListDiscussionCommentsRequest","TeamsListDiscussionCommentsResponse","TeamsListDiscussionsPathParams","TeamsListDiscussionsQueryParams","TeamsListDiscussionsRequest","TeamsListDiscussionsResponse","TeamsListForAuthenticatedUserQueryParams","TeamsListForAuthenticatedUserRequest","TeamsListForAuthenticatedUserResponse","TeamsListMembersPathParams","TeamsListMembersQueryParams","TeamsListMembersRequest","TeamsListMembersResponse","TeamsListProjectsPathParams","TeamsListProjectsQueryParams","TeamsListProjectsHeaders","TeamsListProjectsRequest","TeamsListProjectsResponse","TeamsListReposPathParams","TeamsListReposQueryParams","TeamsListReposRequest","TeamsListReposResponse","TeamsRemoveMemberLegacyPathParams","TeamsRemoveMemberLegacyRequest","TeamsRemoveMemberLegacyResponse","TeamsRemoveMembershipForUserPathParams","TeamsRemoveMembershipForUserRequest","TeamsRemoveMembershipForUserResponse","TeamsRemoveProjectPathParams","TeamsRemoveProjectRequest","TeamsRemoveProjectResponse","TeamsRemoveRepoPathParams","TeamsRemoveRepoRequest","TeamsRemoveRepoResponse","TeamsUpdatePathParams","TeamsUpdateRequestBodyPermissionEnum","TeamsUpdateRequestBodyPrivacyEnum","TeamsUpdateRequestBody","TeamsUpdateRequest","TeamsUpdateResponse","TeamsUpdateDiscussionPathParams","TeamsUpdateDiscussionRequestBody","TeamsUpdateDiscussionRequest","TeamsUpdateDiscussionResponse","TeamsUpdateDiscussionCommentPathParams","TeamsUpdateDiscussionCommentRequestBody","TeamsUpdateDiscussionCommentRequest","TeamsUpdateDiscussionCommentResponse","UsersAddEmailForAuthenticatedRequestBody1","UsersAddEmailForAuthenticatedRequest","UsersAddEmailForAuthenticatedResponse","UsersCheckFollowingForUserPathParams","UsersCheckFollowingForUserRequest","UsersCheckFollowingForUserResponse","UsersCheckPersonIsFollowedByAuthenticatedPathParams","UsersCheckPersonIsFollowedByAuthenticatedRequest","UsersCheckPersonIsFollowedByAuthenticatedResponse","UsersCreateGpgKeyForAuthenticatedRequestBody","UsersCreateGpgKeyForAuthenticatedRequest","UsersCreateGpgKeyForAuthenticatedResponse","UsersCreatePublicSSHKeyForAuthenticatedRequestBody","UsersCreatePublicSSHKeyForAuthenticatedRequest","UsersCreatePublicSSHKeyForAuthenticatedResponse","UsersDeleteEmailForAuthenticatedRequestBody1","UsersDeleteEmailForAuthenticatedRequest","UsersDeleteEmailForAuthenticatedResponse","UsersDeleteGpgKeyForAuthenticatedPathParams","UsersDeleteGpgKeyForAuthenticatedRequest","UsersDeleteGpgKeyForAuthenticatedResponse","UsersDeletePublicSSHKeyForAuthenticatedPathParams","UsersDeletePublicSSHKeyForAuthenticatedRequest","UsersDeletePublicSSHKeyForAuthenticatedResponse","UsersFollowPathParams","UsersFollowRequest","UsersFollowResponse","UsersGetAuthenticatedResponse","UsersGetByUsernamePathParams","UsersGetByUsernameRequest","UsersGetByUsernameResponse","UsersGetContextForUserPathParams","UsersGetContextForUserQueryParams","UsersGetContextForUserRequest","UsersGetContextForUserResponse","UsersGetGpgKeyForAuthenticatedPathParams","UsersGetGpgKeyForAuthenticatedRequest","UsersGetGpgKeyForAuthenticatedResponse","UsersGetPublicSSHKeyForAuthenticatedPathParams","UsersGetPublicSSHKeyForAuthenticatedRequest","UsersGetPublicSSHKeyForAuthenticatedResponse","UsersListQueryParams","UsersListRequest","UsersListResponse","UsersListEmailsForAuthenticatedQueryParams","UsersListEmailsForAuthenticatedRequest","UsersListEmailsForAuthenticatedResponse","UsersListFollowedByAuthenticatedQueryParams","UsersListFollowedByAuthenticatedRequest","UsersListFollowedByAuthenticatedResponse","UsersListFollowersForAuthenticatedUserQueryParams","UsersListFollowersForAuthenticatedUserRequest","UsersListFollowersForAuthenticatedUserResponse","UsersListFollowersForUserPathParams","UsersListFollowersForUserQueryParams","UsersListFollowersForUserRequest","UsersListFollowersForUserResponse","UsersListFollowingForUserPathParams","UsersListFollowingForUserQueryParams","UsersListFollowingForUserRequest","UsersListFollowingForUserResponse","UsersListGpgKeysForAuthenticatedQueryParams","UsersListGpgKeysForAuthenticatedRequest","UsersListGpgKeysForAuthenticatedResponse","UsersListGpgKeysForUserPathParams","UsersListGpgKeysForUserQueryParams","UsersListGpgKeysForUserRequest","UsersListGpgKeysForUserResponse","UsersListPublicEmailsForAuthenticatedQueryParams","UsersListPublicEmailsForAuthenticatedRequest","UsersListPublicEmailsForAuthenticatedResponse","UsersListPublicKeysForUserPathParams","UsersListPublicKeysForUserQueryParams","UsersListPublicKeysForUserRequest","UsersListPublicKeysForUserResponse","UsersListPublicSSHKeysForAuthenticatedQueryParams","UsersListPublicSSHKeysForAuthenticatedRequest","UsersListPublicSSHKeysForAuthenticatedResponse","UsersUnfollowPathParams","UsersUnfollowRequest","UsersUnfollowResponse","UsersUpdateAuthenticatedRequestBody","UsersUpdateAuthenticatedRequest","UsersUpdateAuthenticatedResponse"]