/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.net.http.HttpResponse;

public class ChecksRerequestSuiteResponse {
    
    public String contentType;
    public ChecksRerequestSuiteResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ChecksRerequestSuiteResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ChecksRerequestSuiteResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Response
     */
    
    public java.util.Map<String, Object> emptyObject;
    public ChecksRerequestSuiteResponse withEmptyObject(java.util.Map<String, Object> emptyObject) {
        this.emptyObject = emptyObject;
        return this;
    }
    
}
