"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import defaultimportclientbrandingattributes as shared_defaultimportclientbrandingattributes
from ..shared import iosimportclientbrandingattributes as shared_iosimportclientbrandingattributes
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ImportClientBrandingRequest:
    
    resource_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ResourceId') }})  
    device_type_android: Optional[shared_defaultimportclientbrandingattributes.DefaultImportClientBrandingAttributes] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('DeviceTypeAndroid'), 'exclude': lambda f: f is None }})  
    device_type_ios: Optional[shared_iosimportclientbrandingattributes.IosImportClientBrandingAttributes] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('DeviceTypeIos'), 'exclude': lambda f: f is None }})  
    device_type_linux: Optional[shared_defaultimportclientbrandingattributes.DefaultImportClientBrandingAttributes] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('DeviceTypeLinux'), 'exclude': lambda f: f is None }})  
    device_type_osx: Optional[shared_defaultimportclientbrandingattributes.DefaultImportClientBrandingAttributes] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('DeviceTypeOsx'), 'exclude': lambda f: f is None }})  
    device_type_web: Optional[shared_defaultimportclientbrandingattributes.DefaultImportClientBrandingAttributes] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('DeviceTypeWeb'), 'exclude': lambda f: f is None }})  
    device_type_windows: Optional[shared_defaultimportclientbrandingattributes.DefaultImportClientBrandingAttributes] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('DeviceTypeWindows'), 'exclude': lambda f: f is None }})  
    