from .associateconnectionalias import *
from .associateipgroups import *
from .authorizeiprules import *
from .copyworkspaceimage import *
from .createconnectionalias import *
from .createipgroup import *
from .createtags import *
from .createworkspacebundle import *
from .createworkspaces import *
from .deleteconnectionalias import *
from .deleteipgroup import *
from .deletetags import *
from .deleteworkspacebundle import *
from .deleteworkspaceimage import *
from .deregisterworkspacedirectory import *
from .describeaccount import *
from .describeaccountmodifications import *
from .describeclientproperties import *
from .describeconnectionaliases import *
from .describeconnectionaliaspermissions import *
from .describeipgroups import *
from .describetags import *
from .describeworkspacebundles import *
from .describeworkspacedirectories import *
from .describeworkspaceimagepermissions import *
from .describeworkspaceimages import *
from .describeworkspaces import *
from .describeworkspacesconnectionstatus import *
from .describeworkspacesnapshots import *
from .disassociateconnectionalias import *
from .disassociateipgroups import *
from .importworkspaceimage import *
from .listavailablemanagementcidrranges import *
from .migrateworkspace import *
from .modifyaccount import *
from .modifyclientproperties import *
from .modifyselfservicepermissions import *
from .modifyworkspaceaccessproperties import *
from .modifyworkspacecreationproperties import *
from .modifyworkspaceproperties import *
from .modifyworkspacestate import *
from .rebootworkspaces import *
from .rebuildworkspaces import *
from .registerworkspacedirectory import *
from .restoreworkspace import *
from .revokeiprules import *
from .startworkspaces import *
from .stopworkspaces import *
from .terminateworkspaces import *
from .updateconnectionaliaspermission import *
from .updaterulesofipgroup import *
from .updateworkspacebundle import *
from .updateworkspaceimagepermission import *

__all__ = ["AssociateConnectionAliasXAmzTargetEnum","AssociateConnectionAliasHeaders","AssociateConnectionAliasRequest","AssociateConnectionAliasResponse","AssociateIPGroupsXAmzTargetEnum","AssociateIPGroupsHeaders","AssociateIPGroupsRequest","AssociateIPGroupsResponse","AuthorizeIPRulesXAmzTargetEnum","AuthorizeIPRulesHeaders","AuthorizeIPRulesRequest","AuthorizeIPRulesResponse","CopyWorkspaceImageXAmzTargetEnum","CopyWorkspaceImageHeaders","CopyWorkspaceImageRequest","CopyWorkspaceImageResponse","CreateConnectionAliasXAmzTargetEnum","CreateConnectionAliasHeaders","CreateConnectionAliasRequest","CreateConnectionAliasResponse","CreateIPGroupXAmzTargetEnum","CreateIPGroupHeaders","CreateIPGroupRequest","CreateIPGroupResponse","CreateTagsXAmzTargetEnum","CreateTagsHeaders","CreateTagsRequest","CreateTagsResponse","CreateWorkspaceBundleXAmzTargetEnum","CreateWorkspaceBundleHeaders","CreateWorkspaceBundleRequest","CreateWorkspaceBundleResponse","CreateWorkspacesXAmzTargetEnum","CreateWorkspacesHeaders","CreateWorkspacesRequest","CreateWorkspacesResponse","DeleteConnectionAliasXAmzTargetEnum","DeleteConnectionAliasHeaders","DeleteConnectionAliasRequest","DeleteConnectionAliasResponse","DeleteIPGroupXAmzTargetEnum","DeleteIPGroupHeaders","DeleteIPGroupRequest","DeleteIPGroupResponse","DeleteTagsXAmzTargetEnum","DeleteTagsHeaders","DeleteTagsRequest","DeleteTagsResponse","DeleteWorkspaceBundleXAmzTargetEnum","DeleteWorkspaceBundleHeaders","DeleteWorkspaceBundleRequest","DeleteWorkspaceBundleResponse","DeleteWorkspaceImageXAmzTargetEnum","DeleteWorkspaceImageHeaders","DeleteWorkspaceImageRequest","DeleteWorkspaceImageResponse","DeregisterWorkspaceDirectoryXAmzTargetEnum","DeregisterWorkspaceDirectoryHeaders","DeregisterWorkspaceDirectoryRequest","DeregisterWorkspaceDirectoryResponse","DescribeAccountXAmzTargetEnum","DescribeAccountHeaders","DescribeAccountRequest","DescribeAccountResponse","DescribeAccountModificationsXAmzTargetEnum","DescribeAccountModificationsHeaders","DescribeAccountModificationsRequest","DescribeAccountModificationsResponse","DescribeClientPropertiesXAmzTargetEnum","DescribeClientPropertiesHeaders","DescribeClientPropertiesRequest","DescribeClientPropertiesResponse","DescribeConnectionAliasesXAmzTargetEnum","DescribeConnectionAliasesHeaders","DescribeConnectionAliasesRequest","DescribeConnectionAliasesResponse","DescribeConnectionAliasPermissionsXAmzTargetEnum","DescribeConnectionAliasPermissionsHeaders","DescribeConnectionAliasPermissionsRequest","DescribeConnectionAliasPermissionsResponse","DescribeIPGroupsXAmzTargetEnum","DescribeIPGroupsHeaders","DescribeIPGroupsRequest","DescribeIPGroupsResponse","DescribeTagsXAmzTargetEnum","DescribeTagsHeaders","DescribeTagsRequest","DescribeTagsResponse","DescribeWorkspaceBundlesQueryParams","DescribeWorkspaceBundlesXAmzTargetEnum","DescribeWorkspaceBundlesHeaders","DescribeWorkspaceBundlesRequest","DescribeWorkspaceBundlesResponse","DescribeWorkspaceDirectoriesQueryParams","DescribeWorkspaceDirectoriesXAmzTargetEnum","DescribeWorkspaceDirectoriesHeaders","DescribeWorkspaceDirectoriesRequest","DescribeWorkspaceDirectoriesResponse","DescribeWorkspaceImagePermissionsXAmzTargetEnum","DescribeWorkspaceImagePermissionsHeaders","DescribeWorkspaceImagePermissionsRequest","DescribeWorkspaceImagePermissionsResponse","DescribeWorkspaceImagesXAmzTargetEnum","DescribeWorkspaceImagesHeaders","DescribeWorkspaceImagesRequest","DescribeWorkspaceImagesResponse","DescribeWorkspacesQueryParams","DescribeWorkspacesXAmzTargetEnum","DescribeWorkspacesHeaders","DescribeWorkspacesRequest","DescribeWorkspacesResponse","DescribeWorkspacesConnectionStatusXAmzTargetEnum","DescribeWorkspacesConnectionStatusHeaders","DescribeWorkspacesConnectionStatusRequest","DescribeWorkspacesConnectionStatusResponse","DescribeWorkspaceSnapshotsXAmzTargetEnum","DescribeWorkspaceSnapshotsHeaders","DescribeWorkspaceSnapshotsRequest","DescribeWorkspaceSnapshotsResponse","DisassociateConnectionAliasXAmzTargetEnum","DisassociateConnectionAliasHeaders","DisassociateConnectionAliasRequest","DisassociateConnectionAliasResponse","DisassociateIPGroupsXAmzTargetEnum","DisassociateIPGroupsHeaders","DisassociateIPGroupsRequest","DisassociateIPGroupsResponse","ImportWorkspaceImageXAmzTargetEnum","ImportWorkspaceImageHeaders","ImportWorkspaceImageRequest","ImportWorkspaceImageResponse","ListAvailableManagementCidrRangesXAmzTargetEnum","ListAvailableManagementCidrRangesHeaders","ListAvailableManagementCidrRangesRequest","ListAvailableManagementCidrRangesResponse","MigrateWorkspaceXAmzTargetEnum","MigrateWorkspaceHeaders","MigrateWorkspaceRequest","MigrateWorkspaceResponse","ModifyAccountXAmzTargetEnum","ModifyAccountHeaders","ModifyAccountRequest","ModifyAccountResponse","ModifyClientPropertiesXAmzTargetEnum","ModifyClientPropertiesHeaders","ModifyClientPropertiesRequest","ModifyClientPropertiesResponse","ModifySelfservicePermissionsXAmzTargetEnum","ModifySelfservicePermissionsHeaders","ModifySelfservicePermissionsRequest","ModifySelfservicePermissionsResponse","ModifyWorkspaceAccessPropertiesXAmzTargetEnum","ModifyWorkspaceAccessPropertiesHeaders","ModifyWorkspaceAccessPropertiesRequest","ModifyWorkspaceAccessPropertiesResponse","ModifyWorkspaceCreationPropertiesXAmzTargetEnum","ModifyWorkspaceCreationPropertiesHeaders","ModifyWorkspaceCreationPropertiesRequest","ModifyWorkspaceCreationPropertiesResponse","ModifyWorkspacePropertiesXAmzTargetEnum","ModifyWorkspacePropertiesHeaders","ModifyWorkspacePropertiesRequest","ModifyWorkspacePropertiesResponse","ModifyWorkspaceStateXAmzTargetEnum","ModifyWorkspaceStateHeaders","ModifyWorkspaceStateRequest","ModifyWorkspaceStateResponse","RebootWorkspacesXAmzTargetEnum","RebootWorkspacesHeaders","RebootWorkspacesRequest","RebootWorkspacesResponse","RebuildWorkspacesXAmzTargetEnum","RebuildWorkspacesHeaders","RebuildWorkspacesRequest","RebuildWorkspacesResponse","RegisterWorkspaceDirectoryXAmzTargetEnum","RegisterWorkspaceDirectoryHeaders","RegisterWorkspaceDirectoryRequest","RegisterWorkspaceDirectoryResponse","RestoreWorkspaceXAmzTargetEnum","RestoreWorkspaceHeaders","RestoreWorkspaceRequest","RestoreWorkspaceResponse","RevokeIPRulesXAmzTargetEnum","RevokeIPRulesHeaders","RevokeIPRulesRequest","RevokeIPRulesResponse","StartWorkspacesXAmzTargetEnum","StartWorkspacesHeaders","StartWorkspacesRequest","StartWorkspacesResponse","StopWorkspacesXAmzTargetEnum","StopWorkspacesHeaders","StopWorkspacesRequest","StopWorkspacesResponse","TerminateWorkspacesXAmzTargetEnum","TerminateWorkspacesHeaders","TerminateWorkspacesRequest","TerminateWorkspacesResponse","UpdateConnectionAliasPermissionXAmzTargetEnum","UpdateConnectionAliasPermissionHeaders","UpdateConnectionAliasPermissionRequest","UpdateConnectionAliasPermissionResponse","UpdateRulesOfIPGroupXAmzTargetEnum","UpdateRulesOfIPGroupHeaders","UpdateRulesOfIPGroupRequest","UpdateRulesOfIPGroupResponse","UpdateWorkspaceBundleXAmzTargetEnum","UpdateWorkspaceBundleHeaders","UpdateWorkspaceBundleRequest","UpdateWorkspaceBundleResponse","UpdateWorkspaceImagePermissionXAmzTargetEnum","UpdateWorkspaceImagePermissionHeaders","UpdateWorkspaceImagePermissionRequest","UpdateWorkspaceImagePermissionResponse"]