/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DescribeBundleResult -  Result structure contains the details of the bundle. 
 */
public class DescribeBundleResult {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("details")
    public BundleDetails details;
    public DescribeBundleResult withDetails(BundleDetails details) {
        this.details = details;
        return this;
    }
    
}
