/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Period extends SpeakeasyBase {
  /**
   * The sum of all actuals (transactions) in the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "actual_amount" })
  actualAmount?: number;

  /**
   * The currency of the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "currency_code" })
  currencyCode?: string;

  /**
   * Whether this period is current, such that the current date (in the user's time zone) falls within the date range.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "current" })
  current?: boolean;

  /**
   * The end date of the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "end_date" })
  endDate?: string;

  /**
   * The sum of all forecast sources (budget events) in the period, for comparison against the actual amount.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "forecast_amount" })
  forecastAmount?: number;

  /**
   * Whether the budget has been exceeded in the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "over_budget" })
  overBudget?: boolean;

  /**
   * How much the budget has been exceeded by in the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "over_by" })
  overBy?: number;

  /**
   * The percentage of the budget that has been used in the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "percentage_used" })
  percentageUsed?: number;

  /**
   * This attribute tracks the amount that has been refunded or deducted to the actual amount. When a category is set to "always expense", any credit transactions are treated as refunds and when set to "always income", any debit transactions are treated as deductions.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "refund_amount" })
  refundAmount?: number;

  /**
   * The start date of the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "start_date" })
  startDate?: string;

  /**
   * Whether the budget has not been exceeded in the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "under_budget" })
  underBudget?: boolean;

  /**
   * How much there is left in the budget for the period.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "under_by" })
  underBy?: number;
}
