<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * DescribeProductOutput - Success
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class DescribeProductOutput
{
    /**
     * $budgets
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\BudgetDetail> $budgets
     */
	#[\JMS\Serializer\Annotation\SerializedName('Budgets')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\BudgetDetail>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $budgets = null;
    
    /**
     * $launchPaths
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\LaunchPath> $launchPaths
     */
	#[\JMS\Serializer\Annotation\SerializedName('LaunchPaths')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\LaunchPath>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $launchPaths = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('ProductViewSummary')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Shared\ProductViewSummary')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ProductViewSummary $productViewSummary = null;
    
    /**
     * $provisioningArtifacts
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\ProvisioningArtifact> $provisioningArtifacts
     */
	#[\JMS\Serializer\Annotation\SerializedName('ProvisioningArtifacts')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\ProvisioningArtifact>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $provisioningArtifacts = null;
    
	public function __construct()
	{
		$this->budgets = null;
		$this->launchPaths = null;
		$this->productViewSummary = null;
		$this->provisioningArtifacts = null;
	}
}
