from ._xgafv_enum import *
from .activeviewvideoviewabilitymetricconfig import *
from .adloox import *
from .advertiser import *
from .advertiseradserverconfig import *
from .advertisercreativeconfig import *
from .advertiserdataaccessconfig import *
from .advertisergeneralconfig import *
from .advertisersdfconfig import *
from .advertisertargetingconfig import *
from .agerangeassignedtargetingoptiondetails import *
from .agerangetargetingoptiondetails import *
from .alt_enum import *
from .appassignedtargetingoptiondetails import *
from .appcategoryassignedtargetingoptiondetails import *
from .appcategorytargetingoptiondetails import *
from .asset import *
from .assetassociation import *
from .assignedinventorysource import *
from .assignedlocation import *
from .assignedtargetingoption import *
from .assigneduserrole import *
from .audiencegroupassignedtargetingoptiondetails import *
from .audiocontenttypeassignedtargetingoptiondetails import *
from .audiocontenttypetargetingoptiondetails import *
from .audiovideooffset import *
from .auditadvertiserresponse import *
from .authorizedsellerstatusassignedtargetingoptiondetails import *
from .authorizedsellerstatustargetingoptiondetails import *
from .biddingstrategy import *
from .browserassignedtargetingoptiondetails import *
from .browsertargetingoptiondetails import *
from .budgetsummary import *
from .bulkeditadvertiserassignedtargetingoptionsrequest import *
from .bulkeditadvertiserassignedtargetingoptionsresponse import *
from .bulkeditassignedinventorysourcesrequest import *
from .bulkeditassignedinventorysourcesresponse import *
from .bulkeditassignedlocationsrequest import *
from .bulkeditassignedlocationsresponse import *
from .bulkeditassigneduserrolesrequest import *
from .bulkeditassigneduserrolesresponse import *
from .bulkeditlineitemassignedtargetingoptionsrequest import *
from .bulkeditlineitemassignedtargetingoptionsresponse import *
from .bulkeditnegativekeywordsrequest import *
from .bulkeditnegativekeywordsresponse import *
from .bulkeditpartnerassignedtargetingoptionsrequest import *
from .bulkeditpartnerassignedtargetingoptionsresponse import *
from .bulkeditsitesrequest import *
from .bulkeditsitesresponse import *
from .bulklistadvertiserassignedtargetingoptionsresponse import *
from .bulklistcampaignassignedtargetingoptionsresponse import *
from .bulklistinsertionorderassignedtargetingoptionsresponse import *
from .bulklistlineitemassignedtargetingoptionsresponse import *
from .businesschainassignedtargetingoptiondetails import *
from .businesschainsearchterms import *
from .businesschaintargetingoptiondetails import *
from .campaign import *
from .campaignbudget import *
from .campaignflight import *
from .campaigngoal import *
from .carrierandispassignedtargetingoptiondetails import *
from .carrierandisptargetingoptiondetails import *
from .categoryassignedtargetingoptiondetails import *
from .categorytargetingoptiondetails import *
from .channel import *
from .channelassignedtargetingoptiondetails import *
from .cmhybridconfig import *
from .cmtrackingad import *
from .combinedaudience import *
from .combinedaudiencegroup import *
from .combinedaudiencetargetingsetting import *
from .contactinfo import *
from .contactinfolist import *
from .contentdurationassignedtargetingoptiondetails import *
from .contentdurationtargetingoptiondetails import *
from .contentgenreassignedtargetingoptiondetails import *
from .contentgenretargetingoptiondetails import *
from .contentinstreampositionassignedtargetingoptiondetails import *
from .contentinstreampositiontargetingoptiondetails import *
from .contentoutstreampositionassignedtargetingoptiondetails import *
from .contentoutstreampositiontargetingoptiondetails import *
from .contentstreamtypeassignedtargetingoptiondetails import *
from .contentstreamtypetargetingoptiondetails import *
from .conversioncountingconfig import *
from .counterevent import *
from .createassetresponse import *
from .createassignedtargetingoptionsrequest import *
from .createsdfdownloadtaskrequest import *
from .creative import *
from .creativeconfig import *
from .custombiddingalgorithm import *
from .custombiddingmodelreadinessstate import *
from .custombiddingscript import *
from .custombiddingscriptref import *
from .customlist import *
from .customlistgroup import *
from .customlisttargetingsetting import *
from .date_ import *
from .daterange import *
from .dayandtimeassignedtargetingoptiondetails import *
from .deleteassignedtargetingoptionsrequest import *
from .devicemakemodelassignedtargetingoptiondetails import *
from .devicemakemodeltargetingoptiondetails import *
from .devicetypeassignedtargetingoptiondetails import *
from .devicetypetargetingoptiondetails import *
from .digitalcontentlabelassignedtargetingoptiondetails import *
from .digitalcontentlabeltargetingoptiondetails import *
from .dimensions import *
from .doubleverify import *
from .doubleverifyappstarrating import *
from .doubleverifybrandsafetycategories import *
from .doubleverifydisplayviewability import *
from .doubleverifyfraudinvalidtraffic import *
from .doubleverifyvideoviewability import *
from .editcustomermatchmembersrequest import *
from .editcustomermatchmembersresponse import *
from .editguaranteedorderreadaccessorsrequest import *
from .editguaranteedorderreadaccessorsresponse import *
from .editinventorysourcereadwriteaccessorsrequest import *
from .editinventorysourcereadwriteaccessorsrequestadvertisersupdate import *
from .environmentassignedtargetingoptiondetails import *
from .environmenttargetingoptiondetails import *
from .exchangeassignedtargetingoptiondetails import *
from .exchangeconfig import *
from .exchangeconfigenabledexchange import *
from .exchangereviewstatus import *
from .exchangetargetingoptiondetails import *
from .exitevent import *
from .firstandthirdpartyaudience import *
from .firstandthirdpartyaudiencegroup import *
from .firstandthirdpartyaudiencetargetingsetting import *
from .fixedbidstrategy import *
from .floodlightgroup import *
from .frequencycap import *
from .genderassignedtargetingoptiondetails import *
from .gendertargetingoptiondetails import *
from .generatedefaultlineitemrequest import *
from .georegionassignedtargetingoptiondetails import *
from .georegionsearchterms import *
from .georegiontargetingoptiondetails import *
from .googleaudience import *
from .googleaudiencegroup import *
from .googleaudiencetargetingsetting import *
from .googlebytestreammedia import *
from .guaranteedorder import *
from .guaranteedorderstatus import *
from .householdincomeassignedtargetingoptiondetails import *
from .householdincometargetingoptiondetails import *
from .idfilter import *
from .insertionorder import *
from .insertionorderbudget import *
from .insertionorderbudgetsegment import *
from .integraladscience import *
from .integrationdetails import *
from .inventorysource import *
from .inventorysourceaccessors import *
from .inventorysourceaccessorsadvertiseraccessors import *
from .inventorysourceaccessorspartneraccessor import *
from .inventorysourceassignedtargetingoptiondetails import *
from .inventorysourcedisplaycreativeconfig import *
from .inventorysourcefilter import *
from .inventorysourcegroup import *
from .inventorysourcegroupassignedtargetingoptiondetails import *
from .inventorysourcestatus import *
from .inventorysourcevideocreativeconfig import *
from .invoice import *
from .keywordassignedtargetingoptiondetails import *
from .languageassignedtargetingoptiondetails import *
from .languagetargetingoptiondetails import *
from .lineitem import *
from .lineitembudget import *
from .lineitemflight import *
from .listadvertiserassignedtargetingoptionsresponse import *
from .listadvertisersresponse import *
from .listassignedinventorysourcesresponse import *
from .listassignedlocationsresponse import *
from .listcampaignassignedtargetingoptionsresponse import *
from .listcampaignsresponse import *
from .listchannelsresponse import *
from .listcombinedaudiencesresponse import *
from .listcreativesresponse import *
from .listcustombiddingalgorithmsresponse import *
from .listcustombiddingscriptsresponse import *
from .listcustomlistsresponse import *
from .listfirstandthirdpartyaudiencesresponse import *
from .listgoogleaudiencesresponse import *
from .listguaranteedordersresponse import *
from .listinsertionorderassignedtargetingoptionsresponse import *
from .listinsertionordersresponse import *
from .listinventorysourcegroupsresponse import *
from .listinventorysourcesresponse import *
from .listinvoicesresponse import *
from .listlineitemassignedtargetingoptionsresponse import *
from .listlineitemsresponse import *
from .listlocationlistsresponse import *
from .listmanualtriggersresponse import *
from .listnegativekeywordlistsresponse import *
from .listnegativekeywordsresponse import *
from .listpartnerassignedtargetingoptionsresponse import *
from .listpartnersresponse import *
from .listsitesresponse import *
from .listtargetingoptionsresponse import *
from .listusersresponse import *
from .locationlist import *
from .lookbackwindow import *
from .lookupinvoicecurrencyresponse import *
from .manualtrigger import *
from .maximizespendbidstrategy import *
from .measurementconfig import *
from .mobileapp import *
from .mobiledeviceidlist import *
from .money import *
from .nativecontentpositionassignedtargetingoptiondetails import *
from .nativecontentpositiontargetingoptiondetails import *
from .negativekeyword import *
from .negativekeywordlist import *
from .negativekeywordlistassignedtargetingoptiondetails import *
from .obaicon import *
from .omidassignedtargetingoptiondetails import *
from .omidtargetingoptiondetails import *
from .onscreenpositionassignedtargetingoptiondetails import *
from .onscreenpositiontargetingoptiondetails import *
from .operatingsystemassignedtargetingoptiondetails import *
from .operatingsystemtargetingoptiondetails import *
from .operation import *
from .pacing import *
from .parentalstatusassignedtargetingoptiondetails import *
from .parentalstatustargetingoptiondetails import *
from .parententityfilter import *
from .partner import *
from .partneradserverconfig import *
from .partnercost import *
from .partnerdataaccessconfig import *
from .partnergeneralconfig import *
from .partnerrevenuemodel import *
from .performancegoal import *
from .performancegoalbidstrategy import *
from .poiassignedtargetingoptiondetails import *
from .poisearchterms import *
from .poitargetingoptiondetails import *
from .prismaconfig import *
from .prismacpecode import *
from .proximitylocationlistassignedtargetingoptiondetails import *
from .publisherreviewstatus import *
from .ratedetails import *
from .regionallocationlistassignedtargetingoptiondetails import *
from .replacenegativekeywordsrequest import *
from .replacenegativekeywordsresponse import *
from .replacesitesrequest import *
from .replacesitesresponse import *
from .reviewstatusinfo import *
from .scripterror import *
from .sdfconfig import *
from .searchtargetingoptionsrequest import *
from .searchtargetingoptionsresponse import *
from .security import *
from .sensitivecategoryassignedtargetingoptiondetails import *
from .sensitivecategorytargetingoptiondetails import *
from .site import *
from .status import *
from .subexchangeassignedtargetingoptiondetails import *
from .subexchangetargetingoptiondetails import *
from .targetingexpansionconfig import *
from .targetingoption import *
from .thirdpartyonlyconfig import *
from .thirdpartyurl import *
from .thirdpartyverifierassignedtargetingoptiondetails import *
from .timerange import *
from .timerevent import *
from .trackingfloodlightactivityconfig import *
from .transcode import *
from .universaladid import *
from .urlassignedtargetingoptiondetails import *
from .user import *
from .userrewardedcontentassignedtargetingoptiondetails import *
from .userrewardedcontenttargetingoptiondetails import *
from .videoplayersizeassignedtargetingoptiondetails import *
from .videoplayersizetargetingoptiondetails import *
from .viewabilityassignedtargetingoptiondetails import *
from .viewabilitytargetingoptiondetails import *

__all__ = ["XgafvEnum","ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum","ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum","ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum","ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnum","ActiveViewVideoViewabilityMetricConfig","AdlooxExcludedAdlooxCategoriesEnum","Adloox","AdvertiserEntityStatusEnum","Advertiser","AdvertiserInput","AdvertiserAdServerConfig","AdvertiserCreativeConfig","AdvertiserDataAccessConfig","AdvertiserGeneralConfig","AdvertiserGeneralConfigInput","AdvertiserSdfConfig","AdvertiserTargetingConfig","AgeRangeAssignedTargetingOptionDetailsAgeRangeEnum","AgeRangeAssignedTargetingOptionDetails","AgeRangeTargetingOptionDetailsAgeRangeEnum","AgeRangeTargetingOptionDetails","AltEnum","AppAssignedTargetingOptionDetailsAppPlatformEnum","AppAssignedTargetingOptionDetails","AppAssignedTargetingOptionDetailsInput","AppCategoryAssignedTargetingOptionDetails","AppCategoryAssignedTargetingOptionDetailsInput","AppCategoryTargetingOptionDetails","Asset","AssetAssociationRoleEnum","AssetAssociation","AssignedInventorySource","AssignedInventorySourceInput","AssignedLocation","AssignedLocationInput","AssignedTargetingOptionInheritanceEnum","AssignedTargetingOptionTargetingTypeEnum","AssignedTargetingOption","AssignedTargetingOptionInput","AssignedUserRoleUserRoleEnum","AssignedUserRole","AssignedUserRoleInput","AudienceGroupAssignedTargetingOptionDetails","AudioContentTypeAssignedTargetingOptionDetailsAudioContentTypeEnum","AudioContentTypeAssignedTargetingOptionDetails","AudioContentTypeTargetingOptionDetailsAudioContentTypeEnum","AudioContentTypeTargetingOptionDetails","AudioVideoOffset","AuditAdvertiserResponse","AuthorizedSellerStatusAssignedTargetingOptionDetailsAuthorizedSellerStatusEnum","AuthorizedSellerStatusAssignedTargetingOptionDetails","AuthorizedSellerStatusAssignedTargetingOptionDetailsInput","AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnum","AuthorizedSellerStatusTargetingOptionDetails","BiddingStrategy","BrowserAssignedTargetingOptionDetails","BrowserAssignedTargetingOptionDetailsInput","BrowserTargetingOptionDetails","BudgetSummary","BulkEditAdvertiserAssignedTargetingOptionsRequestInput","BulkEditAdvertiserAssignedTargetingOptionsResponse","BulkEditAssignedInventorySourcesRequestInput","BulkEditAssignedInventorySourcesResponse","BulkEditAssignedLocationsRequestInput","BulkEditAssignedLocationsResponse","BulkEditAssignedUserRolesRequestInput","BulkEditAssignedUserRolesResponse","BulkEditLineItemAssignedTargetingOptionsRequestInput","BulkEditLineItemAssignedTargetingOptionsResponse","BulkEditNegativeKeywordsRequestInput","BulkEditNegativeKeywordsResponse","BulkEditPartnerAssignedTargetingOptionsRequestInput","BulkEditPartnerAssignedTargetingOptionsResponse","BulkEditSitesRequestInput","BulkEditSitesResponse","BulkListAdvertiserAssignedTargetingOptionsResponse","BulkListCampaignAssignedTargetingOptionsResponse","BulkListInsertionOrderAssignedTargetingOptionsResponse","BulkListLineItemAssignedTargetingOptionsResponse","BusinessChainAssignedTargetingOptionDetailsProximityRadiusUnitEnum","BusinessChainAssignedTargetingOptionDetails","BusinessChainAssignedTargetingOptionDetailsInput","BusinessChainSearchTerms","BusinessChainTargetingOptionDetailsGeoRegionTypeEnum","BusinessChainTargetingOptionDetails","CampaignEntityStatusEnum","Campaign","CampaignInput","CampaignBudgetBudgetUnitEnum","CampaignBudgetExternalBudgetSourceEnum","CampaignBudget","CampaignFlight","CampaignGoalCampaignGoalTypeEnum","CampaignGoal","CarrierAndIspAssignedTargetingOptionDetails","CarrierAndIspAssignedTargetingOptionDetailsInput","CarrierAndIspTargetingOptionDetailsTypeEnum","CarrierAndIspTargetingOptionDetails","CategoryAssignedTargetingOptionDetails","CategoryAssignedTargetingOptionDetailsInput","CategoryTargetingOptionDetails","Channel","ChannelInput","ChannelAssignedTargetingOptionDetails","CmHybridConfig","CmTrackingAd","CombinedAudience","CombinedAudienceGroup","CombinedAudienceTargetingSetting","ContactInfo","ContactInfoList","ContentDurationAssignedTargetingOptionDetailsContentDurationEnum","ContentDurationAssignedTargetingOptionDetails","ContentDurationAssignedTargetingOptionDetailsInput","ContentDurationTargetingOptionDetailsContentDurationEnum","ContentDurationTargetingOptionDetails","ContentGenreAssignedTargetingOptionDetails","ContentGenreAssignedTargetingOptionDetailsInput","ContentGenreTargetingOptionDetails","ContentInstreamPositionAssignedTargetingOptionDetailsAdTypeEnum","ContentInstreamPositionAssignedTargetingOptionDetailsContentInstreamPositionEnum","ContentInstreamPositionAssignedTargetingOptionDetails","ContentInstreamPositionAssignedTargetingOptionDetailsInput","ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum","ContentInstreamPositionTargetingOptionDetails","ContentOutstreamPositionAssignedTargetingOptionDetailsAdTypeEnum","ContentOutstreamPositionAssignedTargetingOptionDetailsContentOutstreamPositionEnum","ContentOutstreamPositionAssignedTargetingOptionDetails","ContentOutstreamPositionAssignedTargetingOptionDetailsInput","ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum","ContentOutstreamPositionTargetingOptionDetails","ContentStreamTypeAssignedTargetingOptionDetailsContentStreamTypeEnum","ContentStreamTypeAssignedTargetingOptionDetails","ContentStreamTypeAssignedTargetingOptionDetailsInput","ContentStreamTypeTargetingOptionDetailsContentStreamTypeEnum","ContentStreamTypeTargetingOptionDetails","ConversionCountingConfig","CounterEvent","CreateAssetResponse","CreateAssignedTargetingOptionsRequestTargetingTypeEnum","CreateAssignedTargetingOptionsRequestInput","CreateSdfDownloadTaskRequestVersionEnum","CreateSdfDownloadTaskRequest","CreativeCreativeAttributesEnum","CreativeCreativeTypeEnum","CreativeEntityStatusEnum","CreativeExpandingDirectionEnum","CreativeHostingSourceEnum","Creative","CreativeInput","CreativeConfigCreativeTypeEnum","CreativeConfig","CustomBiddingAlgorithmCustomBiddingAlgorithmStateEnum","CustomBiddingAlgorithmCustomBiddingAlgorithmTypeEnum","CustomBiddingAlgorithmEntityStatusEnum","CustomBiddingAlgorithm","CustomBiddingAlgorithmInput","CustomBiddingModelReadinessStateReadinessStateEnum","CustomBiddingModelReadinessState","CustomBiddingScriptStateEnum","CustomBiddingScript","CustomBiddingScriptInput","CustomBiddingScriptRef","CustomList","CustomListGroup","CustomListTargetingSetting","Date","DateRange","DayAndTimeAssignedTargetingOptionDetailsDayOfWeekEnum","DayAndTimeAssignedTargetingOptionDetailsTimeZoneResolutionEnum","DayAndTimeAssignedTargetingOptionDetails","DeleteAssignedTargetingOptionsRequestTargetingTypeEnum","DeleteAssignedTargetingOptionsRequest","DeviceMakeModelAssignedTargetingOptionDetails","DeviceMakeModelAssignedTargetingOptionDetailsInput","DeviceMakeModelTargetingOptionDetails","DeviceTypeAssignedTargetingOptionDetailsDeviceTypeEnum","DeviceTypeAssignedTargetingOptionDetails","DeviceTypeTargetingOptionDetailsDeviceTypeEnum","DeviceTypeTargetingOptionDetails","DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum","DigitalContentLabelAssignedTargetingOptionDetails","DigitalContentLabelAssignedTargetingOptionDetailsInput","DigitalContentLabelTargetingOptionDetailsContentRatingTierEnum","DigitalContentLabelTargetingOptionDetails","Dimensions","DoubleVerifyAvoidedAgeRatingsEnum","DoubleVerify","DoubleVerifyAppStarRatingAvoidedStarRatingEnum","DoubleVerifyAppStarRating","DoubleVerifyBrandSafetyCategoriesAvoidedHighSeverityCategoriesEnum","DoubleVerifyBrandSafetyCategoriesAvoidedMediumSeverityCategoriesEnum","DoubleVerifyBrandSafetyCategories","DoubleVerifyDisplayViewabilityIabEnum","DoubleVerifyDisplayViewabilityViewableDuringEnum","DoubleVerifyDisplayViewability","DoubleVerifyFraudInvalidTrafficAvoidedFraudOptionEnum","DoubleVerifyFraudInvalidTraffic","DoubleVerifyVideoViewabilityPlayerImpressionRateEnum","DoubleVerifyVideoViewabilityVideoIabEnum","DoubleVerifyVideoViewabilityVideoViewableRateEnum","DoubleVerifyVideoViewability","EditCustomerMatchMembersRequest","EditCustomerMatchMembersResponse","EditGuaranteedOrderReadAccessorsRequest","EditGuaranteedOrderReadAccessorsResponse","EditInventorySourceReadWriteAccessorsRequest","EditInventorySourceReadWriteAccessorsRequestAdvertisersUpdate","EnvironmentAssignedTargetingOptionDetailsEnvironmentEnum","EnvironmentAssignedTargetingOptionDetails","EnvironmentTargetingOptionDetailsEnvironmentEnum","EnvironmentTargetingOptionDetails","ExchangeAssignedTargetingOptionDetails","ExchangeConfig","ExchangeConfigEnabledExchangeExchangeEnum","ExchangeConfigEnabledExchange","ExchangeReviewStatusExchangeEnum","ExchangeReviewStatusStatusEnum","ExchangeReviewStatus","ExchangeTargetingOptionDetailsExchangeEnum","ExchangeTargetingOptionDetails","ExitEventTypeEnum","ExitEvent","FirstAndThirdPartyAudienceAudienceSourceEnum","FirstAndThirdPartyAudienceAudienceTypeEnum","FirstAndThirdPartyAudienceFirstAndThirdPartyAudienceTypeEnum","FirstAndThirdPartyAudience","FirstAndThirdPartyAudienceInput","FirstAndThirdPartyAudienceGroup","FirstAndThirdPartyAudienceTargetingSettingRecencyEnum","FirstAndThirdPartyAudienceTargetingSetting","FixedBidStrategy","FloodlightGroupWebTagTypeEnum","FloodlightGroup","FrequencyCapTimeUnitEnum","FrequencyCap","GenderAssignedTargetingOptionDetailsGenderEnum","GenderAssignedTargetingOptionDetails","GenderTargetingOptionDetailsGenderEnum","GenderTargetingOptionDetails","GenerateDefaultLineItemRequestLineItemTypeEnum","GenerateDefaultLineItemRequestInput","GeoRegionAssignedTargetingOptionDetailsGeoRegionTypeEnum","GeoRegionAssignedTargetingOptionDetails","GeoRegionAssignedTargetingOptionDetailsInput","GeoRegionSearchTerms","GeoRegionTargetingOptionDetailsGeoRegionTypeEnum","GeoRegionTargetingOptionDetails","GoogleAudienceGoogleAudienceTypeEnum","GoogleAudience","GoogleAudienceGroup","GoogleAudienceTargetingSetting","GoogleBytestreamMedia","GuaranteedOrderExchangeEnum","GuaranteedOrder","GuaranteedOrderInput","GuaranteedOrderStatusConfigStatusEnum","GuaranteedOrderStatusEntityStatusEnum","GuaranteedOrderStatus","GuaranteedOrderStatusInput","HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum","HouseholdIncomeAssignedTargetingOptionDetails","HouseholdIncomeTargetingOptionDetailsHouseholdIncomeEnum","HouseholdIncomeTargetingOptionDetails","IDFilter","InsertionOrderBillableOutcomeEnum","InsertionOrderEntityStatusEnum","InsertionOrderInsertionOrderTypeEnum","InsertionOrderReservationTypeEnum","InsertionOrder","InsertionOrderInput","InsertionOrderBudgetAutomationTypeEnum","InsertionOrderBudgetBudgetUnitEnum","InsertionOrderBudget","InsertionOrderBudgetSegment","IntegralAdScienceDisplayViewabilityEnum","IntegralAdScienceExcludedAdFraudRiskEnum","IntegralAdScienceExcludedAdultRiskEnum","IntegralAdScienceExcludedAlcoholRiskEnum","IntegralAdScienceExcludedDrugsRiskEnum","IntegralAdScienceExcludedGamblingRiskEnum","IntegralAdScienceExcludedHateSpeechRiskEnum","IntegralAdScienceExcludedIllegalDownloadsRiskEnum","IntegralAdScienceExcludedOffensiveLanguageRiskEnum","IntegralAdScienceExcludedViolenceRiskEnum","IntegralAdScienceTraqScoreOptionEnum","IntegralAdScienceVideoViewabilityEnum","IntegralAdScience","IntegrationDetails","InventorySourceCommitmentEnum","InventorySourceDeliveryMethodEnum","InventorySourceExchangeEnum","InventorySourceInventorySourceProductTypeEnum","InventorySourceInventorySourceTypeEnum","InventorySource","InventorySourceInput","InventorySourceAccessors","InventorySourceAccessorsAdvertiserAccessors","InventorySourceAccessorsPartnerAccessor","InventorySourceAssignedTargetingOptionDetails","InventorySourceDisplayCreativeConfig","InventorySourceFilter","InventorySourceGroup","InventorySourceGroupInput","InventorySourceGroupAssignedTargetingOptionDetails","InventorySourceStatusConfigStatusEnum","InventorySourceStatusEntityStatusEnum","InventorySourceStatusSellerStatusEnum","InventorySourceStatus","InventorySourceStatusInput","InventorySourceVideoCreativeConfig","InvoiceInvoiceTypeEnum","Invoice","KeywordAssignedTargetingOptionDetails","LanguageAssignedTargetingOptionDetails","LanguageAssignedTargetingOptionDetailsInput","LanguageTargetingOptionDetails","LineItemEntityStatusEnum","LineItemLineItemTypeEnum","LineItemReservationTypeEnum","LineItemWarningMessagesEnum","LineItem","LineItemInput","LineItemBudgetBudgetAllocationTypeEnum","LineItemBudgetBudgetUnitEnum","LineItemBudget","LineItemBudgetInput","LineItemFlightFlightDateTypeEnum","LineItemFlight","ListAdvertiserAssignedTargetingOptionsResponse","ListAdvertisersResponse","ListAssignedInventorySourcesResponse","ListAssignedLocationsResponse","ListCampaignAssignedTargetingOptionsResponse","ListCampaignsResponse","ListChannelsResponse","ListCombinedAudiencesResponse","ListCreativesResponse","ListCustomBiddingAlgorithmsResponse","ListCustomBiddingScriptsResponse","ListCustomListsResponse","ListFirstAndThirdPartyAudiencesResponse","ListGoogleAudiencesResponse","ListGuaranteedOrdersResponse","ListInsertionOrderAssignedTargetingOptionsResponse","ListInsertionOrdersResponse","ListInventorySourceGroupsResponse","ListInventorySourcesResponse","ListInvoicesResponse","ListLineItemAssignedTargetingOptionsResponse","ListLineItemsResponse","ListLocationListsResponse","ListManualTriggersResponse","ListNegativeKeywordListsResponse","ListNegativeKeywordsResponse","ListPartnerAssignedTargetingOptionsResponse","ListPartnersResponse","ListSitesResponse","ListTargetingOptionsResponse","ListUsersResponse","LocationListLocationTypeEnum","LocationList","LocationListInput","LookbackWindow","LookupInvoiceCurrencyResponse","ManualTriggerStateEnum","ManualTrigger","ManualTriggerInput","MaximizeSpendBidStrategyPerformanceGoalTypeEnum","MaximizeSpendBidStrategy","MeasurementConfig","MobileAppPlatformEnum","MobileApp","MobileAppInput","MobileDeviceIDList","Money","NativeContentPositionAssignedTargetingOptionDetailsContentPositionEnum","NativeContentPositionAssignedTargetingOptionDetails","NativeContentPositionTargetingOptionDetailsContentPositionEnum","NativeContentPositionTargetingOptionDetails","NegativeKeyword","NegativeKeywordInput","NegativeKeywordList","NegativeKeywordListInput","NegativeKeywordListAssignedTargetingOptionDetails","ObaIconPositionEnum","ObaIcon","OmidAssignedTargetingOptionDetailsOmidEnum","OmidAssignedTargetingOptionDetails","OmidTargetingOptionDetailsOmidEnum","OmidTargetingOptionDetails","OnScreenPositionAssignedTargetingOptionDetailsAdTypeEnum","OnScreenPositionAssignedTargetingOptionDetailsOnScreenPositionEnum","OnScreenPositionAssignedTargetingOptionDetails","OnScreenPositionAssignedTargetingOptionDetailsInput","OnScreenPositionTargetingOptionDetailsOnScreenPositionEnum","OnScreenPositionTargetingOptionDetails","OperatingSystemAssignedTargetingOptionDetails","OperatingSystemAssignedTargetingOptionDetailsInput","OperatingSystemTargetingOptionDetails","Operation","PacingPacingPeriodEnum","PacingPacingTypeEnum","Pacing","ParentalStatusAssignedTargetingOptionDetailsParentalStatusEnum","ParentalStatusAssignedTargetingOptionDetails","ParentalStatusTargetingOptionDetailsParentalStatusEnum","ParentalStatusTargetingOptionDetails","ParentEntityFilterFileTypeEnum","ParentEntityFilterFilterTypeEnum","ParentEntityFilter","PartnerEntityStatusEnum","Partner","PartnerAdServerConfig","PartnerCostCostTypeEnum","PartnerCostFeeTypeEnum","PartnerCostInvoiceTypeEnum","PartnerCost","PartnerDataAccessConfig","PartnerGeneralConfig","PartnerRevenueModelMarkupTypeEnum","PartnerRevenueModel","PerformanceGoalPerformanceGoalTypeEnum","PerformanceGoal","PerformanceGoalBidStrategyPerformanceGoalTypeEnum","PerformanceGoalBidStrategy","PoiAssignedTargetingOptionDetailsProximityRadiusUnitEnum","PoiAssignedTargetingOptionDetails","PoiAssignedTargetingOptionDetailsInput","PoiSearchTerms","PoiTargetingOptionDetails","PrismaConfigPrismaTypeEnum","PrismaConfig","PrismaCpeCode","ProximityLocationListAssignedTargetingOptionDetailsProximityRadiusRangeEnum","ProximityLocationListAssignedTargetingOptionDetails","PublisherReviewStatusStatusEnum","PublisherReviewStatus","RateDetailsInventorySourceRateTypeEnum","RateDetails","RegionalLocationListAssignedTargetingOptionDetails","ReplaceNegativeKeywordsRequestInput","ReplaceNegativeKeywordsResponse","ReplaceSitesRequestInput","ReplaceSitesResponse","ReviewStatusInfoApprovalStatusEnum","ReviewStatusInfoContentAndPolicyReviewStatusEnum","ReviewStatusInfoCreativeAndLandingPageReviewStatusEnum","ReviewStatusInfo","ScriptErrorErrorCodeEnum","ScriptError","SdfConfigVersionEnum","SdfConfig","SearchTargetingOptionsRequest","SearchTargetingOptionsResponse","SchemeOauth2","SchemeOauth2c","SensitiveCategoryAssignedTargetingOptionDetailsSensitiveCategoryEnum","SensitiveCategoryAssignedTargetingOptionDetails","SensitiveCategoryAssignedTargetingOptionDetailsInput","SensitiveCategoryTargetingOptionDetailsSensitiveCategoryEnum","SensitiveCategoryTargetingOptionDetails","Site","SiteInput","Status","SubExchangeAssignedTargetingOptionDetails","SubExchangeTargetingOptionDetails","TargetingExpansionConfigTargetingExpansionLevelEnum","TargetingExpansionConfig","TargetingOptionTargetingTypeEnum","TargetingOption","ThirdPartyOnlyConfig","ThirdPartyURLTypeEnum","ThirdPartyURL","ThirdPartyVerifierAssignedTargetingOptionDetails","TimeRange","TimerEvent","TrackingFloodlightActivityConfig","Transcode","UniversalAdIDRegistryEnum","UniversalAdID","URLAssignedTargetingOptionDetails","User","UserInput","UserRewardedContentAssignedTargetingOptionDetailsUserRewardedContentEnum","UserRewardedContentAssignedTargetingOptionDetails","UserRewardedContentAssignedTargetingOptionDetailsInput","UserRewardedContentTargetingOptionDetailsUserRewardedContentEnum","UserRewardedContentTargetingOptionDetails","VideoPlayerSizeAssignedTargetingOptionDetailsVideoPlayerSizeEnum","VideoPlayerSizeAssignedTargetingOptionDetails","VideoPlayerSizeTargetingOptionDetailsVideoPlayerSizeEnum","VideoPlayerSizeTargetingOptionDetails","ViewabilityAssignedTargetingOptionDetailsViewabilityEnum","ViewabilityAssignedTargetingOptionDetails","ViewabilityTargetingOptionDetailsViewabilityEnum","ViewabilityTargetingOptionDetails"]