package openapisdk.models.shared;


public enum MediaFileMimeTypeEnum {
    VIDEO_MIME_TYPE_UNSPECIFIED("VIDEO_MIME_TYPE_UNSPECIFIED"),
    MIME_VIDEO_XFLV("MIME_VIDEO_XFLV"),
    MIME_VIDEO_WEBM("MIME_VIDEO_WEBM"),
    MIME_VIDEO_MP4("MIME_VIDEO_MP4"),
    MIME_VIDEO_OGG("MIME_VIDEO_OGG"),
    MIME_VIDEO_YT_HOSTED("MIME_VIDEO_YT_HOSTED"),
    MIME_VIDEO_X_MS_WMV("MIME_VIDEO_X_MS_WMV"),
    MIME_VIDEO3_GPP("MIME_VIDEO_3GPP"),
    MIME_VIDEO_MOV("MIME_VIDEO_MOV"),
    MIME_APPLICATION_SWF("MIME_APPLICATION_SWF"),
    MIME_APPLICATION_SURVEY("MIME_APPLICATION_SURVEY"),
    MIME_APPLICATION_JAVASCRIPT("MIME_APPLICATION_JAVASCRIPT"),
    MIME_APPLICATION_SILVERLIGHT("MIME_APPLICATION_SILVERLIGHT"),
    MIME_APPLICATION_MPEGURL("MIME_APPLICATION_MPEGURL"),
    MIME_APPLICATION_MPEGDASH("MIME_APPLICATION_MPEGDASH"),
    MIME_AUDIO_MP4_A("MIME_AUDIO_MP4A"),
    MIME_AUDIO_MP3("MIME_AUDIO_MP3"),
    MIME_AUDIO_OGG("MIME_AUDIO_OGG");

    public final String value;

    private MediaFileMimeTypeEnum(String value) {
        this.value = value;
    }
}
