<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


class TopicSentimentOutput
{
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('language')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $language = null;
    
    /**
     * $sentiments
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\Sentiment> $sentiments
     */
	#[\JMS\Serializer\Annotation\SerializedName('sentiments')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\Sentiment>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $sentiments = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $text = null;
    
    /**
     * $topicSentiments
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\TopicSentiment> $topicSentiments
     */
	#[\JMS\Serializer\Annotation\SerializedName('topicSentiments')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\TopicSentiment>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $topicSentiments = null;
    
    /**
     * $topics
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\Topic> $topics
     */
	#[\JMS\Serializer\Annotation\SerializedName('topics')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\Topic>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $topics = null;
    
	public function __construct()
	{
		$this->id = null;
		$this->language = null;
		$this->sentiments = null;
		$this->text = null;
		$this->topicSentiments = null;
		$this->topics = null;
	}
}
