<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * ResourceCount - <p>Information about the number of results that match the query. At this time, Amazon Web Services Resource Explorer doesn't count more than 1,000 matches for any query. This structure provides information about whether the query exceeded this limit.</p> <p>This field is included in every page when you paginate the results.</p>
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class ResourceCount
{
	#[\JMS\Serializer\Annotation\SerializedName('Complete')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $complete = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('TotalResources')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $totalResources = null;
    
	public function __construct()
	{
		$this->complete = null;
		$this->totalResources = null;
	}
}
