/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DeleteUsageLimitResponse - Success
 */
public class DeleteUsageLimitResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usageLimit")
    public UsageLimit usageLimit;
    public DeleteUsageLimitResponse withUsageLimit(UsageLimit usageLimit) {
        this.usageLimit = usageLimit;
        return this;
    }
    
}
