/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;

public class PostServersIdActionsChangeDnsPtrRequest {
    /**
     * Select the IP address for which to change the DNS entry by passing `ip`. It can be either IPv4 or IPv6. The target hostname is set by passing `dns_ptr`.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PostServersIdActionsChangeDnsPtrRequestBody requestBody;

    public PostServersIdActionsChangeDnsPtrRequest withRequestBody(PostServersIdActionsChangeDnsPtrRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * ID of the Server
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public Long id;

    public PostServersIdActionsChangeDnsPtrRequest withId(Long id) {
        this.id = id;
        return this;
    }
    
    public PostServersIdActionsChangeDnsPtrRequest(@JsonProperty("id") Long id) {
        this.id = id;
  }
}
