/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PutPrimaryIpsIdPrimaryIPResponsePrimaryIPProtection - Protection configuration for the Resource
 */
public class PutPrimaryIpsIdPrimaryIPResponsePrimaryIPProtection {
    /**
     * If true, prevents the Resource from being deleted
     */
    @JsonProperty("delete")
    public Boolean delete;

    public PutPrimaryIpsIdPrimaryIPResponsePrimaryIPProtection withDelete(Boolean delete) {
        this.delete = delete;
        return this;
    }
    
    public PutPrimaryIpsIdPrimaryIPResponsePrimaryIPProtection(@JsonProperty("delete") Boolean delete) {
        this.delete = delete;
  }
}
