"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import reactionforcomment as shared_reactionforcomment
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetCommentReactionsOutput:
    r"""Success"""
    
    reactions_for_comment: list[shared_reactionforcomment.ReactionForComment] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reactionsForComment') }})  
    next_token: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('nextToken'), 'exclude': lambda f: f is None }})  
    