/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreatePlacementGroupResultPlacementGroupStrategyEnum - The placement strategy.
 */
public enum CreatePlacementGroupResultPlacementGroupStrategyEnum {
    CLUSTER("cluster"),
    SPREAD("spread"),
    PARTITION("partition");

    @JsonValue
    public final String value;

    private CreatePlacementGroupResultPlacementGroupStrategyEnum(String value) {
        this.value = value;
    }
}
