/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;



public class DescribeAccountAttributesRequest {
    
    public DescribeAccountAttributesRequestAttributeNamesEnum[] attributeNames;
    public DescribeAccountAttributesRequest withAttributeNames(DescribeAccountAttributesRequestAttributeNamesEnum[] attributeNames) {
        this.attributeNames = attributeNames;
        return this;
    }
    
    
    public Boolean dryRun;
    public DescribeAccountAttributesRequest withDryRun(Boolean dryRun) {
        this.dryRun = dryRun;
        return this;
    }
    
}
