/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;



public class DescribeAddressesRequest {
    
    public String[] allocationIds;

    public DescribeAddressesRequest withAllocationIds(String[] allocationIds) {
        this.allocationIds = allocationIds;
        return this;
    }
    
    
    public Boolean dryRun;

    public DescribeAddressesRequest withDryRun(Boolean dryRun) {
        this.dryRun = dryRun;
        return this;
    }
    
    
    public DescribeAddressesRequestFilters[] filters;

    public DescribeAddressesRequest withFilters(DescribeAddressesRequestFilters[] filters) {
        this.filters = filters;
        return this;
    }
    
    
    public String[] publicIps;

    public DescribeAddressesRequest withPublicIps(String[] publicIps) {
        this.publicIps = publicIps;
        return this;
    }
    
    public DescribeAddressesRequest(){}
}
