// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateDBSubnetGroupMessage - Represents the input to <a>CreateDBSubnetGroup</a>.
type CreateDBSubnetGroupMessage struct {
	DBSubnetGroupDescription string
	DBSubnetGroupName        string
	SubnetIds                []string
	Tags                     []TagList
}
