/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class WxByDistanceUsV1WxForecastDistanceQueryPostResponse {
    
    public String contentType;

    public WxByDistanceUsV1WxForecastDistanceQueryPostResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Validation Error
     */
    
    public org.openapis.openapi.models.shared.HTTPValidationError httpValidationError;

    public WxByDistanceUsV1WxForecastDistanceQueryPostResponse withHTTPValidationError(org.openapis.openapi.models.shared.HTTPValidationError httpValidationError) {
        this.httpValidationError = httpValidationError;
        return this;
    }
    
    
    public Integer statusCode;

    public WxByDistanceUsV1WxForecastDistanceQueryPostResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public WxByDistanceUsV1WxForecastDistanceQueryPostResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A GeoJSON FeatureCollection with one Feature for each forecast location found within requested area.
     */
    
    public org.openapis.openapi.models.shared.WxDistanceResponse wxDistanceResponse;

    public WxByDistanceUsV1WxForecastDistanceQueryPostResponse withWxDistanceResponse(org.openapis.openapi.models.shared.WxDistanceResponse wxDistanceResponse) {
        this.wxDistanceResponse = wxDistanceResponse;
        return this;
    }
    
    public WxByDistanceUsV1WxForecastDistanceQueryPostResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
