<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/**
 */
enum POSTDescribeFlowLogsActionEnum: string
{
    case DESCRIBE_FLOW_LOGS = 'DescribeFlowLogs';
}
