<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class GetShippingMethodsJsonResponse
{
	
    public string $contentType;
    
    /**
     * An array of Shipping Methods
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\ShippingMethod> $shippingMethods
     */
	
    public ?array $shippingMethods = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->shippingMethods = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
