<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/** Protocol of the Load Balancer */
enum PostLoadBalancersIdActionsUpdateServiceLoadBalancerServiceProtocolEnum: string
{
    case TCP = 'tcp';
    case HTTP = 'http';
    case HTTPS = 'https';
}
