/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.net.http.HttpResponse;

public class ListLexiconsResponse {
    
    public String contentType;
    public ListLexiconsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * InvalidNextTokenException
     */
    
    public Object invalidNextTokenException;
    public ListLexiconsResponse withInvalidNextTokenException(Object invalidNextTokenException) {
        this.invalidNextTokenException = invalidNextTokenException;
        return this;
    }
    
    /**
     * Success
     */
    
    public org.openapis.openapi.models.shared.ListLexiconsOutput listLexiconsOutput;
    public ListLexiconsResponse withListLexiconsOutput(org.openapis.openapi.models.shared.ListLexiconsOutput listLexiconsOutput) {
        this.listLexiconsOutput = listLexiconsOutput;
        return this;
    }
    
    
    public Integer statusCode;
    public ListLexiconsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListLexiconsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * ServiceFailureException
     */
    
    public Object serviceFailureException;
    public ListLexiconsResponse withServiceFailureException(Object serviceFailureException) {
        this.serviceFailureException = serviceFailureException;
        return this;
    }
    
}
