/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class DevicesPostRawRequest {
    /**
     * Device object with all the data
     */
    @SpeakeasyMetadata("request:mediaType=text/xml")
    public byte[] request;
    public DevicesPostRawRequest withRequest(byte[] request) {
        this.request = request;
        return this;
    }
    
}
