/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.net.http.HttpResponse;

public class WarehouseByIdResponse {
    
    public String contentType;
    public WarehouseByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;
    public WarehouseByIdResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    
    public Integer statusCode;
    public WarehouseByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public WarehouseByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public WarehouseById200ApplicationJSON warehouseById200ApplicationJSONObject;
    public WarehouseByIdResponse withWarehouseById200ApplicationJSONObject(WarehouseById200ApplicationJSON warehouseById200ApplicationJSONObject) {
        this.warehouseById200ApplicationJSONObject = warehouseById200ApplicationJSONObject;
        return this;
    }
    
}
