// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"openapi/pkg/models/shared"
)

// ModifyEndpointXAmzTargetEnum
type ModifyEndpointXAmzTargetEnum string

const (
	ModifyEndpointXAmzTargetEnumAmazonDmSv20160101ModifyEndpoint ModifyEndpointXAmzTargetEnum = "AmazonDMSv20160101.ModifyEndpoint"
)

func (e ModifyEndpointXAmzTargetEnum) ToPointer() *ModifyEndpointXAmzTargetEnum {
	return &e
}

func (e *ModifyEndpointXAmzTargetEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AmazonDMSv20160101.ModifyEndpoint":
		*e = ModifyEndpointXAmzTargetEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ModifyEndpointXAmzTargetEnum: %v", v)
	}
}

type ModifyEndpointRequest struct {
	ModifyEndpointMessage shared.ModifyEndpointMessage `request:"mediaType=application/json"`
	XAmzAlgorithm         *string                      `header:"style=simple,explode=false,name=X-Amz-Algorithm"`
	XAmzContentSha256     *string                      `header:"style=simple,explode=false,name=X-Amz-Content-Sha256"`
	XAmzCredential        *string                      `header:"style=simple,explode=false,name=X-Amz-Credential"`
	XAmzDate              *string                      `header:"style=simple,explode=false,name=X-Amz-Date"`
	XAmzSecurityToken     *string                      `header:"style=simple,explode=false,name=X-Amz-Security-Token"`
	XAmzSignature         *string                      `header:"style=simple,explode=false,name=X-Amz-Signature"`
	XAmzSignedHeaders     *string                      `header:"style=simple,explode=false,name=X-Amz-SignedHeaders"`
	XAmzTarget            ModifyEndpointXAmzTargetEnum `header:"style=simple,explode=false,name=X-Amz-Target"`
}

type ModifyEndpointResponse struct {
	// AccessDeniedFault
	AccessDeniedFault interface{}
	ContentType       string
	// InvalidResourceStateFault
	InvalidResourceStateFault interface{}
	// KMSKeyNotAccessibleFault
	KMSKeyNotAccessibleFault interface{}
	// Success
	ModifyEndpointResponse *shared.ModifyEndpointResponse
	// ResourceAlreadyExistsFault
	ResourceAlreadyExistsFault interface{}
	StatusCode                 int
	RawResponse                *http.Response
	// ResourceNotFoundFault
	ResourceNotFoundFault interface{}
}
