// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PutEventsResponse - Success
type PutEventsResponse struct {
	// Provides information about endpoints and the events that they're associated with.
	EventsResponse EventsResponse `json:"EventsResponse"`
}
