// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateSmsChannelResponse - Success
type UpdateSmsChannelResponse struct {
	// Provides information about the status and settings of the SMS channel for an application.
	SMSChannelResponse SMSChannelResponse `json:"SMSChannelResponse"`
}
