package openapisdk.models.shared;


public enum FilterRuleParameterDefinitionValueTypeEnum {
    STRING("STRING"),
    BYTE("BYTE"),
    SHORT_("SHORT"),
    CHARACTER("CHARACTER"),
    INTEGER("INTEGER"),
    LONG_("LONG"),
    FLOAT("FLOAT"),
    DOUBLE("DOUBLE"),
    BOOLEAN_("BOOLEAN"),
    BIG_INTEGER("BIG_INTEGER"),
    BIG_DECIMAL("BIG_DECIMAL"),
    LOCAL_DATE("LOCAL_DATE"),
    LOCAL_DATE_TIME("LOCAL_DATE_TIME"),
    TIMESTAMP("TIMESTAMP"),
    BYTE_ARRAY("BYTE_ARRAY"),
    SHORT_ARRAY("SHORT_ARRAY"),
    CHARACTER_ARRAY("CHARACTER_ARRAY"),
    INTEGER_ARRAY("INTEGER_ARRAY"),
    FLOAT_ARRAY("FLOAT_ARRAY"),
    DOUBLE_ARRAY("DOUBLE_ARRAY"),
    BOOLEAN_ARRAY("BOOLEAN_ARRAY"),
    STRING_ARRAY("STRING_ARRAY"),
    BIG_INTEGER_ARRAY("BIG_INTEGER_ARRAY"),
    BIG_DECIMAL_ARRAY("BIG_DECIMAL_ARRAY"),
    LOCAL_DATE_ARRAY("LOCAL_DATE_ARRAY"),
    LOCAL_DATE_TIME_ARRAY("LOCAL_DATE_TIME_ARRAY"),
    TIMESTAMP_ARRAY("TIMESTAMP_ARRAY");

    public final String value;

    private FilterRuleParameterDefinitionValueTypeEnum(String value) {
        this.value = value;
    }
}
