// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var DeleteUnderstandAssistantServerList = []string{
	"https://preview.twilio.com",
}

type DeleteUnderstandAssistantSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

type DeleteUnderstandAssistantRequest struct {
	// A 34 character string that uniquely identifies this resource.
	Sid string `pathParam:"style=simple,explode=false,name=Sid"`
}

type DeleteUnderstandAssistantResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
