package openapisdk.models.shared;


public enum FirewallInfoFirewallRuleTypeEnum {
    FIREWALL_RULE_TYPE_UNSPECIFIED("FIREWALL_RULE_TYPE_UNSPECIFIED"),
    HIERARCHICAL_FIREWALL_POLICY_RULE("HIERARCHICAL_FIREWALL_POLICY_RULE"),
    VPC_FIREWALL_RULE("VPC_FIREWALL_RULE"),
    IMPLIED_VPC_FIREWALL_RULE("IMPLIED_VPC_FIREWALL_RULE"),
    SERVERLESS_VPC_ACCESS_MANAGED_FIREWALL_RULE("SERVERLESS_VPC_ACCESS_MANAGED_FIREWALL_RULE"),
    NETWORK_FIREWALL_POLICY_RULE("NETWORK_FIREWALL_POLICY_RULE");

    public final String value;

    private FirewallInfoFirewallRuleTypeEnum(String value) {
        this.value = value;
    }
}
