package openapisdk.models.shared;


public enum RouteInfoNextHopTypeEnum {
    NEXT_HOP_TYPE_UNSPECIFIED("NEXT_HOP_TYPE_UNSPECIFIED"),
    NEXT_HOP_IP("NEXT_HOP_IP"),
    NEXT_HOP_INSTANCE("NEXT_HOP_INSTANCE"),
    NEXT_HOP_NETWORK("NEXT_HOP_NETWORK"),
    NEXT_HOP_PEERING("NEXT_HOP_PEERING"),
    NEXT_HOP_INTERCONNECT("NEXT_HOP_INTERCONNECT"),
    NEXT_HOP_VPN_TUNNEL("NEXT_HOP_VPN_TUNNEL"),
    NEXT_HOP_VPN_GATEWAY("NEXT_HOP_VPN_GATEWAY"),
    NEXT_HOP_INTERNET_GATEWAY("NEXT_HOP_INTERNET_GATEWAY"),
    NEXT_HOP_BLACKHOLE("NEXT_HOP_BLACKHOLE"),
    NEXT_HOP_ILB("NEXT_HOP_ILB"),
    NEXT_HOP_ROUTER_APPLIANCE("NEXT_HOP_ROUTER_APPLIANCE");

    public final String value;

    private RouteInfoNextHopTypeEnum(String value) {
        this.value = value;
    }
}
