/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class CreateSinglePaymentIntentRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public CreateSinglePaymentIntentRequestBody requestBody;
    public CreateSinglePaymentIntentRequest withRequestBody(CreateSinglePaymentIntentRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * ApiSecretKey
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-key")
    public String xApiKey;
    public CreateSinglePaymentIntentRequest withXApiKey(String xApiKey) {
        this.xApiKey = xApiKey;
        return this;
    }
    
}
