// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type PutWorkgroupRawPathParams struct {
	WorkgroupID string `pathParam:"style=simple,explode=false,name=workgroup_id"`
}

type PutWorkgroupRawRequest struct {
	PathParams PutWorkgroupRawPathParams
	Request    []byte `request:"mediaType=text/xml"`
}

type PutWorkgroupRawResponse struct {
	Body        []byte
	ContentType string
	// There are not any result matching your search condition
	HTTPStatusVO *shared.HTTPStatusVO
	StatusCode   int
	RawResponse  *http.Response
	// Successful updated
	WorkgroupHTTPStatusVO *shared.WorkgroupHTTPStatusVO
}
