package shared

// AwsSecurityFindingFilters
// <p>A collection of attributes that are applied to all active Security Hub-aggregated findings and that result in a subset of findings that are included in this insight.</p> <p>You can filter by up to 10 finding attributes. For each attribute, you can provide up to 20 filter values.</p>
type AwsSecurityFindingFilters struct {
	AwsAccountID                                   []StringFilter         `json:"AwsAccountId,omitempty"`
	CompanyName                                    []StringFilter         `json:"CompanyName,omitempty"`
	ComplianceStatus                               []StringFilter         `json:"ComplianceStatus,omitempty"`
	Confidence                                     []NumberFilter         `json:"Confidence,omitempty"`
	CreatedAt                                      []DateFilter1          `json:"CreatedAt,omitempty"`
	Criticality                                    []NumberFilter         `json:"Criticality,omitempty"`
	Description                                    []StringFilter         `json:"Description,omitempty"`
	FindingProviderFieldsConfidence                []NumberFilter         `json:"FindingProviderFieldsConfidence,omitempty"`
	FindingProviderFieldsCriticality               []NumberFilter         `json:"FindingProviderFieldsCriticality,omitempty"`
	FindingProviderFieldsRelatedFindingsID         []StringFilter         `json:"FindingProviderFieldsRelatedFindingsId,omitempty"`
	FindingProviderFieldsRelatedFindingsProductArn []StringFilter         `json:"FindingProviderFieldsRelatedFindingsProductArn,omitempty"`
	FindingProviderFieldsSeverityLabel             []StringFilter         `json:"FindingProviderFieldsSeverityLabel,omitempty"`
	FindingProviderFieldsSeverityOriginal          []StringFilter         `json:"FindingProviderFieldsSeverityOriginal,omitempty"`
	FindingProviderFieldsTypes                     []StringFilter         `json:"FindingProviderFieldsTypes,omitempty"`
	FirstObservedAt                                []DateFilter1          `json:"FirstObservedAt,omitempty"`
	GeneratorID                                    []StringFilter         `json:"GeneratorId,omitempty"`
	ID                                             []StringFilter         `json:"Id,omitempty"`
	Keyword                                        map[string]interface{} `json:"Keyword,omitempty"`
	LastObservedAt                                 []DateFilter1          `json:"LastObservedAt,omitempty"`
	MalwareName                                    []StringFilter         `json:"MalwareName,omitempty"`
	MalwarePath                                    []StringFilter         `json:"MalwarePath,omitempty"`
	MalwareState                                   []StringFilter         `json:"MalwareState,omitempty"`
	MalwareType                                    []StringFilter         `json:"MalwareType,omitempty"`
	NetworkDestinationDomain                       []StringFilter         `json:"NetworkDestinationDomain,omitempty"`
	NetworkDestinationIPV4                         []IPFilter             `json:"NetworkDestinationIpV4,omitempty"`
	NetworkDestinationIPV6                         []IPFilter             `json:"NetworkDestinationIpV6,omitempty"`
	NetworkDestinationPort                         []NumberFilter         `json:"NetworkDestinationPort,omitempty"`
	NetworkDirection                               []StringFilter         `json:"NetworkDirection,omitempty"`
	NetworkProtocol                                []StringFilter         `json:"NetworkProtocol,omitempty"`
	NetworkSourceDomain                            []StringFilter         `json:"NetworkSourceDomain,omitempty"`
	NetworkSourceIPV4                              []IPFilter             `json:"NetworkSourceIpV4,omitempty"`
	NetworkSourceIPV6                              []IPFilter             `json:"NetworkSourceIpV6,omitempty"`
	NetworkSourceMac                               []StringFilter         `json:"NetworkSourceMac,omitempty"`
	NetworkSourcePort                              []NumberFilter         `json:"NetworkSourcePort,omitempty"`
	NoteText                                       []StringFilter         `json:"NoteText,omitempty"`
	NoteUpdatedAt                                  []DateFilter1          `json:"NoteUpdatedAt,omitempty"`
	NoteUpdatedBy                                  []StringFilter         `json:"NoteUpdatedBy,omitempty"`
	ProcessLaunchedAt                              []DateFilter1          `json:"ProcessLaunchedAt,omitempty"`
	ProcessName                                    []StringFilter         `json:"ProcessName,omitempty"`
	ProcessParentPid                               []NumberFilter         `json:"ProcessParentPid,omitempty"`
	ProcessPath                                    []StringFilter         `json:"ProcessPath,omitempty"`
	ProcessPid                                     []NumberFilter         `json:"ProcessPid,omitempty"`
	ProcessTerminatedAt                            []DateFilter1          `json:"ProcessTerminatedAt,omitempty"`
	ProductArn                                     []StringFilter         `json:"ProductArn,omitempty"`
	ProductFields                                  []MapFilter            `json:"ProductFields,omitempty"`
	ProductName                                    []StringFilter         `json:"ProductName,omitempty"`
	RecommendationText                             []StringFilter         `json:"RecommendationText,omitempty"`
	RecordState                                    []StringFilter         `json:"RecordState,omitempty"`
	Region                                         []StringFilter         `json:"Region,omitempty"`
	RelatedFindingsID                              []StringFilter         `json:"RelatedFindingsId,omitempty"`
	RelatedFindingsProductArn                      []StringFilter         `json:"RelatedFindingsProductArn,omitempty"`
	ResourceAwsEc2InstanceIamInstanceProfileArn    []StringFilter         `json:"ResourceAwsEc2InstanceIamInstanceProfileArn,omitempty"`
	ResourceAwsEc2InstanceImageID                  []StringFilter         `json:"ResourceAwsEc2InstanceImageId,omitempty"`
	ResourceAwsEc2InstanceIPV4Addresses            []IPFilter             `json:"ResourceAwsEc2InstanceIpV4Addresses,omitempty"`
	ResourceAwsEc2InstanceIPV6Addresses            []IPFilter             `json:"ResourceAwsEc2InstanceIpV6Addresses,omitempty"`
	ResourceAwsEc2InstanceKeyName                  []StringFilter         `json:"ResourceAwsEc2InstanceKeyName,omitempty"`
	ResourceAwsEc2InstanceLaunchedAt               []DateFilter1          `json:"ResourceAwsEc2InstanceLaunchedAt,omitempty"`
	ResourceAwsEc2InstanceSubnetID                 []StringFilter         `json:"ResourceAwsEc2InstanceSubnetId,omitempty"`
	ResourceAwsEc2InstanceType                     []StringFilter         `json:"ResourceAwsEc2InstanceType,omitempty"`
	ResourceAwsEc2InstanceVpcID                    []StringFilter         `json:"ResourceAwsEc2InstanceVpcId,omitempty"`
	ResourceAwsIamAccessKeyCreatedAt               []DateFilter1          `json:"ResourceAwsIamAccessKeyCreatedAt,omitempty"`
	ResourceAwsIamAccessKeyPrincipalName           []StringFilter         `json:"ResourceAwsIamAccessKeyPrincipalName,omitempty"`
	ResourceAwsIamAccessKeyStatus                  []StringFilter         `json:"ResourceAwsIamAccessKeyStatus,omitempty"`
	ResourceAwsIamAccessKeyUserName                map[string]interface{} `json:"ResourceAwsIamAccessKeyUserName,omitempty"`
	ResourceAwsIamUserUserName                     []StringFilter         `json:"ResourceAwsIamUserUserName,omitempty"`
	ResourceAwsS3BucketOwnerID                     []StringFilter         `json:"ResourceAwsS3BucketOwnerId,omitempty"`
	ResourceAwsS3BucketOwnerName                   []StringFilter         `json:"ResourceAwsS3BucketOwnerName,omitempty"`
	ResourceContainerImageID                       []StringFilter         `json:"ResourceContainerImageId,omitempty"`
	ResourceContainerImageName                     []StringFilter         `json:"ResourceContainerImageName,omitempty"`
	ResourceContainerLaunchedAt                    []DateFilter1          `json:"ResourceContainerLaunchedAt,omitempty"`
	ResourceContainerName                          []StringFilter         `json:"ResourceContainerName,omitempty"`
	ResourceDetailsOther                           []MapFilter            `json:"ResourceDetailsOther,omitempty"`
	ResourceID                                     []StringFilter         `json:"ResourceId,omitempty"`
	ResourcePartition                              []StringFilter         `json:"ResourcePartition,omitempty"`
	ResourceRegion                                 []StringFilter         `json:"ResourceRegion,omitempty"`
	ResourceTags                                   []MapFilter            `json:"ResourceTags,omitempty"`
	ResourceType                                   []StringFilter1        `json:"ResourceType,omitempty"`
	SeverityLabel                                  []StringFilter         `json:"SeverityLabel,omitempty"`
	SeverityNormalized                             map[string]interface{} `json:"SeverityNormalized,omitempty"`
	SeverityProduct                                map[string]interface{} `json:"SeverityProduct,omitempty"`
	SourceURL                                      []StringFilter         `json:"SourceUrl,omitempty"`
	ThreatIntelIndicatorCategory                   []StringFilter         `json:"ThreatIntelIndicatorCategory,omitempty"`
	ThreatIntelIndicatorLastObservedAt             []DateFilter1          `json:"ThreatIntelIndicatorLastObservedAt,omitempty"`
	ThreatIntelIndicatorSource                     []StringFilter         `json:"ThreatIntelIndicatorSource,omitempty"`
	ThreatIntelIndicatorSourceURL                  []StringFilter         `json:"ThreatIntelIndicatorSourceUrl,omitempty"`
	ThreatIntelIndicatorType                       []StringFilter         `json:"ThreatIntelIndicatorType,omitempty"`
	ThreatIntelIndicatorValue                      []StringFilter         `json:"ThreatIntelIndicatorValue,omitempty"`
	Title                                          []StringFilter         `json:"Title,omitempty"`
	Type                                           []StringFilter         `json:"Type,omitempty"`
	UpdatedAt                                      []DateFilter1          `json:"UpdatedAt,omitempty"`
	UserDefinedFields                              []MapFilter            `json:"UserDefinedFields,omitempty"`
	VerificationState                              []StringFilter         `json:"VerificationState,omitempty"`
	WorkflowState                                  []StringFilter         `json:"WorkflowState,omitempty"`
	WorkflowStatus                                 []StringFilter         `json:"WorkflowStatus,omitempty"`
}
