/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AllocationSpecificSKUAllocationReservedInstanceProperties - Properties of the SKU instances being reserved. Next ID: 9
 */
public class AllocationSpecificSKUAllocationReservedInstanceProperties {
    /**
     * Specifies accelerator type and count.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("guestAccelerators")
    public AcceleratorConfig[] guestAccelerators;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withGuestAccelerators(AcceleratorConfig[] guestAccelerators) {
        this.guestAccelerators = guestAccelerators;
        return this;
    }
    
    /**
     * Specifies amount of local ssd to reserve with each instance. The type of disk is local-ssd.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("localSsds")
    public AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk[] localSsds;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withLocalSsds(AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk[] localSsds) {
        this.localSsds = localSsds;
        return this;
    }
    
    /**
     * An opaque location hint used to place the allocation close to other resources. This field is for use by internal tools that use the public API.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("locationHint")
    public String locationHint;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withLocationHint(String locationHint) {
        this.locationHint = locationHint;
        return this;
    }
    
    /**
     * Specifies type of machine (name only) which has fixed number of vCPUs and fixed amount of memory. This also includes specifying custom machine type following custom-NUMBER_OF_CPUS-AMOUNT_OF_MEMORY pattern.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("machineType")
    public String machineType;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withMachineType(String machineType) {
        this.machineType = machineType;
        return this;
    }
    
    /**
     * Specifies the number of hours after reservation creation where instances using the reservation won't be scheduled for maintenance.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenanceFreezeDurationHours")
    public Integer maintenanceFreezeDurationHours;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withMaintenanceFreezeDurationHours(Integer maintenanceFreezeDurationHours) {
        this.maintenanceFreezeDurationHours = maintenanceFreezeDurationHours;
        return this;
    }
    
    /**
     * Specifies the frequency of planned maintenance events. The accepted values are: `PERIODIC`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenanceInterval")
    public AllocationSpecificSKUAllocationReservedInstancePropertiesMaintenanceIntervalEnum maintenanceInterval;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withMaintenanceInterval(AllocationSpecificSKUAllocationReservedInstancePropertiesMaintenanceIntervalEnum maintenanceInterval) {
        this.maintenanceInterval = maintenanceInterval;
        return this;
    }
    
    /**
     * Minimum cpu platform the reservation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minCpuPlatform")
    public String minCpuPlatform;

    public AllocationSpecificSKUAllocationReservedInstanceProperties withMinCpuPlatform(String minCpuPlatform) {
        this.minCpuPlatform = minCpuPlatform;
        return this;
    }
    
    public AllocationSpecificSKUAllocationReservedInstanceProperties(){}
}
