/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Crop - Video cropping configuration for the input video. The cropped input video is scaled to match the output resolution.
 */
public class Crop {
    /**
     * The number of pixels to crop from the bottom. The default is 0.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bottomPixels")
    public Integer bottomPixels;
    public Crop withBottomPixels(Integer bottomPixels) {
        this.bottomPixels = bottomPixels;
        return this;
    }
    
    /**
     * The number of pixels to crop from the left. The default is 0.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("leftPixels")
    public Integer leftPixels;
    public Crop withLeftPixels(Integer leftPixels) {
        this.leftPixels = leftPixels;
        return this;
    }
    
    /**
     * The number of pixels to crop from the right. The default is 0.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rightPixels")
    public Integer rightPixels;
    public Crop withRightPixels(Integer rightPixels) {
        this.rightPixels = rightPixels;
        return this;
    }
    
    /**
     * The number of pixels to crop from the top. The default is 0.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("topPixels")
    public Integer topPixels;
    public Crop withTopPixels(Integer topPixels) {
        this.topPixels = topPixels;
        return this;
    }
    
}
