package openapisdk.models.shared;


public enum MeasurementPartnerAdvertiserLinkLinkStatusEnum {
    MEASUREMENT_PARTNER_UNLINKED("MEASUREMENT_PARTNER_UNLINKED"),
    MEASUREMENT_PARTNER_LINKED("MEASUREMENT_PARTNER_LINKED"),
    MEASUREMENT_PARTNER_LINK_PENDING("MEASUREMENT_PARTNER_LINK_PENDING"),
    MEASUREMENT_PARTNER_LINK_FAILURE("MEASUREMENT_PARTNER_LINK_FAILURE"),
    MEASUREMENT_PARTNER_LINK_OPT_OUT("MEASUREMENT_PARTNER_LINK_OPT_OUT"),
    MEASUREMENT_PARTNER_LINK_OPT_OUT_PENDING("MEASUREMENT_PARTNER_LINK_OPT_OUT_PENDING"),
    MEASUREMENT_PARTNER_LINK_WRAPPING_PENDING("MEASUREMENT_PARTNER_LINK_WRAPPING_PENDING"),
    MEASUREMENT_PARTNER_MODE_CHANGE_PENDING("MEASUREMENT_PARTNER_MODE_CHANGE_PENDING");

    public final String value;

    private MeasurementPartnerAdvertiserLinkLinkStatusEnum(String value) {
        this.value = value;
    }
}
