/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GETDeleteDBClusterSnapshotQueryParams {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Action")
    public GETDeleteDBClusterSnapshotActionEnum action;
    public GETDeleteDBClusterSnapshotQueryParams withAction(GETDeleteDBClusterSnapshotActionEnum action) {
        this.action = action;
        return this;
    }
    
    /**
     * &lt;p&gt;The identifier of the DB cluster snapshot to delete.&lt;/p&gt; &lt;p&gt;Constraints: Must be the name of an existing DB cluster snapshot in the &lt;code&gt;available&lt;/code&gt; state.&lt;/p&gt;
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=DBClusterSnapshotIdentifier")
    public String dbClusterSnapshotIdentifier;
    public GETDeleteDBClusterSnapshotQueryParams withDBClusterSnapshotIdentifier(String dbClusterSnapshotIdentifier) {
        this.dbClusterSnapshotIdentifier = dbClusterSnapshotIdentifier;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Version")
    public GETDeleteDBClusterSnapshotVersionEnum version;
    public GETDeleteDBClusterSnapshotQueryParams withVersion(GETDeleteDBClusterSnapshotVersionEnum version) {
        this.version = version;
        return this;
    }
    
}
