/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetControlResponse - Success
 */
public class GetControlResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("control")
    public Control control;

    public GetControlResponse withControl(Control control) {
        this.control = control;
        return this;
    }
    
    public GetControlResponse(){}
}
