package openapisdk.models.shared;


public enum GoogleSecuritySafebrowsingV4ThreatInfoThreatTypesEnum {
    THREAT_TYPE_UNSPECIFIED("THREAT_TYPE_UNSPECIFIED"),
    MALWARE("MALWARE"),
    SOCIAL_ENGINEERING("SOCIAL_ENGINEERING"),
    UNWANTED_SOFTWARE("UNWANTED_SOFTWARE"),
    POTENTIALLY_HARMFUL_APPLICATION("POTENTIALLY_HARMFUL_APPLICATION"),
    SOCIAL_ENGINEERING_INTERNAL("SOCIAL_ENGINEERING_INTERNAL"),
    API_ABUSE("API_ABUSE"),
    MALICIOUS_BINARY("MALICIOUS_BINARY"),
    CSD_WHITELIST("CSD_WHITELIST"),
    CSD_DOWNLOAD_WHITELIST("CSD_DOWNLOAD_WHITELIST"),
    CLIENT_INCIDENT("CLIENT_INCIDENT"),
    CLIENT_INCIDENT_WHITELIST("CLIENT_INCIDENT_WHITELIST"),
    APK_MALWARE_OFFLINE("APK_MALWARE_OFFLINE"),
    SUBRESOURCE_FILTER("SUBRESOURCE_FILTER"),
    SUSPICIOUS("SUSPICIOUS"),
    TRICK_TO_BILL("TRICK_TO_BILL"),
    HIGH_CONFIDENCE_ALLOWLIST("HIGH_CONFIDENCE_ALLOWLIST"),
    ACCURACY_TIPS("ACCURACY_TIPS"),
    SOCIAL_ENGINEERING_LOWER_PRECISION("SOCIAL_ENGINEERING_LOWER_PRECISION");

    public final String value;

    private GoogleSecuritySafebrowsingV4ThreatInfoThreatTypesEnum(String value) {
        this.value = value;
    }
}
