// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetBlockIndexPathParams struct {
	// Block Index
	Blockindex float64 `pathParam:"style=simple,explode=false,name=blockindex"`
}

type GetBlockIndexRequest struct {
	PathParams GetBlockIndexPathParams
}

type GetBlockIndexResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Object containing block hash
	GetBlockIndexResponse *shared.GetBlockIndexResponse
}
