// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ItvHadEntitlement - OK
type ItvHadEntitlement struct {
	// whether the user has been previously entitlement
	HasHadEntitlements bool `json:"hasHadEntitlements"`
}
