<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/**
 */
enum StartCrawlerScheduleXAmzTargetEnum: string
{
    case AWS_GLUE_START_CRAWLER_SCHEDULE = 'AWSGlue.StartCrawlerSchedule';
}
