package openapisdk.models.shared;


public enum CreativeAssetMetadataWarnedValidationRulesEnum {
    CLICK_TAG_NON_TOP_LEVEL("CLICK_TAG_NON_TOP_LEVEL"),
    CLICK_TAG_MISSING("CLICK_TAG_MISSING"),
    CLICK_TAG_MORE_THAN_ONE("CLICK_TAG_MORE_THAN_ONE"),
    CLICK_TAG_INVALID("CLICK_TAG_INVALID"),
    ORPHANED_ASSET("ORPHANED_ASSET"),
    PRIMARY_HTML_MISSING("PRIMARY_HTML_MISSING"),
    EXTERNAL_FILE_REFERENCED("EXTERNAL_FILE_REFERENCED"),
    MRAID_REFERENCED("MRAID_REFERENCED"),
    ADMOB_REFERENCED("ADMOB_REFERENCED"),
    FILE_TYPE_INVALID("FILE_TYPE_INVALID"),
    ZIP_INVALID("ZIP_INVALID"),
    LINKED_FILE_NOT_FOUND("LINKED_FILE_NOT_FOUND"),
    MAX_FLASH_VERSION11("MAX_FLASH_VERSION_11"),
    NOT_SSL_COMPLIANT("NOT_SSL_COMPLIANT"),
    FILE_DETAIL_EMPTY("FILE_DETAIL_EMPTY"),
    ASSET_INVALID("ASSET_INVALID"),
    GWD_PROPERTIES_INVALID("GWD_PROPERTIES_INVALID"),
    ENABLER_UNSUPPORTED_METHOD_DCM("ENABLER_UNSUPPORTED_METHOD_DCM"),
    ASSET_FORMAT_UNSUPPORTED_DCM("ASSET_FORMAT_UNSUPPORTED_DCM"),
    COMPONENT_UNSUPPORTED_DCM("COMPONENT_UNSUPPORTED_DCM"),
    HTML5_FEATURE_UNSUPPORTED("HTML5_FEATURE_UNSUPPORTED"),
    CLICK_TAG_IN_GWD("CLICK_TAG_IN_GWD"),
    CLICK_TAG_HARD_CODED("CLICK_TAG_HARD_CODED"),
    SVG_INVALID("SVG_INVALID"),
    CLICK_TAG_IN_RICH_MEDIA("CLICK_TAG_IN_RICH_MEDIA");

    public final String value;

    private CreativeAssetMetadataWarnedValidationRulesEnum(String value) {
        this.value = value;
    }
}
