package openapisdk.models.shared;


public enum PricingPricingTypeEnum {
    PLANNING_PLACEMENT_PRICING_TYPE_IMPRESSIONS("PLANNING_PLACEMENT_PRICING_TYPE_IMPRESSIONS"),
    PLANNING_PLACEMENT_PRICING_TYPE_CPM("PLANNING_PLACEMENT_PRICING_TYPE_CPM"),
    PLANNING_PLACEMENT_PRICING_TYPE_CLICKS("PLANNING_PLACEMENT_PRICING_TYPE_CLICKS"),
    PLANNING_PLACEMENT_PRICING_TYPE_CPC("PLANNING_PLACEMENT_PRICING_TYPE_CPC"),
    PLANNING_PLACEMENT_PRICING_TYPE_CPA("PLANNING_PLACEMENT_PRICING_TYPE_CPA"),
    PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_IMPRESSIONS("PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_IMPRESSIONS"),
    PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_CLICKS("PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_CLICKS"),
    PLANNING_PLACEMENT_PRICING_TYPE_CPM_ACTIVEVIEW("PLANNING_PLACEMENT_PRICING_TYPE_CPM_ACTIVEVIEW");

    public final String value;

    private PricingPricingTypeEnum(String value) {
        this.value = value;
    }
}
