package openapisdk.models.shared;


public enum RemarketingListListSourceEnum {
    REMARKETING_LIST_SOURCE_OTHER("REMARKETING_LIST_SOURCE_OTHER"),
    REMARKETING_LIST_SOURCE_ADX("REMARKETING_LIST_SOURCE_ADX"),
    REMARKETING_LIST_SOURCE_DFP("REMARKETING_LIST_SOURCE_DFP"),
    REMARKETING_LIST_SOURCE_XFP("REMARKETING_LIST_SOURCE_XFP"),
    REMARKETING_LIST_SOURCE_DFA("REMARKETING_LIST_SOURCE_DFA"),
    REMARKETING_LIST_SOURCE_GA("REMARKETING_LIST_SOURCE_GA"),
    REMARKETING_LIST_SOURCE_YOUTUBE("REMARKETING_LIST_SOURCE_YOUTUBE"),
    REMARKETING_LIST_SOURCE_DBM("REMARKETING_LIST_SOURCE_DBM"),
    REMARKETING_LIST_SOURCE_GPLUS("REMARKETING_LIST_SOURCE_GPLUS"),
    REMARKETING_LIST_SOURCE_DMP("REMARKETING_LIST_SOURCE_DMP"),
    REMARKETING_LIST_SOURCE_PLAY_STORE("REMARKETING_LIST_SOURCE_PLAY_STORE");

    public final String value;

    private RemarketingListListSourceEnum(String value) {
        this.value = value;
    }
}
