package openapisdk.models.shared;


public enum VerificationReasonEnum {
    DATA_NOT_AVAILABLE("DATA_NOT_AVAILABLE"),
    ACCOUNT_HOLDER_MISMATCH("ACCOUNT_HOLDER_MISMATCH"),
    FULL_ACCOUNT_NUMBER_AND_BANK_TRANSFER_CODE_NOT_AVAILABLE("FULL_ACCOUNT_NUMBER_AND_BANK_TRANSFER_CODE_NOT_AVAILABLE"),
    FULL_ACCOUNT_NUMBER_NOT_AVAILABLE("FULL_ACCOUNT_NUMBER_NOT_AVAILABLE"),
    BANK_TRANSFER_CODE_NOT_AVAILABLE("BANK_TRANSFER_CODE_NOT_AVAILABLE"),
    EXPIRED("EXPIRED"),
    DATA_MISMATCH("DATA_MISMATCH"),
    INSTRUCTION_GENERATION_ERROR("INSTRUCTION_GENERATION_ERROR");

    public final String value;

    private VerificationReasonEnum(String value) {
        this.value = value;
    }
}
