package openapisdk.models.shared;


public enum GoogleCloudDatalabelingV1beta1EvaluationAnnotationTypeEnum {
    ANNOTATION_TYPE_UNSPECIFIED("ANNOTATION_TYPE_UNSPECIFIED"),
    IMAGE_CLASSIFICATION_ANNOTATION("IMAGE_CLASSIFICATION_ANNOTATION"),
    IMAGE_BOUNDING_BOX_ANNOTATION("IMAGE_BOUNDING_BOX_ANNOTATION"),
    IMAGE_ORIENTED_BOUNDING_BOX_ANNOTATION("IMAGE_ORIENTED_BOUNDING_BOX_ANNOTATION"),
    IMAGE_BOUNDING_POLY_ANNOTATION("IMAGE_BOUNDING_POLY_ANNOTATION"),
    IMAGE_POLYLINE_ANNOTATION("IMAGE_POLYLINE_ANNOTATION"),
    IMAGE_SEGMENTATION_ANNOTATION("IMAGE_SEGMENTATION_ANNOTATION"),
    VIDEO_SHOTS_CLASSIFICATION_ANNOTATION("VIDEO_SHOTS_CLASSIFICATION_ANNOTATION"),
    VIDEO_OBJECT_TRACKING_ANNOTATION("VIDEO_OBJECT_TRACKING_ANNOTATION"),
    VIDEO_OBJECT_DETECTION_ANNOTATION("VIDEO_OBJECT_DETECTION_ANNOTATION"),
    VIDEO_EVENT_ANNOTATION("VIDEO_EVENT_ANNOTATION"),
    TEXT_CLASSIFICATION_ANNOTATION("TEXT_CLASSIFICATION_ANNOTATION"),
    TEXT_ENTITY_EXTRACTION_ANNOTATION("TEXT_ENTITY_EXTRACTION_ANNOTATION"),
    GENERAL_CLASSIFICATION_ANNOTATION("GENERAL_CLASSIFICATION_ANNOTATION");

    public final String value;

    private GoogleCloudDatalabelingV1beta1EvaluationAnnotationTypeEnum(String value) {
        this.value = value;
    }
}
