/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * The health status of the instance. If the status of either the instance status check or the system status check is <code>impaired</code>, the health status of the instance is <code>unhealthy</code>. Otherwise, the health status is <code>healthy</code>.
 */
export enum DescribeFleetInstancesResultActiveInstancesInstanceHealthEnum {
  Healthy = "healthy",
  Unhealthy = "unhealthy",
}

/**
 * Describes a running instance in a Spot Fleet.
 */
export class DescribeFleetInstancesResultActiveInstances extends SpeakeasyBase {
  @SpeakeasyMetadata()
  instanceHealth?: DescribeFleetInstancesResultActiveInstancesInstanceHealthEnum;

  @SpeakeasyMetadata()
  instanceId?: string;

  @SpeakeasyMetadata()
  instanceType?: string;

  @SpeakeasyMetadata()
  spotInstanceRequestId?: string;
}

/**
 * Success
 */
export class DescribeFleetInstancesResult extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: DescribeFleetInstancesResultActiveInstances })
  activeInstances?: DescribeFleetInstancesResultActiveInstances[];

  @SpeakeasyMetadata()
  fleetId?: string;

  @SpeakeasyMetadata()
  nextToken?: string;
}
