<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


class Project
{
    /**
     * Project id
     * 
     * @var int $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * Date when project was published
     * 
     * @var string $publishedDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('published_date')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $publishedDate;
    
    /**
     * Project title
     * 
     * @var string $title
     */
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $title;
    
    /**
     * Api endpoint
     * 
     * @var string $url
     */
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $url;
    
	public function __construct()
	{
		$this->id = 0;
		$this->publishedDate = "";
		$this->title = "";
		$this->url = "";
	}
}
