// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GETRampMetricsBySubscriptionKeyResponseTypeReasons struct {
	// The error code of response.
	//
	Code *string `json:"code,omitempty"`
	// The detail information of the error response
	//
	Message *string `json:"message,omitempty"`
}

type GETRampMetricsBySubscriptionKeyResponseType struct {
	// The Id of the process that handle the operation.
	//
	ProcessID   *string                                              `json:"processId,omitempty"`
	RampMetrics *RampMetrics                                         `json:"rampMetrics,omitempty"`
	Reasons     []GETRampMetricsBySubscriptionKeyResponseTypeReasons `json:"reasons,omitempty"`
	// Indicates whether the call succeeded.
	//
	Success *bool `json:"success,omitempty"`
}
