/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.net.http.HttpResponse;

public class GetMerchantsMerchantIdApiCredentialsApiCredentialIdAllowedOriginsOriginIdResponse {
    /**
     * OK - the request has succeeded.
     */
    
    public org.openapis.openapi.models.shared.AllowedOrigin allowedOrigin;
    public GetMerchantsMerchantIdApiCredentialsApiCredentialIdAllowedOriginsOriginIdResponse withAllowedOrigin(org.openapis.openapi.models.shared.AllowedOrigin allowedOrigin) {
        this.allowedOrigin = allowedOrigin;
        return this;
    }
    
    
    public String contentType;
    public GetMerchantsMerchantIdApiCredentialsApiCredentialIdAllowedOriginsOriginIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad Request - a problem reading or understanding the request.
     */
    
    public org.openapis.openapi.models.shared.RestServiceError restServiceError;
    public GetMerchantsMerchantIdApiCredentialsApiCredentialIdAllowedOriginsOriginIdResponse withRestServiceError(org.openapis.openapi.models.shared.RestServiceError restServiceError) {
        this.restServiceError = restServiceError;
        return this;
    }
    
    
    public Integer statusCode;
    public GetMerchantsMerchantIdApiCredentialsApiCredentialIdAllowedOriginsOriginIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetMerchantsMerchantIdApiCredentialsApiCredentialIdAllowedOriginsOriginIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
