/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JwtRequest - authenticationRequest
 */
public class JwtRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("healthId")
    public String healthId;
    public JwtRequest withHealthId(String healthId) {
        this.healthId = healthId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("password")
    public String password;
    public JwtRequest withPassword(String password) {
        this.password = password;
        return this;
    }
    
}
