/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class PutSetupV1CompaniesDomainsIdRequest {
    
    public PutSetupV1CompaniesDomainsIdPathParams pathParams;
    public PutSetupV1CompaniesDomainsIdRequest withPathParams(PutSetupV1CompaniesDomainsIdPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    /**
     * Company Domain Update Model
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.CompanyDomainUpdateModel request;
    public PutSetupV1CompaniesDomainsIdRequest withRequest(org.openapis.openapi.models.shared.CompanyDomainUpdateModel request) {
        this.request = request;
        return this;
    }
    
}
