<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * DescribeFpgaImagesResultFpgaImagesProductCodes - Describes a product code.
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class DescribeFpgaImagesResultFpgaImagesProductCodes
{
	
    public ?string $productCodeId = null;
    
	
    public ?DescribeFpgaImagesResultFpgaImagesProductCodesProductCodeTypeEnum $productCodeType = null;
    
	public function __construct()
	{
		$this->productCodeId = null;
		$this->productCodeType = null;
	}
}
