// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type ActionsGetAllowedActionsRepositoryPathParams struct {
	Owner string `pathParam:"style=simple,explode=false,name=owner"`
	Repo  string `pathParam:"style=simple,explode=false,name=repo"`
}

type ActionsGetAllowedActionsRepositoryRequest struct {
	PathParams ActionsGetAllowedActionsRepositoryPathParams
}

type ActionsGetAllowedActionsRepositoryResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Response
	SelectedActions *shared.SelectedActions
}
