/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class VmmigrationProjectsLocationsTargetProjectsListResponse {
    
    public String contentType;

    public VmmigrationProjectsLocationsTargetProjectsListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful response
     */
    
    public org.openapis.openapi.models.shared.ListTargetProjectsResponse listTargetProjectsResponse;

    public VmmigrationProjectsLocationsTargetProjectsListResponse withListTargetProjectsResponse(org.openapis.openapi.models.shared.ListTargetProjectsResponse listTargetProjectsResponse) {
        this.listTargetProjectsResponse = listTargetProjectsResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public VmmigrationProjectsLocationsTargetProjectsListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public VmmigrationProjectsLocationsTargetProjectsListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public VmmigrationProjectsLocationsTargetProjectsListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
