from .acceptgrant import *
from .checkinlicense import *
from .checkoutborrowlicense import *
from .checkoutlicense import *
from .creategrant import *
from .creategrantversion import *
from .createlicense import *
from .createlicenseconfiguration import *
from .createlicensemanagerreportgenerator import *
from .createlicenseversion import *
from .createtoken import *
from .deletegrant import *
from .deletelicense import *
from .deletelicenseconfiguration import *
from .deletelicensemanagerreportgenerator import *
from .deletetoken import *
from .extendlicenseconsumption import *
from .getaccesstoken import *
from .getgrant import *
from .getlicense import *
from .getlicenseconfiguration import *
from .getlicensemanagerreportgenerator import *
from .getlicenseusage import *
from .getservicesettings import *
from .listassociationsforlicenseconfiguration import *
from .listdistributedgrants import *
from .listfailuresforlicenseconfigurationoperations import *
from .listlicenseconfigurations import *
from .listlicensemanagerreportgenerators import *
from .listlicenses import *
from .listlicensespecificationsforresource import *
from .listlicenseversions import *
from .listreceivedgrants import *
from .listreceivedlicenses import *
from .listresourceinventory import *
from .listtagsforresource import *
from .listtokens import *
from .listusageforlicenseconfiguration import *
from .rejectgrant import *
from .tagresource import *
from .untagresource import *
from .updatelicenseconfiguration import *
from .updatelicensemanagerreportgenerator import *
from .updatelicensespecificationsforresource import *
from .updateservicesettings import *

__all__ = ["AcceptGrantXAmzTargetEnum","AcceptGrantHeaders","AcceptGrantRequest","AcceptGrantResponse","CheckInLicenseXAmzTargetEnum","CheckInLicenseHeaders","CheckInLicenseRequest","CheckInLicenseResponse","CheckoutBorrowLicenseXAmzTargetEnum","CheckoutBorrowLicenseHeaders","CheckoutBorrowLicenseRequest","CheckoutBorrowLicenseResponse","CheckoutLicenseXAmzTargetEnum","CheckoutLicenseHeaders","CheckoutLicenseRequest","CheckoutLicenseResponse","CreateGrantXAmzTargetEnum","CreateGrantHeaders","CreateGrantRequest","CreateGrantResponse","CreateGrantVersionXAmzTargetEnum","CreateGrantVersionHeaders","CreateGrantVersionRequest","CreateGrantVersionResponse","CreateLicenseXAmzTargetEnum","CreateLicenseHeaders","CreateLicenseRequest","CreateLicenseResponse","CreateLicenseConfigurationXAmzTargetEnum","CreateLicenseConfigurationHeaders","CreateLicenseConfigurationRequest","CreateLicenseConfigurationResponse","CreateLicenseManagerReportGeneratorXAmzTargetEnum","CreateLicenseManagerReportGeneratorHeaders","CreateLicenseManagerReportGeneratorRequest","CreateLicenseManagerReportGeneratorResponse","CreateLicenseVersionXAmzTargetEnum","CreateLicenseVersionHeaders","CreateLicenseVersionRequest","CreateLicenseVersionResponse","CreateTokenXAmzTargetEnum","CreateTokenHeaders","CreateTokenRequest","CreateTokenResponse","DeleteGrantXAmzTargetEnum","DeleteGrantHeaders","DeleteGrantRequest","DeleteGrantResponse","DeleteLicenseXAmzTargetEnum","DeleteLicenseHeaders","DeleteLicenseRequest","DeleteLicenseResponse","DeleteLicenseConfigurationXAmzTargetEnum","DeleteLicenseConfigurationHeaders","DeleteLicenseConfigurationRequest","DeleteLicenseConfigurationResponse","DeleteLicenseManagerReportGeneratorXAmzTargetEnum","DeleteLicenseManagerReportGeneratorHeaders","DeleteLicenseManagerReportGeneratorRequest","DeleteLicenseManagerReportGeneratorResponse","DeleteTokenXAmzTargetEnum","DeleteTokenHeaders","DeleteTokenRequest","DeleteTokenResponse","ExtendLicenseConsumptionXAmzTargetEnum","ExtendLicenseConsumptionHeaders","ExtendLicenseConsumptionRequest","ExtendLicenseConsumptionResponse","GetAccessTokenXAmzTargetEnum","GetAccessTokenHeaders","GetAccessTokenRequest","GetAccessTokenResponse","GetGrantXAmzTargetEnum","GetGrantHeaders","GetGrantRequest","GetGrantResponse","GetLicenseXAmzTargetEnum","GetLicenseHeaders","GetLicenseRequest","GetLicenseResponse","GetLicenseConfigurationXAmzTargetEnum","GetLicenseConfigurationHeaders","GetLicenseConfigurationRequest","GetLicenseConfigurationResponse","GetLicenseManagerReportGeneratorXAmzTargetEnum","GetLicenseManagerReportGeneratorHeaders","GetLicenseManagerReportGeneratorRequest","GetLicenseManagerReportGeneratorResponse","GetLicenseUsageXAmzTargetEnum","GetLicenseUsageHeaders","GetLicenseUsageRequest","GetLicenseUsageResponse","GetServiceSettingsXAmzTargetEnum","GetServiceSettingsHeaders","GetServiceSettingsRequest","GetServiceSettingsResponse","ListAssociationsForLicenseConfigurationXAmzTargetEnum","ListAssociationsForLicenseConfigurationHeaders","ListAssociationsForLicenseConfigurationRequest","ListAssociationsForLicenseConfigurationResponse","ListDistributedGrantsXAmzTargetEnum","ListDistributedGrantsHeaders","ListDistributedGrantsRequest","ListDistributedGrantsResponse","ListFailuresForLicenseConfigurationOperationsXAmzTargetEnum","ListFailuresForLicenseConfigurationOperationsHeaders","ListFailuresForLicenseConfigurationOperationsRequest","ListFailuresForLicenseConfigurationOperationsResponse","ListLicenseConfigurationsXAmzTargetEnum","ListLicenseConfigurationsHeaders","ListLicenseConfigurationsRequest","ListLicenseConfigurationsResponse","ListLicenseManagerReportGeneratorsXAmzTargetEnum","ListLicenseManagerReportGeneratorsHeaders","ListLicenseManagerReportGeneratorsRequest","ListLicenseManagerReportGeneratorsResponse","ListLicensesXAmzTargetEnum","ListLicensesHeaders","ListLicensesRequest","ListLicensesResponse","ListLicenseSpecificationsForResourceXAmzTargetEnum","ListLicenseSpecificationsForResourceHeaders","ListLicenseSpecificationsForResourceRequest","ListLicenseSpecificationsForResourceResponse","ListLicenseVersionsXAmzTargetEnum","ListLicenseVersionsHeaders","ListLicenseVersionsRequest","ListLicenseVersionsResponse","ListReceivedGrantsXAmzTargetEnum","ListReceivedGrantsHeaders","ListReceivedGrantsRequest","ListReceivedGrantsResponse","ListReceivedLicensesXAmzTargetEnum","ListReceivedLicensesHeaders","ListReceivedLicensesRequest","ListReceivedLicensesResponse","ListResourceInventoryXAmzTargetEnum","ListResourceInventoryHeaders","ListResourceInventoryRequest","ListResourceInventoryResponse","ListTagsForResourceXAmzTargetEnum","ListTagsForResourceHeaders","ListTagsForResourceRequest","ListTagsForResourceResponse","ListTokensXAmzTargetEnum","ListTokensHeaders","ListTokensRequest","ListTokensResponse","ListUsageForLicenseConfigurationXAmzTargetEnum","ListUsageForLicenseConfigurationHeaders","ListUsageForLicenseConfigurationRequest","ListUsageForLicenseConfigurationResponse","RejectGrantXAmzTargetEnum","RejectGrantHeaders","RejectGrantRequest","RejectGrantResponse","TagResourceXAmzTargetEnum","TagResourceHeaders","TagResourceRequest","TagResourceResponse","UntagResourceXAmzTargetEnum","UntagResourceHeaders","UntagResourceRequest","UntagResourceResponse","UpdateLicenseConfigurationXAmzTargetEnum","UpdateLicenseConfigurationHeaders","UpdateLicenseConfigurationRequest","UpdateLicenseConfigurationResponse","UpdateLicenseManagerReportGeneratorXAmzTargetEnum","UpdateLicenseManagerReportGeneratorHeaders","UpdateLicenseManagerReportGeneratorRequest","UpdateLicenseManagerReportGeneratorResponse","UpdateLicenseSpecificationsForResourceXAmzTargetEnum","UpdateLicenseSpecificationsForResourceHeaders","UpdateLicenseSpecificationsForResourceRequest","UpdateLicenseSpecificationsForResourceResponse","UpdateServiceSettingsXAmzTargetEnum","UpdateServiceSettingsHeaders","UpdateServiceSettingsRequest","UpdateServiceSettingsResponse"]