/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GETListsNamesFormat200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("copyright")
    public String copyright;
    public GETListsNamesFormat200ApplicationJSON withCopyright(String copyright) {
        this.copyright = copyright;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("num_results")
    public Long numResults;
    public GETListsNamesFormat200ApplicationJSON withNumResults(Long numResults) {
        this.numResults = numResults;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("results")
    public GETListsNamesFormat200ApplicationJSONResults[] results;
    public GETListsNamesFormat200ApplicationJSON withResults(GETListsNamesFormat200ApplicationJSONResults[] results) {
        this.results = results;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public String status;
    public GETListsNamesFormat200ApplicationJSON withStatus(String status) {
        this.status = status;
        return this;
    }
    
}
