package openapisdk.models.shared;


public enum GoogleAnalyticsAdminV1betaPropertyIndustryCategoryEnum {
    INDUSTRY_CATEGORY_UNSPECIFIED("INDUSTRY_CATEGORY_UNSPECIFIED"),
    AUTOMOTIVE("AUTOMOTIVE"),
    BUSINESS_AND_INDUSTRIAL_MARKETS("BUSINESS_AND_INDUSTRIAL_MARKETS"),
    FINANCE("FINANCE"),
    HEALTHCARE("HEALTHCARE"),
    TECHNOLOGY("TECHNOLOGY"),
    TRAVEL("TRAVEL"),
    OTHER("OTHER"),
    ARTS_AND_ENTERTAINMENT("ARTS_AND_ENTERTAINMENT"),
    BEAUTY_AND_FITNESS("BEAUTY_AND_FITNESS"),
    BOOKS_AND_LITERATURE("BOOKS_AND_LITERATURE"),
    FOOD_AND_DRINK("FOOD_AND_DRINK"),
    GAMES("GAMES"),
    HOBBIES_AND_LEISURE("HOBBIES_AND_LEISURE"),
    HOME_AND_GARDEN("HOME_AND_GARDEN"),
    INTERNET_AND_TELECOM("INTERNET_AND_TELECOM"),
    LAW_AND_GOVERNMENT("LAW_AND_GOVERNMENT"),
    NEWS("NEWS"),
    ONLINE_COMMUNITIES("ONLINE_COMMUNITIES"),
    PEOPLE_AND_SOCIETY("PEOPLE_AND_SOCIETY"),
    PETS_AND_ANIMALS("PETS_AND_ANIMALS"),
    REAL_ESTATE("REAL_ESTATE"),
    REFERENCE("REFERENCE"),
    SCIENCE("SCIENCE"),
    SPORTS("SPORTS"),
    JOBS_AND_EDUCATION("JOBS_AND_EDUCATION"),
    SHOPPING("SHOPPING");

    public final String value;

    private GoogleAnalyticsAdminV1betaPropertyIndustryCategoryEnum(String value) {
        this.value = value;
    }
}
