package shared

type ArticleComplete struct {
	Authors            []Author              `json:"authors,omitempty"`
	Categories         []Category            `json:"categories,omitempty"`
	Citation           *string               `json:"citation,omitempty"`
	ConfidentialReason *string               `json:"confidential_reason,omitempty"`
	CreatedDate        *string               `json:"created_date,omitempty"`
	CustomFields       []CustomArticleField  `json:"custom_fields,omitempty"`
	DefinedType        *int64                `json:"defined_type,omitempty"`
	DefinedTypeName    *string               `json:"defined_type_name,omitempty"`
	Description        *string               `json:"description,omitempty"`
	Doi                *string               `json:"doi,omitempty"`
	EmbargoDate        *string               `json:"embargo_date,omitempty"`
	EmbargoOptions     []GroupEmbargoOptions `json:"embargo_options,omitempty"`
	EmbargoReason      *string               `json:"embargo_reason,omitempty"`
	EmbargoTitle       *string               `json:"embargo_title,omitempty"`
	EmbargoType        *string               `json:"embargo_type,omitempty"`
	FigshareURL        *string               `json:"figshare_url,omitempty"`
	Files              []PublicFile          `json:"files,omitempty"`
	Funding            *string               `json:"funding,omitempty"`
	FundingList        []int64               `json:"funding_list,omitempty"`
	GroupID            *float64              `json:"group_id,omitempty"`
	Handle             *string               `json:"handle,omitempty"`
	HasLinkedFile      *bool                 `json:"has_linked_file,omitempty"`
	ID                 *int64                `json:"id,omitempty"`
	IsActive           *bool                 `json:"is_active,omitempty"`
	IsConfidential     *bool                 `json:"is_confidential,omitempty"`
	IsEmbargoed        *bool                 `json:"is_embargoed,omitempty"`
	IsMetadataRecord   *bool                 `json:"is_metadata_record,omitempty"`
	IsPublic           *bool                 `json:"is_public,omitempty"`
	License            *License              `json:"license,omitempty"`
	MetadataReason     *string               `json:"metadata_reason,omitempty"`
	ModifiedDate       *string               `json:"modified_date,omitempty"`
	PublishedDate      *string               `json:"published_date,omitempty"`
	References         []string              `json:"references,omitempty"`
	ResourceDoi        *string               `json:"resource_doi,omitempty"`
	ResourceTitle      *string               `json:"resource_title,omitempty"`
	Size               *int64                `json:"size,omitempty"`
	Status             *string               `json:"status,omitempty"`
	Tags               []string              `json:"tags,omitempty"`
	Thumb              *string               `json:"thumb,omitempty"`
	Timeline           *Timeline             `json:"timeline,omitempty"`
	Title              *string               `json:"title,omitempty"`
	URL                *string               `json:"url,omitempty"`
	URLPrivateAPI      *string               `json:"url_private_api,omitempty"`
	URLPrivateHTML     *string               `json:"url_private_html,omitempty"`
	URLPublicAPI       *string               `json:"url_public_api,omitempty"`
	URLPublicHTML      *string               `json:"url_public_html,omitempty"`
	Version            *int64                `json:"version,omitempty"`
}
