<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class ComputeResourcePoliciesGetResponse
{
	
    public string $contentType;
    
    /**
     * Successful response
     * 
     * @var ?\OpenAPI\OpenAPI\Models\Shared\ResourcePolicy $resourcePolicy
     */
	
    public ?\OpenAPI\OpenAPI\Models\Shared\ResourcePolicy $resourcePolicy = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->resourcePolicy = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
