/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CloudWatchEncryption } from "./cloudwatchencryption";
import { JobBookmarksEncryption } from "./jobbookmarksencryption";
import { S3Encryption } from "./s3encryption";
import { Expose, Type } from "class-transformer";

/**
 * Specifies an encryption configuration.
 */
export class EncryptionConfiguration extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "CloudWatchEncryption" })
  @Type(() => CloudWatchEncryption)
  cloudWatchEncryption?: CloudWatchEncryption;

  @SpeakeasyMetadata()
  @Expose({ name: "JobBookmarksEncryption" })
  @Type(() => JobBookmarksEncryption)
  jobBookmarksEncryption?: JobBookmarksEncryption;

  @SpeakeasyMetadata({ elemType: S3Encryption })
  @Expose({ name: "S3Encryption" })
  @Type(() => S3Encryption)
  s3Encryption?: S3Encryption[];
}
