package shared

type DoctorCountryEnum string

const (
	DoctorCountryEnumBd DoctorCountryEnum = "BD"
	DoctorCountryEnumWf DoctorCountryEnum = "WF"
	DoctorCountryEnumBf DoctorCountryEnum = "BF"
	DoctorCountryEnumBg DoctorCountryEnum = "BG"
	DoctorCountryEnumBa DoctorCountryEnum = "BA"
	DoctorCountryEnumBb DoctorCountryEnum = "BB"
	DoctorCountryEnumBe DoctorCountryEnum = "BE"
	DoctorCountryEnumBl DoctorCountryEnum = "BL"
	DoctorCountryEnumBm DoctorCountryEnum = "BM"
	DoctorCountryEnumBn DoctorCountryEnum = "BN"
	DoctorCountryEnumBo DoctorCountryEnum = "BO"
	DoctorCountryEnumJp DoctorCountryEnum = "JP"
	DoctorCountryEnumBi DoctorCountryEnum = "BI"
	DoctorCountryEnumBj DoctorCountryEnum = "BJ"
	DoctorCountryEnumBt DoctorCountryEnum = "BT"
	DoctorCountryEnumJm DoctorCountryEnum = "JM"
	DoctorCountryEnumBv DoctorCountryEnum = "BV"
	DoctorCountryEnumJo DoctorCountryEnum = "JO"
	DoctorCountryEnumWs DoctorCountryEnum = "WS"
	DoctorCountryEnumBq DoctorCountryEnum = "BQ"
	DoctorCountryEnumBr DoctorCountryEnum = "BR"
	DoctorCountryEnumBs DoctorCountryEnum = "BS"
	DoctorCountryEnumJe DoctorCountryEnum = "JE"
	DoctorCountryEnumBy DoctorCountryEnum = "BY"
	DoctorCountryEnumBz DoctorCountryEnum = "BZ"
	DoctorCountryEnumRu DoctorCountryEnum = "RU"
	DoctorCountryEnumRw DoctorCountryEnum = "RW"
	DoctorCountryEnumRs DoctorCountryEnum = "RS"
	DoctorCountryEnumTl DoctorCountryEnum = "TL"
	DoctorCountryEnumRe DoctorCountryEnum = "RE"
	DoctorCountryEnumTm DoctorCountryEnum = "TM"
	DoctorCountryEnumTj DoctorCountryEnum = "TJ"
	DoctorCountryEnumRo DoctorCountryEnum = "RO"
	DoctorCountryEnumTk DoctorCountryEnum = "TK"
	DoctorCountryEnumGw DoctorCountryEnum = "GW"
	DoctorCountryEnumGu DoctorCountryEnum = "GU"
	DoctorCountryEnumGt DoctorCountryEnum = "GT"
	DoctorCountryEnumGs DoctorCountryEnum = "GS"
	DoctorCountryEnumGr DoctorCountryEnum = "GR"
	DoctorCountryEnumGq DoctorCountryEnum = "GQ"
	DoctorCountryEnumGp DoctorCountryEnum = "GP"
	DoctorCountryEnumBh DoctorCountryEnum = "BH"
	DoctorCountryEnumGy DoctorCountryEnum = "GY"
	DoctorCountryEnumGg DoctorCountryEnum = "GG"
	DoctorCountryEnumGf DoctorCountryEnum = "GF"
	DoctorCountryEnumGe DoctorCountryEnum = "GE"
	DoctorCountryEnumGd DoctorCountryEnum = "GD"
	DoctorCountryEnumGb DoctorCountryEnum = "GB"
	DoctorCountryEnumGa DoctorCountryEnum = "GA"
	DoctorCountryEnumGn DoctorCountryEnum = "GN"
	DoctorCountryEnumGm DoctorCountryEnum = "GM"
	DoctorCountryEnumGl DoctorCountryEnum = "GL"
	DoctorCountryEnumKw DoctorCountryEnum = "KW"
	DoctorCountryEnumGi DoctorCountryEnum = "GI"
	DoctorCountryEnumGh DoctorCountryEnum = "GH"
	DoctorCountryEnumOm DoctorCountryEnum = "OM"
	DoctorCountryEnumTn DoctorCountryEnum = "TN"
	DoctorCountryEnumBw DoctorCountryEnum = "BW"
	DoctorCountryEnumHr DoctorCountryEnum = "HR"
	DoctorCountryEnumHt DoctorCountryEnum = "HT"
	DoctorCountryEnumHu DoctorCountryEnum = "HU"
	DoctorCountryEnumHk DoctorCountryEnum = "HK"
	DoctorCountryEnumHn DoctorCountryEnum = "HN"
	DoctorCountryEnumHm DoctorCountryEnum = "HM"
	DoctorCountryEnumKr DoctorCountryEnum = "KR"
	DoctorCountryEnumAd DoctorCountryEnum = "AD"
	DoctorCountryEnumPr DoctorCountryEnum = "PR"
	DoctorCountryEnumPs DoctorCountryEnum = "PS"
	DoctorCountryEnumPw DoctorCountryEnum = "PW"
	DoctorCountryEnumPt DoctorCountryEnum = "PT"
	DoctorCountryEnumKn DoctorCountryEnum = "KN"
	DoctorCountryEnumPy DoctorCountryEnum = "PY"
	DoctorCountryEnumAi DoctorCountryEnum = "AI"
	DoctorCountryEnumPa DoctorCountryEnum = "PA"
	DoctorCountryEnumPf DoctorCountryEnum = "PF"
	DoctorCountryEnumPg DoctorCountryEnum = "PG"
	DoctorCountryEnumPe DoctorCountryEnum = "PE"
	DoctorCountryEnumPk DoctorCountryEnum = "PK"
	DoctorCountryEnumPh DoctorCountryEnum = "PH"
	DoctorCountryEnumPn DoctorCountryEnum = "PN"
	DoctorCountryEnumPl DoctorCountryEnum = "PL"
	DoctorCountryEnumPm DoctorCountryEnum = "PM"
	DoctorCountryEnumZm DoctorCountryEnum = "ZM"
	DoctorCountryEnumEh DoctorCountryEnum = "EH"
	DoctorCountryEnumEe DoctorCountryEnum = "EE"
	DoctorCountryEnumEg DoctorCountryEnum = "EG"
	DoctorCountryEnumZa DoctorCountryEnum = "ZA"
	DoctorCountryEnumEc DoctorCountryEnum = "EC"
	DoctorCountryEnumAl DoctorCountryEnum = "AL"
	DoctorCountryEnumAo DoctorCountryEnum = "AO"
	DoctorCountryEnumKz DoctorCountryEnum = "KZ"
	DoctorCountryEnumEt DoctorCountryEnum = "ET"
	DoctorCountryEnumZw DoctorCountryEnum = "ZW"
	DoctorCountryEnumKy DoctorCountryEnum = "KY"
	DoctorCountryEnumEs DoctorCountryEnum = "ES"
	DoctorCountryEnumEr DoctorCountryEnum = "ER"
	DoctorCountryEnumMe DoctorCountryEnum = "ME"
	DoctorCountryEnumMd DoctorCountryEnum = "MD"
	DoctorCountryEnumMg DoctorCountryEnum = "MG"
	DoctorCountryEnumMf DoctorCountryEnum = "MF"
	DoctorCountryEnumMa DoctorCountryEnum = "MA"
	DoctorCountryEnumMc DoctorCountryEnum = "MC"
	DoctorCountryEnumUz DoctorCountryEnum = "UZ"
	DoctorCountryEnumMm DoctorCountryEnum = "MM"
	DoctorCountryEnumMl DoctorCountryEnum = "ML"
	DoctorCountryEnumMo DoctorCountryEnum = "MO"
	DoctorCountryEnumMn DoctorCountryEnum = "MN"
	DoctorCountryEnumMh DoctorCountryEnum = "MH"
	DoctorCountryEnumMk DoctorCountryEnum = "MK"
	DoctorCountryEnumMu DoctorCountryEnum = "MU"
	DoctorCountryEnumMt DoctorCountryEnum = "MT"
	DoctorCountryEnumMw DoctorCountryEnum = "MW"
	DoctorCountryEnumMv DoctorCountryEnum = "MV"
	DoctorCountryEnumMq DoctorCountryEnum = "MQ"
	DoctorCountryEnumMp DoctorCountryEnum = "MP"
	DoctorCountryEnumMs DoctorCountryEnum = "MS"
	DoctorCountryEnumMr DoctorCountryEnum = "MR"
	DoctorCountryEnumAu DoctorCountryEnum = "AU"
	DoctorCountryEnumUg DoctorCountryEnum = "UG"
	DoctorCountryEnumMy DoctorCountryEnum = "MY"
	DoctorCountryEnumMx DoctorCountryEnum = "MX"
	DoctorCountryEnumMz DoctorCountryEnum = "MZ"
	DoctorCountryEnumFr DoctorCountryEnum = "FR"
	DoctorCountryEnumAw DoctorCountryEnum = "AW"
	DoctorCountryEnumAf DoctorCountryEnum = "AF"
	DoctorCountryEnumAx DoctorCountryEnum = "AX"
	DoctorCountryEnumFi DoctorCountryEnum = "FI"
	DoctorCountryEnumFj DoctorCountryEnum = "FJ"
	DoctorCountryEnumFk DoctorCountryEnum = "FK"
	DoctorCountryEnumFm DoctorCountryEnum = "FM"
	DoctorCountryEnumFo DoctorCountryEnum = "FO"
	DoctorCountryEnumNi DoctorCountryEnum = "NI"
	DoctorCountryEnumNl DoctorCountryEnum = "NL"
	DoctorCountryEnumNo DoctorCountryEnum = "NO"
	DoctorCountryEnumNa DoctorCountryEnum = "NA"
	DoctorCountryEnumVu DoctorCountryEnum = "VU"
	DoctorCountryEnumNc DoctorCountryEnum = "NC"
	DoctorCountryEnumNe DoctorCountryEnum = "NE"
	DoctorCountryEnumNf DoctorCountryEnum = "NF"
	DoctorCountryEnumNg DoctorCountryEnum = "NG"
	DoctorCountryEnumNz DoctorCountryEnum = "NZ"
	DoctorCountryEnumNp DoctorCountryEnum = "NP"
	DoctorCountryEnumNr DoctorCountryEnum = "NR"
	DoctorCountryEnumNu DoctorCountryEnum = "NU"
	DoctorCountryEnumCk DoctorCountryEnum = "CK"
	DoctorCountryEnumCi DoctorCountryEnum = "CI"
	DoctorCountryEnumCh DoctorCountryEnum = "CH"
	DoctorCountryEnumCo DoctorCountryEnum = "CO"
	DoctorCountryEnumCn DoctorCountryEnum = "CN"
	DoctorCountryEnumCm DoctorCountryEnum = "CM"
	DoctorCountryEnumCl DoctorCountryEnum = "CL"
	DoctorCountryEnumCc DoctorCountryEnum = "CC"
	DoctorCountryEnumCa DoctorCountryEnum = "CA"
	DoctorCountryEnumCg DoctorCountryEnum = "CG"
	DoctorCountryEnumCf DoctorCountryEnum = "CF"
	DoctorCountryEnumCd DoctorCountryEnum = "CD"
	DoctorCountryEnumCz DoctorCountryEnum = "CZ"
	DoctorCountryEnumCy DoctorCountryEnum = "CY"
	DoctorCountryEnumCx DoctorCountryEnum = "CX"
	DoctorCountryEnumCr DoctorCountryEnum = "CR"
	DoctorCountryEnumKp DoctorCountryEnum = "KP"
	DoctorCountryEnumCw DoctorCountryEnum = "CW"
	DoctorCountryEnumCv DoctorCountryEnum = "CV"
	DoctorCountryEnumCu DoctorCountryEnum = "CU"
	DoctorCountryEnumSz DoctorCountryEnum = "SZ"
	DoctorCountryEnumSy DoctorCountryEnum = "SY"
	DoctorCountryEnumSx DoctorCountryEnum = "SX"
	DoctorCountryEnumKg DoctorCountryEnum = "KG"
	DoctorCountryEnumKe DoctorCountryEnum = "KE"
	DoctorCountryEnumSs DoctorCountryEnum = "SS"
	DoctorCountryEnumSr DoctorCountryEnum = "SR"
	DoctorCountryEnumKi DoctorCountryEnum = "KI"
	DoctorCountryEnumKh DoctorCountryEnum = "KH"
	DoctorCountryEnumSv DoctorCountryEnum = "SV"
	DoctorCountryEnumKm DoctorCountryEnum = "KM"
	DoctorCountryEnumSt DoctorCountryEnum = "ST"
	DoctorCountryEnumSk DoctorCountryEnum = "SK"
	DoctorCountryEnumSj DoctorCountryEnum = "SJ"
	DoctorCountryEnumSi DoctorCountryEnum = "SI"
	DoctorCountryEnumSh DoctorCountryEnum = "SH"
	DoctorCountryEnumSo DoctorCountryEnum = "SO"
	DoctorCountryEnumSn DoctorCountryEnum = "SN"
	DoctorCountryEnumSm DoctorCountryEnum = "SM"
	DoctorCountryEnumSl DoctorCountryEnum = "SL"
	DoctorCountryEnumSc DoctorCountryEnum = "SC"
	DoctorCountryEnumSb DoctorCountryEnum = "SB"
	DoctorCountryEnumSa DoctorCountryEnum = "SA"
	DoctorCountryEnumSg DoctorCountryEnum = "SG"
	DoctorCountryEnumSe DoctorCountryEnum = "SE"
	DoctorCountryEnumSd DoctorCountryEnum = "SD"
	DoctorCountryEnumDo DoctorCountryEnum = "DO"
	DoctorCountryEnumDm DoctorCountryEnum = "DM"
	DoctorCountryEnumDj DoctorCountryEnum = "DJ"
	DoctorCountryEnumDk DoctorCountryEnum = "DK"
	DoctorCountryEnumDe DoctorCountryEnum = "DE"
	DoctorCountryEnumYe DoctorCountryEnum = "YE"
	DoctorCountryEnumAt DoctorCountryEnum = "AT"
	DoctorCountryEnumDz DoctorCountryEnum = "DZ"
	DoctorCountryEnumUs DoctorCountryEnum = "US"
	DoctorCountryEnumUy DoctorCountryEnum = "UY"
	DoctorCountryEnumYt DoctorCountryEnum = "YT"
	DoctorCountryEnumUm DoctorCountryEnum = "UM"
	DoctorCountryEnumLb DoctorCountryEnum = "LB"
	DoctorCountryEnumLc DoctorCountryEnum = "LC"
	DoctorCountryEnumLa DoctorCountryEnum = "LA"
	DoctorCountryEnumTv DoctorCountryEnum = "TV"
	DoctorCountryEnumTw DoctorCountryEnum = "TW"
	DoctorCountryEnumTt DoctorCountryEnum = "TT"
	DoctorCountryEnumTr DoctorCountryEnum = "TR"
	DoctorCountryEnumLk DoctorCountryEnum = "LK"
	DoctorCountryEnumLi DoctorCountryEnum = "LI"
	DoctorCountryEnumLv DoctorCountryEnum = "LV"
	DoctorCountryEnumTo DoctorCountryEnum = "TO"
	DoctorCountryEnumLt DoctorCountryEnum = "LT"
	DoctorCountryEnumLu DoctorCountryEnum = "LU"
	DoctorCountryEnumLr DoctorCountryEnum = "LR"
	DoctorCountryEnumLs DoctorCountryEnum = "LS"
	DoctorCountryEnumTh DoctorCountryEnum = "TH"
	DoctorCountryEnumTf DoctorCountryEnum = "TF"
	DoctorCountryEnumTg DoctorCountryEnum = "TG"
	DoctorCountryEnumTd DoctorCountryEnum = "TD"
	DoctorCountryEnumTc DoctorCountryEnum = "TC"
	DoctorCountryEnumLy DoctorCountryEnum = "LY"
	DoctorCountryEnumVa DoctorCountryEnum = "VA"
	DoctorCountryEnumVc DoctorCountryEnum = "VC"
	DoctorCountryEnumAe DoctorCountryEnum = "AE"
	DoctorCountryEnumVe DoctorCountryEnum = "VE"
	DoctorCountryEnumAg DoctorCountryEnum = "AG"
	DoctorCountryEnumVg DoctorCountryEnum = "VG"
	DoctorCountryEnumIq DoctorCountryEnum = "IQ"
	DoctorCountryEnumVi DoctorCountryEnum = "VI"
	DoctorCountryEnumIs DoctorCountryEnum = "IS"
	DoctorCountryEnumIr DoctorCountryEnum = "IR"
	DoctorCountryEnumAm DoctorCountryEnum = "AM"
	DoctorCountryEnumIt DoctorCountryEnum = "IT"
	DoctorCountryEnumVn DoctorCountryEnum = "VN"
	DoctorCountryEnumAq DoctorCountryEnum = "AQ"
	DoctorCountryEnumAs DoctorCountryEnum = "AS"
	DoctorCountryEnumAr DoctorCountryEnum = "AR"
	DoctorCountryEnumIm DoctorCountryEnum = "IM"
	DoctorCountryEnumIl DoctorCountryEnum = "IL"
	DoctorCountryEnumIo DoctorCountryEnum = "IO"
	DoctorCountryEnumIn DoctorCountryEnum = "IN"
	DoctorCountryEnumTz DoctorCountryEnum = "TZ"
	DoctorCountryEnumAz DoctorCountryEnum = "AZ"
	DoctorCountryEnumIe DoctorCountryEnum = "IE"
	DoctorCountryEnumID DoctorCountryEnum = "ID"
	DoctorCountryEnumUa DoctorCountryEnum = "UA"
	DoctorCountryEnumQa DoctorCountryEnum = "QA"
)

type DoctorJobTitleEnum string

const (
	DoctorJobTitleEnumUnknown                      DoctorJobTitleEnum = ""
	DoctorJobTitleEnumProviderStaffPrivatePractice DoctorJobTitleEnum = "Provider/Staff (Private Practice)"
	DoctorJobTitleEnumProviderStaffHospital        DoctorJobTitleEnum = "Provider/Staff (Hospital)"
	DoctorJobTitleEnumPatientsInterviewCandidate   DoctorJobTitleEnum = "Patients/Interview Candidate"
	DoctorJobTitleEnumEducatorStudent              DoctorJobTitleEnum = "Educator/Student"
	DoctorJobTitleEnumAPIDeveloper                 DoctorJobTitleEnum = "API/Developer"
	DoctorJobTitleEnumConsultant                   DoctorJobTitleEnum = "Consultant"
	DoctorJobTitleEnumOther                        DoctorJobTitleEnum = "Other"
)

type Doctor struct {
	CellPhone          *string             `json:"cell_phone,omitempty"`
	Country            *DoctorCountryEnum  `json:"country,omitempty"`
	Email              *string             `json:"email,omitempty"`
	FirstName          *string             `json:"first_name,omitempty"`
	GroupNpiNumber     *string             `json:"group_npi_number,omitempty"`
	HomePhone          *string             `json:"home_phone,omitempty"`
	ID                 *int64              `json:"id,omitempty"`
	IsAccountSuspended *bool               `json:"is_account_suspended,omitempty"`
	JobTitle           *DoctorJobTitleEnum `json:"job_title,omitempty"`
	LastName           *string             `json:"last_name,omitempty"`
	NpiNumber          *string             `json:"npi_number,omitempty"`
	OfficePhone        *string             `json:"office_phone,omitempty"`
	PracticeGroup      *string             `json:"practice_group,omitempty"`
	PracticeGroupName  *string             `json:"practice_group_name,omitempty"`
	ProfilePicture     *string             `json:"profile_picture,omitempty"`
	Specialty          *string             `json:"specialty,omitempty"`
	Suffix             *string             `json:"suffix,omitempty"`
	Timezone           *string             `json:"timezone,omitempty"`
	Website            *string             `json:"website,omitempty"`
}
