/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class CreateApiKeyFromGroupRequest {
    
    public CreateApiKeyFromGroupPathParams pathParams;
    public CreateApiKeyFromGroupRequest withPathParams(CreateApiKeyFromGroupPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.ApiKey request;
    public CreateApiKeyFromGroupRequest withRequest(org.openapis.openapi.models.shared.ApiKey request) {
        this.request = request;
        return this;
    }
    
    
    public CreateApiKeyFromGroupSecurity security;
    public CreateApiKeyFromGroupRequest withSecurity(CreateApiKeyFromGroupSecurity security) {
        this.security = security;
        return this;
    }
    
}
