from .deleteaeassessment import *
from .deletebatchjob import *
from .deletecisinstruction import *
from .deletecisinstructiontag import *
from .deletecisjob import *
from .deletecisline import *
from .deletecislinetag import *
from .deletecislinetype import *
from .deletecislinetypetag import *
from .deletecistransaction import *
from .deletedpsjob import *
from .deletedpsmessage import *
from .deleteemployee import *
from .deleteemployeerevision import *
from .deleteemployeerevisionbynumber import *
from .deleteemployeesecret import *
from .deleteemployeetag import *
from .deleteemployer import *
from .deleteemployerrevision import *
from .deleteemployerrevisionbynumber import *
from .deleteemployersecret import *
from .deleteemployertag import *
from .deleteholidayscheme import *
from .deleteholidayschemerevision import *
from .deleteholidayschemerevisionbynumber import *
from .deleteholidayschemetag import *
from .deletejournalinstruction import *
from .deletejournalinstructiontemplate import *
from .deletejournallinetag import *
from .deletenominalcode import *
from .deletepaycode import *
from .deletepaycoderevision import *
from .deletepaycoderevisionbynumber import *
from .deletepaycodetag import *
from .deletepayinstruction import *
from .deletepayinstructiontag import *
from .deletepaylinetag import *
from .deletepayrun import *
from .deletepayrunemployee import *
from .deletepayrunjob import *
from .deletepayruntag import *
from .deletepayschedule import *
from .deletepayscheduletag import *
from .deletepension import *
from .deletepensionrevision import *
from .deletepensionrevisionbynumber import *
from .deletepermission import *
from .deletereportdefinition import *
from .deletereportinginstruction import *
from .deletertijob import *
from .deletertitransaction import *
from .deletertitransactiontag import *
from .deletesubcontractor import *
from .deletesubcontractorrevision import *
from .deletesubcontractorrevisionbynumber import *
from .deletesubcontractortag import *
from .deletethirdpartyjob import *
from .deletethirdpartytransaction import *
from .deletethirdpartytransactiontag import *
from .deletetransformdefinition import *
from .deleteuser import *
from .deleteusertag import *
from .getactivepayinstructionsreportoutput import *
from .getaeassessmentfromemployee import *
from .getaeassessmentsfromemployee import *
from .getaeassessmentsfrompayrun import *
from .getallcisinstructiontags import *
from .getallcislinetags import *
from .getallcislinetypetags import *
from .getallemployeetags import *
from .getallemployertags import *
from .getallholidayschemetags import *
from .getalljournallineswithtag import *
from .getalljournallinetags import *
from .getallpaycodetags import *
from .getallpayinstructiontags import *
from .getallpaylinetags import *
from .getallpayruntags import *
from .getallpayscheduletags import *
from .getallrtitransactiontags import *
from .getallsubcontractortags import *
from .getallthirdpartytransactionswithtag import *
from .getallthirdpartytransactiontags import *
from .getalluserswithtag import *
from .getallusertags import *
from .getaoeliabilityreportouput import *
from .getbatchjobinfo import *
from .getbatchjobprogress import *
from .getbatchjobs import *
from .getbatchjobstatus import *
from .getcisinstructionfromsubcontractor import *
from .getcisinstructionsfromsubcontractor import *
from .getcisinstructionswithtag import *
from .getcisjobinfo import *
from .getcisjobprogress import *
from .getcisjobs import *
from .getcisjobstatus import *
from .getcislinefromsubcontractor import *
from .getcislinesfromsubcontractor import *
from .getcislineswithtag import *
from .getcislinetypefromemployer import *
from .getcislinetypesfromemployer import *
from .getcislinetypeswithtag import *
from .getcistransactionfromemployer import *
from .getcistransactionsfromemployer import *
from .getcommentariesfromemployee import *
from .getcommentariesfrompayrun import *
from .getcommentaryfromemployee import *
from .getcommentaryfrompayrunbyemployee import *
from .getdpsjobinfo import *
from .getdpsjobprogress import *
from .getdpsjobs import *
from .getdpsjobstatus import *
from .getdpsmessagefromemployer import *
from .getdpsmessagereportoutput import *
from .getdpsmessagesfromemployer import *
from .getemployeebyeffectivedate import *
from .getemployeefromemployer import *
from .getemployeerevisionbynumber import *
from .getemployeerevisions import *
from .getemployeesbyeffectivedate import *
from .getemployeesecret import *
from .getemployeesecrets import *
from .getemployeesfromemployer import *
from .getemployeesfrompayrun import *
from .getemployeesfrompayschedule import *
from .getemployeesfrompayscheduleoneffectivedate import *
from .getemployeeswithtag import *
from .getemployer import *
from .getemployerbyeffectivedate import *
from .getemployerjobs import *
from .getemployerrevisionbynumber import *
from .getemployerrevisions import *
from .getemployers import *
from .getemployersbyeffectivedate import *
from .getemployersecret import *
from .getemployersecrets import *
from .getemployersummaryreportouput import *
from .getemployerswithtag import *
from .getgrosstonetreportoutput import *
from .gethealthcheck import *
from .getholidaybalancereportoutput import *
from .getholidayschemebyeffectivedate import *
from .getholidayschemefromemployer import *
from .getholidayschemerevisionbynumber import *
from .getholidayschemerevisions import *
from .getholidayschemesbyeffectivedate import *
from .getholidayschemesfromemployer import *
from .getholidayschemeswithtag import *
from .getjournalexpressionschema import *
from .getjournalinstructionfromemployer import *
from .getjournalinstructionsfromemployer import *
from .getjournalinstructiontemplate import *
from .getjournalinstructiontemplates import *
from .getjournallinefromemployer import *
from .getjournallinesfromemployee import *
from .getjournallinesfromemployer import *
from .getjournallinesfrompayrun import *
from .getjournallinesfromsubcontractor import *
from .getjournalreportouput import *
from .getlastpaydatereportouput import *
from .getnetpayreportoutput import *
from .getnextpayperioddatesreportoutput import *
from .getnominalcodefromemployer import *
from .getnominalcodesfromemployer import *
from .getp11summaryreportoutput import *
from .getp32netreportoutput import *
from .getp32summarynetreportoutput import *
from .getp45reportoutput import *
from .getp60reportoutput import *
from .getpapdisreportouput import *
from .getpassreportouput import *
from .getpaycodebyeffectivedate import *
from .getpaycodefromemployer import *
from .getpaycoderevisionbynumber import *
from .getpaycoderevisions import *
from .getpaycodesbyeffectivedate import *
from .getpaycodesfromemployer import *
from .getpaycodesfromnominalcode import *
from .getpaycodeswithtag import *
from .getpaydashboardpayslipreportouput import *
from .getpayinstructionfromemployee import *
from .getpayinstructionsfromemployee import *
from .getpayinstructionswithtag import *
from .getpaylinefromemployee import *
from .getpaylinesfromemployee import *
from .getpaylineswithtag import *
from .getpayrunfrompayschedule import *
from .getpayrunjobinfo import *
from .getpayrunjobprogress import *
from .getpayrunjobs import *
from .getpayrunjobstatus import *
from .getpayrunsfromemployee import *
from .getpayrunsfrompayschedule import *
from .getpayrunswithtag import *
from .getpayschedulefromemployer import *
from .getpayschedulesfromemployer import *
from .getpayscheduleswithtag import *
from .getpayslip3reportoutput import *
from .getpensionbyeffectivedate import *
from .getpensionfromemployer import *
from .getpensionliabilityreportoutput import *
from .getpensionrevisionbynumber import *
from .getpensionrevisions import *
from .getpensionsbyeffectivedate import *
from .getpensionsfromemployer import *
from .getpermission import *
from .getpermissions import *
from .getqueryresponse import *
from .getreportdefinitionfromapplication import *
from .getreportdefinitionsfromapplication import *
from .getreportinginstructionfromemployer import *
from .getreportinginstructionsfromemployer import *
from .getreportlinefromemployer import *
from .getreportlinesfromemployer import *
from .getreportlinesfrompayrun import *
from .getreportoutput import *
from .getrtijobinfo import *
from .getrtijobprogress import *
from .getrtijobs import *
from .getrtijobstatus import *
from .getrtitransactionfromemployer import *
from .getrtitransactionsfromemployer import *
from .getrtitransactionswithtag import *
from .getschema import *
from .getschemas import *
from .getsubcontractorbyeffectivedate import *
from .getsubcontractorfromemployer import *
from .getsubcontractorrevisionbynumber import *
from .getsubcontractorrevisions import *
from .getsubcontractorsbyeffectivedate import *
from .getsubcontractorsfromemployer import *
from .getsubcontractorswithtag import *
from .gettagfromcisinstruction import *
from .gettagfromcisline import *
from .gettagfromcislinetype import *
from .gettagfromemployee import *
from .gettagfromemployeerevision import *
from .gettagfromemployer import *
from .gettagfromemployerrevision import *
from .gettagfromholidayscheme import *
from .gettagfromholidayschemerevision import *
from .gettagfromjournalline import *
from .gettagfrompaycode import *
from .gettagfrompayinstruction import *
from .gettagfrompayline import *
from .gettagfrompayrun import *
from .gettagfrompayschedule import *
from .gettagfromrtitransaction import *
from .gettagfromsubcontractor import *
from .gettagfromsubcontractorrevision import *
from .gettagfromthirdpartytransaction import *
from .gettagfromuser import *
from .gettagsfromcisinstruction import *
from .gettagsfromcisline import *
from .gettagsfromcislinetype import *
from .gettagsfromemployee import *
from .gettagsfromemployeerevision import *
from .gettagsfromemployer import *
from .gettagsfromemployerrevision import *
from .gettagsfromholidayscheme import *
from .gettagsfromholidayschemerevision import *
from .gettagsfromjournalline import *
from .gettagsfrompaycode import *
from .gettagsfrompayinstruction import *
from .gettagsfrompayline import *
from .gettagsfrompayrun import *
from .gettagsfrompayschedule import *
from .gettagsfromrtitransaction import *
from .gettagsfromsubcontractor import *
from .gettagsfromsubcontractorrevision import *
from .gettagsfromthirdpartytransaction import *
from .gettagsfromuser import *
from .gettemplatemodel import *
from .gettemplates import *
from .getthirdpartyjobinfo import *
from .getthirdpartyjobprogress import *
from .getthirdpartyjobs import *
from .getthirdpartyjobstatus import *
from .getthirdpartytransaction import *
from .getthirdpartytransactions import *
from .gettransformdefinitionfromapplication import *
from .gettransformdefinitionsfromapplication import *
from .getuser import *
from .getusers import *
from .patchcisinstruction import *
from .patchdpsmessage import *
from .patchemployee import *
from .patchemployer import *
from .patchholidayscheme import *
from .patchpaycode import *
from .patchpayinstruction import *
from .patchpension import *
from .patchpermission import *
from .patchsubcontractor import *
from .patchuser import *
from .postcisinstructionintosubcontractor import *
from .postcislinetypeintoemployer import *
from .postdpsmessage import *
from .postemployeeintoemployer import *
from .postemployeesecret import *
from .postemployer import *
from .postemployersecret import *
from .postholidayschemeintoemployer import *
from .postjournalinstruction import *
from .postjournalinstructiontemplate import *
from .postnewaeassessment import *
from .postnewbatchjob import *
from .postnewcisjob import *
from .postnewdpsjob import *
from .postnewpayrunjob import *
from .postnewrtijob import *
from .postnewthirdpartyjob import *
from .postnominalcode import *
from .postpaycode import *
from .postpayinstruction import *
from .postpayschedule import *
from .postpensionintoemployer import *
from .postpermission import *
from .postreportdefinition import *
from .postreportinginstruction import *
from .postsubcontractorintoemployer import *
from .posttransformdefinition import *
from .postuser import *
from .putcisinstructionintosubcontractor import *
from .putcisinstructiontag import *
from .putcislinetag import *
from .putcislinetypeintoemployer import *
from .putcislinetypetag import *
from .putdpsmessage import *
from .putemployeeintoemployer import *
from .putemployeesecret import *
from .putemployeetag import *
from .putemployer import *
from .putemployersecret import *
from .putemployertag import *
from .putholidayschemeintoemployer import *
from .putholidayschemetag import *
from .putjournalinstruction import *
from .putjournalinstructiontemplate import *
from .putjournallinetag import *
from .putnewaeassessment import *
from .putnominalcode import *
from .putpaycode import *
from .putpaycodetag import *
from .putpayinstruction import *
from .putpayinstructiontag import *
from .putpaylinetag import *
from .putpayruntag import *
from .putpayschedule import *
from .putpayscheduletag import *
from .putpensionintoemployer import *
from .putpermission import *
from .putreportdefinition import *
from .putreportinginstruction import *
from .putrtitransactiontag import *
from .putsubcontractorintoemployer import *
from .putsubcontractortag import *
from .putthirdpartytransactiontag import *
from .puttransformdefinition import *
from .putuser import *
from .putusertag import *

__all__ = ["DeleteAeAssessmentPathParams","DeleteAeAssessmentHeaders","DeleteAeAssessmentRequest","DeleteAeAssessmentResponse","DeleteBatchJobPathParams","DeleteBatchJobHeaders","DeleteBatchJobRequest","DeleteBatchJobResponse","DeleteCisInstructionPathParams","DeleteCisInstructionHeaders","DeleteCisInstructionRequest","DeleteCisInstructionResponse","DeleteCisInstructionTagPathParams","DeleteCisInstructionTagHeaders","DeleteCisInstructionTagRequest","DeleteCisInstructionTagResponse","DeleteCisJobPathParams","DeleteCisJobHeaders","DeleteCisJobRequest","DeleteCisJobResponse","DeleteCisLinePathParams","DeleteCisLineHeaders","DeleteCisLineRequest","DeleteCisLineResponse","DeleteCisLineTagPathParams","DeleteCisLineTagHeaders","DeleteCisLineTagRequest","DeleteCisLineTagResponse","DeleteCisLineTypePathParams","DeleteCisLineTypeHeaders","DeleteCisLineTypeRequest","DeleteCisLineTypeResponse","DeleteCisLineTypeTagPathParams","DeleteCisLineTypeTagHeaders","DeleteCisLineTypeTagRequest","DeleteCisLineTypeTagResponse","DeleteCisTransactionPathParams","DeleteCisTransactionHeaders","DeleteCisTransactionRequest","DeleteCisTransactionResponse","DeleteDpsJobPathParams","DeleteDpsJobHeaders","DeleteDpsJobRequest","DeleteDpsJobResponse","DeleteDpsMessagePathParams","DeleteDpsMessageHeaders","DeleteDpsMessageRequest","DeleteDpsMessageResponse","DeleteEmployeePathParams","DeleteEmployeeHeaders","DeleteEmployeeRequest","DeleteEmployeeResponse","DeleteEmployeeRevisionPathParams","DeleteEmployeeRevisionHeaders","DeleteEmployeeRevisionRequest","DeleteEmployeeRevisionResponse","DeleteEmployeeRevisionByNumberPathParams","DeleteEmployeeRevisionByNumberHeaders","DeleteEmployeeRevisionByNumberRequest","DeleteEmployeeRevisionByNumberResponse","DeleteEmployeeSecretPathParams","DeleteEmployeeSecretHeaders","DeleteEmployeeSecretRequest","DeleteEmployeeSecretResponse","DeleteEmployeeTagPathParams","DeleteEmployeeTagHeaders","DeleteEmployeeTagRequest","DeleteEmployeeTagResponse","DeleteEmployerPathParams","DeleteEmployerHeaders","DeleteEmployerRequest","DeleteEmployerResponse","DeleteEmployerRevisionPathParams","DeleteEmployerRevisionHeaders","DeleteEmployerRevisionRequest","DeleteEmployerRevisionResponse","DeleteEmployerRevisionByNumberPathParams","DeleteEmployerRevisionByNumberHeaders","DeleteEmployerRevisionByNumberRequest","DeleteEmployerRevisionByNumberResponse","DeleteEmployerSecretPathParams","DeleteEmployerSecretHeaders","DeleteEmployerSecretRequest","DeleteEmployerSecretResponse","DeleteEmployerTagPathParams","DeleteEmployerTagHeaders","DeleteEmployerTagRequest","DeleteEmployerTagResponse","DeleteHolidaySchemePathParams","DeleteHolidaySchemeHeaders","DeleteHolidaySchemeRequest","DeleteHolidaySchemeResponse","DeleteHolidaySchemeRevisionPathParams","DeleteHolidaySchemeRevisionHeaders","DeleteHolidaySchemeRevisionRequest","DeleteHolidaySchemeRevisionResponse","DeleteHolidaySchemeRevisionByNumberPathParams","DeleteHolidaySchemeRevisionByNumberHeaders","DeleteHolidaySchemeRevisionByNumberRequest","DeleteHolidaySchemeRevisionByNumberResponse","DeleteHolidaySchemeTagPathParams","DeleteHolidaySchemeTagHeaders","DeleteHolidaySchemeTagRequest","DeleteHolidaySchemeTagResponse","DeleteJournalInstructionPathParams","DeleteJournalInstructionHeaders","DeleteJournalInstructionRequest","DeleteJournalInstructionResponse","DeleteJournalInstructionTemplatePathParams","DeleteJournalInstructionTemplateHeaders","DeleteJournalInstructionTemplateRequest","DeleteJournalInstructionTemplateResponse","DeleteJournalLineTagPathParams","DeleteJournalLineTagHeaders","DeleteJournalLineTagRequest","DeleteJournalLineTagResponse","DeleteNominalCodePathParams","DeleteNominalCodeHeaders","DeleteNominalCodeRequest","DeleteNominalCodeResponse","DeletePayCodePathParams","DeletePayCodeHeaders","DeletePayCodeRequest","DeletePayCodeResponse","DeletePayCodeRevisionPathParams","DeletePayCodeRevisionHeaders","DeletePayCodeRevisionRequest","DeletePayCodeRevisionResponse","DeletePayCodeRevisionByNumberPathParams","DeletePayCodeRevisionByNumberHeaders","DeletePayCodeRevisionByNumberRequest","DeletePayCodeRevisionByNumberResponse","DeletePayCodeTagPathParams","DeletePayCodeTagHeaders","DeletePayCodeTagRequest","DeletePayCodeTagResponse","DeletePayInstructionPathParams","DeletePayInstructionHeaders","DeletePayInstructionRequest","DeletePayInstructionResponse","DeletePayInstructionTagPathParams","DeletePayInstructionTagHeaders","DeletePayInstructionTagRequest","DeletePayInstructionTagResponse","DeletePayLineTagPathParams","DeletePayLineTagHeaders","DeletePayLineTagRequest","DeletePayLineTagResponse","DeletePayRunPathParams","DeletePayRunHeaders","DeletePayRunRequest","DeletePayRunResponse","DeletePayRunEmployeePathParams","DeletePayRunEmployeeHeaders","DeletePayRunEmployeeRequest","DeletePayRunEmployeeResponse","DeletePayRunJobPathParams","DeletePayRunJobHeaders","DeletePayRunJobRequest","DeletePayRunJobResponse","DeletePayRunTagPathParams","DeletePayRunTagHeaders","DeletePayRunTagRequest","DeletePayRunTagResponse","DeletePaySchedulePathParams","DeletePayScheduleHeaders","DeletePayScheduleRequest","DeletePayScheduleResponse","DeletePayScheduleTagPathParams","DeletePayScheduleTagHeaders","DeletePayScheduleTagRequest","DeletePayScheduleTagResponse","DeletePensionPathParams","DeletePensionHeaders","DeletePensionRequest","DeletePensionResponse","DeletePensionRevisionPathParams","DeletePensionRevisionHeaders","DeletePensionRevisionRequest","DeletePensionRevisionResponse","DeletePensionRevisionByNumberPathParams","DeletePensionRevisionByNumberHeaders","DeletePensionRevisionByNumberRequest","DeletePensionRevisionByNumberResponse","DeletePermissionPathParams","DeletePermissionHeaders","DeletePermissionRequest","DeletePermissionResponse","DeleteReportDefinitionPathParams","DeleteReportDefinitionHeaders","DeleteReportDefinitionRequest","DeleteReportDefinitionResponse","DeleteReportingInstructionPathParams","DeleteReportingInstructionHeaders","DeleteReportingInstructionRequest","DeleteReportingInstructionResponse","DeleteRtiJobPathParams","DeleteRtiJobHeaders","DeleteRtiJobRequest","DeleteRtiJobResponse","DeleteRtiTransactionPathParams","DeleteRtiTransactionHeaders","DeleteRtiTransactionRequest","DeleteRtiTransactionResponse","DeleteRtiTransactionTagPathParams","DeleteRtiTransactionTagHeaders","DeleteRtiTransactionTagRequest","DeleteRtiTransactionTagResponse","DeleteSubContractorPathParams","DeleteSubContractorHeaders","DeleteSubContractorRequest","DeleteSubContractorResponse","DeleteSubContractorRevisionPathParams","DeleteSubContractorRevisionHeaders","DeleteSubContractorRevisionRequest","DeleteSubContractorRevisionResponse","DeleteSubContractorRevisionByNumberPathParams","DeleteSubContractorRevisionByNumberHeaders","DeleteSubContractorRevisionByNumberRequest","DeleteSubContractorRevisionByNumberResponse","DeleteSubContractorTagPathParams","DeleteSubContractorTagHeaders","DeleteSubContractorTagRequest","DeleteSubContractorTagResponse","DeleteThirdPartyJobPathParams","DeleteThirdPartyJobHeaders","DeleteThirdPartyJobRequest","DeleteThirdPartyJobResponse","DeleteThirdPartyTransactionPathParams","DeleteThirdPartyTransactionHeaders","DeleteThirdPartyTransactionRequest","DeleteThirdPartyTransactionResponse","DeleteThirdPartyTransactionTagPathParams","DeleteThirdPartyTransactionTagHeaders","DeleteThirdPartyTransactionTagRequest","DeleteThirdPartyTransactionTagResponse","DeleteTransformDefinitionPathParams","DeleteTransformDefinitionHeaders","DeleteTransformDefinitionRequest","DeleteTransformDefinitionResponse","DeleteUserPathParams","DeleteUserHeaders","DeleteUserRequest","DeleteUserResponse","DeleteUserTagPathParams","DeleteUserTagHeaders","DeleteUserTagRequest","DeleteUserTagResponse","GetActivePayInstructionsReportOutputQueryParams","GetActivePayInstructionsReportOutputHeaders","GetActivePayInstructionsReportOutputRequest","GetActivePayInstructionsReportOutputResponse","GetAeAssessmentFromEmployeePathParams","GetAeAssessmentFromEmployeeHeaders","GetAeAssessmentFromEmployeeRequest","GetAeAssessmentFromEmployeeResponse","GetAeAssessmentsFromEmployeePathParams","GetAeAssessmentsFromEmployeeHeaders","GetAeAssessmentsFromEmployeeRequest","GetAeAssessmentsFromEmployeeResponse","GetAeAssessmentsFromPayRunPathParams","GetAeAssessmentsFromPayRunHeaders","GetAeAssessmentsFromPayRunRequest","GetAeAssessmentsFromPayRunResponse","GetAllCisInstructionTagsPathParams","GetAllCisInstructionTagsHeaders","GetAllCisInstructionTagsRequest","GetAllCisInstructionTagsResponse","GetAllCisLineTagsPathParams","GetAllCisLineTagsHeaders","GetAllCisLineTagsRequest","GetAllCisLineTagsResponse","GetAllCisLineTypeTagsPathParams","GetAllCisLineTypeTagsHeaders","GetAllCisLineTypeTagsRequest","GetAllCisLineTypeTagsResponse","GetAllEmployeeTagsPathParams","GetAllEmployeeTagsHeaders","GetAllEmployeeTagsRequest","GetAllEmployeeTagsResponse","GetAllEmployerTagsHeaders","GetAllEmployerTagsRequest","GetAllEmployerTagsResponse","GetAllHolidaySchemeTagsPathParams","GetAllHolidaySchemeTagsHeaders","GetAllHolidaySchemeTagsRequest","GetAllHolidaySchemeTagsResponse","GetAllJournalLinesWithTagPathParams","GetAllJournalLinesWithTagHeaders","GetAllJournalLinesWithTagRequest","GetAllJournalLinesWithTagResponse","GetAllJournalLineTagsPathParams","GetAllJournalLineTagsHeaders","GetAllJournalLineTagsRequest","GetAllJournalLineTagsResponse","GetAllPayCodeTagsPathParams","GetAllPayCodeTagsHeaders","GetAllPayCodeTagsRequest","GetAllPayCodeTagsResponse","GetAllPayInstructionTagsPathParams","GetAllPayInstructionTagsHeaders","GetAllPayInstructionTagsRequest","GetAllPayInstructionTagsResponse","GetAllPayLineTagsPathParams","GetAllPayLineTagsHeaders","GetAllPayLineTagsRequest","GetAllPayLineTagsResponse","GetAllPayRunTagsPathParams","GetAllPayRunTagsHeaders","GetAllPayRunTagsRequest","GetAllPayRunTagsResponse","GetAllPayScheduleTagsPathParams","GetAllPayScheduleTagsHeaders","GetAllPayScheduleTagsRequest","GetAllPayScheduleTagsResponse","GetAllRtiTransactionTagsPathParams","GetAllRtiTransactionTagsHeaders","GetAllRtiTransactionTagsRequest","GetAllRtiTransactionTagsResponse","GetAllSubContractorTagsPathParams","GetAllSubContractorTagsHeaders","GetAllSubContractorTagsRequest","GetAllSubContractorTagsResponse","GetAllThirdPartyTransactionsWithTagPathParams","GetAllThirdPartyTransactionsWithTagHeaders","GetAllThirdPartyTransactionsWithTagRequest","GetAllThirdPartyTransactionsWithTagResponse","GetAllThirdPartyTransactionTagsPathParams","GetAllThirdPartyTransactionTagsHeaders","GetAllThirdPartyTransactionTagsRequest","GetAllThirdPartyTransactionTagsResponse","GetAllUsersWithTagPathParams","GetAllUsersWithTagHeaders","GetAllUsersWithTagRequest","GetAllUsersWithTagResponse","GetAllUserTagsHeaders","GetAllUserTagsRequest","GetAllUserTagsResponse","GetAoeLiabilityReportOuputQueryParams","GetAoeLiabilityReportOuputHeaders","GetAoeLiabilityReportOuputRequest","GetAoeLiabilityReportOuputResponse","GetBatchJobInfoPathParams","GetBatchJobInfoHeaders","GetBatchJobInfoRequest","GetBatchJobInfoResponse","GetBatchJobProgressPathParams","GetBatchJobProgressHeaders","GetBatchJobProgressRequest","GetBatchJobProgressResponse","GetBatchJobsHeaders","GetBatchJobsRequest","GetBatchJobsResponse","GetBatchJobStatusPathParams","GetBatchJobStatusHeaders","GetBatchJobStatusRequest","GetBatchJobStatusResponse","GetCisInstructionFromSubContractorPathParams","GetCisInstructionFromSubContractorHeaders","GetCisInstructionFromSubContractorRequest","GetCisInstructionFromSubContractorResponse","GetCisInstructionsFromSubContractorPathParams","GetCisInstructionsFromSubContractorHeaders","GetCisInstructionsFromSubContractorRequest","GetCisInstructionsFromSubContractorResponse","GetCisInstructionsWithTagPathParams","GetCisInstructionsWithTagHeaders","GetCisInstructionsWithTagRequest","GetCisInstructionsWithTagResponse","GetCisJobInfoPathParams","GetCisJobInfoHeaders","GetCisJobInfoRequest","GetCisJobInfoResponse","GetCisJobProgressPathParams","GetCisJobProgressHeaders","GetCisJobProgressRequest","GetCisJobProgressResponse","GetCisJobsHeaders","GetCisJobsRequest","GetCisJobsResponse","GetCisJobStatusPathParams","GetCisJobStatusHeaders","GetCisJobStatusRequest","GetCisJobStatusResponse","GetCisLineFromSubContractorPathParams","GetCisLineFromSubContractorHeaders","GetCisLineFromSubContractorRequest","GetCisLineFromSubContractorResponse","GetCisLinesFromSubContractorPathParams","GetCisLinesFromSubContractorHeaders","GetCisLinesFromSubContractorRequest","GetCisLinesFromSubContractorResponse","GetCisLinesWithTagPathParams","GetCisLinesWithTagHeaders","GetCisLinesWithTagRequest","GetCisLinesWithTagResponse","GetCisLineTypeFromEmployerPathParams","GetCisLineTypeFromEmployerHeaders","GetCisLineTypeFromEmployerRequest","GetCisLineTypeFromEmployerResponse","GetCisLineTypesFromEmployerPathParams","GetCisLineTypesFromEmployerHeaders","GetCisLineTypesFromEmployerRequest","GetCisLineTypesFromEmployerResponse","GetCisLineTypesWithTagPathParams","GetCisLineTypesWithTagHeaders","GetCisLineTypesWithTagRequest","GetCisLineTypesWithTagResponse","GetCisTransactionFromEmployerPathParams","GetCisTransactionFromEmployerHeaders","GetCisTransactionFromEmployerRequest","GetCisTransactionFromEmployerResponse","GetCisTransactionsFromEmployerPathParams","GetCisTransactionsFromEmployerHeaders","GetCisTransactionsFromEmployerRequest","GetCisTransactionsFromEmployerResponse","GetCommentariesFromEmployeePathParams","GetCommentariesFromEmployeeHeaders","GetCommentariesFromEmployeeRequest","GetCommentariesFromEmployeeResponse","GetCommentariesFromPayRunPathParams","GetCommentariesFromPayRunHeaders","GetCommentariesFromPayRunRequest","GetCommentariesFromPayRunResponse","GetCommentaryFromEmployeePathParams","GetCommentaryFromEmployeeHeaders","GetCommentaryFromEmployeeRequest","GetCommentaryFromEmployeeResponse","GetCommentaryFromPayRunByEmployeePathParams","GetCommentaryFromPayRunByEmployeeHeaders","GetCommentaryFromPayRunByEmployeeRequest","GetCommentaryFromPayRunByEmployeeResponse","GetDpsJobInfoPathParams","GetDpsJobInfoHeaders","GetDpsJobInfoRequest","GetDpsJobInfoResponse","GetDpsJobProgressPathParams","GetDpsJobProgressHeaders","GetDpsJobProgressRequest","GetDpsJobProgressResponse","GetDpsJobsHeaders","GetDpsJobsRequest","GetDpsJobsResponse","GetDpsJobStatusPathParams","GetDpsJobStatusHeaders","GetDpsJobStatusRequest","GetDpsJobStatusResponse","GetDpsMessageFromEmployerPathParams","GetDpsMessageFromEmployerHeaders","GetDpsMessageFromEmployerRequest","GetDpsMessageFromEmployerResponse","GetDpsMessageReportOutputQueryParams","GetDpsMessageReportOutputHeaders","GetDpsMessageReportOutputRequest","GetDpsMessageReportOutputResponse","GetDpsMessagesFromEmployerPathParams","GetDpsMessagesFromEmployerHeaders","GetDpsMessagesFromEmployerRequest","GetDpsMessagesFromEmployerResponse","GetEmployeeByEffectiveDatePathParams","GetEmployeeByEffectiveDateHeaders","GetEmployeeByEffectiveDateRequest","GetEmployeeByEffectiveDateResponse","GetEmployeeFromEmployerPathParams","GetEmployeeFromEmployerHeaders","GetEmployeeFromEmployerRequest","GetEmployeeFromEmployerResponse","GetEmployeeRevisionByNumberPathParams","GetEmployeeRevisionByNumberHeaders","GetEmployeeRevisionByNumberRequest","GetEmployeeRevisionByNumberResponse","GetEmployeeRevisionsPathParams","GetEmployeeRevisionsHeaders","GetEmployeeRevisionsRequest","GetEmployeeRevisionsResponse","GetEmployeesByEffectiveDatePathParams","GetEmployeesByEffectiveDateHeaders","GetEmployeesByEffectiveDateRequest","GetEmployeesByEffectiveDateResponse","GetEmployeeSecretPathParams","GetEmployeeSecretHeaders","GetEmployeeSecretRequest","GetEmployeeSecretResponse","GetEmployeeSecretsPathParams","GetEmployeeSecretsHeaders","GetEmployeeSecretsRequest","GetEmployeeSecretsResponse","GetEmployeesFromEmployerPathParams","GetEmployeesFromEmployerHeaders","GetEmployeesFromEmployerRequest","GetEmployeesFromEmployerResponse","GetEmployeesFromPayRunPathParams","GetEmployeesFromPayRunHeaders","GetEmployeesFromPayRunRequest","GetEmployeesFromPayRunResponse","GetEmployeesFromPaySchedulePathParams","GetEmployeesFromPayScheduleHeaders","GetEmployeesFromPayScheduleRequest","GetEmployeesFromPayScheduleResponse","GetEmployeesFromPayScheduleOnEffectiveDatePathParams","GetEmployeesFromPayScheduleOnEffectiveDateHeaders","GetEmployeesFromPayScheduleOnEffectiveDateRequest","GetEmployeesFromPayScheduleOnEffectiveDateResponse","GetEmployeesWithTagPathParams","GetEmployeesWithTagHeaders","GetEmployeesWithTagRequest","GetEmployeesWithTagResponse","GetEmployerPathParams","GetEmployerHeaders","GetEmployerRequest","GetEmployerResponse","GetEmployerByEffectiveDatePathParams","GetEmployerByEffectiveDateHeaders","GetEmployerByEffectiveDateRequest","GetEmployerByEffectiveDateResponse","GetEmployerJobsPathParams","GetEmployerJobsHeaders","GetEmployerJobsRequest","GetEmployerJobsResponse","GetEmployerRevisionByNumberPathParams","GetEmployerRevisionByNumberHeaders","GetEmployerRevisionByNumberRequest","GetEmployerRevisionByNumberResponse","GetEmployerRevisionsPathParams","GetEmployerRevisionsHeaders","GetEmployerRevisionsRequest","GetEmployerRevisionsResponse","GetEmployersHeaders","GetEmployersRequest","GetEmployersResponse","GetEmployersByEffectiveDatePathParams","GetEmployersByEffectiveDateHeaders","GetEmployersByEffectiveDateRequest","GetEmployersByEffectiveDateResponse","GetEmployerSecretPathParams","GetEmployerSecretHeaders","GetEmployerSecretRequest","GetEmployerSecretResponse","GetEmployerSecretsPathParams","GetEmployerSecretsHeaders","GetEmployerSecretsRequest","GetEmployerSecretsResponse","GetEmployerSummaryReportOuputQueryParams","GetEmployerSummaryReportOuputHeaders","GetEmployerSummaryReportOuputRequest","GetEmployerSummaryReportOuputResponse","GetEmployersWithTagPathParams","GetEmployersWithTagHeaders","GetEmployersWithTagRequest","GetEmployersWithTagResponse","GetGrossToNetReportOutputQueryParams","GetGrossToNetReportOutputHeaders","GetGrossToNetReportOutputRequest","GetGrossToNetReportOutputResponse","GetHealthCheckResponse","GetHolidayBalanceReportOutputQueryParams","GetHolidayBalanceReportOutputHeaders","GetHolidayBalanceReportOutputRequest","GetHolidayBalanceReportOutputResponse","GetHolidaySchemeByEffectiveDatePathParams","GetHolidaySchemeByEffectiveDateHeaders","GetHolidaySchemeByEffectiveDateRequest","GetHolidaySchemeByEffectiveDateResponse","GetHolidaySchemeFromEmployerPathParams","GetHolidaySchemeFromEmployerHeaders","GetHolidaySchemeFromEmployerRequest","GetHolidaySchemeFromEmployerResponse","GetHolidaySchemeRevisionByNumberPathParams","GetHolidaySchemeRevisionByNumberHeaders","GetHolidaySchemeRevisionByNumberRequest","GetHolidaySchemeRevisionByNumberResponse","GetHolidaySchemeRevisionsPathParams","GetHolidaySchemeRevisionsHeaders","GetHolidaySchemeRevisionsRequest","GetHolidaySchemeRevisionsResponse","GetHolidaySchemesByEffectiveDatePathParams","GetHolidaySchemesByEffectiveDateHeaders","GetHolidaySchemesByEffectiveDateRequest","GetHolidaySchemesByEffectiveDateResponse","GetHolidaySchemesFromEmployerPathParams","GetHolidaySchemesFromEmployerHeaders","GetHolidaySchemesFromEmployerRequest","GetHolidaySchemesFromEmployerResponse","GetHolidaySchemesWithTagPathParams","GetHolidaySchemesWithTagHeaders","GetHolidaySchemesWithTagRequest","GetHolidaySchemesWithTagResponse","GetJournalExpressionSchemaHeaders","GetJournalExpressionSchemaRequest","GetJournalExpressionSchemaResponse","GetJournalInstructionFromEmployerPathParams","GetJournalInstructionFromEmployerHeaders","GetJournalInstructionFromEmployerRequest","GetJournalInstructionFromEmployerResponse","GetJournalInstructionsFromEmployerPathParams","GetJournalInstructionsFromEmployerHeaders","GetJournalInstructionsFromEmployerRequest","GetJournalInstructionsFromEmployerResponse","GetJournalInstructionTemplatePathParams","GetJournalInstructionTemplateHeaders","GetJournalInstructionTemplateRequest","GetJournalInstructionTemplateResponse","GetJournalInstructionTemplatesHeaders","GetJournalInstructionTemplatesRequest","GetJournalInstructionTemplatesResponse","GetJournalLineFromEmployerPathParams","GetJournalLineFromEmployerHeaders","GetJournalLineFromEmployerRequest","GetJournalLineFromEmployerResponse","GetJournalLinesFromEmployeePathParams","GetJournalLinesFromEmployeeHeaders","GetJournalLinesFromEmployeeRequest","GetJournalLinesFromEmployeeResponse","GetJournalLinesFromEmployerPathParams","GetJournalLinesFromEmployerHeaders","GetJournalLinesFromEmployerRequest","GetJournalLinesFromEmployerResponse","GetJournalLinesFromPayRunPathParams","GetJournalLinesFromPayRunHeaders","GetJournalLinesFromPayRunRequest","GetJournalLinesFromPayRunResponse","GetJournalLinesFromSubContractorPathParams","GetJournalLinesFromSubContractorHeaders","GetJournalLinesFromSubContractorRequest","GetJournalLinesFromSubContractorResponse","GetJournalReportOuputQueryParams","GetJournalReportOuputHeaders","GetJournalReportOuputRequest","GetJournalReportOuputResponse","GetLastPayDateReportOuputQueryParams","GetLastPayDateReportOuputHeaders","GetLastPayDateReportOuputRequest","GetLastPayDateReportOuputResponse","GetNetPayReportOutputQueryParams","GetNetPayReportOutputHeaders","GetNetPayReportOutputRequest","GetNetPayReportOutputResponse","GetNextPayPeriodDatesReportOutputQueryParams","GetNextPayPeriodDatesReportOutputHeaders","GetNextPayPeriodDatesReportOutputRequest","GetNextPayPeriodDatesReportOutputResponse","GetNominalCodeFromEmployerPathParams","GetNominalCodeFromEmployerHeaders","GetNominalCodeFromEmployerRequest","GetNominalCodeFromEmployerResponse","GetNominalCodesFromEmployerPathParams","GetNominalCodesFromEmployerHeaders","GetNominalCodesFromEmployerRequest","GetNominalCodesFromEmployerResponse","GetP11SummaryReportOutputQueryParams","GetP11SummaryReportOutputHeaders","GetP11SummaryReportOutputRequest","GetP11SummaryReportOutputResponse","GetP32NetReportOutputQueryParams","GetP32NetReportOutputHeaders","GetP32NetReportOutputRequest","GetP32NetReportOutputResponse","GetP32SummaryNetReportOutputQueryParams","GetP32SummaryNetReportOutputHeaders","GetP32SummaryNetReportOutputRequest","GetP32SummaryNetReportOutputResponse","GetP45ReportOutputQueryParams","GetP45ReportOutputHeaders","GetP45ReportOutputRequest","GetP45ReportOutputResponse","GetP60ReportOutputQueryParams","GetP60ReportOutputHeaders","GetP60ReportOutputRequest","GetP60ReportOutputResponse","GetPapdisReportOuputQueryParams","GetPapdisReportOuputHeaders","GetPapdisReportOuputRequest","GetPapdisReportOuputResponse","GetPassReportOuputQueryParams","GetPassReportOuputHeaders","GetPassReportOuputRequest","GetPassReportOuputResponse","GetPayCodeByEffectiveDatePathParams","GetPayCodeByEffectiveDateHeaders","GetPayCodeByEffectiveDateRequest","GetPayCodeByEffectiveDateResponse","GetPayCodeFromEmployerPathParams","GetPayCodeFromEmployerHeaders","GetPayCodeFromEmployerRequest","GetPayCodeFromEmployerResponse","GetPayCodeRevisionByNumberPathParams","GetPayCodeRevisionByNumberHeaders","GetPayCodeRevisionByNumberRequest","GetPayCodeRevisionByNumberResponse","GetPayCodeRevisionsPathParams","GetPayCodeRevisionsHeaders","GetPayCodeRevisionsRequest","GetPayCodeRevisionsResponse","GetPayCodesByEffectiveDatePathParams","GetPayCodesByEffectiveDateHeaders","GetPayCodesByEffectiveDateRequest","GetPayCodesByEffectiveDateResponse","GetPayCodesFromEmployerPathParams","GetPayCodesFromEmployerHeaders","GetPayCodesFromEmployerRequest","GetPayCodesFromEmployerResponse","GetPayCodesFromNominalCodePathParams","GetPayCodesFromNominalCodeHeaders","GetPayCodesFromNominalCodeRequest","GetPayCodesFromNominalCodeResponse","GetPayCodesWithTagPathParams","GetPayCodesWithTagHeaders","GetPayCodesWithTagRequest","GetPayCodesWithTagResponse","GetPayDashboardPayslipReportOuputQueryParams","GetPayDashboardPayslipReportOuputHeaders","GetPayDashboardPayslipReportOuputRequest","GetPayDashboardPayslipReportOuputResponse","GetPayInstructionFromEmployeePathParams","GetPayInstructionFromEmployeeHeaders","GetPayInstructionFromEmployeeRequest","GetPayInstructionFromEmployeeResponse","GetPayInstructionsFromEmployeePathParams","GetPayInstructionsFromEmployeeHeaders","GetPayInstructionsFromEmployeeRequest","GetPayInstructionsFromEmployeeResponse","GetPayInstructionsWithTagPathParams","GetPayInstructionsWithTagHeaders","GetPayInstructionsWithTagRequest","GetPayInstructionsWithTagResponse","GetPayLineFromEmployeePathParams","GetPayLineFromEmployeeHeaders","GetPayLineFromEmployeeRequest","GetPayLineFromEmployeeResponse","GetPayLinesFromEmployeePathParams","GetPayLinesFromEmployeeHeaders","GetPayLinesFromEmployeeRequest","GetPayLinesFromEmployeeResponse","GetPayLinesWithTagPathParams","GetPayLinesWithTagHeaders","GetPayLinesWithTagRequest","GetPayLinesWithTagResponse","GetPayRunFromPaySchedulePathParams","GetPayRunFromPayScheduleHeaders","GetPayRunFromPayScheduleRequest","GetPayRunFromPayScheduleResponse","GetPayRunJobInfoPathParams","GetPayRunJobInfoHeaders","GetPayRunJobInfoRequest","GetPayRunJobInfoResponse","GetPayRunJobProgressPathParams","GetPayRunJobProgressHeaders","GetPayRunJobProgressRequest","GetPayRunJobProgressResponse","GetPayRunJobsHeaders","GetPayRunJobsRequest","GetPayRunJobsResponse","GetPayRunJobStatusPathParams","GetPayRunJobStatusHeaders","GetPayRunJobStatusRequest","GetPayRunJobStatusResponse","GetPayRunsFromEmployeePathParams","GetPayRunsFromEmployeeHeaders","GetPayRunsFromEmployeeRequest","GetPayRunsFromEmployeeResponse","GetPayRunsFromPaySchedulePathParams","GetPayRunsFromPayScheduleHeaders","GetPayRunsFromPayScheduleRequest","GetPayRunsFromPayScheduleResponse","GetPayRunsWithTagPathParams","GetPayRunsWithTagHeaders","GetPayRunsWithTagRequest","GetPayRunsWithTagResponse","GetPayScheduleFromEmployerPathParams","GetPayScheduleFromEmployerHeaders","GetPayScheduleFromEmployerRequest","GetPayScheduleFromEmployerResponse","GetPaySchedulesFromEmployerPathParams","GetPaySchedulesFromEmployerHeaders","GetPaySchedulesFromEmployerRequest","GetPaySchedulesFromEmployerResponse","GetPaySchedulesWithTagPathParams","GetPaySchedulesWithTagHeaders","GetPaySchedulesWithTagRequest","GetPaySchedulesWithTagResponse","GetPayslip3ReportOutputQueryParams","GetPayslip3ReportOutputHeaders","GetPayslip3ReportOutputRequest","GetPayslip3ReportOutputResponse","GetPensionByEffectiveDatePathParams","GetPensionByEffectiveDateHeaders","GetPensionByEffectiveDateRequest","GetPensionByEffectiveDateResponse","GetPensionFromEmployerPathParams","GetPensionFromEmployerHeaders","GetPensionFromEmployerRequest","GetPensionFromEmployerResponse","GetPensionLiabilityReportOutputQueryParams","GetPensionLiabilityReportOutputHeaders","GetPensionLiabilityReportOutputRequest","GetPensionLiabilityReportOutputResponse","GetPensionRevisionByNumberPathParams","GetPensionRevisionByNumberHeaders","GetPensionRevisionByNumberRequest","GetPensionRevisionByNumberResponse","GetPensionRevisionsPathParams","GetPensionRevisionsHeaders","GetPensionRevisionsRequest","GetPensionRevisionsResponse","GetPensionsByEffectiveDatePathParams","GetPensionsByEffectiveDateHeaders","GetPensionsByEffectiveDateRequest","GetPensionsByEffectiveDateResponse","GetPensionsFromEmployerPathParams","GetPensionsFromEmployerHeaders","GetPensionsFromEmployerRequest","GetPensionsFromEmployerResponse","GetPermissionPathParams","GetPermissionHeaders","GetPermissionRequest","GetPermissionResponse","GetPermissionsHeaders","GetPermissionsRequest","GetPermissionsResponse","GetQueryResponseHeaders","GetQueryResponseRequest","GetQueryResponseResponse","GetReportDefinitionFromApplicationPathParams","GetReportDefinitionFromApplicationHeaders","GetReportDefinitionFromApplicationRequest","GetReportDefinitionFromApplicationResponse","GetReportDefinitionsFromApplicationHeaders","GetReportDefinitionsFromApplicationRequest","GetReportDefinitionsFromApplicationResponse","GetReportingInstructionFromEmployerPathParams","GetReportingInstructionFromEmployerHeaders","GetReportingInstructionFromEmployerRequest","GetReportingInstructionFromEmployerResponse","GetReportingInstructionsFromEmployerPathParams","GetReportingInstructionsFromEmployerHeaders","GetReportingInstructionsFromEmployerRequest","GetReportingInstructionsFromEmployerResponse","GetReportLineFromEmployerPathParams","GetReportLineFromEmployerHeaders","GetReportLineFromEmployerRequest","GetReportLineFromEmployerResponse","GetReportLinesFromEmployerPathParams","GetReportLinesFromEmployerHeaders","GetReportLinesFromEmployerRequest","GetReportLinesFromEmployerResponse","GetReportLinesFromPayRunPathParams","GetReportLinesFromPayRunHeaders","GetReportLinesFromPayRunRequest","GetReportLinesFromPayRunResponse","GetReportOutputPathParams","GetReportOutputHeaders","GetReportOutputRequest","GetReportOutputResponse","GetRtiJobInfoPathParams","GetRtiJobInfoHeaders","GetRtiJobInfoRequest","GetRtiJobInfoResponse","GetRtiJobProgressPathParams","GetRtiJobProgressHeaders","GetRtiJobProgressRequest","GetRtiJobProgressResponse","GetRtiJobsHeaders","GetRtiJobsRequest","GetRtiJobsResponse","GetRtiJobStatusPathParams","GetRtiJobStatusHeaders","GetRtiJobStatusRequest","GetRtiJobStatusResponse","GetRtiTransactionFromEmployerPathParams","GetRtiTransactionFromEmployerHeaders","GetRtiTransactionFromEmployerRequest","GetRtiTransactionFromEmployerResponse","GetRtiTransactionsFromEmployerPathParams","GetRtiTransactionsFromEmployerHeaders","GetRtiTransactionsFromEmployerRequest","GetRtiTransactionsFromEmployerResponse","GetRtiTransactionsWithTagPathParams","GetRtiTransactionsWithTagHeaders","GetRtiTransactionsWithTagRequest","GetRtiTransactionsWithTagResponse","GetSchemaPathParams","GetSchemaHeaders","GetSchemaRequest","GetSchemaResponse","GetSchemasHeaders","GetSchemasRequest","GetSchemasResponse","GetSubContractorByEffectiveDatePathParams","GetSubContractorByEffectiveDateHeaders","GetSubContractorByEffectiveDateRequest","GetSubContractorByEffectiveDateResponse","GetSubContractorFromEmployerPathParams","GetSubContractorFromEmployerHeaders","GetSubContractorFromEmployerRequest","GetSubContractorFromEmployerResponse","GetSubContractorRevisionByNumberPathParams","GetSubContractorRevisionByNumberHeaders","GetSubContractorRevisionByNumberRequest","GetSubContractorRevisionByNumberResponse","GetSubContractorRevisionsPathParams","GetSubContractorRevisionsHeaders","GetSubContractorRevisionsRequest","GetSubContractorRevisionsResponse","GetSubContractorsByEffectiveDatePathParams","GetSubContractorsByEffectiveDateHeaders","GetSubContractorsByEffectiveDateRequest","GetSubContractorsByEffectiveDateResponse","GetSubContractorsFromEmployerPathParams","GetSubContractorsFromEmployerHeaders","GetSubContractorsFromEmployerRequest","GetSubContractorsFromEmployerResponse","GetSubContractorsWithTagPathParams","GetSubContractorsWithTagHeaders","GetSubContractorsWithTagRequest","GetSubContractorsWithTagResponse","GetTagFromCisInstructionPathParams","GetTagFromCisInstructionHeaders","GetTagFromCisInstructionRequest","GetTagFromCisInstructionResponse","GetTagFromCisLinePathParams","GetTagFromCisLineHeaders","GetTagFromCisLineRequest","GetTagFromCisLineResponse","GetTagFromCisLineTypePathParams","GetTagFromCisLineTypeHeaders","GetTagFromCisLineTypeRequest","GetTagFromCisLineTypeResponse","GetTagFromEmployeePathParams","GetTagFromEmployeeHeaders","GetTagFromEmployeeRequest","GetTagFromEmployeeResponse","GetTagFromEmployeeRevisionPathParams","GetTagFromEmployeeRevisionHeaders","GetTagFromEmployeeRevisionRequest","GetTagFromEmployeeRevisionResponse","GetTagFromEmployerPathParams","GetTagFromEmployerHeaders","GetTagFromEmployerRequest","GetTagFromEmployerResponse","GetTagFromEmployerRevisionPathParams","GetTagFromEmployerRevisionHeaders","GetTagFromEmployerRevisionRequest","GetTagFromEmployerRevisionResponse","GetTagFromHolidaySchemePathParams","GetTagFromHolidaySchemeHeaders","GetTagFromHolidaySchemeRequest","GetTagFromHolidaySchemeResponse","GetTagFromHolidaySchemeRevisionPathParams","GetTagFromHolidaySchemeRevisionHeaders","GetTagFromHolidaySchemeRevisionRequest","GetTagFromHolidaySchemeRevisionResponse","GetTagFromJournalLinePathParams","GetTagFromJournalLineHeaders","GetTagFromJournalLineRequest","GetTagFromJournalLineResponse","GetTagFromPayCodePathParams","GetTagFromPayCodeHeaders","GetTagFromPayCodeRequest","GetTagFromPayCodeResponse","GetTagFromPayInstructionPathParams","GetTagFromPayInstructionHeaders","GetTagFromPayInstructionRequest","GetTagFromPayInstructionResponse","GetTagFromPayLinePathParams","GetTagFromPayLineHeaders","GetTagFromPayLineRequest","GetTagFromPayLineResponse","GetTagFromPayRunPathParams","GetTagFromPayRunHeaders","GetTagFromPayRunRequest","GetTagFromPayRunResponse","GetTagFromPaySchedulePathParams","GetTagFromPayScheduleHeaders","GetTagFromPayScheduleRequest","GetTagFromPayScheduleResponse","GetTagFromRtiTransactionPathParams","GetTagFromRtiTransactionHeaders","GetTagFromRtiTransactionRequest","GetTagFromRtiTransactionResponse","GetTagFromSubContractorPathParams","GetTagFromSubContractorHeaders","GetTagFromSubContractorRequest","GetTagFromSubContractorResponse","GetTagFromSubContractorRevisionPathParams","GetTagFromSubContractorRevisionHeaders","GetTagFromSubContractorRevisionRequest","GetTagFromSubContractorRevisionResponse","GetTagFromThirdPartyTransactionPathParams","GetTagFromThirdPartyTransactionHeaders","GetTagFromThirdPartyTransactionRequest","GetTagFromThirdPartyTransactionResponse","GetTagFromUserPathParams","GetTagFromUserHeaders","GetTagFromUserRequest","GetTagFromUserResponse","GetTagsFromCisInstructionPathParams","GetTagsFromCisInstructionHeaders","GetTagsFromCisInstructionRequest","GetTagsFromCisInstructionResponse","GetTagsFromCisLinePathParams","GetTagsFromCisLineHeaders","GetTagsFromCisLineRequest","GetTagsFromCisLineResponse","GetTagsFromCisLineTypePathParams","GetTagsFromCisLineTypeHeaders","GetTagsFromCisLineTypeRequest","GetTagsFromCisLineTypeResponse","GetTagsFromEmployeePathParams","GetTagsFromEmployeeHeaders","GetTagsFromEmployeeRequest","GetTagsFromEmployeeResponse","GetTagsFromEmployeeRevisionPathParams","GetTagsFromEmployeeRevisionHeaders","GetTagsFromEmployeeRevisionRequest","GetTagsFromEmployeeRevisionResponse","GetTagsFromEmployerPathParams","GetTagsFromEmployerHeaders","GetTagsFromEmployerRequest","GetTagsFromEmployerResponse","GetTagsFromEmployerRevisionPathParams","GetTagsFromEmployerRevisionHeaders","GetTagsFromEmployerRevisionRequest","GetTagsFromEmployerRevisionResponse","GetTagsFromHolidaySchemePathParams","GetTagsFromHolidaySchemeHeaders","GetTagsFromHolidaySchemeRequest","GetTagsFromHolidaySchemeResponse","GetTagsFromHolidaySchemeRevisionPathParams","GetTagsFromHolidaySchemeRevisionHeaders","GetTagsFromHolidaySchemeRevisionRequest","GetTagsFromHolidaySchemeRevisionResponse","GetTagsFromJournalLinePathParams","GetTagsFromJournalLineHeaders","GetTagsFromJournalLineRequest","GetTagsFromJournalLineResponse","GetTagsFromPayCodePathParams","GetTagsFromPayCodeHeaders","GetTagsFromPayCodeRequest","GetTagsFromPayCodeResponse","GetTagsFromPayInstructionPathParams","GetTagsFromPayInstructionHeaders","GetTagsFromPayInstructionRequest","GetTagsFromPayInstructionResponse","GetTagsFromPayLinePathParams","GetTagsFromPayLineHeaders","GetTagsFromPayLineRequest","GetTagsFromPayLineResponse","GetTagsFromPayRunPathParams","GetTagsFromPayRunHeaders","GetTagsFromPayRunRequest","GetTagsFromPayRunResponse","GetTagsFromPaySchedulePathParams","GetTagsFromPayScheduleHeaders","GetTagsFromPayScheduleRequest","GetTagsFromPayScheduleResponse","GetTagsFromRtiTransactionPathParams","GetTagsFromRtiTransactionHeaders","GetTagsFromRtiTransactionRequest","GetTagsFromRtiTransactionResponse","GetTagsFromSubContractorPathParams","GetTagsFromSubContractorHeaders","GetTagsFromSubContractorRequest","GetTagsFromSubContractorResponse","GetTagsFromSubContractorRevisionPathParams","GetTagsFromSubContractorRevisionHeaders","GetTagsFromSubContractorRevisionRequest","GetTagsFromSubContractorRevisionResponse","GetTagsFromThirdPartyTransactionPathParams","GetTagsFromThirdPartyTransactionHeaders","GetTagsFromThirdPartyTransactionRequest","GetTagsFromThirdPartyTransactionResponse","GetTagsFromUserPathParams","GetTagsFromUserHeaders","GetTagsFromUserRequest","GetTagsFromUserResponse","GetTemplateModelPathParams","GetTemplateModelHeaders","GetTemplateModelRequest","GetTemplateModelResponse","GetTemplatesHeaders","GetTemplatesRequest","GetTemplatesResponse","GetThirdPartyJobInfoPathParams","GetThirdPartyJobInfoHeaders","GetThirdPartyJobInfoRequest","GetThirdPartyJobInfoResponse","GetThirdPartyJobProgressPathParams","GetThirdPartyJobProgressHeaders","GetThirdPartyJobProgressRequest","GetThirdPartyJobProgressResponse","GetThirdPartyJobsHeaders","GetThirdPartyJobsRequest","GetThirdPartyJobsResponse","GetThirdPartyJobStatusPathParams","GetThirdPartyJobStatusHeaders","GetThirdPartyJobStatusRequest","GetThirdPartyJobStatusResponse","GetThirdPartyTransactionPathParams","GetThirdPartyTransactionHeaders","GetThirdPartyTransactionRequest","GetThirdPartyTransactionResponse","GetThirdPartyTransactionsPathParams","GetThirdPartyTransactionsHeaders","GetThirdPartyTransactionsRequest","GetThirdPartyTransactionsResponse","GetTransformDefinitionFromApplicationPathParams","GetTransformDefinitionFromApplicationHeaders","GetTransformDefinitionFromApplicationRequest","GetTransformDefinitionFromApplicationResponse","GetTransformDefinitionsFromApplicationHeaders","GetTransformDefinitionsFromApplicationRequest","GetTransformDefinitionsFromApplicationResponse","GetUserPathParams","GetUserHeaders","GetUserRequest","GetUserResponse","GetUsersHeaders","GetUsersRequest","GetUsersResponse","PatchCisInstructionPathParams","PatchCisInstructionHeaders","PatchCisInstructionRequest","PatchCisInstructionResponse","PatchDpsMessagePathParams","PatchDpsMessageHeaders","PatchDpsMessageRequest","PatchDpsMessageResponse","PatchEmployeePathParams","PatchEmployeeHeaders","PatchEmployeeRequest","PatchEmployeeResponse","PatchEmployerPathParams","PatchEmployerHeaders","PatchEmployerRequest","PatchEmployerResponse","PatchHolidaySchemePathParams","PatchHolidaySchemeHeaders","PatchHolidaySchemeRequest","PatchHolidaySchemeResponse","PatchPayCodePathParams","PatchPayCodeHeaders","PatchPayCodeRequest","PatchPayCodeResponse","PatchPayInstructionPathParams","PatchPayInstructionHeaders","PatchPayInstructionRequest","PatchPayInstructionResponse","PatchPensionPathParams","PatchPensionHeaders","PatchPensionRequest","PatchPensionResponse","PatchPermissionPathParams","PatchPermissionHeaders","PatchPermissionRequest","PatchPermissionResponse","PatchSubContractorPathParams","PatchSubContractorHeaders","PatchSubContractorRequest","PatchSubContractorResponse","PatchUserPathParams","PatchUserHeaders","PatchUserRequest","PatchUserResponse","PostCisInstructionIntoSubContractorPathParams","PostCisInstructionIntoSubContractorHeaders","PostCisInstructionIntoSubContractorRequest","PostCisInstructionIntoSubContractorResponse","PostCisLineTypeIntoEmployerPathParams","PostCisLineTypeIntoEmployerHeaders","PostCisLineTypeIntoEmployerRequest","PostCisLineTypeIntoEmployerResponse","PostDpsMessagePathParams","PostDpsMessageHeaders","PostDpsMessageRequest","PostDpsMessageResponse","PostEmployeeIntoEmployerPathParams","PostEmployeeIntoEmployerHeaders","PostEmployeeIntoEmployerRequest","PostEmployeeIntoEmployerResponse","PostEmployeeSecretPathParams","PostEmployeeSecretHeaders","PostEmployeeSecretRequest","PostEmployeeSecretResponse","PostEmployerHeaders","PostEmployerRequest","PostEmployerResponse","PostEmployerSecretPathParams","PostEmployerSecretHeaders","PostEmployerSecretRequest","PostEmployerSecretResponse","PostHolidaySchemeIntoEmployerPathParams","PostHolidaySchemeIntoEmployerHeaders","PostHolidaySchemeIntoEmployerRequest","PostHolidaySchemeIntoEmployerResponse","PostJournalInstructionPathParams","PostJournalInstructionHeaders","PostJournalInstructionRequest","PostJournalInstructionResponse","PostJournalInstructionTemplateHeaders","PostJournalInstructionTemplateRequest","PostJournalInstructionTemplateResponse","PostNewAeAssessmentPathParams","PostNewAeAssessmentHeaders","PostNewAeAssessmentRequest","PostNewAeAssessmentResponse","PostNewBatchJobHeaders","PostNewBatchJobRequest","PostNewBatchJobResponse","PostNewCisJobHeaders","PostNewCisJobRequest","PostNewCisJobResponse","PostNewDpsJobHeaders","PostNewDpsJobRequest","PostNewDpsJobResponse","PostNewPayRunJobHeaders","PostNewPayRunJobRequest","PostNewPayRunJobResponse","PostNewRtiJobHeaders","PostNewRtiJobRequest","PostNewRtiJobResponse","PostNewThirdPartyJobHeaders","PostNewThirdPartyJobRequest","PostNewThirdPartyJobResponse","PostNominalCodePathParams","PostNominalCodeHeaders","PostNominalCodeRequest","PostNominalCodeResponse","PostPayCodePathParams","PostPayCodeHeaders","PostPayCodeRequest","PostPayCodeResponse","PostPayInstructionPathParams","PostPayInstructionHeaders","PostPayInstructionRequest","PostPayInstructionResponse","PostPaySchedulePathParams","PostPayScheduleHeaders","PostPayScheduleRequest","PostPayScheduleResponse","PostPensionIntoEmployerPathParams","PostPensionIntoEmployerHeaders","PostPensionIntoEmployerRequest","PostPensionIntoEmployerResponse","PostPermissionHeaders","PostPermissionRequest","PostPermissionResponse","PostReportDefinitionHeaders","PostReportDefinitionRequest","PostReportDefinitionResponse","PostReportingInstructionPathParams","PostReportingInstructionHeaders","PostReportingInstructionRequest","PostReportingInstructionResponse","PostSubContractorIntoEmployerPathParams","PostSubContractorIntoEmployerHeaders","PostSubContractorIntoEmployerRequest","PostSubContractorIntoEmployerResponse","PostTransformDefinitionHeaders","PostTransformDefinitionRequest","PostTransformDefinitionResponse","PostUserHeaders","PostUserRequest","PostUserResponse","PutCisInstructionIntoSubContractorPathParams","PutCisInstructionIntoSubContractorHeaders","PutCisInstructionIntoSubContractorRequest","PutCisInstructionIntoSubContractorResponse","PutCisInstructionTagPathParams","PutCisInstructionTagHeaders","PutCisInstructionTagRequest","PutCisInstructionTagResponse","PutCisLineTagPathParams","PutCisLineTagHeaders","PutCisLineTagRequest","PutCisLineTagResponse","PutCisLineTypeIntoEmployerPathParams","PutCisLineTypeIntoEmployerHeaders","PutCisLineTypeIntoEmployerRequest","PutCisLineTypeIntoEmployerResponse","PutCisLineTypeTagPathParams","PutCisLineTypeTagHeaders","PutCisLineTypeTagRequest","PutCisLineTypeTagResponse","PutDpsMessagePathParams","PutDpsMessageHeaders","PutDpsMessageRequest","PutDpsMessageResponse","PutEmployeeIntoEmployerPathParams","PutEmployeeIntoEmployerHeaders","PutEmployeeIntoEmployerRequest","PutEmployeeIntoEmployerResponse","PutEmployeeSecretPathParams","PutEmployeeSecretHeaders","PutEmployeeSecretRequest","PutEmployeeSecretResponse","PutEmployeeTagPathParams","PutEmployeeTagHeaders","PutEmployeeTagRequest","PutEmployeeTagResponse","PutEmployerPathParams","PutEmployerHeaders","PutEmployerRequest","PutEmployerResponse","PutEmployerSecretPathParams","PutEmployerSecretHeaders","PutEmployerSecretRequest","PutEmployerSecretResponse","PutEmployerTagPathParams","PutEmployerTagHeaders","PutEmployerTagRequest","PutEmployerTagResponse","PutHolidaySchemeIntoEmployerPathParams","PutHolidaySchemeIntoEmployerHeaders","PutHolidaySchemeIntoEmployerRequest","PutHolidaySchemeIntoEmployerResponse","PutHolidaySchemeTagPathParams","PutHolidaySchemeTagHeaders","PutHolidaySchemeTagRequest","PutHolidaySchemeTagResponse","PutJournalInstructionPathParams","PutJournalInstructionHeaders","PutJournalInstructionRequest","PutJournalInstructionResponse","PutJournalInstructionTemplatePathParams","PutJournalInstructionTemplateHeaders","PutJournalInstructionTemplateRequest","PutJournalInstructionTemplateResponse","PutJournalLineTagPathParams","PutJournalLineTagHeaders","PutJournalLineTagRequest","PutJournalLineTagResponse","PutNewAeAssessmentPathParams","PutNewAeAssessmentHeaders","PutNewAeAssessmentRequest","PutNewAeAssessmentResponse","PutNominalCodePathParams","PutNominalCodeHeaders","PutNominalCodeRequest","PutNominalCodeResponse","PutPayCodePathParams","PutPayCodeHeaders","PutPayCodeRequest","PutPayCodeResponse","PutPayCodeTagPathParams","PutPayCodeTagHeaders","PutPayCodeTagRequest","PutPayCodeTagResponse","PutPayInstructionPathParams","PutPayInstructionHeaders","PutPayInstructionRequest","PutPayInstructionResponse","PutPayInstructionTagPathParams","PutPayInstructionTagHeaders","PutPayInstructionTagRequest","PutPayInstructionTagResponse","PutPayLineTagPathParams","PutPayLineTagHeaders","PutPayLineTagRequest","PutPayLineTagResponse","PutPayRunTagPathParams","PutPayRunTagHeaders","PutPayRunTagRequest","PutPayRunTagResponse","PutPaySchedulePathParams","PutPayScheduleHeaders","PutPayScheduleRequest","PutPayScheduleResponse","PutPayScheduleTagPathParams","PutPayScheduleTagHeaders","PutPayScheduleTagRequest","PutPayScheduleTagResponse","PutPensionIntoEmployerPathParams","PutPensionIntoEmployerHeaders","PutPensionIntoEmployerRequest","PutPensionIntoEmployerResponse","PutPermissionPathParams","PutPermissionHeaders","PutPermissionRequest","PutPermissionResponse","PutReportDefinitionPathParams","PutReportDefinitionHeaders","PutReportDefinitionRequest","PutReportDefinitionResponse","PutReportingInstructionPathParams","PutReportingInstructionHeaders","PutReportingInstructionRequest","PutReportingInstructionResponse","PutRtiTransactionTagPathParams","PutRtiTransactionTagHeaders","PutRtiTransactionTagRequest","PutRtiTransactionTagResponse","PutSubContractorIntoEmployerPathParams","PutSubContractorIntoEmployerHeaders","PutSubContractorIntoEmployerRequest","PutSubContractorIntoEmployerResponse","PutSubContractorTagPathParams","PutSubContractorTagHeaders","PutSubContractorTagRequest","PutSubContractorTagResponse","PutThirdPartyTransactionTagPathParams","PutThirdPartyTransactionTagHeaders","PutThirdPartyTransactionTagRequest","PutThirdPartyTransactionTagResponse","PutTransformDefinitionPathParams","PutTransformDefinitionHeaders","PutTransformDefinitionRequest","PutTransformDefinitionResponse","PutUserPathParams","PutUserHeaders","PutUserRequest","PutUserResponse","PutUserTagPathParams","PutUserTagHeaders","PutUserTagRequest","PutUserTagResponse"]