/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The description of the location of an object in Amazon S3.
 */
export class S3LocationDescription extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "bucketArn" })
  bucketArn?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "fileKey" })
  fileKey?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "objectVersion" })
  objectVersion?: string;
}
