import dataclasses
from enum import Enum

class SmartPostHubEnum(str, Enum):
    NONE = "none"
    ALLENTOWN_PA = "allentown_pa"
    ATLANTA_GA = "atlanta_ga"
    BALTIMORE_MD = "baltimore_md"
    CHARLOTTE_NC = "charlotte_nc"
    CHINO_CA = "chino_ca"
    DALLAS_TX = "dallas_tx"
    DENVER_CO = "denver_co"
    DETROIT_MI = "detroit_mi"
    EDISON_NJ = "edison_nj"
    GROVE_CITY_OH = "grove_city_oh"
    GROVEPORT_OH = "groveport_oh"
    HOUSTON_TX = "houston_tx"
    INDIANAPOLIS_IN = "indianapolis_in"
    KANSAS_CITY_KS = "kansas_city_ks"
    LOS_ANGELES_CA = "los_angeles_ca"
    MARTINSBURG_WV = "martinsburg_wv"
    MEMPHIS_TN = "memphis_tn"
    MINNEAPOLIS_MN = "minneapolis_mn"
    NEW_BERLIN_WI = "new_berlin_wi"
    NORTHBOROUGH_MA = "northborough_ma"
    ORLANDO_FL = "orlando_fl"
    PHONEIX_AZ = "phoneix_az"
    PITTSBURGH_PA = "pittsburgh_pa"
    RENO_NV = "reno_nv"
    SACRAMENTO_CA = "sacramento_ca"
    SALT_LAKE_CITY_UT = "salt_lake_city_ut"
    SEATTLE_WA = "seattle_wa"
    ST_LOUIS_MO = "st_louis_mo"
    WINDSOR_CT = "windsor_ct"
    NEWARK_NY = "newark_ny"
    SOUTH_BRUNSWICK_NJ = "south_brunswick_nj"
    SCRANTON_PA = "scranton_pa"
    WHEELING_IL = "wheeling_il"

