"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RepositoryHeadSourceCodeType:
    r"""A <a href=\\"https://docs.aws.amazon.com/codeguru/latest/reviewer-api/API_SourceCodeType\\">SourceCodeType</a> that specifies the tip of a branch in an associated repository."""
    
    branch_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('BranchName') }})  
    