package openapisdk.models.shared;


public enum MappingJobIdTypeEnum {
    ID_ISIN("ID_ISIN"),
    ID_BB_UNIQUE("ID_BB_UNIQUE"),
    ID_SEDOL("ID_SEDOL"),
    ID_COMMON("ID_COMMON"),
    ID_WERTPAPIER("ID_WERTPAPIER"),
    ID_CUSIP("ID_CUSIP"),
    ID_BB("ID_BB"),
    ID_ITALY("ID_ITALY"),
    ID_EXCH_SYMBOL("ID_EXCH_SYMBOL"),
    ID_FULL_EXCHANGE_SYMBOL("ID_FULL_EXCHANGE_SYMBOL"),
    COMPOSITE_ID_BB_GLOBAL("COMPOSITE_ID_BB_GLOBAL"),
    ID_BB_GLOBAL_SHARE_CLASS_LEVEL("ID_BB_GLOBAL_SHARE_CLASS_LEVEL"),
    ID_BB_SEC_NUM_DES("ID_BB_SEC_NUM_DES"),
    ID_BB_GLOBAL("ID_BB_GLOBAL"),
    TICKER("TICKER"),
    ID_CUSIP8_CHR("ID_CUSIP_8_CHR"),
    OCC_SYMBOL("OCC_SYMBOL"),
    UNIQUE_ID_FUT_OPT("UNIQUE_ID_FUT_OPT"),
    OPRA_SYMBOL("OPRA_SYMBOL"),
    TRADING_SYSTEM_IDENTIFIER("TRADING_SYSTEM_IDENTIFIER"),
    ID_CINS("ID_CINS"),
    ID_SHORT_CODE("ID_SHORT_CODE"),
    BASE_TICKER("BASE_TICKER"),
    VENDOR_INDEX_CODE("VENDOR_INDEX_CODE");

    public final String value;

    private MappingJobIdTypeEnum(String value) {
        this.value = value;
    }
}
