/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ClinicalNoteFieldValuesReadResponse {
    
    public String contentType;

    public ClinicalNoteFieldValuesReadResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public org.openapis.openapi.models.shared.SoapNoteLineItemFieldValue soapNoteLineItemFieldValue;

    public ClinicalNoteFieldValuesReadResponse withSoapNoteLineItemFieldValue(org.openapis.openapi.models.shared.SoapNoteLineItemFieldValue soapNoteLineItemFieldValue) {
        this.soapNoteLineItemFieldValue = soapNoteLineItemFieldValue;
        return this;
    }
    
    
    public Integer statusCode;

    public ClinicalNoteFieldValuesReadResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ClinicalNoteFieldValuesReadResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ClinicalNoteFieldValuesReadResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
