"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import journeysmsmessage as shared_journeysmsmessage
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SMSMessageActivity:
    r"""Specifies the settings for an SMS activity in a journey. This type of activity sends a text message to participants."""
    
    message_config: Optional[shared_journeysmsmessage.JourneySMSMessage] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('MessageConfig'), 'exclude': lambda f: f is None }})  
    next_activity: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('NextActivity'), 'exclude': lambda f: f is None }})  
    template_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('TemplateName'), 'exclude': lambda f: f is None }})  
    template_version: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('TemplateVersion'), 'exclude': lambda f: f is None }})  
    