/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateHyperParameterTuningJobRequest {
    @JsonProperty("HyperParameterTuningJobConfig")
    public HyperParameterTuningJobConfig hyperParameterTuningJobConfig;

    public CreateHyperParameterTuningJobRequest withHyperParameterTuningJobConfig(HyperParameterTuningJobConfig hyperParameterTuningJobConfig) {
        this.hyperParameterTuningJobConfig = hyperParameterTuningJobConfig;
        return this;
    }
    
    @JsonProperty("HyperParameterTuningJobName")
    public String hyperParameterTuningJobName;

    public CreateHyperParameterTuningJobRequest withHyperParameterTuningJobName(String hyperParameterTuningJobName) {
        this.hyperParameterTuningJobName = hyperParameterTuningJobName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("Tags")
    public Tag[] tags;

    public CreateHyperParameterTuningJobRequest withTags(Tag[] tags) {
        this.tags = tags;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("TrainingJobDefinition")
    public HyperParameterTrainingJobDefinition trainingJobDefinition;

    public CreateHyperParameterTuningJobRequest withTrainingJobDefinition(HyperParameterTrainingJobDefinition trainingJobDefinition) {
        this.trainingJobDefinition = trainingJobDefinition;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("TrainingJobDefinitions")
    public HyperParameterTrainingJobDefinition[] trainingJobDefinitions;

    public CreateHyperParameterTuningJobRequest withTrainingJobDefinitions(HyperParameterTrainingJobDefinition[] trainingJobDefinitions) {
        this.trainingJobDefinitions = trainingJobDefinitions;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("WarmStartConfig")
    public HyperParameterTuningJobWarmStartConfig warmStartConfig;

    public CreateHyperParameterTuningJobRequest withWarmStartConfig(HyperParameterTuningJobWarmStartConfig warmStartConfig) {
        this.warmStartConfig = warmStartConfig;
        return this;
    }
    
    public CreateHyperParameterTuningJobRequest(@JsonProperty("HyperParameterTuningJobConfig") HyperParameterTuningJobConfig hyperParameterTuningJobConfig, @JsonProperty("HyperParameterTuningJobName") String hyperParameterTuningJobName) {
        this.hyperParameterTuningJobConfig = hyperParameterTuningJobConfig;
        this.hyperParameterTuningJobName = hyperParameterTuningJobName;
  }
}
