<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


enum PolicyTypeEnum: string
{
    case TARGET_TRACKING_SCALING = 'TargetTrackingScaling';
}
