package openapisdk.models.shared;


public enum ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum {
    CONTENT_OUTSTREAM_POSITION_UNSPECIFIED("CONTENT_OUTSTREAM_POSITION_UNSPECIFIED"),
    CONTENT_OUTSTREAM_POSITION_UNKNOWN("CONTENT_OUTSTREAM_POSITION_UNKNOWN"),
    CONTENT_OUTSTREAM_POSITION_IN_ARTICLE("CONTENT_OUTSTREAM_POSITION_IN_ARTICLE"),
    CONTENT_OUTSTREAM_POSITION_IN_BANNER("CONTENT_OUTSTREAM_POSITION_IN_BANNER"),
    CONTENT_OUTSTREAM_POSITION_IN_FEED("CONTENT_OUTSTREAM_POSITION_IN_FEED"),
    CONTENT_OUTSTREAM_POSITION_INTERSTITIAL("CONTENT_OUTSTREAM_POSITION_INTERSTITIAL");

    public final String value;

    private ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum(String value) {
        this.value = value;
    }
}
