package openapisdk.models.shared;


public enum CreativeExpandingDirectionEnum {
    EXPANDING_DIRECTION_UNSPECIFIED("EXPANDING_DIRECTION_UNSPECIFIED"),
    EXPANDING_DIRECTION_NONE("EXPANDING_DIRECTION_NONE"),
    EXPANDING_DIRECTION_UP("EXPANDING_DIRECTION_UP"),
    EXPANDING_DIRECTION_DOWN("EXPANDING_DIRECTION_DOWN"),
    EXPANDING_DIRECTION_LEFT("EXPANDING_DIRECTION_LEFT"),
    EXPANDING_DIRECTION_RIGHT("EXPANDING_DIRECTION_RIGHT"),
    EXPANDING_DIRECTION_UP_AND_LEFT("EXPANDING_DIRECTION_UP_AND_LEFT"),
    EXPANDING_DIRECTION_UP_AND_RIGHT("EXPANDING_DIRECTION_UP_AND_RIGHT"),
    EXPANDING_DIRECTION_DOWN_AND_LEFT("EXPANDING_DIRECTION_DOWN_AND_LEFT"),
    EXPANDING_DIRECTION_DOWN_AND_RIGHT("EXPANDING_DIRECTION_DOWN_AND_RIGHT"),
    EXPANDING_DIRECTION_UP_OR_DOWN("EXPANDING_DIRECTION_UP_OR_DOWN"),
    EXPANDING_DIRECTION_LEFT_OR_RIGHT("EXPANDING_DIRECTION_LEFT_OR_RIGHT"),
    EXPANDING_DIRECTION_ANY_DIAGONAL("EXPANDING_DIRECTION_ANY_DIAGONAL");

    public final String value;

    private CreativeExpandingDirectionEnum(String value) {
        this.value = value;
    }
}
