package openapisdk.models.shared;


public enum DoubleVerifyDisplayViewabilityIabEnum {
    IAB_VIEWED_RATE_UNSPECIFIED("IAB_VIEWED_RATE_UNSPECIFIED"),
    IAB_VIEWED_RATE80_PERCENT_HIGHER("IAB_VIEWED_RATE_80_PERCENT_HIGHER"),
    IAB_VIEWED_RATE75_PERCENT_HIGHER("IAB_VIEWED_RATE_75_PERCENT_HIGHER"),
    IAB_VIEWED_RATE70_PERCENT_HIGHER("IAB_VIEWED_RATE_70_PERCENT_HIGHER"),
    IAB_VIEWED_RATE65_PERCENT_HIGHER("IAB_VIEWED_RATE_65_PERCENT_HIGHER"),
    IAB_VIEWED_RATE60_PERCENT_HIGHER("IAB_VIEWED_RATE_60_PERCENT_HIGHER"),
    IAB_VIEWED_RATE55_PERCENT_HIGHER("IAB_VIEWED_RATE_55_PERCENT_HIGHER"),
    IAB_VIEWED_RATE50_PERCENT_HIGHER("IAB_VIEWED_RATE_50_PERCENT_HIGHER"),
    IAB_VIEWED_RATE40_PERCENT_HIGHER("IAB_VIEWED_RATE_40_PERCENT_HIGHER"),
    IAB_VIEWED_RATE30_PERCENT_HIGHER("IAB_VIEWED_RATE_30_PERCENT_HIGHER");

    public final String value;

    private DoubleVerifyDisplayViewabilityIabEnum(String value) {
        this.value = value;
    }
}
