package openapisdk.models.shared;


public enum DoubleVerifyVideoViewabilityVideoViewableRateEnum {
    VIDEO_VIEWABLE_RATE_UNSPECIFIED("VIDEO_VIEWABLE_RATE_UNSPECIFIED"),
    VIEWED_PERFORMANCE40_PERCENT_HIGHER("VIEWED_PERFORMANCE_40_PERCENT_HIGHER"),
    VIEWED_PERFORMANCE35_PERCENT_HIGHER("VIEWED_PERFORMANCE_35_PERCENT_HIGHER"),
    VIEWED_PERFORMANCE30_PERCENT_HIGHER("VIEWED_PERFORMANCE_30_PERCENT_HIGHER"),
    VIEWED_PERFORMANCE25_PERCENT_HIGHER("VIEWED_PERFORMANCE_25_PERCENT_HIGHER"),
    VIEWED_PERFORMANCE20_PERCENT_HIGHER("VIEWED_PERFORMANCE_20_PERCENT_HIGHER"),
    VIEWED_PERFORMANCE10_PERCENT_HIGHER("VIEWED_PERFORMANCE_10_PERCENT_HIGHER");

    public final String value;

    private DoubleVerifyVideoViewabilityVideoViewableRateEnum(String value) {
        this.value = value;
    }
}
