package openapisdk.models.shared;


public enum FirstAndThirdPartyAudienceTargetingSettingRecencyEnum {
    RECENCY_NO_LIMIT("RECENCY_NO_LIMIT"),
    RECENCY1_MINUTE("RECENCY_1_MINUTE"),
    RECENCY5_MINUTES("RECENCY_5_MINUTES"),
    RECENCY10_MINUTES("RECENCY_10_MINUTES"),
    RECENCY15_MINUTES("RECENCY_15_MINUTES"),
    RECENCY30_MINUTES("RECENCY_30_MINUTES"),
    RECENCY1_HOUR("RECENCY_1_HOUR"),
    RECENCY2_HOURS("RECENCY_2_HOURS"),
    RECENCY3_HOURS("RECENCY_3_HOURS"),
    RECENCY6_HOURS("RECENCY_6_HOURS"),
    RECENCY12_HOURS("RECENCY_12_HOURS"),
    RECENCY1_DAY("RECENCY_1_DAY"),
    RECENCY2_DAYS("RECENCY_2_DAYS"),
    RECENCY3_DAYS("RECENCY_3_DAYS"),
    RECENCY5_DAYS("RECENCY_5_DAYS"),
    RECENCY7_DAYS("RECENCY_7_DAYS"),
    RECENCY10_DAYS("RECENCY_10_DAYS"),
    RECENCY14_DAYS("RECENCY_14_DAYS"),
    RECENCY15_DAYS("RECENCY_15_DAYS"),
    RECENCY21_DAYS("RECENCY_21_DAYS"),
    RECENCY28_DAYS("RECENCY_28_DAYS"),
    RECENCY30_DAYS("RECENCY_30_DAYS"),
    RECENCY40_DAYS("RECENCY_40_DAYS"),
    RECENCY45_DAYS("RECENCY_45_DAYS"),
    RECENCY60_DAYS("RECENCY_60_DAYS"),
    RECENCY90_DAYS("RECENCY_90_DAYS"),
    RECENCY120_DAYS("RECENCY_120_DAYS"),
    RECENCY180_DAYS("RECENCY_180_DAYS"),
    RECENCY270_DAYS("RECENCY_270_DAYS"),
    RECENCY365_DAYS("RECENCY_365_DAYS");

    public final String value;

    private FirstAndThirdPartyAudienceTargetingSettingRecencyEnum(String value) {
        this.value = value;
    }
}
