package openapisdk.models.shared;


public enum GenerateDefaultLineItemRequestLineItemTypeEnum {
    LINE_ITEM_TYPE_UNSPECIFIED("LINE_ITEM_TYPE_UNSPECIFIED"),
    LINE_ITEM_TYPE_DISPLAY_DEFAULT("LINE_ITEM_TYPE_DISPLAY_DEFAULT"),
    LINE_ITEM_TYPE_DISPLAY_MOBILE_APP_INSTALL("LINE_ITEM_TYPE_DISPLAY_MOBILE_APP_INSTALL"),
    LINE_ITEM_TYPE_VIDEO_DEFAULT("LINE_ITEM_TYPE_VIDEO_DEFAULT"),
    LINE_ITEM_TYPE_VIDEO_MOBILE_APP_INSTALL("LINE_ITEM_TYPE_VIDEO_MOBILE_APP_INSTALL"),
    LINE_ITEM_TYPE_DISPLAY_MOBILE_APP_INVENTORY("LINE_ITEM_TYPE_DISPLAY_MOBILE_APP_INVENTORY"),
    LINE_ITEM_TYPE_VIDEO_MOBILE_APP_INVENTORY("LINE_ITEM_TYPE_VIDEO_MOBILE_APP_INVENTORY"),
    LINE_ITEM_TYPE_AUDIO_DEFAULT("LINE_ITEM_TYPE_AUDIO_DEFAULT"),
    LINE_ITEM_TYPE_VIDEO_OVER_THE_TOP("LINE_ITEM_TYPE_VIDEO_OVER_THE_TOP"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_ACTION("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_ACTION"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_NON_SKIPPABLE("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_NON_SKIPPABLE"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_VIDEO_SEQUENCE("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_VIDEO_SEQUENCE"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_AUDIO("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_AUDIO"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_REACH("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_REACH"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_SIMPLE("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_SIMPLE"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_NON_SKIPPABLE_OVER_THE_TOP("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_NON_SKIPPABLE_OVER_THE_TOP"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_REACH_OVER_THE_TOP("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_REACH_OVER_THE_TOP"),
    LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_SIMPLE_OVER_THE_TOP("LINE_ITEM_TYPE_YOUTUBE_AND_PARTNERS_SIMPLE_OVER_THE_TOP");

    public final String value;

    private GenerateDefaultLineItemRequestLineItemTypeEnum(String value) {
        this.value = value;
    }
}
