package openapisdk.models.shared;


public enum GoogleAudienceGoogleAudienceTypeEnum {
    GOOGLE_AUDIENCE_TYPE_UNSPECIFIED("GOOGLE_AUDIENCE_TYPE_UNSPECIFIED"),
    GOOGLE_AUDIENCE_TYPE_AFFINITY("GOOGLE_AUDIENCE_TYPE_AFFINITY"),
    GOOGLE_AUDIENCE_TYPE_IN_MARKET("GOOGLE_AUDIENCE_TYPE_IN_MARKET"),
    GOOGLE_AUDIENCE_TYPE_INSTALLED_APPS("GOOGLE_AUDIENCE_TYPE_INSTALLED_APPS"),
    GOOGLE_AUDIENCE_TYPE_NEW_MOBILE_DEVICES("GOOGLE_AUDIENCE_TYPE_NEW_MOBILE_DEVICES"),
    GOOGLE_AUDIENCE_TYPE_LIFE_EVENT("GOOGLE_AUDIENCE_TYPE_LIFE_EVENT"),
    GOOGLE_AUDIENCE_TYPE_EXTENDED_DEMOGRAPHIC("GOOGLE_AUDIENCE_TYPE_EXTENDED_DEMOGRAPHIC");

    public final String value;

    private GoogleAudienceGoogleAudienceTypeEnum(String value) {
        this.value = value;
    }
}
