package openapisdk.models.shared;


public enum HouseholdIncomeTargetingOptionDetailsHouseholdIncomeEnum {
    HOUSEHOLD_INCOME_UNSPECIFIED("HOUSEHOLD_INCOME_UNSPECIFIED"),
    HOUSEHOLD_INCOME_UNKNOWN("HOUSEHOLD_INCOME_UNKNOWN"),
    HOUSEHOLD_INCOME_LOWER50_PERCENT("HOUSEHOLD_INCOME_LOWER_50_PERCENT"),
    HOUSEHOLD_INCOME_TOP41_TO50_PERCENT("HOUSEHOLD_INCOME_TOP_41_TO_50_PERCENT"),
    HOUSEHOLD_INCOME_TOP31_TO40_PERCENT("HOUSEHOLD_INCOME_TOP_31_TO_40_PERCENT"),
    HOUSEHOLD_INCOME_TOP21_TO30_PERCENT("HOUSEHOLD_INCOME_TOP_21_TO_30_PERCENT"),
    HOUSEHOLD_INCOME_TOP11_TO20_PERCENT("HOUSEHOLD_INCOME_TOP_11_TO_20_PERCENT"),
    HOUSEHOLD_INCOME_TOP10_PERCENT("HOUSEHOLD_INCOME_TOP_10_PERCENT");

    public final String value;

    private HouseholdIncomeTargetingOptionDetailsHouseholdIncomeEnum(String value) {
        this.value = value;
    }
}
