package openapisdk.models.shared;


public enum LineItemBudgetBudgetAllocationTypeEnum {
    LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNSPECIFIED("LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNSPECIFIED"),
    LINE_ITEM_BUDGET_ALLOCATION_TYPE_AUTOMATIC("LINE_ITEM_BUDGET_ALLOCATION_TYPE_AUTOMATIC"),
    LINE_ITEM_BUDGET_ALLOCATION_TYPE_FIXED("LINE_ITEM_BUDGET_ALLOCATION_TYPE_FIXED"),
    LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNLIMITED("LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNLIMITED");

    public final String value;

    private LineItemBudgetBudgetAllocationTypeEnum(String value) {
        this.value = value;
    }
}
