package openapisdk.models.shared;


public enum PerformanceGoalBidStrategyPerformanceGoalTypeEnum {
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_UNSPECIFIED("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_UNSPECIFIED"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CPA("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CPA"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CPC("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CPC"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_VIEWABLE_CPM("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_VIEWABLE_CPM"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CUSTOM_ALGO("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CUSTOM_ALGO"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CIVA("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_CIVA"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_IVO_TEN("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_IVO_TEN"),
    BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_AV_VIEWED("BIDDING_STRATEGY_PERFORMANCE_GOAL_TYPE_AV_VIEWED");

    public final String value;

    private PerformanceGoalBidStrategyPerformanceGoalTypeEnum(String value) {
        this.value = value;
    }
}
