<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * GitTag - Metadata for a Git tag
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class GitTag
{
    /**
     * Message describing the purpose of the tag
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	#[\JMS\Serializer\Annotation\SerializedName('node_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $nodeId;
    
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Shared\GitTagObject')]
    public GitTagObject $object;
    
	#[\JMS\Serializer\Annotation\SerializedName('sha')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sha;
    
    /**
     * Name of the tag
     * 
     * @var string $tag
     */
	#[\JMS\Serializer\Annotation\SerializedName('tag')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tag;
    
	#[\JMS\Serializer\Annotation\SerializedName('tagger')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Shared\GitTagTagger')]
    public GitTagTagger $tagger;
    
    /**
     * URL for the tag
     * 
     * @var string $url
     */
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $url;
    
	#[\JMS\Serializer\Annotation\SerializedName('verification')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Shared\Verification')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Verification $verification = null;
    
	public function __construct()
	{
		$this->message = "";
		$this->nodeId = "";
		$this->object = new \OpenAPI\OpenAPI\Models\Shared\GitTagObject();
		$this->sha = "";
		$this->tag = "";
		$this->tagger = new \OpenAPI\OpenAPI\Models\Shared\GitTagTagger();
		$this->url = "";
		$this->verification = null;
	}
}
