


export enum VatEnum {
    ZeroPercent = "0%",
    OnePercent = "1%",
    TenPercent = "10%",
    ElevenPercent = "11%",
    TwelvePercent = "12%",
    ThirteenPercent = "13%",
    FourteenPercent = "14%",
    FifteenPercent = "15%",
    SixteenPercent = "16%",
    SeventeenPercent = "17%",
    EighteenPercent = "18%",
    NineteenPercent = "19%",
    TwoPercent = "2%",
    TwentyPercent = "20%",
    TwentyOnePercent = "21%",
    TwentyTwoPercent = "22%",
    TwentyThreePercent = "23%",
    TwentyFourPercent = "24%",
    TwentyFivePercent = "25%",
    TwentySixPercent = "26%",
    TwentySevenPercent = "27%",
    ThreePercent = "3%",
    FourPercent = "4%",
    FivePercent = "5%",
    SixPercent = "6%",
    SevenPercent = "7%",
    EightPercent = "8%",
    NinePercent = "9%",
    Aam = "AAM",
    Am = "AM",
    Eu = "EU",
    Euk = "EUK",
    FAfa = "F.AFA",
    Fad = "FAD",
    KAfa = "K.AFA",
    Maa = "MAA",
    Tam = "TAM",
    Akk = "ÁKK",
    Athk = "ÁTHK"
}
