/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetNetworkPiiPiiKeysResponse {
    
    public String contentType;

    public GetNetworkPiiPiiKeysResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetNetworkPiiPiiKeysResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetNetworkPiiPiiKeysResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Successful operation
     */
    
    public java.util.Map<String, Object> getNetworkPiiPiiKeys200ApplicationJSONObject;

    public GetNetworkPiiPiiKeysResponse withGetNetworkPiiPiiKeys200ApplicationJSONObject(java.util.Map<String, Object> getNetworkPiiPiiKeys200ApplicationJSONObject) {
        this.getNetworkPiiPiiKeys200ApplicationJSONObject = getNetworkPiiPiiKeys200ApplicationJSONObject;
        return this;
    }
    
    public GetNetworkPiiPiiKeysResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
