/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GetOrganizationInventoryDeviceRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public String organizationId;

    public GetOrganizationInventoryDeviceRequest withOrganizationId(String organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=serial")
    public String serial;

    public GetOrganizationInventoryDeviceRequest withSerial(String serial) {
        this.serial = serial;
        return this;
    }
    
    public GetOrganizationInventoryDeviceRequest(@JsonProperty("organizationId") String organizationId, @JsonProperty("serial") String serial) {
        this.organizationId = organizationId;
        this.serial = serial;
  }
}
