package shared

type CurrencyEnum string

const (
	CurrencyEnumAud CurrencyEnum = "AUD"
	CurrencyEnumBgn CurrencyEnum = "BGN"
	CurrencyEnumBrl CurrencyEnum = "BRL"
	CurrencyEnumCad CurrencyEnum = "CAD"
	CurrencyEnumChf CurrencyEnum = "CHF"
	CurrencyEnumCny CurrencyEnum = "CNY"
	CurrencyEnumCzk CurrencyEnum = "CZK"
	CurrencyEnumDkk CurrencyEnum = "DKK"
	CurrencyEnumEur CurrencyEnum = "EUR"
	CurrencyEnumGbp CurrencyEnum = "GBP"
	CurrencyEnumHkd CurrencyEnum = "HKD"
	CurrencyEnumHrk CurrencyEnum = "HRK"
	CurrencyEnumHuf CurrencyEnum = "HUF"
	CurrencyEnumIdr CurrencyEnum = "IDR"
	CurrencyEnumIls CurrencyEnum = "ILS"
	CurrencyEnumInr CurrencyEnum = "INR"
	CurrencyEnumIsk CurrencyEnum = "ISK"
	CurrencyEnumJpy CurrencyEnum = "JPY"
	CurrencyEnumKrw CurrencyEnum = "KRW"
	CurrencyEnumLtl CurrencyEnum = "LTL"
	CurrencyEnumLvl CurrencyEnum = "LVL"
	CurrencyEnumMxn CurrencyEnum = "MXN"
	CurrencyEnumMyr CurrencyEnum = "MYR"
	CurrencyEnumNok CurrencyEnum = "NOK"
	CurrencyEnumNzd CurrencyEnum = "NZD"
	CurrencyEnumPhp CurrencyEnum = "PHP"
	CurrencyEnumPln CurrencyEnum = "PLN"
	CurrencyEnumRon CurrencyEnum = "RON"
	CurrencyEnumRsd CurrencyEnum = "RSD"
	CurrencyEnumRub CurrencyEnum = "RUB"
	CurrencyEnumSek CurrencyEnum = "SEK"
	CurrencyEnumSgd CurrencyEnum = "SGD"
	CurrencyEnumThb CurrencyEnum = "THB"
	CurrencyEnumTry CurrencyEnum = "TRY"
	CurrencyEnumUah CurrencyEnum = "UAH"
	CurrencyEnumUsd CurrencyEnum = "USD"
	CurrencyEnumZar CurrencyEnum = "ZAR"
)
