from ._xgafv_enum import *
from .alt_enum import *
from .aptsettings import *
from .cvssv3 import *
from .date_ import *
from .execstep import *
from .execstepconfig import *
from .executepatchjobrequest import *
from .fixedorpercent import *
from .gcsobject import *
from .inventory import *
from .inventoryitem import *
from .inventoryosinfo import *
from .inventorysoftwarepackage import *
from .inventoryversionedpackage import *
from .inventorywindowsapplication import *
from .inventorywindowsquickfixengineeringpackage import *
from .inventorywindowsupdatepackage import *
from .inventorywindowsupdatepackagewindowsupdatecategory import *
from .inventoryzypperpatch import *
from .listinventoriesresponse import *
from .listospolicyassignmentreportsresponse import *
from .listospolicyassignmentrevisionsresponse import *
from .listospolicyassignmentsresponse import *
from .listpatchdeploymentsresponse import *
from .listpatchjobinstancedetailsresponse import *
from .listpatchjobsresponse import *
from .listvulnerabilityreportsresponse import *
from .monthlyschedule import *
from .onetimeschedule import *
from .operation import *
from .ospolicy import *
from .ospolicyassignment import *
from .ospolicyassignmentinstancefilter import *
from .ospolicyassignmentinstancefilterinventory import *
from .ospolicyassignmentlabelset import *
from .ospolicyassignmentreport import *
from .ospolicyassignmentreportospolicycompliance import *
from .ospolicyassignmentreportospolicycomplianceospolicyresourcecompliance import *
from .ospolicyassignmentreportospolicycomplianceospolicyresourcecomplianceexecresourceoutput import *
from .ospolicyassignmentreportospolicycomplianceospolicyresourcecomplianceospolicyresourceconfigstep import *
from .ospolicyassignmentrollout import *
from .ospolicyinventoryfilter import *
from .ospolicyresource import *
from .ospolicyresourceexecresource import *
from .ospolicyresourceexecresourceexec import *
from .ospolicyresourcefile import *
from .ospolicyresourcefilegcs import *
from .ospolicyresourcefileremote import *
from .ospolicyresourcefileresource import *
from .ospolicyresourcegroup import *
from .ospolicyresourcepackageresource import *
from .ospolicyresourcepackageresourceapt import *
from .ospolicyresourcepackageresourcedeb import *
from .ospolicyresourcepackageresourcegooget import *
from .ospolicyresourcepackageresourcemsi import *
from .ospolicyresourcepackageresourcerpm import *
from .ospolicyresourcepackageresourceyum import *
from .ospolicyresourcepackageresourcezypper import *
from .ospolicyresourcerepositoryresource import *
from .ospolicyresourcerepositoryresourceaptrepository import *
from .ospolicyresourcerepositoryresourcegoorepository import *
from .ospolicyresourcerepositoryresourceyumrepository import *
from .ospolicyresourcerepositoryresourcezypperrepository import *
from .patchconfig import *
from .patchdeployment import *
from .patchinstancefilter import *
from .patchinstancefiltergrouplabel import *
from .patchjob import *
from .patchjobinstancedetails import *
from .patchjobinstancedetailssummary import *
from .patchrollout import *
from .recurringschedule import *
from .security import *
from .status import *
from .timeofday import *
from .timezone import *
from .vulnerabilityreport import *
from .vulnerabilityreportvulnerability import *
from .vulnerabilityreportvulnerabilitydetails import *
from .vulnerabilityreportvulnerabilitydetailsreference import *
from .vulnerabilityreportvulnerabilityitem import *
from .weekdayofmonth import *
from .weeklyschedule import *
from .windowsupdatesettings import *
from .yumsettings import *
from .zyppersettings import *

__all__ = ["XgafvEnum","AltEnum","AptSettingsTypeEnum","AptSettings","CvsSv3AttackComplexityEnum","CvsSv3AttackVectorEnum","CvsSv3AvailabilityImpactEnum","CvsSv3ConfidentialityImpactEnum","CvsSv3IntegrityImpactEnum","CvsSv3PrivilegesRequiredEnum","CvsSv3ScopeEnum","CvsSv3UserInteractionEnum","CvsSv3","Date","ExecStep","ExecStepConfigInterpreterEnum","ExecStepConfig","ExecutePatchJobRequest","FixedOrPercent","GcsObject","Inventory","InventoryItemOriginTypeEnum","InventoryItemTypeEnum","InventoryItem","InventoryOsInfo","InventorySoftwarePackage","InventoryVersionedPackage","InventoryWindowsApplication","InventoryWindowsQuickFixEngineeringPackage","InventoryWindowsUpdatePackage","InventoryWindowsUpdatePackageWindowsUpdateCategory","InventoryZypperPatch","ListInventoriesResponse","ListOsPolicyAssignmentReportsResponse","ListOsPolicyAssignmentRevisionsResponse","ListOsPolicyAssignmentsResponse","ListPatchDeploymentsResponse","ListPatchJobInstanceDetailsResponse","ListPatchJobsResponse","ListVulnerabilityReportsResponse","MonthlySchedule","OneTimeSchedule","Operation","OsPolicyModeEnum","OsPolicy","OsPolicyAssignmentRolloutStateEnum","OsPolicyAssignment","OsPolicyAssignmentInput","OsPolicyAssignmentInstanceFilter","OsPolicyAssignmentInstanceFilterInventory","OsPolicyAssignmentLabelSet","OsPolicyAssignmentReport","OsPolicyAssignmentReportOsPolicyComplianceComplianceStateEnum","OsPolicyAssignmentReportOsPolicyCompliance","OsPolicyAssignmentReportOsPolicyComplianceOsPolicyResourceComplianceComplianceStateEnum","OsPolicyAssignmentReportOsPolicyComplianceOsPolicyResourceCompliance","OsPolicyAssignmentReportOsPolicyComplianceOsPolicyResourceComplianceExecResourceOutput","OsPolicyAssignmentReportOsPolicyComplianceOsPolicyResourceComplianceOsPolicyResourceConfigStepTypeEnum","OsPolicyAssignmentReportOsPolicyComplianceOsPolicyResourceComplianceOsPolicyResourceConfigStep","OsPolicyAssignmentRollout","OsPolicyInventoryFilter","OsPolicyResource","OsPolicyResourceExecResource","OsPolicyResourceExecResourceExecInterpreterEnum","OsPolicyResourceExecResourceExec","OsPolicyResourceFile","OsPolicyResourceFileGcs","OsPolicyResourceFileRemote","OsPolicyResourceFileResourceStateEnum","OsPolicyResourceFileResource","OsPolicyResourceGroup","OsPolicyResourcePackageResourceDesiredStateEnum","OsPolicyResourcePackageResource","OsPolicyResourcePackageResourceApt","OsPolicyResourcePackageResourceDeb","OsPolicyResourcePackageResourceGooGet","OsPolicyResourcePackageResourceMsi","OsPolicyResourcePackageResourceRpm","OsPolicyResourcePackageResourceYum","OsPolicyResourcePackageResourceZypper","OsPolicyResourceRepositoryResource","OsPolicyResourceRepositoryResourceAptRepositoryArchiveTypeEnum","OsPolicyResourceRepositoryResourceAptRepository","OsPolicyResourceRepositoryResourceGooRepository","OsPolicyResourceRepositoryResourceYumRepository","OsPolicyResourceRepositoryResourceZypperRepository","PatchConfigRebootConfigEnum","PatchConfig","PatchDeploymentInput","PatchDeploymentStateEnum","PatchDeployment","PatchInstanceFilter","PatchInstanceFilterGroupLabel","PatchJobStateEnum","PatchJob","PatchJobInstanceDetailsStateEnum","PatchJobInstanceDetails","PatchJobInstanceDetailsSummary","PatchRolloutModeEnum","PatchRollout","RecurringScheduleFrequencyEnum","RecurringScheduleInput","RecurringSchedule","SchemeOauth2","SchemeOauth2c","Status","TimeOfDay","TimeZone","VulnerabilityReport","VulnerabilityReportVulnerability","VulnerabilityReportVulnerabilityDetails","VulnerabilityReportVulnerabilityDetailsReference","VulnerabilityReportVulnerabilityItem","WeekDayOfMonthDayOfWeekEnum","WeekDayOfMonth","WeeklyScheduleDayOfWeekEnum","WeeklySchedule","WindowsUpdateSettingsClassificationsEnum","WindowsUpdateSettings","YumSettings","ZypperSettings"]