/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateBreakTypeRequest - A request to create a new `BreakType`.
 */
public class CreateBreakTypeRequest {
    /**
     * A defined break template that sets an expectation for possible `Break`
     * instances on a `Shift`.
     */
    @JsonProperty("break_type")
    public BreakType breakType;

    public CreateBreakTypeRequest withBreakType(BreakType breakType) {
        this.breakType = breakType;
        return this;
    }
    
    /**
     * A unique string value to ensure the idempotency of the operation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idempotency_key")
    public String idempotencyKey;

    public CreateBreakTypeRequest withIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }
    
    public CreateBreakTypeRequest(@JsonProperty("break_type") BreakType breakType) {
        this.breakType = breakType;
  }
}
