/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class ApproveAnAchTransferPathParams {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ach_transfer_id")
    public String achTransferId;
    public ApproveAnAchTransferPathParams withAchTransferId(String achTransferId) {
        this.achTransferId = achTransferId;
        return this;
    }
    
}
