/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;

public class EnableUserV2Request {
    /**
     * The UUID of the User.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")
    public String userId;

    public EnableUserV2Request withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public EnableUserV2Request(@JsonProperty("userId") String userId) {
        this.userId = userId;
  }
}
