/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;

public class ResendPayeeInviteV4Request {
    /**
     * Provide Payor Id in body of request
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.InvitePayeeRequestV4 invitePayeeRequestV4;

    public ResendPayeeInviteV4Request withInvitePayeeRequestV4(org.openapis.openapi.models.shared.InvitePayeeRequestV4 invitePayeeRequestV4) {
        this.invitePayeeRequestV4 = invitePayeeRequestV4;
        return this;
    }
    
    /**
     * The UUID of the payee.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=payeeId")
    public String payeeId;

    public ResendPayeeInviteV4Request withPayeeId(String payeeId) {
        this.payeeId = payeeId;
        return this;
    }
    
    public ResendPayeeInviteV4Request(@JsonProperty("InvitePayeeRequestV4") org.openapis.openapi.models.shared.InvitePayeeRequestV4 invitePayeeRequestV4, @JsonProperty("payeeId") String payeeId) {
        this.invitePayeeRequestV4 = invitePayeeRequestV4;
        this.payeeId = payeeId;
  }
}
