// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResourceRequestStatusFilter - The filter criteria to use in determining the requests returned.
type ResourceRequestStatusFilter struct {
	OperationStatuses []OperationStatusEnum `json:"OperationStatuses,omitempty"`
	Operations        []OperationEnum       `json:"Operations,omitempty"`
}
