/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GetTransactionsHeaders {
    /**
     * This header identifies the seller's eBay marketplace. It is required for all marketplaces outside of the US. See &lt;a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank "&gt;HTTP request headers&lt;/a&gt; for the marketplace ID values.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-EBAY-C-MARKETPLACE-ID")
    public String xEbayCMarketplaceId;
    public GetTransactionsHeaders withXEbayCMarketplaceId(String xEbayCMarketplaceId) {
        this.xEbayCMarketplaceId = xEbayCMarketplaceId;
        return this;
    }
    
}
