/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class GetConversationsRequest {
    
    public GetConversationsQueryParams queryParams;
    public GetConversationsRequest withQueryParams(GetConversationsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
