<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/** Device to which metrics apply. */
enum GoogleAdsSearchads360V0CommonSegmentsDeviceEnum: string
{
    case UNSPECIFIED = 'UNSPECIFIED';
    case UNKNOWN = 'UNKNOWN';
    case MOBILE = 'MOBILE';
    case TABLET = 'TABLET';
    case DESKTOP = 'DESKTOP';
    case CONNECTED_TV = 'CONNECTED_TV';
    case OTHER = 'OTHER';
}
