<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


class TagResourceResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Success
     * 
     * @var ?array<string, mixed> $tagResourceResponse
     */
	
    public ?array $tagResourceResponse = null;
    
    /**
     * WAFBadRequestException
     * 
     * @var mixed $wafBadRequestException
     */
	
    public mixed $wafBadRequestException = null;
    
    /**
     * WAFInternalErrorException
     * 
     * @var mixed $wafInternalErrorException
     */
	
    public mixed $wafInternalErrorException = null;
    
    /**
     * WAFInvalidParameterException
     * 
     * @var mixed $wafInvalidParameterException
     */
	
    public mixed $wafInvalidParameterException = null;
    
    /**
     * WAFLimitsExceededException
     * 
     * @var mixed $wafLimitsExceededException
     */
	
    public mixed $wafLimitsExceededException = null;
    
    /**
     * WAFNonexistentItemException
     * 
     * @var mixed $wafNonexistentItemException
     */
	
    public mixed $wafNonexistentItemException = null;
    
    /**
     * WAFTagOperationException
     * 
     * @var mixed $wafTagOperationException
     */
	
    public mixed $wafTagOperationException = null;
    
    /**
     * WAFTagOperationInternalErrorException
     * 
     * @var mixed $wafTagOperationInternalErrorException
     */
	
    public mixed $wafTagOperationInternalErrorException = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->tagResourceResponse = null;
		$this->wafBadRequestException = null;
		$this->wafInternalErrorException = null;
		$this->wafInvalidParameterException = null;
		$this->wafLimitsExceededException = null;
		$this->wafNonexistentItemException = null;
		$this->wafTagOperationException = null;
		$this->wafTagOperationInternalErrorException = null;
	}
}
