/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class AccountCallLogsQueryParams {
    /**
     * Start date from which you would like to get the call logs. The start date should be within past six months. &lt;br&gt;
     * 
     * The API only returns data pertaining to a month. Thus, the date range(defined using "from" and "to" fields) for which the call logs are to be returned must not exceed a month.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=from")
    public String from;
    public AccountCallLogsQueryParams withFrom(String from) {
        this.from = from;
        return this;
    }
    
    /**
     * The next page token is used to paginate through large result sets. A next page token will be returned whenever the set of available results exceeds the current page size. The expiration period for this token is 15 minutes.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=next_page_token")
    public String nextPageToken;
    public AccountCallLogsQueryParams withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    /**
     * The number of records returned within a single API call.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    public Long pageSize;
    public AccountCallLogsQueryParams withPageSize(Long pageSize) {
        this.pageSize = pageSize;
        return this;
    }
    
    /**
     * Filter the API response by [path](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs#h_646b46c6-0623-4ab1-8b8b-ea5b8bcef679) of the call. The value of this field can be one of the following: `voiceMail`, `message`, `forward`, `extension`, `callQueue`, `ivrMenu`, `companyDirectory`, `autoReceptionist`, `contactCenter`, `disconnected`, `commonAreaPhone`,
     * `pstn`, `transfer`, `sharedLines`, `sharedLineGroup`, `tollFreeBilling`, `meetingService`, `parkPickup`,
     * `parkTimeout`, `monitor`, `takeover`, `sipGroup`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=path")
    public String path;
    public AccountCallLogsQueryParams withPath(String path) {
        this.path = path;
        return this;
    }
    
    /**
     * Unique identifier of the [site](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-multiple-sites). Use this query parameter if you have enabled multiple sites and would like to filter the response of this API call by call logs of a specific phone site.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=site_id")
    public String siteId;
    public AccountCallLogsQueryParams withSiteId(String siteId) {
        this.siteId = siteId;
        return this;
    }
    
    /**
     * Enables you to sort call logs by start or end time. Choose the sort time value. Values include `startTime` or `endTime`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=time_type")
    public AccountCallLogsTimeTypeEnum timeType;
    public AccountCallLogsQueryParams withTimeType(AccountCallLogsTimeTypeEnum timeType) {
        this.timeType = timeType;
        return this;
    }
    
    /**
     * The end date upto which you would like to get the call logs for. The end date should be within past six months.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=to")
    public String to;
    public AccountCallLogsQueryParams withTo(String to) {
        this.to = to;
        return this;
    }
    
    /**
     * The type of the call logs. The value can be either "all" or "missed".
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")
    public String type;
    public AccountCallLogsQueryParams withType(String type) {
        this.type = type;
        return this;
    }
    
}
