import dataclasses
from enum import Enum

class VatEnum(str, Enum):
    ZERO_PERCENT_ = "0%"
    ONE_PERCENT_ = "1%"
    TEN_PERCENT_ = "10%"
    ELEVEN_PERCENT_ = "11%"
    TWELVE_PERCENT_ = "12%"
    THIRTEEN_PERCENT_ = "13%"
    FOURTEEN_PERCENT_ = "14%"
    FIFTEEN_PERCENT_ = "15%"
    SIXTEEN_PERCENT_ = "16%"
    SEVENTEEN_PERCENT_ = "17%"
    EIGHTEEN_PERCENT_ = "18%"
    NINETEEN_PERCENT_ = "19%"
    TWO_PERCENT_ = "2%"
    TWENTY_PERCENT_ = "20%"
    TWENTY_ONE_PERCENT_ = "21%"
    TWENTY_TWO_PERCENT_ = "22%"
    TWENTY_THREE_PERCENT_ = "23%"
    TWENTY_FOUR_PERCENT_ = "24%"
    TWENTY_FIVE_PERCENT_ = "25%"
    TWENTY_SIX_PERCENT_ = "26%"
    TWENTY_SEVEN_PERCENT_ = "27%"
    THREE_PERCENT_ = "3%"
    FOUR_PERCENT_ = "4%"
    FIVE_PERCENT_ = "5%"
    SIX_PERCENT_ = "6%"
    SEVEN_PERCENT_ = "7%"
    EIGHT_PERCENT_ = "8%"
    NINE_PERCENT_ = "9%"
    AAM = "AAM"
    AM = "AM"
    EU = "EU"
    EUK = "EUK"
    F_AFA = "F.AFA"
    FAD = "FAD"
    K_AFA = "K.AFA"
    MAA = "MAA"
    TAM = "TAM"
    AKK = "ÁKK"
    ATHK = "ÁTHK"

