/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.net.http.HttpResponse;

public class CreateAccountSecretResponse {
    
    public String contentType;
    public CreateAccountSecretResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public CreateAccountSecretResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public CreateAccountSecretResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public org.openapis.openapi.models.shared.MicrovisorV1AccountSecret microvisorV1AccountSecret;
    public CreateAccountSecretResponse withMicrovisorV1AccountSecret(org.openapis.openapi.models.shared.MicrovisorV1AccountSecret microvisorV1AccountSecret) {
        this.microvisorV1AccountSecret = microvisorV1AccountSecret;
        return this;
    }
    
}
