// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PreviewMarketplaceAvailableAddOn - OK
type PreviewMarketplaceAvailableAddOn struct {
	// The JSON object with the configuration that must be provided when installing a given Add-on.
	ConfigurationSchema interface{} `json:"configuration_schema,omitempty"`
	// A short description of the Add-on's functionality.
	Description *string `json:"description,omitempty"`
	// The string that you assigned to describe the resource.
	FriendlyName *string `json:"friendly_name,omitempty"`
	// The URLs of related resources.
	Links map[string]interface{} `json:"links,omitempty"`
	// How customers are charged for using this Add-on.
	PricingType *string `json:"pricing_type,omitempty"`
	// The unique string that we created to identify the AvailableAddOn resource.
	Sid *string `json:"sid,omitempty"`
	// The absolute URL of the resource.
	URL *string `json:"url,omitempty"`
}
