// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LinksPercentiles - Successful operation
type LinksPercentiles struct {
	Domain      string                 `json:"domain"`
	Percentiles []LinksPercentilesItem `json:"percentiles"`
}
