from .acceptmatch import *
from .claimgameserver import *
from .createalias import *
from .createbuild import *
from .createfleet import *
from .createfleetlocations import *
from .creategameservergroup import *
from .creategamesession import *
from .creategamesessionqueue import *
from .creatematchmakingconfiguration import *
from .creatematchmakingruleset import *
from .createplayersession import *
from .createplayersessions import *
from .createscript import *
from .createvpcpeeringauthorization import *
from .createvpcpeeringconnection import *
from .deletealias import *
from .deletebuild import *
from .deletefleet import *
from .deletefleetlocations import *
from .deletegameservergroup import *
from .deletegamesessionqueue import *
from .deletematchmakingconfiguration import *
from .deletematchmakingruleset import *
from .deletescalingpolicy import *
from .deletescript import *
from .deletevpcpeeringauthorization import *
from .deletevpcpeeringconnection import *
from .deregistergameserver import *
from .describealias import *
from .describebuild import *
from .describeec2instancelimits import *
from .describefleetattributes import *
from .describefleetcapacity import *
from .describefleetevents import *
from .describefleetlocationattributes import *
from .describefleetlocationcapacity import *
from .describefleetlocationutilization import *
from .describefleetportsettings import *
from .describefleetutilization import *
from .describegameserver import *
from .describegameservergroup import *
from .describegameserverinstances import *
from .describegamesessiondetails import *
from .describegamesessionplacement import *
from .describegamesessionqueues import *
from .describegamesessions import *
from .describeinstances import *
from .describematchmaking import *
from .describematchmakingconfigurations import *
from .describematchmakingrulesets import *
from .describeplayersessions import *
from .describeruntimeconfiguration import *
from .describescalingpolicies import *
from .describescript import *
from .describevpcpeeringauthorizations import *
from .describevpcpeeringconnections import *
from .getgamesessionlogurl import *
from .getinstanceaccess import *
from .listaliases import *
from .listbuilds import *
from .listfleets import *
from .listgameservergroups import *
from .listgameservers import *
from .listscripts import *
from .listtagsforresource import *
from .putscalingpolicy import *
from .registergameserver import *
from .requestuploadcredentials import *
from .resolvealias import *
from .resumegameservergroup import *
from .searchgamesessions import *
from .startfleetactions import *
from .startgamesessionplacement import *
from .startmatchbackfill import *
from .startmatchmaking import *
from .stopfleetactions import *
from .stopgamesessionplacement import *
from .stopmatchmaking import *
from .suspendgameservergroup import *
from .tagresource import *
from .untagresource import *
from .updatealias import *
from .updatebuild import *
from .updatefleetattributes import *
from .updatefleetcapacity import *
from .updatefleetportsettings import *
from .updategameserver import *
from .updategameservergroup import *
from .updategamesession import *
from .updategamesessionqueue import *
from .updatematchmakingconfiguration import *
from .updateruntimeconfiguration import *
from .updatescript import *
from .validatematchmakingruleset import *

__all__ = ["AcceptMatchXAmzTargetEnum","AcceptMatchHeaders","AcceptMatchRequest","AcceptMatchResponse","ClaimGameServerXAmzTargetEnum","ClaimGameServerHeaders","ClaimGameServerRequest","ClaimGameServerResponse","CreateAliasXAmzTargetEnum","CreateAliasHeaders","CreateAliasRequest","CreateAliasResponse","CreateBuildXAmzTargetEnum","CreateBuildHeaders","CreateBuildRequest","CreateBuildResponse","CreateFleetXAmzTargetEnum","CreateFleetHeaders","CreateFleetRequest","CreateFleetResponse","CreateFleetLocationsXAmzTargetEnum","CreateFleetLocationsHeaders","CreateFleetLocationsRequest","CreateFleetLocationsResponse","CreateGameServerGroupXAmzTargetEnum","CreateGameServerGroupHeaders","CreateGameServerGroupRequest","CreateGameServerGroupResponse","CreateGameSessionXAmzTargetEnum","CreateGameSessionHeaders","CreateGameSessionRequest","CreateGameSessionResponse","CreateGameSessionQueueXAmzTargetEnum","CreateGameSessionQueueHeaders","CreateGameSessionQueueRequest","CreateGameSessionQueueResponse","CreateMatchmakingConfigurationXAmzTargetEnum","CreateMatchmakingConfigurationHeaders","CreateMatchmakingConfigurationRequest","CreateMatchmakingConfigurationResponse","CreateMatchmakingRuleSetXAmzTargetEnum","CreateMatchmakingRuleSetHeaders","CreateMatchmakingRuleSetRequest","CreateMatchmakingRuleSetResponse","CreatePlayerSessionXAmzTargetEnum","CreatePlayerSessionHeaders","CreatePlayerSessionRequest","CreatePlayerSessionResponse","CreatePlayerSessionsXAmzTargetEnum","CreatePlayerSessionsHeaders","CreatePlayerSessionsRequest","CreatePlayerSessionsResponse","CreateScriptXAmzTargetEnum","CreateScriptHeaders","CreateScriptRequest","CreateScriptResponse","CreateVpcPeeringAuthorizationXAmzTargetEnum","CreateVpcPeeringAuthorizationHeaders","CreateVpcPeeringAuthorizationRequest","CreateVpcPeeringAuthorizationResponse","CreateVpcPeeringConnectionXAmzTargetEnum","CreateVpcPeeringConnectionHeaders","CreateVpcPeeringConnectionRequest","CreateVpcPeeringConnectionResponse","DeleteAliasXAmzTargetEnum","DeleteAliasHeaders","DeleteAliasRequest","DeleteAliasResponse","DeleteBuildXAmzTargetEnum","DeleteBuildHeaders","DeleteBuildRequest","DeleteBuildResponse","DeleteFleetXAmzTargetEnum","DeleteFleetHeaders","DeleteFleetRequest","DeleteFleetResponse","DeleteFleetLocationsXAmzTargetEnum","DeleteFleetLocationsHeaders","DeleteFleetLocationsRequest","DeleteFleetLocationsResponse","DeleteGameServerGroupXAmzTargetEnum","DeleteGameServerGroupHeaders","DeleteGameServerGroupRequest","DeleteGameServerGroupResponse","DeleteGameSessionQueueXAmzTargetEnum","DeleteGameSessionQueueHeaders","DeleteGameSessionQueueRequest","DeleteGameSessionQueueResponse","DeleteMatchmakingConfigurationXAmzTargetEnum","DeleteMatchmakingConfigurationHeaders","DeleteMatchmakingConfigurationRequest","DeleteMatchmakingConfigurationResponse","DeleteMatchmakingRuleSetXAmzTargetEnum","DeleteMatchmakingRuleSetHeaders","DeleteMatchmakingRuleSetRequest","DeleteMatchmakingRuleSetResponse","DeleteScalingPolicyXAmzTargetEnum","DeleteScalingPolicyHeaders","DeleteScalingPolicyRequest","DeleteScalingPolicyResponse","DeleteScriptXAmzTargetEnum","DeleteScriptHeaders","DeleteScriptRequest","DeleteScriptResponse","DeleteVpcPeeringAuthorizationXAmzTargetEnum","DeleteVpcPeeringAuthorizationHeaders","DeleteVpcPeeringAuthorizationRequest","DeleteVpcPeeringAuthorizationResponse","DeleteVpcPeeringConnectionXAmzTargetEnum","DeleteVpcPeeringConnectionHeaders","DeleteVpcPeeringConnectionRequest","DeleteVpcPeeringConnectionResponse","DeregisterGameServerXAmzTargetEnum","DeregisterGameServerHeaders","DeregisterGameServerRequest","DeregisterGameServerResponse","DescribeAliasXAmzTargetEnum","DescribeAliasHeaders","DescribeAliasRequest","DescribeAliasResponse","DescribeBuildXAmzTargetEnum","DescribeBuildHeaders","DescribeBuildRequest","DescribeBuildResponse","DescribeEc2InstanceLimitsXAmzTargetEnum","DescribeEc2InstanceLimitsHeaders","DescribeEc2InstanceLimitsRequest","DescribeEc2InstanceLimitsResponse","DescribeFleetAttributesQueryParams","DescribeFleetAttributesXAmzTargetEnum","DescribeFleetAttributesHeaders","DescribeFleetAttributesRequest","DescribeFleetAttributesResponse","DescribeFleetCapacityQueryParams","DescribeFleetCapacityXAmzTargetEnum","DescribeFleetCapacityHeaders","DescribeFleetCapacityRequest","DescribeFleetCapacityResponse","DescribeFleetEventsQueryParams","DescribeFleetEventsXAmzTargetEnum","DescribeFleetEventsHeaders","DescribeFleetEventsRequest","DescribeFleetEventsResponse","DescribeFleetLocationAttributesQueryParams","DescribeFleetLocationAttributesXAmzTargetEnum","DescribeFleetLocationAttributesHeaders","DescribeFleetLocationAttributesRequest","DescribeFleetLocationAttributesResponse","DescribeFleetLocationCapacityXAmzTargetEnum","DescribeFleetLocationCapacityHeaders","DescribeFleetLocationCapacityRequest","DescribeFleetLocationCapacityResponse","DescribeFleetLocationUtilizationXAmzTargetEnum","DescribeFleetLocationUtilizationHeaders","DescribeFleetLocationUtilizationRequest","DescribeFleetLocationUtilizationResponse","DescribeFleetPortSettingsXAmzTargetEnum","DescribeFleetPortSettingsHeaders","DescribeFleetPortSettingsRequest","DescribeFleetPortSettingsResponse","DescribeFleetUtilizationQueryParams","DescribeFleetUtilizationXAmzTargetEnum","DescribeFleetUtilizationHeaders","DescribeFleetUtilizationRequest","DescribeFleetUtilizationResponse","DescribeGameServerXAmzTargetEnum","DescribeGameServerHeaders","DescribeGameServerRequest","DescribeGameServerResponse","DescribeGameServerGroupXAmzTargetEnum","DescribeGameServerGroupHeaders","DescribeGameServerGroupRequest","DescribeGameServerGroupResponse","DescribeGameServerInstancesQueryParams","DescribeGameServerInstancesXAmzTargetEnum","DescribeGameServerInstancesHeaders","DescribeGameServerInstancesRequest","DescribeGameServerInstancesResponse","DescribeGameSessionDetailsQueryParams","DescribeGameSessionDetailsXAmzTargetEnum","DescribeGameSessionDetailsHeaders","DescribeGameSessionDetailsRequest","DescribeGameSessionDetailsResponse","DescribeGameSessionPlacementXAmzTargetEnum","DescribeGameSessionPlacementHeaders","DescribeGameSessionPlacementRequest","DescribeGameSessionPlacementResponse","DescribeGameSessionQueuesQueryParams","DescribeGameSessionQueuesXAmzTargetEnum","DescribeGameSessionQueuesHeaders","DescribeGameSessionQueuesRequest","DescribeGameSessionQueuesResponse","DescribeGameSessionsQueryParams","DescribeGameSessionsXAmzTargetEnum","DescribeGameSessionsHeaders","DescribeGameSessionsRequest","DescribeGameSessionsResponse","DescribeInstancesQueryParams","DescribeInstancesXAmzTargetEnum","DescribeInstancesHeaders","DescribeInstancesRequest","DescribeInstancesResponse","DescribeMatchmakingXAmzTargetEnum","DescribeMatchmakingHeaders","DescribeMatchmakingRequest","DescribeMatchmakingResponse","DescribeMatchmakingConfigurationsQueryParams","DescribeMatchmakingConfigurationsXAmzTargetEnum","DescribeMatchmakingConfigurationsHeaders","DescribeMatchmakingConfigurationsRequest","DescribeMatchmakingConfigurationsResponse","DescribeMatchmakingRuleSetsQueryParams","DescribeMatchmakingRuleSetsXAmzTargetEnum","DescribeMatchmakingRuleSetsHeaders","DescribeMatchmakingRuleSetsRequest","DescribeMatchmakingRuleSetsResponse","DescribePlayerSessionsQueryParams","DescribePlayerSessionsXAmzTargetEnum","DescribePlayerSessionsHeaders","DescribePlayerSessionsRequest","DescribePlayerSessionsResponse","DescribeRuntimeConfigurationXAmzTargetEnum","DescribeRuntimeConfigurationHeaders","DescribeRuntimeConfigurationRequest","DescribeRuntimeConfigurationResponse","DescribeScalingPoliciesQueryParams","DescribeScalingPoliciesXAmzTargetEnum","DescribeScalingPoliciesHeaders","DescribeScalingPoliciesRequest","DescribeScalingPoliciesResponse","DescribeScriptXAmzTargetEnum","DescribeScriptHeaders","DescribeScriptRequest","DescribeScriptResponse","DescribeVpcPeeringAuthorizationsXAmzTargetEnum","DescribeVpcPeeringAuthorizationsHeaders","DescribeVpcPeeringAuthorizationsRequest","DescribeVpcPeeringAuthorizationsResponse","DescribeVpcPeeringConnectionsXAmzTargetEnum","DescribeVpcPeeringConnectionsHeaders","DescribeVpcPeeringConnectionsRequest","DescribeVpcPeeringConnectionsResponse","GetGameSessionLogURLXAmzTargetEnum","GetGameSessionLogURLHeaders","GetGameSessionLogURLRequest","GetGameSessionLogURLResponse","GetInstanceAccessXAmzTargetEnum","GetInstanceAccessHeaders","GetInstanceAccessRequest","GetInstanceAccessResponse","ListAliasesQueryParams","ListAliasesXAmzTargetEnum","ListAliasesHeaders","ListAliasesRequest","ListAliasesResponse","ListBuildsQueryParams","ListBuildsXAmzTargetEnum","ListBuildsHeaders","ListBuildsRequest","ListBuildsResponse","ListFleetsQueryParams","ListFleetsXAmzTargetEnum","ListFleetsHeaders","ListFleetsRequest","ListFleetsResponse","ListGameServerGroupsQueryParams","ListGameServerGroupsXAmzTargetEnum","ListGameServerGroupsHeaders","ListGameServerGroupsRequest","ListGameServerGroupsResponse","ListGameServersQueryParams","ListGameServersXAmzTargetEnum","ListGameServersHeaders","ListGameServersRequest","ListGameServersResponse","ListScriptsQueryParams","ListScriptsXAmzTargetEnum","ListScriptsHeaders","ListScriptsRequest","ListScriptsResponse","ListTagsForResourceXAmzTargetEnum","ListTagsForResourceHeaders","ListTagsForResourceRequest","ListTagsForResourceResponse","PutScalingPolicyXAmzTargetEnum","PutScalingPolicyHeaders","PutScalingPolicyRequest","PutScalingPolicyResponse","RegisterGameServerXAmzTargetEnum","RegisterGameServerHeaders","RegisterGameServerRequest","RegisterGameServerResponse","RequestUploadCredentialsXAmzTargetEnum","RequestUploadCredentialsHeaders","RequestUploadCredentialsRequest","RequestUploadCredentialsResponse","ResolveAliasXAmzTargetEnum","ResolveAliasHeaders","ResolveAliasRequest","ResolveAliasResponse","ResumeGameServerGroupXAmzTargetEnum","ResumeGameServerGroupHeaders","ResumeGameServerGroupRequest","ResumeGameServerGroupResponse","SearchGameSessionsQueryParams","SearchGameSessionsXAmzTargetEnum","SearchGameSessionsHeaders","SearchGameSessionsRequest","SearchGameSessionsResponse","StartFleetActionsXAmzTargetEnum","StartFleetActionsHeaders","StartFleetActionsRequest","StartFleetActionsResponse","StartGameSessionPlacementXAmzTargetEnum","StartGameSessionPlacementHeaders","StartGameSessionPlacementRequest","StartGameSessionPlacementResponse","StartMatchBackfillXAmzTargetEnum","StartMatchBackfillHeaders","StartMatchBackfillRequest","StartMatchBackfillResponse","StartMatchmakingXAmzTargetEnum","StartMatchmakingHeaders","StartMatchmakingRequest","StartMatchmakingResponse","StopFleetActionsXAmzTargetEnum","StopFleetActionsHeaders","StopFleetActionsRequest","StopFleetActionsResponse","StopGameSessionPlacementXAmzTargetEnum","StopGameSessionPlacementHeaders","StopGameSessionPlacementRequest","StopGameSessionPlacementResponse","StopMatchmakingXAmzTargetEnum","StopMatchmakingHeaders","StopMatchmakingRequest","StopMatchmakingResponse","SuspendGameServerGroupXAmzTargetEnum","SuspendGameServerGroupHeaders","SuspendGameServerGroupRequest","SuspendGameServerGroupResponse","TagResourceXAmzTargetEnum","TagResourceHeaders","TagResourceRequest","TagResourceResponse","UntagResourceXAmzTargetEnum","UntagResourceHeaders","UntagResourceRequest","UntagResourceResponse","UpdateAliasXAmzTargetEnum","UpdateAliasHeaders","UpdateAliasRequest","UpdateAliasResponse","UpdateBuildXAmzTargetEnum","UpdateBuildHeaders","UpdateBuildRequest","UpdateBuildResponse","UpdateFleetAttributesXAmzTargetEnum","UpdateFleetAttributesHeaders","UpdateFleetAttributesRequest","UpdateFleetAttributesResponse","UpdateFleetCapacityXAmzTargetEnum","UpdateFleetCapacityHeaders","UpdateFleetCapacityRequest","UpdateFleetCapacityResponse","UpdateFleetPortSettingsXAmzTargetEnum","UpdateFleetPortSettingsHeaders","UpdateFleetPortSettingsRequest","UpdateFleetPortSettingsResponse","UpdateGameServerXAmzTargetEnum","UpdateGameServerHeaders","UpdateGameServerRequest","UpdateGameServerResponse","UpdateGameServerGroupXAmzTargetEnum","UpdateGameServerGroupHeaders","UpdateGameServerGroupRequest","UpdateGameServerGroupResponse","UpdateGameSessionXAmzTargetEnum","UpdateGameSessionHeaders","UpdateGameSessionRequest","UpdateGameSessionResponse","UpdateGameSessionQueueXAmzTargetEnum","UpdateGameSessionQueueHeaders","UpdateGameSessionQueueRequest","UpdateGameSessionQueueResponse","UpdateMatchmakingConfigurationXAmzTargetEnum","UpdateMatchmakingConfigurationHeaders","UpdateMatchmakingConfigurationRequest","UpdateMatchmakingConfigurationResponse","UpdateRuntimeConfigurationXAmzTargetEnum","UpdateRuntimeConfigurationHeaders","UpdateRuntimeConfigurationRequest","UpdateRuntimeConfigurationResponse","UpdateScriptXAmzTargetEnum","UpdateScriptHeaders","UpdateScriptRequest","UpdateScriptResponse","ValidateMatchmakingRuleSetXAmzTargetEnum","ValidateMatchmakingRuleSetHeaders","ValidateMatchmakingRuleSetRequest","ValidateMatchmakingRuleSetResponse"]