/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class BatchAssociateClientDeviceWithCoreDeviceResponse {
    /**
     * AccessDeniedException
     */
    
    public Object accessDeniedException;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withAccessDeniedException(Object accessDeniedException) {
        this.accessDeniedException = accessDeniedException;
        return this;
    }
    
    /**
     * Success
     */
    
    public org.openapis.openapi.models.shared.BatchAssociateClientDeviceWithCoreDeviceResponse batchAssociateClientDeviceWithCoreDeviceResponse;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withBatchAssociateClientDeviceWithCoreDeviceResponse(org.openapis.openapi.models.shared.BatchAssociateClientDeviceWithCoreDeviceResponse batchAssociateClientDeviceWithCoreDeviceResponse) {
        this.batchAssociateClientDeviceWithCoreDeviceResponse = batchAssociateClientDeviceWithCoreDeviceResponse;
        return this;
    }
    
    
    public String contentType;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * InternalServerException
     */
    
    public Object internalServerException;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withInternalServerException(Object internalServerException) {
        this.internalServerException = internalServerException;
        return this;
    }
    
    /**
     * ResourceNotFoundException
     */
    
    public Object resourceNotFoundException;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withResourceNotFoundException(Object resourceNotFoundException) {
        this.resourceNotFoundException = resourceNotFoundException;
        return this;
    }
    
    
    public Integer statusCode;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * ThrottlingException
     */
    
    public Object throttlingException;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withThrottlingException(Object throttlingException) {
        this.throttlingException = throttlingException;
        return this;
    }
    
    /**
     * ValidationException
     */
    
    public Object validationException;

    public BatchAssociateClientDeviceWithCoreDeviceResponse withValidationException(Object validationException) {
        this.validationException = validationException;
        return this;
    }
    
    public BatchAssociateClientDeviceWithCoreDeviceResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
