package openapisdk.models.shared;


public enum GoogleCloudRecaptchaenterpriseV1AccountVerificationInfoLatestVerificationResultEnum {
    RESULT_UNSPECIFIED("RESULT_UNSPECIFIED"),
    SUCCESS_USER_VERIFIED("SUCCESS_USER_VERIFIED"),
    ERROR_USER_NOT_VERIFIED("ERROR_USER_NOT_VERIFIED"),
    ERROR_SITE_ONBOARDING_INCOMPLETE("ERROR_SITE_ONBOARDING_INCOMPLETE"),
    ERROR_RECIPIENT_NOT_ALLOWED("ERROR_RECIPIENT_NOT_ALLOWED"),
    ERROR_RECIPIENT_ABUSE_LIMIT_EXHAUSTED("ERROR_RECIPIENT_ABUSE_LIMIT_EXHAUSTED"),
    ERROR_CRITICAL_INTERNAL("ERROR_CRITICAL_INTERNAL"),
    ERROR_CUSTOMER_QUOTA_EXHAUSTED("ERROR_CUSTOMER_QUOTA_EXHAUSTED"),
    ERROR_VERIFICATION_BYPASSED("ERROR_VERIFICATION_BYPASSED"),
    ERROR_VERDICT_MISMATCH("ERROR_VERDICT_MISMATCH");

    public final String value;

    private GoogleCloudRecaptchaenterpriseV1AccountVerificationInfoLatestVerificationResultEnum(String value) {
        this.value = value;
    }
}
