package openapisdk.models.shared;


public enum GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentRequestReasonsEnum {
    REASON_UNSPECIFIED("REASON_UNSPECIFIED"),
    CHARGEBACK("CHARGEBACK"),
    CHARGEBACK_FRAUD("CHARGEBACK_FRAUD"),
    CHARGEBACK_DISPUTE("CHARGEBACK_DISPUTE"),
    REFUND("REFUND"),
    REFUND_FRAUD("REFUND_FRAUD"),
    TRANSACTION_ACCEPTED("TRANSACTION_ACCEPTED"),
    TRANSACTION_DECLINED("TRANSACTION_DECLINED"),
    PAYMENT_HEURISTICS("PAYMENT_HEURISTICS"),
    INITIATED_TWO_FACTOR("INITIATED_TWO_FACTOR"),
    PASSED_TWO_FACTOR("PASSED_TWO_FACTOR"),
    FAILED_TWO_FACTOR("FAILED_TWO_FACTOR"),
    CORRECT_PASSWORD("CORRECT_PASSWORD"),
    INCORRECT_PASSWORD("INCORRECT_PASSWORD"),
    SOCIAL_SPAM("SOCIAL_SPAM");

    public final String value;

    private GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentRequestReasonsEnum(String value) {
        this.value = value;
    }
}
