/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class DeleteRealmAuthenticationExecutionsExecutionIdRequest {
    
    public DeleteRealmAuthenticationExecutionsExecutionIdPathParams pathParams;
    public DeleteRealmAuthenticationExecutionsExecutionIdRequest withPathParams(DeleteRealmAuthenticationExecutionsExecutionIdPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
