/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class UpdateDistribution20161125RequestBody {
    /**
     * A distribution configuration.
     */
    
    public UpdateDistribution20161125RequestBodyDistributionConfig distributionConfig;
    public UpdateDistribution20161125RequestBody withDistributionConfig(UpdateDistribution20161125RequestBodyDistributionConfig distributionConfig) {
        this.distributionConfig = distributionConfig;
        return this;
    }
    
}
