// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type BuildStatusEnum string

const (
	BuildStatusEnumInitialized BuildStatusEnum = "INITIALIZED"
	BuildStatusEnumReady       BuildStatusEnum = "READY"
	BuildStatusEnumFailed      BuildStatusEnum = "FAILED"
)

func (e *BuildStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "INITIALIZED":
		fallthrough
	case "READY":
		fallthrough
	case "FAILED":
		*e = BuildStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for BuildStatusEnum: %s", s)
	}
}
