// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type CatalogGetProductsRequest struct {
	GetProductsRequest shared.GetProductsRequest `request:"mediaType=application/json"`
	// Your store identifier
	StoreID string `pathParam:"style=simple,explode=false,name=storeId"`
}

type CatalogGetProductsResponse struct {
	// StoreId not found
	BeezUPCommonErrorResponseMessage *shared.BeezUPCommonErrorResponseMessage
	ContentType                      string
	StatusCode                       int
	RawResponse                      *http.Response
	// Product list
	ProductList *shared.ProductList
}
