from .comparefaces import *
from .createcollection import *
from .createproject import *
from .createprojectversion import *
from .createstreamprocessor import *
from .deletecollection import *
from .deletefaces import *
from .deleteproject import *
from .deleteprojectversion import *
from .deletestreamprocessor import *
from .describecollection import *
from .describeprojects import *
from .describeprojectversions import *
from .describestreamprocessor import *
from .detectcustomlabels import *
from .detectfaces import *
from .detectlabels import *
from .detectmoderationlabels import *
from .detectprotectiveequipment import *
from .detecttext import *
from .getcelebrityinfo import *
from .getcelebrityrecognition import *
from .getcontentmoderation import *
from .getfacedetection import *
from .getfacesearch import *
from .getlabeldetection import *
from .getpersontracking import *
from .getsegmentdetection import *
from .gettextdetection import *
from .indexfaces import *
from .listcollections import *
from .listfaces import *
from .liststreamprocessors import *
from .listtagsforresource import *
from .recognizecelebrities import *
from .searchfaces import *
from .searchfacesbyimage import *
from .startcelebrityrecognition import *
from .startcontentmoderation import *
from .startfacedetection import *
from .startfacesearch import *
from .startlabeldetection import *
from .startpersontracking import *
from .startprojectversion import *
from .startsegmentdetection import *
from .startstreamprocessor import *
from .starttextdetection import *
from .stopprojectversion import *
from .stopstreamprocessor import *
from .tagresource import *
from .untagresource import *

__all__ = ["CompareFacesXAmzTargetEnum","CompareFacesHeaders","CompareFacesRequest","CompareFacesResponse","CreateCollectionXAmzTargetEnum","CreateCollectionHeaders","CreateCollectionRequest","CreateCollectionResponse","CreateProjectXAmzTargetEnum","CreateProjectHeaders","CreateProjectRequest","CreateProjectResponse","CreateProjectVersionXAmzTargetEnum","CreateProjectVersionHeaders","CreateProjectVersionRequest","CreateProjectVersionResponse","CreateStreamProcessorXAmzTargetEnum","CreateStreamProcessorHeaders","CreateStreamProcessorRequest","CreateStreamProcessorResponse","DeleteCollectionXAmzTargetEnum","DeleteCollectionHeaders","DeleteCollectionRequest","DeleteCollectionResponse","DeleteFacesXAmzTargetEnum","DeleteFacesHeaders","DeleteFacesRequest","DeleteFacesResponse","DeleteProjectXAmzTargetEnum","DeleteProjectHeaders","DeleteProjectRequest","DeleteProjectResponse","DeleteProjectVersionXAmzTargetEnum","DeleteProjectVersionHeaders","DeleteProjectVersionRequest","DeleteProjectVersionResponse","DeleteStreamProcessorXAmzTargetEnum","DeleteStreamProcessorHeaders","DeleteStreamProcessorRequest","DeleteStreamProcessorResponse","DescribeCollectionXAmzTargetEnum","DescribeCollectionHeaders","DescribeCollectionRequest","DescribeCollectionResponse","DescribeProjectsQueryParams","DescribeProjectsXAmzTargetEnum","DescribeProjectsHeaders","DescribeProjectsRequest","DescribeProjectsResponse","DescribeProjectVersionsQueryParams","DescribeProjectVersionsXAmzTargetEnum","DescribeProjectVersionsHeaders","DescribeProjectVersionsRequest","DescribeProjectVersionsResponse","DescribeStreamProcessorXAmzTargetEnum","DescribeStreamProcessorHeaders","DescribeStreamProcessorRequest","DescribeStreamProcessorResponse","DetectCustomLabelsXAmzTargetEnum","DetectCustomLabelsHeaders","DetectCustomLabelsRequest","DetectCustomLabelsResponse","DetectFacesXAmzTargetEnum","DetectFacesHeaders","DetectFacesRequest","DetectFacesResponse","DetectLabelsXAmzTargetEnum","DetectLabelsHeaders","DetectLabelsRequest","DetectLabelsResponse","DetectModerationLabelsXAmzTargetEnum","DetectModerationLabelsHeaders","DetectModerationLabelsRequest","DetectModerationLabelsResponse","DetectProtectiveEquipmentXAmzTargetEnum","DetectProtectiveEquipmentHeaders","DetectProtectiveEquipmentRequest","DetectProtectiveEquipmentResponse","DetectTextXAmzTargetEnum","DetectTextHeaders","DetectTextRequest","DetectTextResponse","GetCelebrityInfoXAmzTargetEnum","GetCelebrityInfoHeaders","GetCelebrityInfoRequest","GetCelebrityInfoResponse","GetCelebrityRecognitionQueryParams","GetCelebrityRecognitionXAmzTargetEnum","GetCelebrityRecognitionHeaders","GetCelebrityRecognitionRequest","GetCelebrityRecognitionResponse","GetContentModerationQueryParams","GetContentModerationXAmzTargetEnum","GetContentModerationHeaders","GetContentModerationRequest","GetContentModerationResponse","GetFaceDetectionQueryParams","GetFaceDetectionXAmzTargetEnum","GetFaceDetectionHeaders","GetFaceDetectionRequest","GetFaceDetectionResponse","GetFaceSearchQueryParams","GetFaceSearchXAmzTargetEnum","GetFaceSearchHeaders","GetFaceSearchRequest","GetFaceSearchResponse","GetLabelDetectionQueryParams","GetLabelDetectionXAmzTargetEnum","GetLabelDetectionHeaders","GetLabelDetectionRequest","GetLabelDetectionResponse","GetPersonTrackingQueryParams","GetPersonTrackingXAmzTargetEnum","GetPersonTrackingHeaders","GetPersonTrackingRequest","GetPersonTrackingResponse","GetSegmentDetectionQueryParams","GetSegmentDetectionXAmzTargetEnum","GetSegmentDetectionHeaders","GetSegmentDetectionRequest","GetSegmentDetectionResponse","GetTextDetectionQueryParams","GetTextDetectionXAmzTargetEnum","GetTextDetectionHeaders","GetTextDetectionRequest","GetTextDetectionResponse","IndexFacesXAmzTargetEnum","IndexFacesHeaders","IndexFacesRequest","IndexFacesResponse","ListCollectionsQueryParams","ListCollectionsXAmzTargetEnum","ListCollectionsHeaders","ListCollectionsRequest","ListCollectionsResponse","ListFacesQueryParams","ListFacesXAmzTargetEnum","ListFacesHeaders","ListFacesRequest","ListFacesResponse","ListStreamProcessorsQueryParams","ListStreamProcessorsXAmzTargetEnum","ListStreamProcessorsHeaders","ListStreamProcessorsRequest","ListStreamProcessorsResponse","ListTagsForResourceXAmzTargetEnum","ListTagsForResourceHeaders","ListTagsForResourceRequest","ListTagsForResourceResponse","RecognizeCelebritiesXAmzTargetEnum","RecognizeCelebritiesHeaders","RecognizeCelebritiesRequest","RecognizeCelebritiesResponse","SearchFacesXAmzTargetEnum","SearchFacesHeaders","SearchFacesRequest","SearchFacesResponse","SearchFacesByImageXAmzTargetEnum","SearchFacesByImageHeaders","SearchFacesByImageRequest","SearchFacesByImageResponse","StartCelebrityRecognitionXAmzTargetEnum","StartCelebrityRecognitionHeaders","StartCelebrityRecognitionRequest","StartCelebrityRecognitionResponse","StartContentModerationXAmzTargetEnum","StartContentModerationHeaders","StartContentModerationRequest","StartContentModerationResponse","StartFaceDetectionXAmzTargetEnum","StartFaceDetectionHeaders","StartFaceDetectionRequest","StartFaceDetectionResponse","StartFaceSearchXAmzTargetEnum","StartFaceSearchHeaders","StartFaceSearchRequest","StartFaceSearchResponse","StartLabelDetectionXAmzTargetEnum","StartLabelDetectionHeaders","StartLabelDetectionRequest","StartLabelDetectionResponse","StartPersonTrackingXAmzTargetEnum","StartPersonTrackingHeaders","StartPersonTrackingRequest","StartPersonTrackingResponse","StartProjectVersionXAmzTargetEnum","StartProjectVersionHeaders","StartProjectVersionRequest","StartProjectVersionResponse","StartSegmentDetectionXAmzTargetEnum","StartSegmentDetectionHeaders","StartSegmentDetectionRequest","StartSegmentDetectionResponse","StartStreamProcessorXAmzTargetEnum","StartStreamProcessorHeaders","StartStreamProcessorRequest","StartStreamProcessorResponse","StartTextDetectionXAmzTargetEnum","StartTextDetectionHeaders","StartTextDetectionRequest","StartTextDetectionResponse","StopProjectVersionXAmzTargetEnum","StopProjectVersionHeaders","StopProjectVersionRequest","StopProjectVersionResponse","StopStreamProcessorXAmzTargetEnum","StopStreamProcessorHeaders","StopStreamProcessorRequest","StopStreamProcessorResponse","TagResourceXAmzTargetEnum","TagResourceHeaders","TagResourceRequest","TagResourceResponse","UntagResourceXAmzTargetEnum","UntagResourceHeaders","UntagResourceRequest","UntagResourceResponse"]