// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type UpdateAPIKeySecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

type UpdateAPIKeyRequest struct {
	APIKey *shared.APIKey `request:"mediaType=application/json"`
	// the api key id
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
	// The api key service id
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

type UpdateAPIKeyResponse struct {
	// Successful operation
	APIKey      *shared.APIKey
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
