package openapisdk.models.shared;


public enum AggregationCrossSeriesReducerEnum {
    REDUCE_NONE("REDUCE_NONE"),
    REDUCE_MEAN("REDUCE_MEAN"),
    REDUCE_MIN("REDUCE_MIN"),
    REDUCE_MAX("REDUCE_MAX"),
    REDUCE_SUM("REDUCE_SUM"),
    REDUCE_STDDEV("REDUCE_STDDEV"),
    REDUCE_COUNT("REDUCE_COUNT"),
    REDUCE_COUNT_TRUE("REDUCE_COUNT_TRUE"),
    REDUCE_COUNT_FALSE("REDUCE_COUNT_FALSE"),
    REDUCE_FRACTION_TRUE("REDUCE_FRACTION_TRUE"),
    REDUCE_PERCENTILE99("REDUCE_PERCENTILE_99"),
    REDUCE_PERCENTILE95("REDUCE_PERCENTILE_95"),
    REDUCE_PERCENTILE50("REDUCE_PERCENTILE_50"),
    REDUCE_PERCENTILE05("REDUCE_PERCENTILE_05");

    public final String value;

    private AggregationCrossSeriesReducerEnum(String value) {
        this.value = value;
    }
}
