/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PutDataCatalogEncryptionSettingsRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("CatalogId")
    public String catalogId;
    public PutDataCatalogEncryptionSettingsRequest withCatalogId(String catalogId) {
        this.catalogId = catalogId;
        return this;
    }
    
    @JsonProperty("DataCatalogEncryptionSettings")
    public DataCatalogEncryptionSettings dataCatalogEncryptionSettings;
    public PutDataCatalogEncryptionSettingsRequest withDataCatalogEncryptionSettings(DataCatalogEncryptionSettings dataCatalogEncryptionSettings) {
        this.dataCatalogEncryptionSettings = dataCatalogEncryptionSettings;
        return this;
    }
    
}
