/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TransformSortColumnTypeEnum {
    NAME("NAME"),
    TRANSFORM_TYPE("TRANSFORM_TYPE"),
    STATUS("STATUS"),
    CREATED("CREATED"),
    LAST_MODIFIED("LAST_MODIFIED");

    @JsonValue
    public final String value;

    private TransformSortColumnTypeEnum(String value) {
        this.value = value;
    }
}
