from .acceptancetype_enum import *
from .acceptmatchinput import *
from .alias import *
from .attributevalue import *
from .awscredentials import *
from .backfillmode_enum import *
from .balancingstrategy_enum import *
from .build import *
from .buildstatus_enum import *
from .certificateconfiguration import *
from .certificatetype_enum import *
from .claimgameserverinput import *
from .claimgameserveroutput import *
from .comparisonoperatortype_enum import *
from .createaliasinput import *
from .createaliasoutput import *
from .createbuildinput import *
from .createbuildoutput import *
from .createfleetinput import *
from .createfleetlocationsinput import *
from .createfleetlocationsoutput import *
from .createfleetoutput import *
from .creategameservergroupinput import *
from .creategameservergroupoutput import *
from .creategamesessioninput import *
from .creategamesessionoutput import *
from .creategamesessionqueueinput import *
from .creategamesessionqueueoutput import *
from .creatematchmakingconfigurationinput import *
from .creatematchmakingconfigurationoutput import *
from .creatematchmakingrulesetinput import *
from .creatematchmakingrulesetoutput import *
from .createplayersessioninput import *
from .createplayersessionoutput import *
from .createplayersessionsinput import *
from .createplayersessionsoutput import *
from .createscriptinput import *
from .createscriptoutput import *
from .createvpcpeeringauthorizationinput import *
from .createvpcpeeringauthorizationoutput import *
from .createvpcpeeringconnectioninput import *
from .deletealiasinput import *
from .deletebuildinput import *
from .deletefleetinput import *
from .deletefleetlocationsinput import *
from .deletefleetlocationsoutput import *
from .deletegameservergroupinput import *
from .deletegameservergroupoutput import *
from .deletegamesessionqueueinput import *
from .deletematchmakingconfigurationinput import *
from .deletematchmakingrulesetinput import *
from .deletescalingpolicyinput import *
from .deletescriptinput import *
from .deletevpcpeeringauthorizationinput import *
from .deletevpcpeeringconnectioninput import *
from .deregistergameserverinput import *
from .describealiasinput import *
from .describealiasoutput import *
from .describebuildinput import *
from .describebuildoutput import *
from .describeec2instancelimitsinput import *
from .describeec2instancelimitsoutput import *
from .describefleetattributesinput import *
from .describefleetattributesoutput import *
from .describefleetcapacityinput import *
from .describefleetcapacityoutput import *
from .describefleeteventsinput import *
from .describefleeteventsoutput import *
from .describefleetlocationattributesinput import *
from .describefleetlocationattributesoutput import *
from .describefleetlocationcapacityinput import *
from .describefleetlocationcapacityoutput import *
from .describefleetlocationutilizationinput import *
from .describefleetlocationutilizationoutput import *
from .describefleetportsettingsinput import *
from .describefleetportsettingsoutput import *
from .describefleetutilizationinput import *
from .describefleetutilizationoutput import *
from .describegameservergroupinput import *
from .describegameservergroupoutput import *
from .describegameserverinput import *
from .describegameserverinstancesinput import *
from .describegameserverinstancesoutput import *
from .describegameserveroutput import *
from .describegamesessiondetailsinput import *
from .describegamesessiondetailsoutput import *
from .describegamesessionplacementinput import *
from .describegamesessionplacementoutput import *
from .describegamesessionqueuesinput import *
from .describegamesessionqueuesoutput import *
from .describegamesessionsinput import *
from .describegamesessionsoutput import *
from .describeinstancesinput import *
from .describeinstancesoutput import *
from .describematchmakingconfigurationsinput import *
from .describematchmakingconfigurationsoutput import *
from .describematchmakinginput import *
from .describematchmakingoutput import *
from .describematchmakingrulesetsinput import *
from .describematchmakingrulesetsoutput import *
from .describeplayersessionsinput import *
from .describeplayersessionsoutput import *
from .describeruntimeconfigurationinput import *
from .describeruntimeconfigurationoutput import *
from .describescalingpoliciesinput import *
from .describescalingpoliciesoutput import *
from .describescriptinput import *
from .describescriptoutput import *
from .describevpcpeeringauthorizationsoutput import *
from .describevpcpeeringconnectionsinput import *
from .describevpcpeeringconnectionsoutput import *
from .desiredplayersession import *
from .ec2instancecounts import *
from .ec2instancelimit import *
from .ec2instancetype_enum import *
from .event import *
from .eventcode_enum import *
from .filterconfiguration import *
from .fleetaction_enum import *
from .fleetattributes import *
from .fleetcapacity import *
from .fleetstatus_enum import *
from .fleettype_enum import *
from .fleetutilization import *
from .flexmatchmode_enum import *
from .gameproperty import *
from .gameserver import *
from .gameserverclaimstatus_enum import *
from .gameservergroup import *
from .gameservergroupaction_enum import *
from .gameservergroupautoscalingpolicy import *
from .gameservergroupdeleteoption_enum import *
from .gameservergroupinstancetype_enum import *
from .gameservergroupstatus_enum import *
from .gameserverhealthcheck_enum import *
from .gameserverinstance import *
from .gameserverinstancestatus_enum import *
from .gameserverprotectionpolicy_enum import *
from .gameserverutilizationstatus_enum import *
from .gamesession import *
from .gamesessionconnectioninfo import *
from .gamesessiondetail import *
from .gamesessionplacement import *
from .gamesessionplacementstate_enum import *
from .gamesessionqueue import *
from .gamesessionqueuedestination import *
from .gamesessionstatus_enum import *
from .gamesessionstatusreason_enum import *
from .getgamesessionlogurlinput import *
from .getgamesessionlogurloutput import *
from .getinstanceaccessinput import *
from .getinstanceaccessoutput import *
from .instance import *
from .instanceaccess import *
from .instancecredentials import *
from .instancedefinition import *
from .instancestatus_enum import *
from .ippermission import *
from .ipprotocol_enum import *
from .launchtemplatespecification import *
from .listaliasesinput import *
from .listaliasesoutput import *
from .listbuildsinput import *
from .listbuildsoutput import *
from .listfleetsinput import *
from .listfleetsoutput import *
from .listgameservergroupsinput import *
from .listgameservergroupsoutput import *
from .listgameserversinput import *
from .listgameserversoutput import *
from .listscriptsinput import *
from .listscriptsoutput import *
from .listtagsforresourcerequest import *
from .listtagsforresourceresponse import *
from .locationattributes import *
from .locationconfiguration import *
from .locationstate import *
from .locationupdatestatus_enum import *
from .matchedplayersession import *
from .matchmakingconfiguration import *
from .matchmakingconfigurationstatus_enum import *
from .matchmakingruleset import *
from .matchmakingticket import *
from .metricname_enum import *
from .operatingsystem_enum import *
from .placedplayersession import *
from .player import *
from .playerlatency import *
from .playerlatencypolicy import *
from .playersession import *
from .playersessioncreationpolicy_enum import *
from .playersessionstatus_enum import *
from .policytype_enum import *
from .priorityconfiguration import *
from .prioritytype_enum import *
from .protectionpolicy_enum import *
from .putscalingpolicyinput import *
from .putscalingpolicyoutput import *
from .registergameserverinput import *
from .registergameserveroutput import *
from .requestuploadcredentialsinput import *
from .requestuploadcredentialsoutput import *
from .resolvealiasinput import *
from .resolvealiasoutput import *
from .resourcecreationlimitpolicy import *
from .resumegameservergroupinput import *
from .resumegameservergroupoutput import *
from .routingstrategy import *
from .routingstrategytype_enum import *
from .runtimeconfiguration import *
from .s3location import *
from .scalingadjustmenttype_enum import *
from .scalingpolicy import *
from .scalingstatustype_enum import *
from .script import *
from .searchgamesessionsinput import *
from .searchgamesessionsoutput import *
from .security import *
from .serverprocess import *
from .sortorder_enum import *
from .startfleetactionsinput import *
from .startfleetactionsoutput import *
from .startgamesessionplacementinput import *
from .startgamesessionplacementoutput import *
from .startmatchbackfillinput import *
from .startmatchbackfilloutput import *
from .startmatchmakinginput import *
from .startmatchmakingoutput import *
from .stopfleetactionsinput import *
from .stopfleetactionsoutput import *
from .stopgamesessionplacementinput import *
from .stopgamesessionplacementoutput import *
from .stopmatchmakinginput import *
from .suspendgameservergroupinput import *
from .suspendgameservergroupoutput import *
from .tag import *
from .tagresourcerequest import *
from .targetconfiguration import *
from .targettrackingconfiguration import *
from .untagresourcerequest import *
from .updatealiasinput import *
from .updatealiasoutput import *
from .updatebuildinput import *
from .updatebuildoutput import *
from .updatefleetattributesinput import *
from .updatefleetattributesoutput import *
from .updatefleetcapacityinput import *
from .updatefleetcapacityoutput import *
from .updatefleetportsettingsinput import *
from .updatefleetportsettingsoutput import *
from .updategameservergroupinput import *
from .updategameservergroupoutput import *
from .updategameserverinput import *
from .updategameserveroutput import *
from .updategamesessioninput import *
from .updategamesessionoutput import *
from .updategamesessionqueueinput import *
from .updategamesessionqueueoutput import *
from .updatematchmakingconfigurationinput import *
from .updatematchmakingconfigurationoutput import *
from .updateruntimeconfigurationinput import *
from .updateruntimeconfigurationoutput import *
from .updatescriptinput import *
from .updatescriptoutput import *
from .validatematchmakingrulesetinput import *
from .validatematchmakingrulesetoutput import *
from .vpcpeeringauthorization import *
from .vpcpeeringconnection import *
from .vpcpeeringconnectionstatus import *

__all__ = ["AcceptanceTypeEnum","AcceptMatchInput","Alias","AttributeValue","AwsCredentials","BackfillModeEnum","BalancingStrategyEnum","Build","BuildStatusEnum","CertificateConfiguration","CertificateTypeEnum","ClaimGameServerInput","ClaimGameServerOutput","ComparisonOperatorTypeEnum","CreateAliasInput","CreateAliasOutput","CreateBuildInput","CreateBuildOutput","CreateFleetInput","CreateFleetLocationsInput","CreateFleetLocationsOutput","CreateFleetOutput","CreateGameServerGroupInput","CreateGameServerGroupOutput","CreateGameSessionInput","CreateGameSessionOutput","CreateGameSessionQueueInput","CreateGameSessionQueueOutput","CreateMatchmakingConfigurationInput","CreateMatchmakingConfigurationOutput","CreateMatchmakingRuleSetInput","CreateMatchmakingRuleSetOutput","CreatePlayerSessionInput","CreatePlayerSessionOutput","CreatePlayerSessionsInput","CreatePlayerSessionsOutput","CreateScriptInput","CreateScriptOutput","CreateVpcPeeringAuthorizationInput","CreateVpcPeeringAuthorizationOutput","CreateVpcPeeringConnectionInput","DeleteAliasInput","DeleteBuildInput","DeleteFleetInput","DeleteFleetLocationsInput","DeleteFleetLocationsOutput","DeleteGameServerGroupInput","DeleteGameServerGroupOutput","DeleteGameSessionQueueInput","DeleteMatchmakingConfigurationInput","DeleteMatchmakingRuleSetInput","DeleteScalingPolicyInput","DeleteScriptInput","DeleteVpcPeeringAuthorizationInput","DeleteVpcPeeringConnectionInput","DeregisterGameServerInput","DescribeAliasInput","DescribeAliasOutput","DescribeBuildInput","DescribeBuildOutput","DescribeEc2InstanceLimitsInput","DescribeEc2InstanceLimitsOutput","DescribeFleetAttributesInput","DescribeFleetAttributesOutput","DescribeFleetCapacityInput","DescribeFleetCapacityOutput","DescribeFleetEventsInput","DescribeFleetEventsOutput","DescribeFleetLocationAttributesInput","DescribeFleetLocationAttributesOutput","DescribeFleetLocationCapacityInput","DescribeFleetLocationCapacityOutput","DescribeFleetLocationUtilizationInput","DescribeFleetLocationUtilizationOutput","DescribeFleetPortSettingsInput","DescribeFleetPortSettingsOutput","DescribeFleetUtilizationInput","DescribeFleetUtilizationOutput","DescribeGameServerGroupInput","DescribeGameServerGroupOutput","DescribeGameServerInput","DescribeGameServerInstancesInput","DescribeGameServerInstancesOutput","DescribeGameServerOutput","DescribeGameSessionDetailsInput","DescribeGameSessionDetailsOutput","DescribeGameSessionPlacementInput","DescribeGameSessionPlacementOutput","DescribeGameSessionQueuesInput","DescribeGameSessionQueuesOutput","DescribeGameSessionsInput","DescribeGameSessionsOutput","DescribeInstancesInput","DescribeInstancesOutput","DescribeMatchmakingConfigurationsInput","DescribeMatchmakingConfigurationsOutput","DescribeMatchmakingInput","DescribeMatchmakingOutput","DescribeMatchmakingRuleSetsInput","DescribeMatchmakingRuleSetsOutput","DescribePlayerSessionsInput","DescribePlayerSessionsOutput","DescribeRuntimeConfigurationInput","DescribeRuntimeConfigurationOutput","DescribeScalingPoliciesInput","DescribeScalingPoliciesOutput","DescribeScriptInput","DescribeScriptOutput","DescribeVpcPeeringAuthorizationsOutput","DescribeVpcPeeringConnectionsInput","DescribeVpcPeeringConnectionsOutput","DesiredPlayerSession","Ec2InstanceCounts","Ec2InstanceLimit","Ec2InstanceTypeEnum","Event","EventCodeEnum","FilterConfiguration","FleetActionEnum","FleetAttributes","FleetCapacity","FleetStatusEnum","FleetTypeEnum","FleetUtilization","FlexMatchModeEnum","GameProperty","GameServer","GameServerClaimStatusEnum","GameServerGroup","GameServerGroupActionEnum","GameServerGroupAutoScalingPolicy","GameServerGroupDeleteOptionEnum","GameServerGroupInstanceTypeEnum","GameServerGroupStatusEnum","GameServerHealthCheckEnum","GameServerInstance","GameServerInstanceStatusEnum","GameServerProtectionPolicyEnum","GameServerUtilizationStatusEnum","GameSession","GameSessionConnectionInfo","GameSessionDetail","GameSessionPlacement","GameSessionPlacementStateEnum","GameSessionQueue","GameSessionQueueDestination","GameSessionStatusEnum","GameSessionStatusReasonEnum","GetGameSessionLogURLInput","GetGameSessionLogURLOutput","GetInstanceAccessInput","GetInstanceAccessOutput","Instance","InstanceAccess","InstanceCredentials","InstanceDefinition","InstanceStatusEnum","IPPermission","IPProtocolEnum","LaunchTemplateSpecification","ListAliasesInput","ListAliasesOutput","ListBuildsInput","ListBuildsOutput","ListFleetsInput","ListFleetsOutput","ListGameServerGroupsInput","ListGameServerGroupsOutput","ListGameServersInput","ListGameServersOutput","ListScriptsInput","ListScriptsOutput","ListTagsForResourceRequest","ListTagsForResourceResponse","LocationAttributes","LocationConfiguration","LocationState","LocationUpdateStatusEnum","MatchedPlayerSession","MatchmakingConfiguration","MatchmakingConfigurationStatusEnum","MatchmakingRuleSet","MatchmakingTicket","MetricNameEnum","OperatingSystemEnum","PlacedPlayerSession","Player","PlayerLatency","PlayerLatencyPolicy","PlayerSession","PlayerSessionCreationPolicyEnum","PlayerSessionStatusEnum","PolicyTypeEnum","PriorityConfiguration","PriorityTypeEnum","ProtectionPolicyEnum","PutScalingPolicyInput","PutScalingPolicyOutput","RegisterGameServerInput","RegisterGameServerOutput","RequestUploadCredentialsInput","RequestUploadCredentialsOutput","ResolveAliasInput","ResolveAliasOutput","ResourceCreationLimitPolicy","ResumeGameServerGroupInput","ResumeGameServerGroupOutput","RoutingStrategy","RoutingStrategyTypeEnum","RuntimeConfiguration","S3Location","ScalingAdjustmentTypeEnum","ScalingPolicy","ScalingStatusTypeEnum","Script","SearchGameSessionsInput","SearchGameSessionsOutput","SchemeHmac","Security","ServerProcess","SortOrderEnum","StartFleetActionsInput","StartFleetActionsOutput","StartGameSessionPlacementInput","StartGameSessionPlacementOutput","StartMatchBackfillInput","StartMatchBackfillOutput","StartMatchmakingInput","StartMatchmakingOutput","StopFleetActionsInput","StopFleetActionsOutput","StopGameSessionPlacementInput","StopGameSessionPlacementOutput","StopMatchmakingInput","SuspendGameServerGroupInput","SuspendGameServerGroupOutput","Tag","TagResourceRequest","TargetConfiguration","TargetTrackingConfiguration","UntagResourceRequest","UpdateAliasInput","UpdateAliasOutput","UpdateBuildInput","UpdateBuildOutput","UpdateFleetAttributesInput","UpdateFleetAttributesOutput","UpdateFleetCapacityInput","UpdateFleetCapacityOutput","UpdateFleetPortSettingsInput","UpdateFleetPortSettingsOutput","UpdateGameServerGroupInput","UpdateGameServerGroupOutput","UpdateGameServerInput","UpdateGameServerOutput","UpdateGameSessionInput","UpdateGameSessionOutput","UpdateGameSessionQueueInput","UpdateGameSessionQueueOutput","UpdateMatchmakingConfigurationInput","UpdateMatchmakingConfigurationOutput","UpdateRuntimeConfigurationInput","UpdateRuntimeConfigurationOutput","UpdateScriptInput","UpdateScriptOutput","ValidateMatchmakingRuleSetInput","ValidateMatchmakingRuleSetOutput","VpcPeeringAuthorization","VpcPeeringConnection","VpcPeeringConnectionStatus"]