/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ProjectStatusResponseColorEnum - The color associated with the status update.
 */
public enum ProjectStatusResponseColorEnum {
    GREEN("green"),
    YELLOW("yellow"),
    RED("red"),
    BLUE("blue");

    @JsonValue
    public final String value;

    private ProjectStatusResponseColorEnum(String value) {
        this.value = value;
    }
}
