/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WorkspaceAddUserRequest - A user identification object for specification with the addUser/removeUser endpoints.
 */
public class WorkspaceAddUserRequest {
    /**
     * A string identifying a user. This can either be the string "me", an email, or the gid of a user.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public String user;
    public WorkspaceAddUserRequest withUser(String user) {
        this.user = user;
        return this;
    }
    
}
