/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GooglePrivacyDlpV2DateTime } from "./googleprivacydlpv2datetime";
import { Expose, Type } from "class-transformer";

/**
 * Message for infoType-dependent details parsed from quote.
 */
export class GooglePrivacyDlpV2QuoteInfo extends SpeakeasyBase {
  /**
   * Message for a date time object. e.g. 2018-01-01, 5th August.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "dateTime" })
  @Type(() => GooglePrivacyDlpV2DateTime)
  dateTime?: GooglePrivacyDlpV2DateTime;
}
