/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListPaymentsRequest extends SpeakeasyBase {
  /**
   * Number of results to return per page.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
  limit?: number;

  /**
   * The initial index from which to return the results.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=offset",
  })
  offset?: number;
}

export class ListPaymentsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * List payments
   */
  @SpeakeasyMetadata()
  paginatedPaymentReadList?: shared.PaginatedPaymentReadList;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Unknown Fields
   */
  @SpeakeasyMetadata()
  listPayments400ApplicationJSONObject?: Record<string, any>;

  /**
   * Invalid token
   */
  @SpeakeasyMetadata()
  listPayments401ApplicationJSONObject?: Record<string, any>;

  /**
   * IP Access denied
   */
  @SpeakeasyMetadata()
  listPayments403ApplicationJSONObject?: Record<string, any>;
}
