// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListPreviewRotationShiftsResult - Success
type ListPreviewRotationShiftsResult struct {
	NextToken      *string         `json:"NextToken,omitempty"`
	RotationShifts []RotationShift `json:"RotationShifts,omitempty"`
}
