from .createdevicepool import *
from .createinstanceprofile import *
from .createnetworkprofile import *
from .createproject import *
from .createremoteaccesssession import *
from .createtestgridproject import *
from .createtestgridurl import *
from .createupload import *
from .createvpceconfiguration import *
from .deletedevicepool import *
from .deleteinstanceprofile import *
from .deletenetworkprofile import *
from .deleteproject import *
from .deleteremoteaccesssession import *
from .deleterun import *
from .deletetestgridproject import *
from .deleteupload import *
from .deletevpceconfiguration import *
from .getaccountsettings import *
from .getdevice import *
from .getdeviceinstance import *
from .getdevicepool import *
from .getdevicepoolcompatibility import *
from .getinstanceprofile import *
from .getjob import *
from .getnetworkprofile import *
from .getofferingstatus import *
from .getproject import *
from .getremoteaccesssession import *
from .getrun import *
from .getsuite import *
from .gettest import *
from .gettestgridproject import *
from .gettestgridsession import *
from .getupload import *
from .getvpceconfiguration import *
from .installtoremoteaccesssession import *
from .listartifacts import *
from .listdeviceinstances import *
from .listdevicepools import *
from .listdevices import *
from .listinstanceprofiles import *
from .listjobs import *
from .listnetworkprofiles import *
from .listofferingpromotions import *
from .listofferings import *
from .listofferingtransactions import *
from .listprojects import *
from .listremoteaccesssessions import *
from .listruns import *
from .listsamples import *
from .listsuites import *
from .listtagsforresource import *
from .listtestgridprojects import *
from .listtestgridsessionactions import *
from .listtestgridsessionartifacts import *
from .listtestgridsessions import *
from .listtests import *
from .listuniqueproblems import *
from .listuploads import *
from .listvpceconfigurations import *
from .purchaseoffering import *
from .renewoffering import *
from .schedulerun import *
from .stopjob import *
from .stopremoteaccesssession import *
from .stoprun import *
from .tagresource import *
from .untagresource import *
from .updatedeviceinstance import *
from .updatedevicepool import *
from .updateinstanceprofile import *
from .updatenetworkprofile import *
from .updateproject import *
from .updatetestgridproject import *
from .updateupload import *
from .updatevpceconfiguration import *

__all__ = ["CreateDevicePoolXAmzTargetEnum","CreateDevicePoolHeaders","CreateDevicePoolRequest","CreateDevicePoolResponse","CreateInstanceProfileXAmzTargetEnum","CreateInstanceProfileHeaders","CreateInstanceProfileRequest","CreateInstanceProfileResponse","CreateNetworkProfileXAmzTargetEnum","CreateNetworkProfileHeaders","CreateNetworkProfileRequest","CreateNetworkProfileResponse","CreateProjectXAmzTargetEnum","CreateProjectHeaders","CreateProjectRequest","CreateProjectResponse","CreateRemoteAccessSessionXAmzTargetEnum","CreateRemoteAccessSessionHeaders","CreateRemoteAccessSessionRequest","CreateRemoteAccessSessionResponse","CreateTestGridProjectXAmzTargetEnum","CreateTestGridProjectHeaders","CreateTestGridProjectRequest","CreateTestGridProjectResponse","CreateTestGridURLXAmzTargetEnum","CreateTestGridURLHeaders","CreateTestGridURLRequest","CreateTestGridURLResponse","CreateUploadXAmzTargetEnum","CreateUploadHeaders","CreateUploadRequest","CreateUploadResponse","CreateVpceConfigurationXAmzTargetEnum","CreateVpceConfigurationHeaders","CreateVpceConfigurationRequest","CreateVpceConfigurationResponse","DeleteDevicePoolXAmzTargetEnum","DeleteDevicePoolHeaders","DeleteDevicePoolRequest","DeleteDevicePoolResponse","DeleteInstanceProfileXAmzTargetEnum","DeleteInstanceProfileHeaders","DeleteInstanceProfileRequest","DeleteInstanceProfileResponse","DeleteNetworkProfileXAmzTargetEnum","DeleteNetworkProfileHeaders","DeleteNetworkProfileRequest","DeleteNetworkProfileResponse","DeleteProjectXAmzTargetEnum","DeleteProjectHeaders","DeleteProjectRequest","DeleteProjectResponse","DeleteRemoteAccessSessionXAmzTargetEnum","DeleteRemoteAccessSessionHeaders","DeleteRemoteAccessSessionRequest","DeleteRemoteAccessSessionResponse","DeleteRunXAmzTargetEnum","DeleteRunHeaders","DeleteRunRequest","DeleteRunResponse","DeleteTestGridProjectXAmzTargetEnum","DeleteTestGridProjectHeaders","DeleteTestGridProjectRequest","DeleteTestGridProjectResponse","DeleteUploadXAmzTargetEnum","DeleteUploadHeaders","DeleteUploadRequest","DeleteUploadResponse","DeleteVpceConfigurationXAmzTargetEnum","DeleteVpceConfigurationHeaders","DeleteVpceConfigurationRequest","DeleteVpceConfigurationResponse","GetAccountSettingsXAmzTargetEnum","GetAccountSettingsHeaders","GetAccountSettingsRequest","GetAccountSettingsResponse","GetDeviceXAmzTargetEnum","GetDeviceHeaders","GetDeviceRequest","GetDeviceResponse","GetDeviceInstanceXAmzTargetEnum","GetDeviceInstanceHeaders","GetDeviceInstanceRequest","GetDeviceInstanceResponse","GetDevicePoolXAmzTargetEnum","GetDevicePoolHeaders","GetDevicePoolRequest","GetDevicePoolResponse","GetDevicePoolCompatibilityXAmzTargetEnum","GetDevicePoolCompatibilityHeaders","GetDevicePoolCompatibilityRequest","GetDevicePoolCompatibilityResponse","GetInstanceProfileXAmzTargetEnum","GetInstanceProfileHeaders","GetInstanceProfileRequest","GetInstanceProfileResponse","GetJobXAmzTargetEnum","GetJobHeaders","GetJobRequest","GetJobResponse","GetNetworkProfileXAmzTargetEnum","GetNetworkProfileHeaders","GetNetworkProfileRequest","GetNetworkProfileResponse","GetOfferingStatusQueryParams","GetOfferingStatusXAmzTargetEnum","GetOfferingStatusHeaders","GetOfferingStatusRequest","GetOfferingStatusResponse","GetProjectXAmzTargetEnum","GetProjectHeaders","GetProjectRequest","GetProjectResponse","GetRemoteAccessSessionXAmzTargetEnum","GetRemoteAccessSessionHeaders","GetRemoteAccessSessionRequest","GetRemoteAccessSessionResponse","GetRunXAmzTargetEnum","GetRunHeaders","GetRunRequest","GetRunResponse","GetSuiteXAmzTargetEnum","GetSuiteHeaders","GetSuiteRequest","GetSuiteResponse","GetTestXAmzTargetEnum","GetTestHeaders","GetTestRequest","GetTestResponse","GetTestGridProjectXAmzTargetEnum","GetTestGridProjectHeaders","GetTestGridProjectRequest","GetTestGridProjectResponse","GetTestGridSessionXAmzTargetEnum","GetTestGridSessionHeaders","GetTestGridSessionRequest","GetTestGridSessionResponse","GetUploadXAmzTargetEnum","GetUploadHeaders","GetUploadRequest","GetUploadResponse","GetVpceConfigurationXAmzTargetEnum","GetVpceConfigurationHeaders","GetVpceConfigurationRequest","GetVpceConfigurationResponse","InstallToRemoteAccessSessionXAmzTargetEnum","InstallToRemoteAccessSessionHeaders","InstallToRemoteAccessSessionRequest","InstallToRemoteAccessSessionResponse","ListArtifactsQueryParams","ListArtifactsXAmzTargetEnum","ListArtifactsHeaders","ListArtifactsRequest","ListArtifactsResponse","ListDeviceInstancesXAmzTargetEnum","ListDeviceInstancesHeaders","ListDeviceInstancesRequest","ListDeviceInstancesResponse","ListDevicePoolsQueryParams","ListDevicePoolsXAmzTargetEnum","ListDevicePoolsHeaders","ListDevicePoolsRequest","ListDevicePoolsResponse","ListDevicesQueryParams","ListDevicesXAmzTargetEnum","ListDevicesHeaders","ListDevicesRequest","ListDevicesResponse","ListInstanceProfilesXAmzTargetEnum","ListInstanceProfilesHeaders","ListInstanceProfilesRequest","ListInstanceProfilesResponse","ListJobsQueryParams","ListJobsXAmzTargetEnum","ListJobsHeaders","ListJobsRequest","ListJobsResponse","ListNetworkProfilesXAmzTargetEnum","ListNetworkProfilesHeaders","ListNetworkProfilesRequest","ListNetworkProfilesResponse","ListOfferingPromotionsXAmzTargetEnum","ListOfferingPromotionsHeaders","ListOfferingPromotionsRequest","ListOfferingPromotionsResponse","ListOfferingsQueryParams","ListOfferingsXAmzTargetEnum","ListOfferingsHeaders","ListOfferingsRequest","ListOfferingsResponse","ListOfferingTransactionsQueryParams","ListOfferingTransactionsXAmzTargetEnum","ListOfferingTransactionsHeaders","ListOfferingTransactionsRequest","ListOfferingTransactionsResponse","ListProjectsQueryParams","ListProjectsXAmzTargetEnum","ListProjectsHeaders","ListProjectsRequest","ListProjectsResponse","ListRemoteAccessSessionsXAmzTargetEnum","ListRemoteAccessSessionsHeaders","ListRemoteAccessSessionsRequest","ListRemoteAccessSessionsResponse","ListRunsQueryParams","ListRunsXAmzTargetEnum","ListRunsHeaders","ListRunsRequest","ListRunsResponse","ListSamplesQueryParams","ListSamplesXAmzTargetEnum","ListSamplesHeaders","ListSamplesRequest","ListSamplesResponse","ListSuitesQueryParams","ListSuitesXAmzTargetEnum","ListSuitesHeaders","ListSuitesRequest","ListSuitesResponse","ListTagsForResourceXAmzTargetEnum","ListTagsForResourceHeaders","ListTagsForResourceRequest","ListTagsForResourceResponse","ListTestGridProjectsQueryParams","ListTestGridProjectsXAmzTargetEnum","ListTestGridProjectsHeaders","ListTestGridProjectsRequest","ListTestGridProjectsResponse","ListTestGridSessionActionsQueryParams","ListTestGridSessionActionsXAmzTargetEnum","ListTestGridSessionActionsHeaders","ListTestGridSessionActionsRequest","ListTestGridSessionActionsResponse","ListTestGridSessionArtifactsQueryParams","ListTestGridSessionArtifactsXAmzTargetEnum","ListTestGridSessionArtifactsHeaders","ListTestGridSessionArtifactsRequest","ListTestGridSessionArtifactsResponse","ListTestGridSessionsQueryParams","ListTestGridSessionsXAmzTargetEnum","ListTestGridSessionsHeaders","ListTestGridSessionsRequest","ListTestGridSessionsResponse","ListTestsQueryParams","ListTestsXAmzTargetEnum","ListTestsHeaders","ListTestsRequest","ListTestsResponse","ListUniqueProblemsQueryParams","ListUniqueProblemsXAmzTargetEnum","ListUniqueProblemsHeaders","ListUniqueProblemsRequest","ListUniqueProblemsResponse","ListUploadsQueryParams","ListUploadsXAmzTargetEnum","ListUploadsHeaders","ListUploadsRequest","ListUploadsResponse","ListVpceConfigurationsXAmzTargetEnum","ListVpceConfigurationsHeaders","ListVpceConfigurationsRequest","ListVpceConfigurationsResponse","PurchaseOfferingXAmzTargetEnum","PurchaseOfferingHeaders","PurchaseOfferingRequest","PurchaseOfferingResponse","RenewOfferingXAmzTargetEnum","RenewOfferingHeaders","RenewOfferingRequest","RenewOfferingResponse","ScheduleRunXAmzTargetEnum","ScheduleRunHeaders","ScheduleRunRequest","ScheduleRunResponse","StopJobXAmzTargetEnum","StopJobHeaders","StopJobRequest","StopJobResponse","StopRemoteAccessSessionXAmzTargetEnum","StopRemoteAccessSessionHeaders","StopRemoteAccessSessionRequest","StopRemoteAccessSessionResponse","StopRunXAmzTargetEnum","StopRunHeaders","StopRunRequest","StopRunResponse","TagResourceXAmzTargetEnum","TagResourceHeaders","TagResourceRequest","TagResourceResponse","UntagResourceXAmzTargetEnum","UntagResourceHeaders","UntagResourceRequest","UntagResourceResponse","UpdateDeviceInstanceXAmzTargetEnum","UpdateDeviceInstanceHeaders","UpdateDeviceInstanceRequest","UpdateDeviceInstanceResponse","UpdateDevicePoolXAmzTargetEnum","UpdateDevicePoolHeaders","UpdateDevicePoolRequest","UpdateDevicePoolResponse","UpdateInstanceProfileXAmzTargetEnum","UpdateInstanceProfileHeaders","UpdateInstanceProfileRequest","UpdateInstanceProfileResponse","UpdateNetworkProfileXAmzTargetEnum","UpdateNetworkProfileHeaders","UpdateNetworkProfileRequest","UpdateNetworkProfileResponse","UpdateProjectXAmzTargetEnum","UpdateProjectHeaders","UpdateProjectRequest","UpdateProjectResponse","UpdateTestGridProjectXAmzTargetEnum","UpdateTestGridProjectHeaders","UpdateTestGridProjectRequest","UpdateTestGridProjectResponse","UpdateUploadXAmzTargetEnum","UpdateUploadHeaders","UpdateUploadRequest","UpdateUploadResponse","UpdateVpceConfigurationXAmzTargetEnum","UpdateVpceConfigurationHeaders","UpdateVpceConfigurationRequest","UpdateVpceConfigurationResponse"]