/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GoogleCloudDataplexV1EntityInput - Represents tables and fileset metadata contained within a zone.
 */
public class GoogleCloudDataplexV1EntityInput {
    /**
     * Required. Immutable. The ID of the asset associated with the storage location containing the entity data. The entity must be with in the same zone with the asset.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("asset")
    public String asset;
    public GoogleCloudDataplexV1EntityInput withAsset(String asset) {
        this.asset = asset;
        return this;
    }
    
    /**
     * Required. Immutable. The storage path of the entity data. For Cloud Storage data, this is the fully-qualified path to the entity, such as gs://bucket/path/to/data. For BigQuery data, this is the name of the table resource, such as projects/project_id/datasets/dataset_id/tables/table_id.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dataPath")
    public String dataPath;
    public GoogleCloudDataplexV1EntityInput withDataPath(String dataPath) {
        this.dataPath = dataPath;
        return this;
    }
    
    /**
     * Optional. The set of items within the data path constituting the data in the entity, represented as a glob path. Example: gs://bucket/path/to/data/** /*.csv.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dataPathPattern")
    public String dataPathPattern;
    public GoogleCloudDataplexV1EntityInput withDataPathPattern(String dataPathPattern) {
        this.dataPathPattern = dataPathPattern;
        return this;
    }
    
    /**
     * Optional. User friendly longer description text. Must be shorter than or equal to 1024 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;
    public GoogleCloudDataplexV1EntityInput withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Optional. Display name must be shorter than or equal to 256 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("displayName")
    public String displayName;
    public GoogleCloudDataplexV1EntityInput withDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }
    
    /**
     * Optional. The etag associated with the entity, which can be retrieved with a GetEntity request. Required for update and delete requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("etag")
    public String etag;
    public GoogleCloudDataplexV1EntityInput withEtag(String etag) {
        this.etag = etag;
        return this;
    }
    
    /**
     * Describes the format of the data within its storage location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("format")
    public GoogleCloudDataplexV1StorageFormatInput format;
    public GoogleCloudDataplexV1EntityInput withFormat(GoogleCloudDataplexV1StorageFormatInput format) {
        this.format = format;
        return this;
    }
    
    /**
     * Required. A user-provided entity ID. It is mutable, and will be used as the published table name. Specifying a new ID in an update entity request will override the existing value. The ID must contain only letters (a-z, A-Z), numbers (0-9), and underscores. Must begin with a letter and consist of 256 or fewer characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;
    public GoogleCloudDataplexV1EntityInput withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Schema information describing the structure and layout of the data.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schema")
    public GoogleCloudDataplexV1Schema schema;
    public GoogleCloudDataplexV1EntityInput withSchema(GoogleCloudDataplexV1Schema schema) {
        this.schema = schema;
        return this;
    }
    
    /**
     * Required. Immutable. Identifies the storage system of the entity data.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("system")
    public GoogleCloudDataplexV1EntitySystemEnum system;
    public GoogleCloudDataplexV1EntityInput withSystem(GoogleCloudDataplexV1EntitySystemEnum system) {
        this.system = system;
        return this;
    }
    
    /**
     * Required. Immutable. The type of entity.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public GoogleCloudDataplexV1EntityTypeEnum type;
    public GoogleCloudDataplexV1EntityInput withType(GoogleCloudDataplexV1EntityTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
