package openapisdk.models.operations;


public enum PostOrdersOrderRequestV2IntegratorEnum {
    ONE_SHOPPING_CART("1ShoppingCart"),
    THREED_CART("3dCart"),
    ADOBE_BC("AdobeBC"),
    AMAZON_AU("AmazonAU"),
    AMAZON_EU("AmazonEU"),
    AMAZON_NA("AmazonNA"),
    BIG_COMMERCE("BigCommerce"),
    BRAND_BOOM("BrandBoom"),
    BRIGHT_PEARL("BrightPearl"),
    BUY_GOODS("BuyGoods"),
    CELERY("Celery"),
    CHANNEL_ADVISOR("ChannelAdvisor"),
    CLICKBANK("Clickbank"),
    COMMERCE_HUB("CommerceHub"),
    CUSTOM("Custom"),
    DEMANDWARE("Demandware"),
    EBAY("Ebay"),
    ECWID("Ecwid"),
    ETSY("Etsy"),
    FOXY_CART("FoxyCart"),
    GOODSIE("Goodsie"),
    INFUSIONSOFT("Infusionsoft"),
    KONNEKTIVE("Konnektive"),
    LIME_LIGHT("LimeLight"),
    LINIO("Linio"),
    LINNWORKS("Linnworks"),
    MAGENTO("Magento"),
    NETSUITE("Netsuite"),
    NEW_EGG("NewEgg"),
    NEXTERNAL("Nexternal"),
    NU_ORDER("NuOrder"),
    OPENCART("Opencart"),
    ORDER_WAVE("OrderWave"),
    OS_COMMERCE1("osCommerce1"),
    OVERSTOCK("Overstock"),
    PAY_PAL("PayPal"),
    PRESTA_SHOP("PrestaShop"),
    PRICEFALLS("Pricefalls"),
    QUICKBOOKS("Quickbooks"),
    RAKUTEN("Rakuten"),
    SEARS("Sears"),
    SELLBRITE("Sellbrite"),
    SELLER_CLOUD("SellerCloud"),
    SHIPSTATION("Shipstation"),
    SHOPIFY("Shopify"),
    SKUBANA("Skubana"),
    SOLID_COMMERCE("SolidCommerce"),
    SPARK_PAY("SparkPay"),
    SPREE_COMMERCE("SpreeCommerce"),
    SPS_COMMERCE("spsCommerce"),
    STITCH_LABS("StitchLabs"),
    STONE_EDGE("StoneEdge"),
    TRADE_GECKO("TradeGecko"),
    ULTRA_CART("UltraCart"),
    VOLUSION("Volusion"),
    VTEX("VTEX"),
    WALMART("Walmart"),
    WOO_COMMERCE("WooCommerce"),
    YAHOO("Yahoo");

    public final String value;

    private PostOrdersOrderRequestV2IntegratorEnum(String value) {
        this.value = value;
    }
}
