package openapisdk.models.shared;


public enum StepStateEnum {
    STATE_UNSPECIFIED("STATE_UNSPECIFIED"),
    START_FROM_INSTANCE("START_FROM_INSTANCE"),
    START_FROM_INTERNET("START_FROM_INTERNET"),
    START_FROM_PRIVATE_NETWORK("START_FROM_PRIVATE_NETWORK"),
    START_FROM_GKE_MASTER("START_FROM_GKE_MASTER"),
    START_FROM_CLOUD_SQL_INSTANCE("START_FROM_CLOUD_SQL_INSTANCE"),
    START_FROM_CLOUD_FUNCTION("START_FROM_CLOUD_FUNCTION"),
    START_FROM_APP_ENGINE_VERSION("START_FROM_APP_ENGINE_VERSION"),
    START_FROM_CLOUD_RUN_REVISION("START_FROM_CLOUD_RUN_REVISION"),
    APPLY_INGRESS_FIREWALL_RULE("APPLY_INGRESS_FIREWALL_RULE"),
    APPLY_EGRESS_FIREWALL_RULE("APPLY_EGRESS_FIREWALL_RULE"),
    APPLY_ROUTE("APPLY_ROUTE"),
    APPLY_FORWARDING_RULE("APPLY_FORWARDING_RULE"),
    SPOOFING_APPROVED("SPOOFING_APPROVED"),
    ARRIVE_AT_INSTANCE("ARRIVE_AT_INSTANCE"),
    ARRIVE_AT_INTERNAL_LOAD_BALANCER("ARRIVE_AT_INTERNAL_LOAD_BALANCER"),
    ARRIVE_AT_EXTERNAL_LOAD_BALANCER("ARRIVE_AT_EXTERNAL_LOAD_BALANCER"),
    ARRIVE_AT_VPN_GATEWAY("ARRIVE_AT_VPN_GATEWAY"),
    ARRIVE_AT_VPN_TUNNEL("ARRIVE_AT_VPN_TUNNEL"),
    ARRIVE_AT_VPC_CONNECTOR("ARRIVE_AT_VPC_CONNECTOR"),
    NAT("NAT"),
    PROXY_CONNECTION("PROXY_CONNECTION"),
    DELIVER("DELIVER"),
    DROP("DROP"),
    FORWARD("FORWARD"),
    ABORT("ABORT"),
    VIEWER_PERMISSION_MISSING("VIEWER_PERMISSION_MISSING");

    public final String value;

    private StepStateEnum(String value) {
        this.value = value;
    }
}
