// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddProfileKeyResponse - Success
type AddProfileKeyResponse struct {
	KeyName *string  `json:"KeyName,omitempty"`
	Values  []string `json:"Values,omitempty"`
}
