/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.net.http.HttpResponse;

public class GetRelationalDatabaseParametersResponse {
    /**
     * AccessDeniedException
     */
    
    public Object accessDeniedException;
    public GetRelationalDatabaseParametersResponse withAccessDeniedException(Object accessDeniedException) {
        this.accessDeniedException = accessDeniedException;
        return this;
    }
    
    /**
     * AccountSetupInProgressException
     */
    
    public Object accountSetupInProgressException;
    public GetRelationalDatabaseParametersResponse withAccountSetupInProgressException(Object accountSetupInProgressException) {
        this.accountSetupInProgressException = accountSetupInProgressException;
        return this;
    }
    
    
    public String contentType;
    public GetRelationalDatabaseParametersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Success
     */
    
    public org.openapis.openapi.models.shared.GetRelationalDatabaseParametersResult getRelationalDatabaseParametersResult;
    public GetRelationalDatabaseParametersResponse withGetRelationalDatabaseParametersResult(org.openapis.openapi.models.shared.GetRelationalDatabaseParametersResult getRelationalDatabaseParametersResult) {
        this.getRelationalDatabaseParametersResult = getRelationalDatabaseParametersResult;
        return this;
    }
    
    /**
     * InvalidInputException
     */
    
    public Object invalidInputException;
    public GetRelationalDatabaseParametersResponse withInvalidInputException(Object invalidInputException) {
        this.invalidInputException = invalidInputException;
        return this;
    }
    
    /**
     * NotFoundException
     */
    
    public Object notFoundException;
    public GetRelationalDatabaseParametersResponse withNotFoundException(Object notFoundException) {
        this.notFoundException = notFoundException;
        return this;
    }
    
    /**
     * OperationFailureException
     */
    
    public Object operationFailureException;
    public GetRelationalDatabaseParametersResponse withOperationFailureException(Object operationFailureException) {
        this.operationFailureException = operationFailureException;
        return this;
    }
    
    /**
     * ServiceException
     */
    
    public Object serviceException;
    public GetRelationalDatabaseParametersResponse withServiceException(Object serviceException) {
        this.serviceException = serviceException;
        return this;
    }
    
    
    public Integer statusCode;
    public GetRelationalDatabaseParametersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetRelationalDatabaseParametersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * UnauthenticatedException
     */
    
    public Object unauthenticatedException;
    public GetRelationalDatabaseParametersResponse withUnauthenticatedException(Object unauthenticatedException) {
        this.unauthenticatedException = unauthenticatedException;
        return this;
    }
    
}
