/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ReplaceNamedRangeContentRequest - Replaces the contents of the specified NamedRange or NamedRanges with the given replacement content. Note that an individual NamedRange may consist of multiple discontinuous ranges. In this case, only the content in the first range will be replaced. The other ranges and their content will be deleted. In cases where replacing or deleting any ranges would result in an invalid document structure, a 400 bad request error is returned.
 */
public class ReplaceNamedRangeContentRequest {
    /**
     * The ID of the named range whose content will be replaced. If there is no named range with the given ID a 400 bad request error is returned.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("namedRangeId")
    public String namedRangeId;
    public ReplaceNamedRangeContentRequest withNamedRangeId(String namedRangeId) {
        this.namedRangeId = namedRangeId;
        return this;
    }
    
    /**
     * The name of the NamedRanges whose content will be replaced. If there are multiple named ranges with the given name, then the content of each one will be replaced. If there are no named ranges with the given name, then the request will be a no-op.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("namedRangeName")
    public String namedRangeName;
    public ReplaceNamedRangeContentRequest withNamedRangeName(String namedRangeName) {
        this.namedRangeName = namedRangeName;
        return this;
    }
    
    /**
     * Replaces the content of the specified named range(s) with the given text.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("text")
    public String text;
    public ReplaceNamedRangeContentRequest withText(String text) {
        this.text = text;
        return this;
    }
    
}
