from ._xgafv_enum import *
from .alt_enum import *
from .googlecloudvideointelligencev1_annotatevideorequest import *
from .googlecloudvideointelligencev1_explicitcontentdetectionconfig import *
from .googlecloudvideointelligencev1_facedetectionconfig import *
from .googlecloudvideointelligencev1_labeldetectionconfig import *
from .googlecloudvideointelligencev1_objecttrackingconfig import *
from .googlecloudvideointelligencev1_persondetectionconfig import *
from .googlecloudvideointelligencev1_shotchangedetectionconfig import *
from .googlecloudvideointelligencev1_speechcontext import *
from .googlecloudvideointelligencev1_speechtranscriptionconfig import *
from .googlecloudvideointelligencev1_textdetectionconfig import *
from .googlecloudvideointelligencev1_videocontext import *
from .googlecloudvideointelligencev1_videosegment import *
from .googlelongrunning_listoperationsresponse import *
from .googlelongrunning_operation import *
from .googlerpc_status import *
from .security import *

__all__ = ["XgafvEnum","AltEnum","GoogleCloudVideointelligenceV1AnnotateVideoRequestFeaturesEnum","GoogleCloudVideointelligenceV1AnnotateVideoRequest","GoogleCloudVideointelligenceV1ExplicitContentDetectionConfig","GoogleCloudVideointelligenceV1FaceDetectionConfig","GoogleCloudVideointelligenceV1LabelDetectionConfigLabelDetectionModeEnum","GoogleCloudVideointelligenceV1LabelDetectionConfig","GoogleCloudVideointelligenceV1ObjectTrackingConfig","GoogleCloudVideointelligenceV1PersonDetectionConfig","GoogleCloudVideointelligenceV1ShotChangeDetectionConfig","GoogleCloudVideointelligenceV1SpeechContext","GoogleCloudVideointelligenceV1SpeechTranscriptionConfig","GoogleCloudVideointelligenceV1TextDetectionConfig","GoogleCloudVideointelligenceV1VideoContext","GoogleCloudVideointelligenceV1VideoSegment","GoogleLongrunningListOperationsResponse","GoogleLongrunningOperation","GoogleRPCStatus","SchemeOauth2","SchemeOauth2c"]