/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Certificate } from "./certificate";
import { Expose, Type } from "class-transformer";

/**
 * Response message for CertificateAuthorityService.ListCertificates.
 */
export class ListCertificatesResponse extends SpeakeasyBase {
  /**
   * The list of Certificates.
   */
  @SpeakeasyMetadata({ elemType: Certificate })
  @Expose({ name: "certificates" })
  @Type(() => Certificate)
  certificates?: Certificate[];

  /**
   * A token to retrieve next page of results. Pass this value in ListCertificatesRequest.next_page_token to retrieve the next page of results.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nextPageToken" })
  nextPageToken?: string;

  /**
   * A list of locations (e.g. "us-west1") that could not be reached.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "unreachable" })
  unreachable?: string[];
}
