package openapisdk.models.shared;


public enum StreamingImageStatusCodeEnum {
    STREAMING_IMAGE_CREATE_IN_PROGRESS("STREAMING_IMAGE_CREATE_IN_PROGRESS"),
    STREAMING_IMAGE_READY("STREAMING_IMAGE_READY"),
    STREAMING_IMAGE_DELETE_IN_PROGRESS("STREAMING_IMAGE_DELETE_IN_PROGRESS"),
    STREAMING_IMAGE_DELETED("STREAMING_IMAGE_DELETED"),
    STREAMING_IMAGE_UPDATE_IN_PROGRESS("STREAMING_IMAGE_UPDATE_IN_PROGRESS"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    public final String value;

    private StreamingImageStatusCodeEnum(String value) {
        this.value = value;
    }
}
