from ._xgafv_enum import *
from .address import *
from .agerangetype import *
from .alt_enum import *
from .batchcreatecontactsrequest import *
from .batchcreatecontactsresponse import *
from .batchdeletecontactsrequest import *
from .batchgetcontactgroupsresponse import *
from .batchupdatecontactsrequest import *
from .batchupdatecontactsresponse import *
from .biography import *
from .birthday import *
from .braggingrights import *
from .calendarurl import *
from .clientdata import *
from .contactgroup import *
from .contactgroupmembership import *
from .contactgroupmetadata import *
from .contactgroupresponse import *
from .contacttocreate import *
from .copyothercontacttomycontactsgrouprequest import *
from .coverphoto import *
from .createcontactgrouprequest import *
from .date_ import *
from .deletecontactphotoresponse import *
from .domainmembership import *
from .emailaddress import *
from .event import *
from .externalid import *
from .fieldmetadata import *
from .fileas import *
from .gender import *
from .getpeopleresponse import *
from .groupclientdata import *
from .imclient import *
from .interest import *
from .listconnectionsresponse import *
from .listcontactgroupsresponse import *
from .listdirectorypeopleresponse import *
from .listothercontactsresponse import *
from .locale import *
from .location import *
from .membership import *
from .misckeyword import *
from .modifycontactgroupmembersrequest import *
from .modifycontactgroupmembersresponse import *
from .name import *
from .nickname import *
from .occupation import *
from .organization import *
from .person import *
from .personmetadata import *
from .personresponse import *
from .phonenumber import *
from .photo import *
from .profilemetadata import *
from .relation import *
from .relationshipinterest import *
from .relationshipstatus import *
from .residence import *
from .searchdirectorypeopleresponse import *
from .searchresponse import *
from .searchresult import *
from .security import *
from .sipaddress import *
from .skill import *
from .source import *
from .status import *
from .tagline import *
from .updatecontactgrouprequest import *
from .updatecontactphotorequest import *
from .updatecontactphotoresponse import *
from .url import *
from .userdefined import *

__all__ = ["XgafvEnum","Address","AddressInput","AgeRangeTypeAgeRangeEnum","AgeRangeType","AltEnum","BatchCreateContactsRequestSourcesEnum","BatchCreateContactsRequestInput","BatchCreateContactsResponse","BatchDeleteContactsRequest","BatchGetContactGroupsResponse","BatchUpdateContactsRequestSourcesEnum","BatchUpdateContactsRequestInput","BatchUpdateContactsResponse","BiographyContentTypeEnum","Biography","BiographyInput","Birthday","BirthdayInput","BraggingRights","BraggingRightsInput","CalendarURL","CalendarURLInput","ClientData","ClientDataInput","ContactGroupGroupTypeEnum","ContactGroup","ContactGroupInput","ContactGroupMembership","ContactGroupMembershipInput","ContactGroupMetadata","ContactGroupResponse","ContactToCreateInput","CopyOtherContactToMyContactsGroupRequestSourcesEnum","CopyOtherContactToMyContactsGroupRequest","CoverPhoto","CreateContactGroupRequestInput","Date","DeleteContactPhotoResponse","DomainMembership","EmailAddress","EmailAddressInput","Event","EventInput","ExternalID","ExternalIDInput","FieldMetadata","FieldMetadataInput","FileAs","FileAsInput","Gender","GenderInput","GetPeopleResponse","GroupClientData","ImClient","ImClientInput","Interest","InterestInput","ListConnectionsResponse","ListContactGroupsResponse","ListDirectoryPeopleResponse","ListOtherContactsResponse","Locale","LocaleInput","Location","LocationInput","Membership","MembershipInput","MiscKeywordTypeEnum","MiscKeyword","MiscKeywordInput","ModifyContactGroupMembersRequest","ModifyContactGroupMembersResponse","Name","NameInput","NicknameTypeEnum","Nickname","NicknameInput","Occupation","OccupationInput","Organization","OrganizationInput","PersonAgeRangeEnum","Person","PersonInput","PersonMetadataObjectTypeEnum","PersonMetadata","PersonMetadataInput","PersonResponse","PhoneNumber","PhoneNumberInput","Photo","ProfileMetadataObjectTypeEnum","ProfileMetadataUserTypesEnum","ProfileMetadata","Relation","RelationInput","RelationshipInterest","RelationshipStatus","Residence","ResidenceInput","SearchDirectoryPeopleResponse","SearchResponse","SearchResult","SchemeOauth2","SchemeOauth2c","SipAddress","SipAddressInput","Skill","SkillInput","SourceTypeEnum","Source","SourceInput","Status","Tagline","UpdateContactGroupRequestInput","UpdateContactPhotoRequestSourcesEnum","UpdateContactPhotoRequest","UpdateContactPhotoResponse","URL","URLInput","UserDefined","UserDefinedInput"]