/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Collaboration } from "./collaboration";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class CreateCollaborationOutput extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "collaboration" })
  @Type(() => Collaboration)
  collaboration: Collaboration;
}
