package openapisdk.models.shared;


public enum CreativeAuthoringSourceEnum {
    CREATIVE_AUTHORING_SOURCE_DCM("CREATIVE_AUTHORING_SOURCE_DCM"),
    CREATIVE_AUTHORING_SOURCE_DBM("CREATIVE_AUTHORING_SOURCE_DBM"),
    CREATIVE_AUTHORING_SOURCE_STUDIO("CREATIVE_AUTHORING_SOURCE_STUDIO"),
    CREATIVE_AUTHORING_SOURCE_GWD("CREATIVE_AUTHORING_SOURCE_GWD"),
    CREATIVE_AUTHORING_SOURCE_ACS("CREATIVE_AUTHORING_SOURCE_ACS");

    public final String value;

    private CreativeAuthoringSourceEnum(String value) {
        this.value = value;
    }
}
