// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type EnvironmentAccountConnectionStatusEnum string

const (
	EnvironmentAccountConnectionStatusEnumPending   EnvironmentAccountConnectionStatusEnum = "PENDING"
	EnvironmentAccountConnectionStatusEnumConnected EnvironmentAccountConnectionStatusEnum = "CONNECTED"
	EnvironmentAccountConnectionStatusEnumRejected  EnvironmentAccountConnectionStatusEnum = "REJECTED"
)

func (e EnvironmentAccountConnectionStatusEnum) ToPointer() *EnvironmentAccountConnectionStatusEnum {
	return &e
}

func (e *EnvironmentAccountConnectionStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "CONNECTED":
		fallthrough
	case "REJECTED":
		*e = EnvironmentAccountConnectionStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvironmentAccountConnectionStatusEnum: %v", v)
	}
}
