/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class CreateAFileParametersFile {
    @SpeakeasyMetadata("multipartForm:content")
    public byte[] content;
    public CreateAFileParametersFile withContent(byte[] content) {
        this.content = content;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=file")
    public String file;
    public CreateAFileParametersFile withFile(String file) {
        this.file = file;
        return this;
    }
    
}
