// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetSetupV1ResourcesIDCalendarAuthOutlookOutlookEmailAddressPathParams struct {
	// id of resource object
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Email address of Outlook Calendar
	OutlookEmailAddress string `pathParam:"style=simple,explode=false,name=outlookEmailAddress"`
}

type GetSetupV1ResourcesIDCalendarAuthOutlookOutlookEmailAddressQueryParams struct {
	// Outlook calendar authorization return url
	OutlookAuthReturnURL *string `queryParam:"style=form,explode=true,name=outlookAuthReturnUrl"`
}

type GetSetupV1ResourcesIDCalendarAuthOutlookOutlookEmailAddressRequest struct {
	PathParams  GetSetupV1ResourcesIDCalendarAuthOutlookOutlookEmailAddressPathParams
	QueryParams GetSetupV1ResourcesIDCalendarAuthOutlookOutlookEmailAddressQueryParams
}

type GetSetupV1ResourcesIDCalendarAuthOutlookOutlookEmailAddressResponse struct {
	// Success
	CalendarAuthViewModel *shared.CalendarAuthViewModel
	ContentType           string
	StatusCode            int
	RawResponse           *http.Response
}
