package openapisdk.models.shared;


public enum QueryMetadataDataRangeEnum {
    CUSTOM_DATES("CUSTOM_DATES"),
    CURRENT_DAY("CURRENT_DAY"),
    PREVIOUS_DAY("PREVIOUS_DAY"),
    WEEK_TO_DATE("WEEK_TO_DATE"),
    MONTH_TO_DATE("MONTH_TO_DATE"),
    QUARTER_TO_DATE("QUARTER_TO_DATE"),
    YEAR_TO_DATE("YEAR_TO_DATE"),
    PREVIOUS_WEEK("PREVIOUS_WEEK"),
    PREVIOUS_HALF_MONTH("PREVIOUS_HALF_MONTH"),
    PREVIOUS_MONTH("PREVIOUS_MONTH"),
    PREVIOUS_QUARTER("PREVIOUS_QUARTER"),
    PREVIOUS_YEAR("PREVIOUS_YEAR"),
    LAST7_DAYS("LAST_7_DAYS"),
    LAST30_DAYS("LAST_30_DAYS"),
    LAST90_DAYS("LAST_90_DAYS"),
    LAST365_DAYS("LAST_365_DAYS"),
    ALL_TIME("ALL_TIME"),
    LAST14_DAYS("LAST_14_DAYS"),
    TYPE_NOT_SUPPORTED("TYPE_NOT_SUPPORTED"),
    LAST60_DAYS("LAST_60_DAYS");

    public final String value;

    private QueryMetadataDataRangeEnum(String value) {
        this.value = value;
    }
}
