/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ImportCertificateResponse {
    /**
     * Summary of the certificate.
     */
    
    public org.openapis.openapi.models.shared.CertificateSummary certificateSummary;

    public ImportCertificateResponse withCertificateSummary(org.openapis.openapi.models.shared.CertificateSummary certificateSummary) {
        this.certificateSummary = certificateSummary;
        return this;
    }
    
    
    public String contentType;

    public ImportCertificateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ImportCertificateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ImportCertificateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ImportCertificateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
