from .canceljob import *
from .checkconnectiontodestination import *
from .checkconnectiontodestinationforupdate import *
from .checkconnectiontosource import *
from .checkconnectiontosourceforupdate import *
from .checkoperation import *
from .createconnection import *
from .createdestination import *
from .createdestinationdefinition import *
from .createoperation import *
from .createsource import *
from .createsourcedefinition import *
from .createworkspace import *
from .deleteconnection import *
from .deletedestination import *
from .deleteoperation import *
from .deletesource import *
from .deleteworkspace import *
from .discoverschemaforsource import *
from .executedestinationcheckconnection import *
from .executesourcecheckconnection import *
from .executesourcediscoverschema import *
from .exportarchive import *
from .getconnection import *
from .getdestination import *
from .getdestinationdefinition import *
from .getdestinationdefinitionspecification import *
from .gethealthcheck import *
from .getjobinfo import *
from .getlogs import *
from .getopenapispec import *
from .getoperation import *
from .getsource import *
from .getsourcedefinition import *
from .getsourcedefinitionspecification import *
from .getstate import *
from .getworkspace import *
from .getworkspacebyslug import *
from .importarchive import *
from .listconnectionsforworkspace import *
from .listdestinationdefinitions import *
from .listdestinationsforworkspace import *
from .listjobsfor import *
from .listlatestdestinationdefinitions import *
from .listlatestsourcedefinitions import *
from .listoperationsforconnection import *
from .listsourcedefinitions import *
from .listsourcesforworkspace import *
from .listworkspaces import *
from .resetconnection import *
from .syncconnection import *
from .trynotificationconfig import *
from .updateconnection import *
from .updatedestination import *
from .updatedestinationdefinition import *
from .updateoperation import *
from .updatesource import *
from .updatesourcedefinition import *
from .updateworkspace import *
from .webbackendcreateconnection import *
from .webbackendgetconnection import *
from .webbackendlistconnectionsforworkspace import *
from .webbackendrecreatedestination import *
from .webbackendrecreatesource import *
from .webbackendupdateconnection import *

__all__ = ["CancelJobRequest","CancelJobResponse","CheckConnectionToDestinationRequest","CheckConnectionToDestinationResponse","CheckConnectionToDestinationForUpdateRequest","CheckConnectionToDestinationForUpdateResponse","CheckConnectionToSourceRequest","CheckConnectionToSourceResponse","CheckConnectionToSourceForUpdateRequest","CheckConnectionToSourceForUpdateResponse","CheckOperationRequest","CheckOperationResponse","CreateConnectionRequest","CreateConnectionResponse","CreateDestinationRequest","CreateDestinationResponse","CreateDestinationDefinitionRequest","CreateDestinationDefinitionResponse","CreateOperationRequest","CreateOperationResponse","CreateSourceRequest","CreateSourceResponse","CreateSourceDefinitionRequest","CreateSourceDefinitionResponse","CreateWorkspaceRequest","CreateWorkspaceResponse","DeleteConnectionRequest","DeleteConnectionResponse","DeleteDestinationRequest","DeleteDestinationResponse","DeleteOperationRequest","DeleteOperationResponse","DeleteSourceRequest","DeleteSourceResponse","DeleteWorkspaceRequest","DeleteWorkspaceResponse","DiscoverSchemaForSourceRequest","DiscoverSchemaForSourceResponse","ExecuteDestinationCheckConnectionRequest","ExecuteDestinationCheckConnectionResponse","ExecuteSourceCheckConnectionRequest","ExecuteSourceCheckConnectionResponse","ExecuteSourceDiscoverSchemaRequest","ExecuteSourceDiscoverSchemaResponse","ExportArchiveResponse","GetConnectionRequest","GetConnectionResponse","GetDestinationRequest","GetDestinationResponse","GetDestinationDefinitionRequest","GetDestinationDefinitionResponse","GetDestinationDefinitionSpecificationRequest","GetDestinationDefinitionSpecificationResponse","GetHealthCheckResponse","GetJobInfoRequest","GetJobInfoResponse","GetLogsRequest","GetLogsResponse","GetOpenAPISpecResponse","GetOperationRequest","GetOperationResponse","GetSourceRequest","GetSourceResponse","GetSourceDefinitionRequest","GetSourceDefinitionResponse","GetSourceDefinitionSpecificationRequest","GetSourceDefinitionSpecificationResponse","GetStateRequest","GetStateResponse","GetWorkspaceRequest","GetWorkspaceResponse","GetWorkspaceBySlugRequest","GetWorkspaceBySlugResponse","ImportArchiveRequest","ImportArchiveResponse","ListConnectionsForWorkspaceRequest","ListConnectionsForWorkspaceResponse","ListDestinationDefinitionsResponse","ListDestinationsForWorkspaceRequest","ListDestinationsForWorkspaceResponse","ListJobsForRequest","ListJobsForResponse","ListLatestDestinationDefinitionsResponse","ListLatestSourceDefinitionsResponse","ListOperationsForConnectionRequest","ListOperationsForConnectionResponse","ListSourceDefinitionsResponse","ListSourcesForWorkspaceRequest","ListSourcesForWorkspaceResponse","ListWorkspacesResponse","ResetConnectionRequest","ResetConnectionResponse","SyncConnectionRequest","SyncConnectionResponse","TryNotificationConfigRequest","TryNotificationConfigResponse","UpdateConnectionRequest","UpdateConnectionResponse","UpdateDestinationRequest","UpdateDestinationResponse","UpdateDestinationDefinitionRequest","UpdateDestinationDefinitionResponse","UpdateOperationRequest","UpdateOperationResponse","UpdateSourceRequest","UpdateSourceResponse","UpdateSourceDefinitionRequest","UpdateSourceDefinitionResponse","UpdateWorkspaceRequest","UpdateWorkspaceResponse","WebBackendCreateConnectionRequest","WebBackendCreateConnectionResponse","WebBackendGetConnectionRequest","WebBackendGetConnectionResponse","WebBackendListConnectionsForWorkspaceRequest","WebBackendListConnectionsForWorkspaceResponse","WebBackendRecreateDestinationRequest","WebBackendRecreateDestinationResponse","WebBackendRecreateSourceRequest","WebBackendRecreateSourceResponse","WebBackendUpdateConnectionRequest","WebBackendUpdateConnectionResponse"]