/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PendingMaintenanceActionDetails } from "./pendingmaintenanceactiondetails";

/**
 * Represents the output of <a>ApplyPendingMaintenanceAction</a>.
 */
export class PendingMaintenanceActions extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: PendingMaintenanceActionDetails })
  pendingMaintenanceActionDetails?: PendingMaintenanceActionDetails[];

  @SpeakeasyMetadata()
  resourceIdentifier?: string;
}
