// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Detail struct {
	IconList []IconList `json:"icon_list"`
	Locale   Locale     `json:"locale"`
	Timezone Timezone   `json:"timezone"`
}
