/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum StepExecutionStateEnum {
    PENDING("PENDING"),
    RUNNING("RUNNING"),
    CONTINUE_("CONTINUE"),
    COMPLETED("COMPLETED"),
    CANCELLED("CANCELLED"),
    FAILED("FAILED"),
    INTERRUPTED("INTERRUPTED");

    @JsonValue
    public final String value;

    private StepExecutionStateEnum(String value) {
        this.value = value;
    }
}
