from ._xgafv_enum import *
from .addgroupmigrationrequest import *
from .alt_enum import *
from .applianceversion import *
from .appliedlicense import *
from .availableupdates import *
from .clonejob import *
from .clonestep import *
from .computeenginetargetdefaults import *
from .computeenginetargetdetails import *
from .computescheduling import *
from .cutoverjob import *
from .cutoverstep import *
from .cyclestep import *
from .datacenterconnector import *
from .fetchinventoryresponse import *
from .group import *
from .listclonejobsresponse import *
from .listcutoverjobsresponse import *
from .listdatacenterconnectorsresponse import *
from .listgroupsresponse import *
from .listlocationsresponse import *
from .listmigratingvmsresponse import *
from .listoperationsresponse import *
from .listreplicationcyclesresponse import *
from .listsourcesresponse import *
from .listtargetprojectsresponse import *
from .listutilizationreportsresponse import *
from .location import *
from .migratingvm import *
from .networkinterface import *
from .operation import *
from .removegroupmigrationrequest import *
from .replicatingstep import *
from .replicationcycle import *
from .replicationsync import *
from .schedulepolicy import *
from .schedulingnodeaffinity import *
from .security import *
from .source import *
from .status import *
from .targetproject import *
from .upgradeappliancerequest import *
from .upgradestatus import *
from .utilizationreport import *
from .vmutilizationinfo import *
from .vmutilizationmetrics import *
from .vmwaresourcedetails import *
from .vmwarevmdetails import *
from .vmwarevmsdetails import *

__all__ = ["XgafvEnum","AddGroupMigrationRequest","AltEnum","ApplianceVersion","AppliedLicenseTypeEnum","AppliedLicense","AvailableUpdates","CloneJobStateEnum","CloneJob","CloneJobInput","CloneStep","ComputeEngineTargetDefaultsBootOptionEnum","ComputeEngineTargetDefaultsDiskTypeEnum","ComputeEngineTargetDefaultsLicenseTypeEnum","ComputeEngineTargetDefaults","ComputeEngineTargetDefaultsInput","ComputeEngineTargetDetailsBootOptionEnum","ComputeEngineTargetDetailsDiskTypeEnum","ComputeEngineTargetDetailsLicenseTypeEnum","ComputeEngineTargetDetails","ComputeSchedulingOnHostMaintenanceEnum","ComputeSchedulingRestartTypeEnum","ComputeScheduling","CutoverJobStateEnum","CutoverJob","CutoverJobInput","CutoverStep","CycleStep","DatacenterConnectorStateEnum","DatacenterConnector","DatacenterConnectorInput","FetchInventoryResponse","Group","GroupInput","ListCloneJobsResponse","ListCutoverJobsResponse","ListDatacenterConnectorsResponse","ListGroupsResponse","ListLocationsResponse","ListMigratingVmsResponse","ListOperationsResponse","ListReplicationCyclesResponse","ListSourcesResponse","ListTargetProjectsResponse","ListUtilizationReportsResponse","Location","MigratingVMStateEnum","MigratingVM","MigratingVMInput","NetworkInterface","Operation","RemoveGroupMigrationRequest","ReplicatingStep","ReplicationCycleStateEnum","ReplicationCycle","ReplicationSync","SchedulePolicy","SchedulingNodeAffinityOperatorEnum","SchedulingNodeAffinity","SchemeOauth2","SchemeOauth2c","Source","SourceInput","Status","TargetProject","TargetProjectInput","UpgradeApplianceRequest","UpgradeStatusStateEnum","UpgradeStatus","UtilizationReportStateEnum","UtilizationReportTimeFrameEnum","UtilizationReport","UtilizationReportInput","VMUtilizationInfo","VMUtilizationInfoInput","VMUtilizationMetrics","VmwareSourceDetails","VmwareVMDetailsBootOptionEnum","VmwareVMDetailsPowerStateEnum","VmwareVMDetails","VmwareVMDetailsInput","VmwareVmsDetails"]