package openapisdk.models.shared;


public enum AppointmentSystemVitalsSmokingStatusEnum {
    BLANK("blank"),
    FOUR_HUNDRED_AND_FORTY_NINE_MILLION_EIGHT_HUNDRED_AND_SIXTY_EIGHT_THOUSAND_AND_TWO("449868002"),
    FOUR_HUNDRED_AND_TWENTY_EIGHT_TRILLION_FORTY_ONE_BILLION_ONE_HUNDRED_AND_TWENTY_FOUR_THOUSAND_ONE_HUNDRED_AND_SIX("428041000124106"),
    EIGHT_MILLION_FIVE_HUNDRED_AND_SEVENTEEN_THOUSAND_AND_SIX("8517006"),
    TWO_HUNDRED_AND_SIXTY_SIX_MILLION_NINE_HUNDRED_AND_NINETEEN_THOUSAND_AND_FIVE("266919005"),
    SEVENTY_SEVEN_MILLION_ONE_HUNDRED_AND_SEVENTY_SIX_THOUSAND_AND_TWO("77176002"),
    TWO_HUNDRED_AND_SIXTY_SIX_MILLION_NINE_HUNDRED_AND_TWENTY_SEVEN_THOUSAND_AND_ONE("266927001"),
    FOUR_HUNDRED_AND_TWENTY_EIGHT_TRILLION_SEVENTY_ONE_BILLION_ONE_HUNDRED_AND_TWENTY_FOUR_THOUSAND_ONE_HUNDRED_AND_THREE("428071000124103"),
    FOUR_HUNDRED_AND_TWENTY_EIGHT_TRILLION_SIXTY_ONE_BILLION_ONE_HUNDRED_AND_TWENTY_FOUR_THOUSAND_ONE_HUNDRED_AND_FIVE("428061000124105");

    public final String value;

    private AppointmentSystemVitalsSmokingStatusEnum(String value) {
        this.value = value;
    }
}
