package openapisdk.models.shared;


public enum PatientVaccineRecordObservedImmunityEnum {
    THREE_HUNDRED_AND_NINETY_EIGHT_MILLION_ONE_HUNDRED_AND_TWO_THOUSAND_AND_NINE("398102009"),
    FOUR_HUNDRED_AND_NINE_MILLION_FOUR_HUNDRED_AND_NINETY_EIGHT_THOUSAND_AND_FOUR("409498004"),
    THREE_HUNDRED_AND_NINETY_SEVEN_MILLION_FOUR_HUNDRED_AND_TWENTY_EIGHT_THOUSAND("397428000"),
    EIGHTEEN_MILLION_SIX_HUNDRED_AND_TWENTY_FOUR_THOUSAND("18624000"),
    NINETY_ONE_MILLION_FOUR_HUNDRED_AND_TWENTY_EIGHT_THOUSAND_AND_FIVE("91428005"),
    TWO_HUNDRED_AND_SEVENTY_ONE_MILLION_FIVE_HUNDRED_AND_ELEVEN_THOUSAND("271511000"),
    TWO_HUNDRED_AND_FORTY_MILLION_FIVE_HUNDRED_AND_THIRTY_TWO_THOUSAND_AND_NINE("240532009"),
    SIX_MILLION_ONE_HUNDRED_AND_FORTY_TWO_THOUSAND_AND_FOUR("6142004"),
    FIFTY_TWO_MILLION_NINE_HUNDRED_AND_FORTY_SEVEN_THOUSAND_AND_SIX("52947006"),
    FOURTEEN_MILLION_ONE_HUNDRED_AND_EIGHTY_NINE_THOUSAND_AND_FOUR("14189004"),
    TWENTY_THREE_MILLION_FIVE_HUNDRED_AND_ELEVEN_THOUSAND_AND_SIX("23511006"),
    THIRTY_SIX_MILLION_NINE_HUNDRED_AND_EIGHTY_NINE_THOUSAND_AND_FIVE("36989005"),
    TWENTY_SEVEN_MILLION_EIGHT_HUNDRED_AND_THIRTY_SIX_THOUSAND_AND_SEVEN("27836007"),
    SIXTEEN_MILLION_EIGHT_HUNDRED_AND_FOURTEEN_THOUSAND_AND_FOUR("16814004"),
    FOURTEEN_MILLION_ONE_HUNDRED_AND_SIXTY_EIGHT_THOUSAND_AND_EIGHT("14168008"),
    THIRTY_SIX_MILLION_SIX_HUNDRED_AND_FIFTY_THREE_THOUSAND("36653000"),
    SEVENTY_SIX_MILLION_NINE_HUNDRED_AND_TWO_THOUSAND_AND_SIX("76902006"),
    SIXTY_SIX_MILLION_SEVENTY_ONE_THOUSAND_AND_TWO("66071002"),
    FOUR_MILLION_EIGHT_HUNDRED_AND_THIRTY_FOUR_THOUSAND("4834000"),
    ONE_HUNDRED_AND_ELEVEN_MILLION_EIGHT_HUNDRED_AND_FIFTY_TWO_THOUSAND_AND_THREE("111852003"),
    THIRTY_EIGHT_MILLION_NINE_HUNDRED_AND_SEVEN_THOUSAND_AND_THREE("38907003"),
    FORTY_MILLION_FOUR_HUNDRED_AND_SIXTY_EIGHT_THOUSAND_AND_THREE("40468003"),
    SIXTEEN_MILLION_FIVE_HUNDRED_AND_FORTY_ONE_THOUSAND_AND_ONE("16541001");

    public final String value;

    private PatientVaccineRecordObservedImmunityEnum(String value) {
        this.value = value;
    }
}
