"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import reconciliationreport as shared_reconciliationreport
from ..shared import reconciliationreportvalidationissue as shared_reconciliationreportvalidationissue
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateReconciliationReportResponse:
    r"""Response message for ReconciliationReportService.CreateReconciliationReport."""
    
    issues: Optional[list[shared_reconciliationreportvalidationissue.ReconciliationReportValidationIssue]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('issues'), 'exclude': lambda f: f is None }})
    r"""Issues that were encountered when validating the file."""  
    reconciliation_report: Optional[shared_reconciliationreport.ReconciliationReport] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reconciliationReport'), 'exclude': lambda f: f is None }})
    r"""Reconciliation report (Hotel Ads only). Covers the Reconciliation Reports functionality in pre-v3.0 API versions. Lets you see the status, validate, and upload your Commissions reconciliation reports. This only applies if you are in the Google Hotel Ads Commissions Program (GHACP). For more information about working with reconciliation reports in Hotel Center, refer to [Reconciliation reports](//support.google.com/hotelprices/answer/7019060#sending)."""  
    successful_record_count: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('successfulRecordCount'), 'exclude': lambda f: f is None }})
    r"""The number of commission records that were successfully saved."""  
    