/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GetNoteRequest {
    /**
     * HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept")
    public String accept;

    public GetNoteRequest withAccept(String accept) {
        this.accept = accept;
        return this;
    }
    
    /**
     * Type of the content being sent.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Content-Type")
    public String contentType;

    public GetNoteRequest withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Note's ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=noteId")
    public String noteId;

    public GetNoteRequest withNoteId(String noteId) {
        this.noteId = noteId;
        return this;
    }
    
    /**
     * This parameter is relevant only for PII-compliant accounts. When sending requests to this endpoint, PII-compliant accounts can use this parameter to declare the reason for requesting unmasked data. Otherwise, this endpoint will return masked PII data.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reason")
    public String reason;

    public GetNoteRequest withReason(String reason) {
        this.reason = reason;
        return this;
    }
    
    public GetNoteRequest(@JsonProperty("Accept") String accept, @JsonProperty("Content-Type") String contentType, @JsonProperty("noteId") String noteId) {
        this.accept = accept;
        this.contentType = contentType;
        this.noteId = noteId;
  }
}
