/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class AuthVerifyotpGetSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=apiKey;subtype=header;name=X-Auth",
  })
  authKey: string;
}

export class AuthVerifyotpGetRequest extends SpeakeasyBase {
  /**
   * YubiKey OTP code
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=otp" })
  otp: string;
}

export class AuthVerifyotpGetResponse extends SpeakeasyBase {
  /**
   * Access Denied
   */
  @SpeakeasyMetadata()
  fourHundredAndThree?: shared.FourHundredAndThree;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
