import dataclasses
from enum import Enum

class LanguageEnum(str, Enum):
    CS = "cs"
    DA = "da"
    DE = "de"
    EL = "el"
    EN = "en"
    ES = "es"
    FI = "fi"
    FR = "fr"
    HU = "hu"
    ID = "id"
    IT = "it"
    JA = "ja"
    KO = "ko"
    NB = "nb"
    NL = "nl"
    PL = "pl"
    PT = "pt"
    RO = "ro"
    RU = "ru"
    SV = "sv"
    TH = "th"
    TR = "tr"
    VI = "vi"
    ZH = "zh"
    ZH_HANT = "zh-Hant"

