// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CreateFlowLogsRequestTagSpecificationsResourceTypeEnum - The type of resource to tag on creation.
type CreateFlowLogsRequestTagSpecificationsResourceTypeEnum string

const (
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumCapacityReservation                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "capacity-reservation"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumClientVpnEndpoint                                      CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "client-vpn-endpoint"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumCustomerGateway                                        CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "customer-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumCarrierGateway                                         CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "carrier-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumCoipPool                                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "coip-pool"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumDedicatedHost                                          CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "dedicated-host"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumDhcpOptions                                            CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "dhcp-options"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumEgressOnlyInternetGateway                              CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "egress-only-internet-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumElasticIP                                              CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "elastic-ip"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumElasticGpu                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "elastic-gpu"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumExportImageTask                                        CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "export-image-task"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumExportInstanceTask                                     CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "export-instance-task"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumFleet                                                  CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "fleet"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumFpgaImage                                              CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "fpga-image"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumHostReservation                                        CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "host-reservation"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumImage                                                  CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "image"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumImportImageTask                                        CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "import-image-task"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumImportSnapshotTask                                     CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "import-snapshot-task"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumInstance                                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "instance"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumInstanceEventWindow                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "instance-event-window"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumInternetGateway                                        CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "internet-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpam                                                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipam"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpamPool                                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipam-pool"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpamScope                                              CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipam-scope"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpv4poolEc2                                            CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipv4pool-ec2"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpv6poolEc2                                            CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipv6pool-ec2"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumKeyPair                                                CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "key-pair"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLaunchTemplate                                         CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "launch-template"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLocalGateway                                           CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "local-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLocalGatewayRouteTable                                 CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "local-gateway-route-table"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLocalGatewayVirtualInterface                           CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "local-gateway-virtual-interface"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLocalGatewayVirtualInterfaceGroup                      CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "local-gateway-virtual-interface-group"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLocalGatewayRouteTableVpcAssociation                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "local-gateway-route-table-vpc-association"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumLocalGatewayRouteTableVirtualInterfaceGroupAssociation CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "local-gateway-route-table-virtual-interface-group-association"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNatgateway                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "natgateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNetworkACL                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "network-acl"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNetworkInterface                                       CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "network-interface"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNetworkInsightsAnalysis                                CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "network-insights-analysis"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNetworkInsightsPath                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "network-insights-path"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNetworkInsightsAccessScope                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "network-insights-access-scope"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumNetworkInsightsAccessScopeAnalysis                     CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "network-insights-access-scope-analysis"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumPlacementGroup                                         CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "placement-group"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumPrefixList                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "prefix-list"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumReplaceRootVolumeTask                                  CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "replace-root-volume-task"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumReservedInstances                                      CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "reserved-instances"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumRouteTable                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "route-table"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSecurityGroup                                          CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "security-group"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSecurityGroupRule                                      CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "security-group-rule"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSnapshot                                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "snapshot"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSpotFleetRequest                                       CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "spot-fleet-request"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSpotInstancesRequest                                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "spot-instances-request"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSubnet                                                 CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "subnet"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumSubnetCidrReservation                                  CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "subnet-cidr-reservation"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTrafficMirrorFilter                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "traffic-mirror-filter"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTrafficMirrorSession                                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "traffic-mirror-session"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTrafficMirrorTarget                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "traffic-mirror-target"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGateway                                         CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGatewayAttachment                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway-attachment"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGatewayConnectPeer                              CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway-connect-peer"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGatewayMulticastDomain                          CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway-multicast-domain"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGatewayPolicyTable                              CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway-policy-table"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGatewayRouteTable                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway-route-table"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTransitGatewayRouteTableAnnouncement                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "transit-gateway-route-table-announcement"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVolume                                                 CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "volume"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpc                                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcEndpoint                                            CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-endpoint"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcEndpointConnection                                  CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-endpoint-connection"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcEndpointService                                     CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-endpoint-service"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcEndpointServicePermission                           CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-endpoint-service-permission"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcPeeringConnection                                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-peering-connection"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpnConnection                                          CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpn-connection"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpnGateway                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpn-gateway"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcFlowLog                                             CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-flow-log"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumCapacityReservationFleet                               CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "capacity-reservation-fleet"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumTrafficMirrorFilterRule                                CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "traffic-mirror-filter-rule"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcEndpointConnectionDeviceType                        CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-endpoint-connection-device-type"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVerifiedAccessInstance                                 CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "verified-access-instance"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVerifiedAccessGroup                                    CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "verified-access-group"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVerifiedAccessEndpoint                                 CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "verified-access-endpoint"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVerifiedAccessPolicy                                   CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "verified-access-policy"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVerifiedAccessTrustProvider                            CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "verified-access-trust-provider"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpnConnectionDeviceType                                CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpn-connection-device-type"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumVpcBlockPublicAccessExclusion                          CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "vpc-block-public-access-exclusion"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpamResourceDiscovery                                  CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipam-resource-discovery"
	CreateFlowLogsRequestTagSpecificationsResourceTypeEnumIpamResourceDiscoveryAssociation                       CreateFlowLogsRequestTagSpecificationsResourceTypeEnum = "ipam-resource-discovery-association"
)

func (e CreateFlowLogsRequestTagSpecificationsResourceTypeEnum) ToPointer() *CreateFlowLogsRequestTagSpecificationsResourceTypeEnum {
	return &e
}

func (e *CreateFlowLogsRequestTagSpecificationsResourceTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "capacity-reservation":
		fallthrough
	case "client-vpn-endpoint":
		fallthrough
	case "customer-gateway":
		fallthrough
	case "carrier-gateway":
		fallthrough
	case "coip-pool":
		fallthrough
	case "dedicated-host":
		fallthrough
	case "dhcp-options":
		fallthrough
	case "egress-only-internet-gateway":
		fallthrough
	case "elastic-ip":
		fallthrough
	case "elastic-gpu":
		fallthrough
	case "export-image-task":
		fallthrough
	case "export-instance-task":
		fallthrough
	case "fleet":
		fallthrough
	case "fpga-image":
		fallthrough
	case "host-reservation":
		fallthrough
	case "image":
		fallthrough
	case "import-image-task":
		fallthrough
	case "import-snapshot-task":
		fallthrough
	case "instance":
		fallthrough
	case "instance-event-window":
		fallthrough
	case "internet-gateway":
		fallthrough
	case "ipam":
		fallthrough
	case "ipam-pool":
		fallthrough
	case "ipam-scope":
		fallthrough
	case "ipv4pool-ec2":
		fallthrough
	case "ipv6pool-ec2":
		fallthrough
	case "key-pair":
		fallthrough
	case "launch-template":
		fallthrough
	case "local-gateway":
		fallthrough
	case "local-gateway-route-table":
		fallthrough
	case "local-gateway-virtual-interface":
		fallthrough
	case "local-gateway-virtual-interface-group":
		fallthrough
	case "local-gateway-route-table-vpc-association":
		fallthrough
	case "local-gateway-route-table-virtual-interface-group-association":
		fallthrough
	case "natgateway":
		fallthrough
	case "network-acl":
		fallthrough
	case "network-interface":
		fallthrough
	case "network-insights-analysis":
		fallthrough
	case "network-insights-path":
		fallthrough
	case "network-insights-access-scope":
		fallthrough
	case "network-insights-access-scope-analysis":
		fallthrough
	case "placement-group":
		fallthrough
	case "prefix-list":
		fallthrough
	case "replace-root-volume-task":
		fallthrough
	case "reserved-instances":
		fallthrough
	case "route-table":
		fallthrough
	case "security-group":
		fallthrough
	case "security-group-rule":
		fallthrough
	case "snapshot":
		fallthrough
	case "spot-fleet-request":
		fallthrough
	case "spot-instances-request":
		fallthrough
	case "subnet":
		fallthrough
	case "subnet-cidr-reservation":
		fallthrough
	case "traffic-mirror-filter":
		fallthrough
	case "traffic-mirror-session":
		fallthrough
	case "traffic-mirror-target":
		fallthrough
	case "transit-gateway":
		fallthrough
	case "transit-gateway-attachment":
		fallthrough
	case "transit-gateway-connect-peer":
		fallthrough
	case "transit-gateway-multicast-domain":
		fallthrough
	case "transit-gateway-policy-table":
		fallthrough
	case "transit-gateway-route-table":
		fallthrough
	case "transit-gateway-route-table-announcement":
		fallthrough
	case "volume":
		fallthrough
	case "vpc":
		fallthrough
	case "vpc-endpoint":
		fallthrough
	case "vpc-endpoint-connection":
		fallthrough
	case "vpc-endpoint-service":
		fallthrough
	case "vpc-endpoint-service-permission":
		fallthrough
	case "vpc-peering-connection":
		fallthrough
	case "vpn-connection":
		fallthrough
	case "vpn-gateway":
		fallthrough
	case "vpc-flow-log":
		fallthrough
	case "capacity-reservation-fleet":
		fallthrough
	case "traffic-mirror-filter-rule":
		fallthrough
	case "vpc-endpoint-connection-device-type":
		fallthrough
	case "verified-access-instance":
		fallthrough
	case "verified-access-group":
		fallthrough
	case "verified-access-endpoint":
		fallthrough
	case "verified-access-policy":
		fallthrough
	case "verified-access-trust-provider":
		fallthrough
	case "vpn-connection-device-type":
		fallthrough
	case "vpc-block-public-access-exclusion":
		fallthrough
	case "ipam-resource-discovery":
		fallthrough
	case "ipam-resource-discovery-association":
		*e = CreateFlowLogsRequestTagSpecificationsResourceTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFlowLogsRequestTagSpecificationsResourceTypeEnum: %v", v)
	}
}

// CreateFlowLogsRequestTagSpecificationsTags - Describes a tag.
type CreateFlowLogsRequestTagSpecificationsTags struct {
	Key   *string
	Value *string
}

// CreateFlowLogsRequestTagSpecifications - <p>The tags to apply to a resource when the resource is being created. When you specify a tag, you must specify the resource type to tag, otherwise the request will fail.</p> <note> <p>The <code>Valid Values</code> lists all the resource types that can be tagged. However, the action you're using might not support tagging all of these resource types. If you try to tag a resource type that is unsupported for the action you're using, you'll get an error.</p> </note>
type CreateFlowLogsRequestTagSpecifications struct {
	ResourceType *CreateFlowLogsRequestTagSpecificationsResourceTypeEnum
	Tags         []CreateFlowLogsRequestTagSpecificationsTags
}

type CreateFlowLogsRequest struct {
	ClientToken              *string
	DeliverCrossAccountRole  *string
	DeliverLogsPermissionArn *string
	DestinationOptions       *DestinationOptionsRequest
	DryRun                   *bool
	LogDestination           *string
	LogDestinationType       *LogDestinationTypeEnum
	LogFormat                *string
	LogGroupName             *string
	MaxAggregationInterval   *int64
	ResourceIds              []string
	ResourceType             FlowLogsResourceTypeEnum
	TagSpecifications        []CreateFlowLogsRequestTagSpecifications
	TrafficType              *TrafficTypeEnum
}
