"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import dpsjobinstruction as shared_dpsjobinstruction
from ..shared import errormodel as shared_errormodel
from ..shared import link as shared_link
from typing import Optional


@dataclasses.dataclass
class PostNewDpsJobRequest:
    
    api_version: str = dataclasses.field(metadata={'header': { 'field_name': 'Api-Version', 'style': 'simple', 'explode': False }})
    r"""The version of the api to target. Omit or set as &apos;default&apos; to target the current api version."""  
    authorization: str = dataclasses.field(metadata={'header': { 'field_name': 'Authorization', 'style': 'simple', 'explode': False }})
    r"""The OAuth 1 authorization header. &apos;Auto&apos; enables auto complete."""  
    dps_job_instruction: shared_dpsjobinstruction.DpsJobInstruction = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""The the DPS job instruction object."""  
    

@dataclasses.dataclass
class PostNewDpsJobResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    error_model: Optional[shared_errormodel.ErrorModel] = dataclasses.field(default=None)
    r"""Bad Request"""  
    link: Optional[shared_link.Link] = dataclasses.field(default=None)
    r"""The link object."""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    