/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ManifestsListResponse - A response containing a partial list of manifests and a page token used to build the next request if the request has been truncated.
 */
public class ManifestsListResponse {
    /**
     * Output only. Manifests contained in this list response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("manifests")
    public Manifest[] manifests;

    public ManifestsListResponse withManifests(Manifest[] manifests) {
        this.manifests = manifests;
        return this;
    }
    
    /**
     * Output only. A token used to continue a truncated list request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nextPageToken")
    public String nextPageToken;

    public ManifestsListResponse withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    public ManifestsListResponse(){}
}
