<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * ListMetricDescriptorsResponse - The ListMetricDescriptors response.
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class ListMetricDescriptorsResponse
{
    /**
     * The metric descriptors that are available to the project and that match the value of filter, if present.
     * 
     * @var ?array<\OpenAPI\OpenAPI\Models\Shared\MetricDescriptor> $metricDescriptors
     */
	#[\JMS\Serializer\Annotation\SerializedName('metricDescriptors')]
    #[\JMS\Serializer\Annotation\Type('array<OpenAPI\OpenAPI\Models\Shared\MetricDescriptor>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $metricDescriptors = null;
    
    /**
     * If there are more results than have been returned, then this field is set to a non-empty value. To see the additional results, use that value as page_token in the next call to this method.
     * 
     * @var ?string $nextPageToken
     */
	#[\JMS\Serializer\Annotation\SerializedName('nextPageToken')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nextPageToken = null;
    
	public function __construct()
	{
		$this->metricDescriptors = null;
		$this->nextPageToken = null;
	}
}
