package openapisdk.models.shared;


public enum GoogleCloudAssuredworkloadsV1ViolationRemediationRemediationTypeEnum {
    REMEDIATION_TYPE_UNSPECIFIED("REMEDIATION_TYPE_UNSPECIFIED"),
    REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION("REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION"),
    REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION("REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION"),
    REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION("REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION"),
    REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION("REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION");

    public final String value;

    private GoogleCloudAssuredworkloadsV1ViolationRemediationRemediationTypeEnum(String value) {
        this.value = value;
    }
}
