package openapisdk.models.shared;


public enum MetricValueMetricEnum {
    METRIC_UNSPECIFIED("METRIC_UNSPECIFIED"),
    ALL("ALL"),
    QUERIES_DIRECT("QUERIES_DIRECT"),
    QUERIES_INDIRECT("QUERIES_INDIRECT"),
    QUERIES_CHAIN("QUERIES_CHAIN"),
    VIEWS_MAPS("VIEWS_MAPS"),
    VIEWS_SEARCH("VIEWS_SEARCH"),
    ACTIONS_WEBSITE("ACTIONS_WEBSITE"),
    ACTIONS_PHONE("ACTIONS_PHONE"),
    ACTIONS_DRIVING_DIRECTIONS("ACTIONS_DRIVING_DIRECTIONS"),
    PHOTOS_VIEWS_MERCHANT("PHOTOS_VIEWS_MERCHANT"),
    PHOTOS_VIEWS_CUSTOMERS("PHOTOS_VIEWS_CUSTOMERS"),
    PHOTOS_COUNT_MERCHANT("PHOTOS_COUNT_MERCHANT"),
    PHOTOS_COUNT_CUSTOMERS("PHOTOS_COUNT_CUSTOMERS"),
    LOCAL_POST_VIEWS_SEARCH("LOCAL_POST_VIEWS_SEARCH"),
    LOCAL_POST_ACTIONS_CALL_TO_ACTION("LOCAL_POST_ACTIONS_CALL_TO_ACTION");

    public final String value;

    private MetricValueMetricEnum(String value) {
        this.value = value;
    }
}
