<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * SearchResultSnippet - Basic details about a search result, including title, description and thumbnails of the item referenced by the search result.
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class SearchResultSnippet
{
    /**
     * The value that YouTube uses to uniquely identify the channel that published the resource that the search result identifies.
     * 
     * @var ?string $channelId
     */
	#[\JMS\Serializer\Annotation\SerializedName('channelId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $channelId = null;
    
    /**
     * The title of the channel that published the resource that the search result identifies.
     * 
     * @var ?string $channelTitle
     */
	#[\JMS\Serializer\Annotation\SerializedName('channelTitle')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $channelTitle = null;
    
    /**
     * A description of the search result.
     * 
     * @var ?string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * It indicates if the resource (video or channel) has upcoming/active live broadcast content. Or it's "none" if there is not any upcoming/active live broadcasts.
     * 
     * @var ?\OpenAPI\OpenAPI\Models\Shared\SearchResultSnippetLiveBroadcastContentEnum $liveBroadcastContent
     */
	#[\JMS\Serializer\Annotation\SerializedName('liveBroadcastContent')]
    #[\JMS\Serializer\Annotation\Type('enum<OpenAPI\OpenAPI\Models\Shared\SearchResultSnippetLiveBroadcastContentEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SearchResultSnippetLiveBroadcastContentEnum $liveBroadcastContent = null;
    
    /**
     * The creation date and time of the resource that the search result identifies.
     * 
     * @var ?\DateTime $publishedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('publishedAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $publishedAt = null;
    
    /**
     * Internal representation of thumbnails for a YouTube resource.
     * 
     * @var ?\OpenAPI\OpenAPI\Models\Shared\ThumbnailDetails $thumbnails
     */
	#[\JMS\Serializer\Annotation\SerializedName('thumbnails')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Shared\ThumbnailDetails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ThumbnailDetails $thumbnails = null;
    
    /**
     * The title of the search result.
     * 
     * @var ?string $title
     */
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;
    
	public function __construct()
	{
		$this->channelId = null;
		$this->channelTitle = null;
		$this->description = null;
		$this->liveBroadcastContent = null;
		$this->publishedAt = null;
		$this->thumbnails = null;
		$this->title = null;
	}
}
