"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import tfl_api_presentation_entities_routesequence as shared_tfl_api_presentation_entities_routesequence
from enum import Enum
from typing import Optional

class LineRouteSequenceDirectionEnum(str, Enum):
    r"""The direction of travel. Can be inbound or outbound."""
    INBOUND = 'inbound'
    OUTBOUND = 'outbound'
    ALL = 'all'

class LineRouteSequenceServiceTypesEnum(str, Enum):
    REGULAR = 'Regular'
    NIGHT = 'Night'


@dataclasses.dataclass
class LineRouteSequenceRequest:
    
    direction: LineRouteSequenceDirectionEnum = dataclasses.field(metadata={'path_param': { 'field_name': 'direction', 'style': 'simple', 'explode': False }})
    r"""The direction of travel. Can be inbound or outbound."""  
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""A single line id e.g. victoria"""  
    exclude_crowding: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'excludeCrowding', 'style': 'form', 'explode': True }})
    r"""That excludes crowding from line disruptions. Can be true or false."""  
    service_types: Optional[list[LineRouteSequenceServiceTypesEnum]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'serviceTypes', 'style': 'form', 'explode': True }})
    r"""A comma seperated list of service types to filter on. Supported values: Regular, Night. Defaulted to 'Regular' if not specified"""  
    

@dataclasses.dataclass
class LineRouteSequenceResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    body: Optional[bytes] = dataclasses.field(default=None)  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    tfl_api_presentation_entities_route_sequence: Optional[shared_tfl_api_presentation_entities_routesequence.TflAPIPresentationEntitiesRouteSequence] = dataclasses.field(default=None)
    r"""OK"""  
    