<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * HttpRouteQueryParameterMatch - Specifications to match a query parameter in the request.
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class HttpRouteQueryParameterMatch
{
    /**
     * The value of the query parameter must exactly match the contents of exact_match. Only one of exact_match, regex_match, or present_match must be set.
     * 
     * @var ?string $exactMatch
     */
	#[\JMS\Serializer\Annotation\SerializedName('exactMatch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $exactMatch = null;
    
    /**
     * Specifies that the QueryParameterMatcher matches if request contains query parameter, irrespective of whether the parameter has a value or not. Only one of exact_match, regex_match, or present_match must be set.
     * 
     * @var ?bool $presentMatch
     */
	#[\JMS\Serializer\Annotation\SerializedName('presentMatch')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $presentMatch = null;
    
    /**
     * The name of the query parameter to match.
     * 
     * @var ?string $queryParameter
     */
	#[\JMS\Serializer\Annotation\SerializedName('queryParameter')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $queryParameter = null;
    
    /**
     * The value of the query parameter must match the regular expression specified by regex_match. For regular expression grammar, please see https://github.com/google/re2/wiki/Syntax Only one of exact_match, regex_match, or present_match must be set.
     * 
     * @var ?string $regexMatch
     */
	#[\JMS\Serializer\Annotation\SerializedName('regexMatch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $regexMatch = null;
    
	public function __construct()
	{
		$this->exactMatch = null;
		$this->presentMatch = null;
		$this->queryParameter = null;
		$this->regexMatch = null;
	}
}
