/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Success
 */
export class DescribeDRTAccessResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "LogBucketList" })
  logBucketList?: string[];

  @SpeakeasyMetadata()
  @Expose({ name: "RoleArn" })
  roleArn?: string;
}
