<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/** dataType */
enum GETAnalyticsDataUsingGETDataTypeEnum: string
{
    case ACTIVE_DEVICES = 'activeDevices';
    case ACTIVE_LOCATIONS = 'activeLocations';
    case ACTIVE_USERS = 'activeUsers';
    case AVERAGE_BANDWIDTH_PER_USER = 'averageBandwidthPerUser';
    case AVERAGE_DAU_OVER_MAU = 'averageDauOverMau';
    case AVERAGE_JS_EXECUTION_TIME = 'averageJsExecutionTime';
    case AVERAGE_REQUESTS_PER_USER = 'averageRequestsPerUser';
    case AVERAGE_RESPONSE_TIME = 'averageResponseTime';
    case AVERAGE_RESPONSE_TIME_PER_TYPE = 'averageResponseTimePerType';
    case SCRIPT_LOG_LEVELS_COUNT = 'scriptLogLevelsCount';
    case SESSION_ANALYTIC = 'sessionAnalytic';
    case STORAGE_PER_USER = 'storagePerUser';
    case CUSTOM_ANALYTIC_TOTAL = 'customAnalyticTotal';
    case CUSTOM_ANALYTIC_USER = 'customAnalyticUser';
    case TIMED_ANALYTIC_TOTAL = 'timedAnalyticTotal';
    case SESSION_ANALYTIC_TOTAL = 'sessionAnalyticTotal';
    case CONNECTED_USERS = 'connectedUsers';
}
