/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ManagedZoneServiceDirectoryConfigNamespace {
    /**
     * The time that the namespace backing this zone was deleted; an empty string if it still exists. This is in RFC3339 text format. Output only.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deletionTime")
    public String deletionTime;

    public ManagedZoneServiceDirectoryConfigNamespace withDeletionTime(String deletionTime) {
        this.deletionTime = deletionTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kind")
    public String kind;

    public ManagedZoneServiceDirectoryConfigNamespace withKind(String kind) {
        this.kind = kind;
        return this;
    }
    
    /**
     * The fully qualified URL of the namespace associated with the zone. Format must be https://servicedirectory.googleapis.com/v1/projects/{project}/locations/{location}/namespaces/{namespace}
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("namespaceUrl")
    public String namespaceUrl;

    public ManagedZoneServiceDirectoryConfigNamespace withNamespaceUrl(String namespaceUrl) {
        this.namespaceUrl = namespaceUrl;
        return this;
    }
    
    public ManagedZoneServiceDirectoryConfigNamespace(){}
}
