package openapisdk.models.shared;


public enum CloudStorageEgressWorkloadDestinationContinentEnum {
    DESTINATION_CONTINENT_UNSPECIFIED("DESTINATION_CONTINENT_UNSPECIFIED"),
    DESTINATION_CONTINENT_ASIA_PACIFIC("DESTINATION_CONTINENT_ASIA_PACIFIC"),
    DESTINATION_CONTINENT_AUTRALIA("DESTINATION_CONTINENT_AUTRALIA"),
    DESTINATION_CONTINENT_EUROPE("DESTINATION_CONTINENT_EUROPE"),
    DESTINATION_CONTINENT_NORTH_AMERICA("DESTINATION_CONTINENT_NORTH_AMERICA"),
    DESTINATION_CONTINENT_SOUTH_AMERICA("DESTINATION_CONTINENT_SOUTH_AMERICA");

    public final String value;

    private CloudStorageEgressWorkloadDestinationContinentEnum(String value) {
        this.value = value;
    }
}
