package openapisdk.models.shared;


public enum CloudInterconnectEgressWorkloadInterconnectConnectionLocationEnum {
    INTERCONNECT_CONNECTION_LOCATION_UNSPECIFIED("INTERCONNECT_CONNECTION_LOCATION_UNSPECIFIED"),
    INTERCONNECT_CONNECTION_LOCATION_ASIA("INTERCONNECT_CONNECTION_LOCATION_ASIA"),
    INTERCONNECT_CONNECTION_LOCATION_EUROPE("INTERCONNECT_CONNECTION_LOCATION_EUROPE"),
    INTERCONNECT_CONNECTION_LOCATION_NORTH_AMERICA("INTERCONNECT_CONNECTION_LOCATION_NORTH_AMERICA"),
    INTERCONNECT_CONNECTION_LOCATION_SOUTH_AMERICA("INTERCONNECT_CONNECTION_LOCATION_SOUTH_AMERICA"),
    INTERCONNECT_CONNECTION_LOCATION_AUSTRALIA("INTERCONNECT_CONNECTION_LOCATION_AUSTRALIA");

    public final String value;

    private CloudInterconnectEgressWorkloadInterconnectConnectionLocationEnum(String value) {
        this.value = value;
    }
}
