package openapisdk.models.shared;


public enum CloudCdnEgressWorkloadCacheEgressDestinationEnum {
    CACHE_EGRESS_DESTINATION_UNSPECIFIED("CACHE_EGRESS_DESTINATION_UNSPECIFIED"),
    CACHE_EGRESS_DESTINATION_ASIA_PACIFIC("CACHE_EGRESS_DESTINATION_ASIA_PACIFIC"),
    CACHE_EGRESS_DESTINATION_CHINA("CACHE_EGRESS_DESTINATION_CHINA"),
    CACHE_EGRESS_DESTINATION_EUROPE("CACHE_EGRESS_DESTINATION_EUROPE"),
    CACHE_EGRESS_DESTINATION_NORTH_AMERICA("CACHE_EGRESS_DESTINATION_NORTH_AMERICA"),
    CACHE_EGRESS_DESTINATION_OCEANIA("CACHE_EGRESS_DESTINATION_OCEANIA"),
    CACHE_EGRESS_DESTINATION_LATIN_AMERICA("CACHE_EGRESS_DESTINATION_LATIN_AMERICA"),
    CACHE_EGRESS_DESTINATION_OTHER_DESTINATIONS("CACHE_EGRESS_DESTINATION_OTHER_DESTINATIONS");

    public final String value;

    private CloudCdnEgressWorkloadCacheEgressDestinationEnum(String value) {
        this.value = value;
    }
}
