package openapisdk.models.shared;


public enum PremiumTierEgressWorkloadDestinationContinentEnum {
    DESTINATION_CONTINENT_UNSPECIFIED("DESTINATION_CONTINENT_UNSPECIFIED"),
    DESTINATION_CONTINENT_ASIA_PACIFIC("DESTINATION_CONTINENT_ASIA_PACIFIC"),
    DESTINATION_CONTINENT_AFRICA("DESTINATION_CONTINENT_AFRICA"),
    DESTINATION_CONTINENT_NORTH_AMERICA("DESTINATION_CONTINENT_NORTH_AMERICA"),
    DESTINATION_CONTINENT_AUTRALIA("DESTINATION_CONTINENT_AUTRALIA"),
    DESTINATION_CONTINENT_CENTRAL_AMERICA("DESTINATION_CONTINENT_CENTRAL_AMERICA"),
    DESTINATION_CONTINENT_CHINA("DESTINATION_CONTINENT_CHINA"),
    DESTINATION_CONTINENT_EASTERN_EUROPE("DESTINATION_CONTINENT_EASTERN_EUROPE"),
    DESTINATION_CONTINENT_WESTERN_EUROPE("DESTINATION_CONTINENT_WESTERN_EUROPE"),
    DESTINATION_CONTINENT_EMEA("DESTINATION_CONTINENT_EMEA"),
    DESTINATION_CONTINENT_INDIA("DESTINATION_CONTINENT_INDIA"),
    DESTINATION_CONTINENT_MIDDLE_EAST("DESTINATION_CONTINENT_MIDDLE_EAST"),
    DESTINATION_CONTINENT_SOUTH_AMERICA("DESTINATION_CONTINENT_SOUTH_AMERICA");

    public final String value;

    private PremiumTierEgressWorkloadDestinationContinentEnum(String value) {
        this.value = value;
    }
}
