package openapisdk.models.shared;


public enum AccountTypeEnum {
    BANK("BANK"),
    CURRENT("CURRENT"),
    CURRLIAB("CURRLIAB"),
    DEPRECIATN("DEPRECIATN"),
    DIRECTCOSTS("DIRECTCOSTS"),
    EQUITY("EQUITY"),
    EXPENSE("EXPENSE"),
    FIXED("FIXED"),
    INVENTORY("INVENTORY"),
    LIABILITY("LIABILITY"),
    NONCURRENT("NONCURRENT"),
    OTHERINCOME("OTHERINCOME"),
    OVERHEADS("OVERHEADS"),
    PREPAYMENT("PREPAYMENT"),
    REVENUE("REVENUE"),
    SALES("SALES"),
    TERMLIAB("TERMLIAB"),
    PAYGLIABILITY("PAYGLIABILITY"),
    PAYG("PAYG"),
    SUPERANNUATIONEXPENSE("SUPERANNUATIONEXPENSE"),
    SUPERANNUATIONLIABILITY("SUPERANNUATIONLIABILITY"),
    WAGESEXPENSE("WAGESEXPENSE"),
    WAGESPAYABLELIABILITY("WAGESPAYABLELIABILITY");

    public final String value;

    private AccountTypeEnum(String value) {
        this.value = value;
    }
}
