/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AuditNodeInfoResponse - OK
 */
public class AuditNodeInfoResponse {
    /**
     * List of audit node info items
     */
    @JsonProperty("items")
    public AuditNodeInfo[] items;
    public AuditNodeInfoResponse withItems(AuditNodeInfo[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * Range information
     */
    @JsonProperty("range")
    public Range range;
    public AuditNodeInfoResponse withRange(Range range) {
        this.range = range;
        return this;
    }
    
}
