<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * ObjectId - An ObjectId specifies an object identifier (OID). These provide context and describe types in ASN.1 messages.
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class ObjectId
{
    /**
     * Required. The parts of an OID path. The most significant parts of the path come first.
     * 
     * @var ?array<int> $objectIdPath
     */
	#[\JMS\Serializer\Annotation\SerializedName('objectIdPath')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $objectIdPath = null;
    
	public function __construct()
	{
		$this->objectIdPath = null;
	}
}
