/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * List of URLs
 */
export class Urls extends SpeakeasyBase {
  /**
   * URLs
   */
  @SpeakeasyMetadata()
  @Expose({ name: "urls" })
  urls: string[];
}
