/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyActionIsolationEnum - Defines the isolation policy for actions on this instance. DO NOT USE: Experimental / unlaunched feature.
 */
public enum GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyActionIsolationEnum {
    ACTION_ISOLATION_UNSPECIFIED("ACTION_ISOLATION_UNSPECIFIED"),
    ACTION_ISOLATION_OFF("ACTION_ISOLATION_OFF"),
    ACTION_ISOLATION_ENFORCED("ACTION_ISOLATION_ENFORCED");

    @JsonValue
    public final String value;

    private GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyActionIsolationEnum(String value) {
        this.value = value;
    }
}
