/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GetAggregateConfigRuleComplianceSummaryRequest {
    
    public GetAggregateConfigRuleComplianceSummaryQueryParams queryParams;
    public GetAggregateConfigRuleComplianceSummaryRequest withQueryParams(GetAggregateConfigRuleComplianceSummaryQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    
    public GetAggregateConfigRuleComplianceSummaryHeaders headers;
    public GetAggregateConfigRuleComplianceSummaryRequest withHeaders(GetAggregateConfigRuleComplianceSummaryHeaders headers) {
        this.headers = headers;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.GetAggregateConfigRuleComplianceSummaryRequest request;
    public GetAggregateConfigRuleComplianceSummaryRequest withRequest(org.openapis.openapi.models.shared.GetAggregateConfigRuleComplianceSummaryRequest request) {
        this.request = request;
        return this;
    }
    
}
