import dataclasses
from datetime import date, datetime
from marshmallow import fields
import dateutil.parser
from enum import Enum
from dataclasses_json import dataclass_json
from sdk import utils

class CustomVisionErrorCodeEnum(str, Enum):
    NO_ERROR = "NoError"
    BAD_REQUEST = "BadRequest"
    BAD_REQUEST_EXCEEDED_BATCH_SIZE = "BadRequestExceededBatchSize"
    BAD_REQUEST_NOT_SUPPORTED = "BadRequestNotSupported"
    BAD_REQUEST_INVALID_IDS = "BadRequestInvalidIds"
    BAD_REQUEST_PROJECT_NAME = "BadRequestProjectName"
    BAD_REQUEST_PROJECT_NAME_NOT_UNIQUE = "BadRequestProjectNameNotUnique"
    BAD_REQUEST_PROJECT_DESCRIPTION = "BadRequestProjectDescription"
    BAD_REQUEST_PROJECT_UNKNOWN_DOMAIN = "BadRequestProjectUnknownDomain"
    BAD_REQUEST_PROJECT_UNKNOWN_CLASSIFICATION = "BadRequestProjectUnknownClassification"
    BAD_REQUEST_PROJECT_UNSUPPORTED_DOMAIN_TYPE_CHANGE = "BadRequestProjectUnsupportedDomainTypeChange"
    BAD_REQUEST_PROJECT_UNSUPPORTED_EXPORT_PLATFORM = "BadRequestProjectUnsupportedExportPlatform"
    BAD_REQUEST_ITERATION_NAME = "BadRequestIterationName"
    BAD_REQUEST_ITERATION_NAME_NOT_UNIQUE = "BadRequestIterationNameNotUnique"
    BAD_REQUEST_ITERATION_DESCRIPTION = "BadRequestIterationDescription"
    BAD_REQUEST_ITERATION_IS_NOT_TRAINED = "BadRequestIterationIsNotTrained"
    BAD_REQUEST_WORKSPACE_CANNOT_BE_MODIFIED = "BadRequestWorkspaceCannotBeModified"
    BAD_REQUEST_WORKSPACE_NOT_DELETABLE = "BadRequestWorkspaceNotDeletable"
    BAD_REQUEST_TAG_NAME = "BadRequestTagName"
    BAD_REQUEST_TAG_NAME_NOT_UNIQUE = "BadRequestTagNameNotUnique"
    BAD_REQUEST_TAG_DESCRIPTION = "BadRequestTagDescription"
    BAD_REQUEST_TAG_TYPE = "BadRequestTagType"
    BAD_REQUEST_MULTIPLE_NEGATIVE_TAG = "BadRequestMultipleNegativeTag"
    BAD_REQUEST_IMAGE_TAGS = "BadRequestImageTags"
    BAD_REQUEST_IMAGE_REGIONS = "BadRequestImageRegions"
    BAD_REQUEST_NEGATIVE_AND_REGULAR_TAG_ON_SAME_IMAGE = "BadRequestNegativeAndRegularTagOnSameImage"
    BAD_REQUEST_REQUIRED_PARAM_IS_NULL = "BadRequestRequiredParamIsNull"
    BAD_REQUEST_ITERATION_IS_PUBLISHED = "BadRequestIterationIsPublished"
    BAD_REQUEST_INVALID_PUBLISH_NAME = "BadRequestInvalidPublishName"
    BAD_REQUEST_INVALID_PUBLISH_TARGET = "BadRequestInvalidPublishTarget"
    BAD_REQUEST_UNPUBLISH_FAILED = "BadRequestUnpublishFailed"
    BAD_REQUEST_ITERATION_NOT_PUBLISHED = "BadRequestIterationNotPublished"
    BAD_REQUEST_SUBSCRIPTION_API = "BadRequestSubscriptionApi"
    BAD_REQUEST_EXCEED_PROJECT_LIMIT = "BadRequestExceedProjectLimit"
    BAD_REQUEST_EXCEED_ITERATION_PER_PROJECT_LIMIT = "BadRequestExceedIterationPerProjectLimit"
    BAD_REQUEST_EXCEED_TAG_PER_PROJECT_LIMIT = "BadRequestExceedTagPerProjectLimit"
    BAD_REQUEST_EXCEED_TAG_PER_IMAGE_LIMIT = "BadRequestExceedTagPerImageLimit"
    BAD_REQUEST_EXCEEDED_QUOTA = "BadRequestExceededQuota"
    BAD_REQUEST_CANNOT_MIGRATE_PROJECT_WITH_NAME = "BadRequestCannotMigrateProjectWithName"
    BAD_REQUEST_NOT_LIMITED_TRIAL = "BadRequestNotLimitedTrial"
    BAD_REQUEST_IMAGE_BATCH = "BadRequestImageBatch"
    BAD_REQUEST_IMAGE_STREAM = "BadRequestImageStream"
    BAD_REQUEST_IMAGE_URL = "BadRequestImageUrl"
    BAD_REQUEST_IMAGE_FORMAT = "BadRequestImageFormat"
    BAD_REQUEST_IMAGE_SIZE_BYTES = "BadRequestImageSizeBytes"
    BAD_REQUEST_IMAGE_EXCEEDED_COUNT = "BadRequestImageExceededCount"
    BAD_REQUEST_TRAINING_NOT_NEEDED = "BadRequestTrainingNotNeeded"
    BAD_REQUEST_TRAINING_NOT_NEEDED_BUT_TRAINING_PIPELINE_UPDATED = "BadRequestTrainingNotNeededButTrainingPipelineUpdated"
    BAD_REQUEST_TRAINING_VALIDATION_FAILED = "BadRequestTrainingValidationFailed"
    BAD_REQUEST_CLASSIFICATION_TRAINING_VALIDATION_FAILED = "BadRequestClassificationTrainingValidationFailed"
    BAD_REQUEST_MULTI_CLASS_CLASSIFICATION_TRAINING_VALIDATION_FAILED = "BadRequestMultiClassClassificationTrainingValidationFailed"
    BAD_REQUEST_MULTI_LABEL_CLASSIFICATION_TRAINING_VALIDATION_FAILED = "BadRequestMultiLabelClassificationTrainingValidationFailed"
    BAD_REQUEST_DETECTION_TRAINING_VALIDATION_FAILED = "BadRequestDetectionTrainingValidationFailed"
    BAD_REQUEST_TRAINING_ALREADY_IN_PROGRESS = "BadRequestTrainingAlreadyInProgress"
    BAD_REQUEST_DETECTION_TRAINING_NOT_ALLOW_NEGATIVE_TAG = "BadRequestDetectionTrainingNotAllowNegativeTag"
    BAD_REQUEST_INVALID_EMAIL_ADDRESS = "BadRequestInvalidEmailAddress"
    BAD_REQUEST_DOMAIN_NOT_SUPPORTED_FOR_ADVANCED_TRAINING = "BadRequestDomainNotSupportedForAdvancedTraining"
    BAD_REQUEST_EXPORT_PLATFORM_NOT_SUPPORTED_FOR_ADVANCED_TRAINING = "BadRequestExportPlatformNotSupportedForAdvancedTraining"
    BAD_REQUEST_RESERVED_BUDGET_IN_HOURS_NOT_ENOUGH_FOR_ADVANCED_TRAINING = "BadRequestReservedBudgetInHoursNotEnoughForAdvancedTraining"
    BAD_REQUEST_EXPORT_VALIDATION_FAILED = "BadRequestExportValidationFailed"
    BAD_REQUEST_EXPORT_ALREADY_IN_PROGRESS = "BadRequestExportAlreadyInProgress"
    BAD_REQUEST_PREDICTION_IDS_MISSING = "BadRequestPredictionIdsMissing"
    BAD_REQUEST_PREDICTION_IDS_EXCEEDED_COUNT = "BadRequestPredictionIdsExceededCount"
    BAD_REQUEST_PREDICTION_TAGS_EXCEEDED_COUNT = "BadRequestPredictionTagsExceededCount"
    BAD_REQUEST_PREDICTION_RESULTS_EXCEEDED_COUNT = "BadRequestPredictionResultsExceededCount"
    BAD_REQUEST_PREDICTION_INVALID_APPLICATION_NAME = "BadRequestPredictionInvalidApplicationName"
    BAD_REQUEST_PREDICTION_INVALID_QUERY_PARAMETERS = "BadRequestPredictionInvalidQueryParameters"
    BAD_REQUEST_INVALID = "BadRequestInvalid"
    UNSUPPORTED_MEDIA_TYPE = "UnsupportedMediaType"
    FORBIDDEN = "Forbidden"
    FORBIDDEN_USER = "ForbiddenUser"
    FORBIDDEN_USER_RESOURCE = "ForbiddenUserResource"
    FORBIDDEN_USER_SIGNUP_DISABLED = "ForbiddenUserSignupDisabled"
    FORBIDDEN_USER_SIGNUP_ALLOWANCE_EXCEEDED = "ForbiddenUserSignupAllowanceExceeded"
    FORBIDDEN_USER_DOES_NOT_EXIST = "ForbiddenUserDoesNotExist"
    FORBIDDEN_USER_DISABLED = "ForbiddenUserDisabled"
    FORBIDDEN_USER_INSUFFICIENT_CAPABILITY = "ForbiddenUserInsufficientCapability"
    FORBIDDEN_DR_MODE_ENABLED = "ForbiddenDRModeEnabled"
    FORBIDDEN_INVALID = "ForbiddenInvalid"
    NOT_FOUND = "NotFound"
    NOT_FOUND_PROJECT = "NotFoundProject"
    NOT_FOUND_PROJECT_DEFAULT_ITERATION = "NotFoundProjectDefaultIteration"
    NOT_FOUND_ITERATION = "NotFoundIteration"
    NOT_FOUND_ITERATION_PERFORMANCE = "NotFoundIterationPerformance"
    NOT_FOUND_TAG = "NotFoundTag"
    NOT_FOUND_IMAGE = "NotFoundImage"
    NOT_FOUND_DOMAIN = "NotFoundDomain"
    NOT_FOUND_APIM_SUBSCRIPTION = "NotFoundApimSubscription"
    NOT_FOUND_INVALID = "NotFoundInvalid"
    CONFLICT = "Conflict"
    CONFLICT_INVALID = "ConflictInvalid"
    ERROR_UNKNOWN = "ErrorUnknown"
    ERROR_PROJECT_INVALID_WORKSPACE = "ErrorProjectInvalidWorkspace"
    ERROR_PROJECT_INVALID_PIPELINE_CONFIGURATION = "ErrorProjectInvalidPipelineConfiguration"
    ERROR_PROJECT_INVALID_DOMAIN = "ErrorProjectInvalidDomain"
    ERROR_PROJECT_TRAINING_REQUEST_FAILED = "ErrorProjectTrainingRequestFailed"
    ERROR_PROJECT_EXPORT_REQUEST_FAILED = "ErrorProjectExportRequestFailed"
    ERROR_FEATURIZATION_SERVICE_UNAVAILABLE = "ErrorFeaturizationServiceUnavailable"
    ERROR_FEATURIZATION_QUEUE_TIMEOUT = "ErrorFeaturizationQueueTimeout"
    ERROR_FEATURIZATION_INVALID_FEATURIZER = "ErrorFeaturizationInvalidFeaturizer"
    ERROR_FEATURIZATION_AUGMENTATION_UNAVAILABLE = "ErrorFeaturizationAugmentationUnavailable"
    ERROR_FEATURIZATION_UNRECOGNIZED_JOB = "ErrorFeaturizationUnrecognizedJob"
    ERROR_FEATURIZATION_AUGMENTATION_ERROR = "ErrorFeaturizationAugmentationError"
    ERROR_EXPORTER_INVALID_PLATFORM = "ErrorExporterInvalidPlatform"
    ERROR_EXPORTER_INVALID_FEATURIZER = "ErrorExporterInvalidFeaturizer"
    ERROR_EXPORTER_INVALID_CLASSIFIER = "ErrorExporterInvalidClassifier"
    ERROR_PREDICTION_SERVICE_UNAVAILABLE = "ErrorPredictionServiceUnavailable"
    ERROR_PREDICTION_MODEL_NOT_FOUND = "ErrorPredictionModelNotFound"
    ERROR_PREDICTION_MODEL_NOT_CACHED = "ErrorPredictionModelNotCached"
    ERROR_PREDICTION = "ErrorPrediction"
    ERROR_PREDICTION_STORAGE = "ErrorPredictionStorage"
    ERROR_REGION_PROPOSAL = "ErrorRegionProposal"
    ERROR_INVALID = "ErrorInvalid"


@dataclass_json
@dataclasses.dataclass
class CustomVisionError:
    code: CustomVisionErrorCodeEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.field_name('code') }})
    message: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.field_name('message') }})
    
