"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from typing import Optional


@dataclasses.dataclass
class EventSubscription:
    r"""Detailed information about an event to which you have subscribed."""
    
    customer_aws_id: Optional[str] = dataclasses.field(default=None)  
    cust_subscription_id: Optional[str] = dataclasses.field(default=None)  
    enabled: Optional[bool] = dataclasses.field(default=None)  
    event_categories_list: Optional[list[str]] = dataclasses.field(default=None)  
    event_subscription_arn: Optional[str] = dataclasses.field(default=None)  
    sns_topic_arn: Optional[str] = dataclasses.field(default=None)  
    source_ids_list: Optional[list[str]] = dataclasses.field(default=None)  
    source_type: Optional[str] = dataclasses.field(default=None)  
    status: Optional[str] = dataclasses.field(default=None)  
    subscription_creation_time: Optional[str] = dataclasses.field(default=None)  
    