/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class GETDetachInternetGatewayRequest {
    
    public GETDetachInternetGatewayQueryParams queryParams;
    public GETDetachInternetGatewayRequest withQueryParams(GETDetachInternetGatewayQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    
    public GETDetachInternetGatewayHeaders headers;
    public GETDetachInternetGatewayRequest withHeaders(GETDetachInternetGatewayHeaders headers) {
        this.headers = headers;
        return this;
    }
    
}
