package openapisdk.models.shared;


public enum ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum {
    VIDEO_DURATION_UNSPECIFIED("VIDEO_DURATION_UNSPECIFIED"),
    VIDEO_DURATION_SECONDS_NONE("VIDEO_DURATION_SECONDS_NONE"),
    VIDEO_DURATION_SECONDS0("VIDEO_DURATION_SECONDS_0"),
    VIDEO_DURATION_SECONDS1("VIDEO_DURATION_SECONDS_1"),
    VIDEO_DURATION_SECONDS2("VIDEO_DURATION_SECONDS_2"),
    VIDEO_DURATION_SECONDS3("VIDEO_DURATION_SECONDS_3"),
    VIDEO_DURATION_SECONDS4("VIDEO_DURATION_SECONDS_4"),
    VIDEO_DURATION_SECONDS5("VIDEO_DURATION_SECONDS_5"),
    VIDEO_DURATION_SECONDS6("VIDEO_DURATION_SECONDS_6"),
    VIDEO_DURATION_SECONDS7("VIDEO_DURATION_SECONDS_7"),
    VIDEO_DURATION_SECONDS8("VIDEO_DURATION_SECONDS_8"),
    VIDEO_DURATION_SECONDS9("VIDEO_DURATION_SECONDS_9"),
    VIDEO_DURATION_SECONDS10("VIDEO_DURATION_SECONDS_10"),
    VIDEO_DURATION_SECONDS11("VIDEO_DURATION_SECONDS_11"),
    VIDEO_DURATION_SECONDS12("VIDEO_DURATION_SECONDS_12"),
    VIDEO_DURATION_SECONDS13("VIDEO_DURATION_SECONDS_13"),
    VIDEO_DURATION_SECONDS14("VIDEO_DURATION_SECONDS_14"),
    VIDEO_DURATION_SECONDS15("VIDEO_DURATION_SECONDS_15"),
    VIDEO_DURATION_SECONDS30("VIDEO_DURATION_SECONDS_30"),
    VIDEO_DURATION_SECONDS45("VIDEO_DURATION_SECONDS_45"),
    VIDEO_DURATION_SECONDS60("VIDEO_DURATION_SECONDS_60");

    public final String value;

    private ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum(String value) {
        this.value = value;
    }
}
