package openapisdk.models.shared;


public enum AppAssignedTargetingOptionDetailsAppPlatformEnum {
    APP_PLATFORM_UNSPECIFIED("APP_PLATFORM_UNSPECIFIED"),
    APP_PLATFORM_IOS("APP_PLATFORM_IOS"),
    APP_PLATFORM_ANDROID("APP_PLATFORM_ANDROID"),
    APP_PLATFORM_ROKU("APP_PLATFORM_ROKU"),
    APP_PLATFORM_AMAZON_FIRETV("APP_PLATFORM_AMAZON_FIRETV"),
    APP_PLATFORM_PLAYSTATION("APP_PLATFORM_PLAYSTATION"),
    APP_PLATFORM_APPLE_TV("APP_PLATFORM_APPLE_TV"),
    APP_PLATFORM_XBOX("APP_PLATFORM_XBOX"),
    APP_PLATFORM_SAMSUNG_TV("APP_PLATFORM_SAMSUNG_TV"),
    APP_PLATFORM_ANDROID_TV("APP_PLATFORM_ANDROID_TV"),
    APP_PLATFORM_GENERIC_CTV("APP_PLATFORM_GENERIC_CTV");

    public final String value;

    private AppAssignedTargetingOptionDetailsAppPlatformEnum(String value) {
        this.value = value;
    }
}
