package openapisdk.models.shared;


public enum CampaignGoalCampaignGoalTypeEnum {
    CAMPAIGN_GOAL_TYPE_UNSPECIFIED("CAMPAIGN_GOAL_TYPE_UNSPECIFIED"),
    CAMPAIGN_GOAL_TYPE_APP_INSTALL("CAMPAIGN_GOAL_TYPE_APP_INSTALL"),
    CAMPAIGN_GOAL_TYPE_BRAND_AWARENESS("CAMPAIGN_GOAL_TYPE_BRAND_AWARENESS"),
    CAMPAIGN_GOAL_TYPE_OFFLINE_ACTION("CAMPAIGN_GOAL_TYPE_OFFLINE_ACTION"),
    CAMPAIGN_GOAL_TYPE_ONLINE_ACTION("CAMPAIGN_GOAL_TYPE_ONLINE_ACTION");

    public final String value;

    private CampaignGoalCampaignGoalTypeEnum(String value) {
        this.value = value;
    }
}
