package openapisdk.models.shared;


public enum DoubleVerifyVideoViewabilityVideoIabEnum {
    VIDEO_IAB_UNSPECIFIED("VIDEO_IAB_UNSPECIFIED"),
    IAB_VIEWABILITY80_PERCENT_HIGHER("IAB_VIEWABILITY_80_PERCENT_HIGHER"),
    IAB_VIEWABILITY75_PERCENT_HIGHER("IAB_VIEWABILITY_75_PERCENT_HIGHER"),
    IAB_VIEWABILITY70_PERCENT_HIGHER("IAB_VIEWABILITY_70_PERCENT_HIGHER"),
    IAB_VIEWABILITY65_PERCENT_HIHGER("IAB_VIEWABILITY_65_PERCENT_HIHGER"),
    IAB_VIEWABILITY60_PERCENT_HIGHER("IAB_VIEWABILITY_60_PERCENT_HIGHER"),
    IAB_VIEWABILITY55_PERCENT_HIHGER("IAB_VIEWABILITY_55_PERCENT_HIHGER"),
    IAB_VIEWABILITY50_PERCENT_HIGHER("IAB_VIEWABILITY_50_PERCENT_HIGHER"),
    IAB_VIEWABILITY40_PERCENT_HIHGER("IAB_VIEWABILITY_40_PERCENT_HIHGER"),
    IAB_VIEWABILITY30_PERCENT_HIHGER("IAB_VIEWABILITY_30_PERCENT_HIHGER");

    public final String value;

    private DoubleVerifyVideoViewabilityVideoIabEnum(String value) {
        this.value = value;
    }
}
