package openapisdk.models.shared;


public enum DoubleVerifyBrandSafetyCategoriesAvoidedMediumSeverityCategoriesEnum {
    MEDIUM_SEVERITY_UNSPECIFIED("MEDIUM_SEVERITY_UNSPECIFIED"),
    AD_SERVERS("AD_SERVERS"),
    ADULT_CONTENT_SWIMSUIT("ADULT_CONTENT_SWIMSUIT"),
    ALTERNATIVE_LIFESTYLES("ALTERNATIVE_LIFESTYLES"),
    CELEBRITY_GOSSIP("CELEBRITY_GOSSIP"),
    GAMBLING("GAMBLING"),
    OCCULT("OCCULT"),
    SEX_EDUCATION("SEX_EDUCATION"),
    DISASTER_AVIATION("DISASTER_AVIATION"),
    DISASTER_MAN_MADE("DISASTER_MAN_MADE"),
    DISASTER_NATURAL("DISASTER_NATURAL"),
    DISASTER_TERRORIST_EVENTS("DISASTER_TERRORIST_EVENTS"),
    DISASTER_VEHICLE("DISASTER_VEHICLE"),
    ALCOHOL("ALCOHOL"),
    SMOKING("SMOKING"),
    NEGATIVE_NEWS_FINANCIAL("NEGATIVE_NEWS_FINANCIAL"),
    NON_ENGLISH("NON_ENGLISH"),
    PARKING_PAGE("PARKING_PAGE"),
    UNMODERATED_UGC("UNMODERATED_UGC"),
    INFLAMMATORY_POLITICS_AND_NEWS("INFLAMMATORY_POLITICS_AND_NEWS"),
    NEGATIVE_NEWS_PHARMACEUTICAL("NEGATIVE_NEWS_PHARMACEUTICAL");

    public final String value;

    private DoubleVerifyBrandSafetyCategoriesAvoidedMediumSeverityCategoriesEnum(String value) {
        this.value = value;
    }
}
