package openapisdk.models.shared;


public enum PerformanceGoalPerformanceGoalTypeEnum {
    PERFORMANCE_GOAL_TYPE_UNSPECIFIED("PERFORMANCE_GOAL_TYPE_UNSPECIFIED"),
    PERFORMANCE_GOAL_TYPE_CPM("PERFORMANCE_GOAL_TYPE_CPM"),
    PERFORMANCE_GOAL_TYPE_CPC("PERFORMANCE_GOAL_TYPE_CPC"),
    PERFORMANCE_GOAL_TYPE_CPA("PERFORMANCE_GOAL_TYPE_CPA"),
    PERFORMANCE_GOAL_TYPE_CTR("PERFORMANCE_GOAL_TYPE_CTR"),
    PERFORMANCE_GOAL_TYPE_VIEWABILITY("PERFORMANCE_GOAL_TYPE_VIEWABILITY"),
    PERFORMANCE_GOAL_TYPE_CPIAVC("PERFORMANCE_GOAL_TYPE_CPIAVC"),
    PERFORMANCE_GOAL_TYPE_CPE("PERFORMANCE_GOAL_TYPE_CPE"),
    PERFORMANCE_GOAL_TYPE_CLICK_CVR("PERFORMANCE_GOAL_TYPE_CLICK_CVR"),
    PERFORMANCE_GOAL_TYPE_IMPRESSION_CVR("PERFORMANCE_GOAL_TYPE_IMPRESSION_CVR"),
    PERFORMANCE_GOAL_TYPE_VCPM("PERFORMANCE_GOAL_TYPE_VCPM"),
    PERFORMANCE_GOAL_TYPE_VTR("PERFORMANCE_GOAL_TYPE_VTR"),
    PERFORMANCE_GOAL_TYPE_AUDIO_COMPLETION_RATE("PERFORMANCE_GOAL_TYPE_AUDIO_COMPLETION_RATE"),
    PERFORMANCE_GOAL_TYPE_VIDEO_COMPLETION_RATE("PERFORMANCE_GOAL_TYPE_VIDEO_COMPLETION_RATE"),
    PERFORMANCE_GOAL_TYPE_OTHER("PERFORMANCE_GOAL_TYPE_OTHER");

    public final String value;

    private PerformanceGoalPerformanceGoalTypeEnum(String value) {
        this.value = value;
    }
}
