/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GetSchemaVersionsDiffRequest {
    
    public GetSchemaVersionsDiffHeaders headers;
    public GetSchemaVersionsDiffRequest withHeaders(GetSchemaVersionsDiffHeaders headers) {
        this.headers = headers;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.GetSchemaVersionsDiffInput request;
    public GetSchemaVersionsDiffRequest withRequest(org.openapis.openapi.models.shared.GetSchemaVersionsDiffInput request) {
        this.request = request;
        return this;
    }
    
}
