/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetSchemaXAmzTargetEnum
 */
public enum GetSchemaXAmzTargetEnum {
    AWS_GLUE_GET_SCHEMA("AWSGlue.GetSchema");

    @JsonValue
    public final String value;

    private GetSchemaXAmzTargetEnum(String value) {
        this.value = value;
    }
}
