// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// GETDeleteVpnGatewayActionEnum
type GETDeleteVpnGatewayActionEnum string

const (
	GETDeleteVpnGatewayActionEnumDeleteVpnGateway GETDeleteVpnGatewayActionEnum = "DeleteVpnGateway"
)

func (e *GETDeleteVpnGatewayActionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "DeleteVpnGateway":
		*e = GETDeleteVpnGatewayActionEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GETDeleteVpnGatewayActionEnum: %s", s)
	}
}

// GETDeleteVpnGatewayVersionEnum
type GETDeleteVpnGatewayVersionEnum string

const (
	GETDeleteVpnGatewayVersionEnumTwoThousandAndSixteen1115 GETDeleteVpnGatewayVersionEnum = "2016-11-15"
)

func (e *GETDeleteVpnGatewayVersionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "2016-11-15":
		*e = GETDeleteVpnGatewayVersionEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GETDeleteVpnGatewayVersionEnum: %s", s)
	}
}

type GETDeleteVpnGatewayQueryParams struct {
	Action GETDeleteVpnGatewayActionEnum `queryParam:"style=form,explode=true,name=Action"`
	// Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is <code>DryRunOperation</code>. Otherwise, it is <code>UnauthorizedOperation</code>.
	DryRun  *bool                          `queryParam:"style=form,explode=true,name=DryRun"`
	Version GETDeleteVpnGatewayVersionEnum `queryParam:"style=form,explode=true,name=Version"`
	// The ID of the virtual private gateway.
	VpnGatewayID string `queryParam:"style=form,explode=true,name=VpnGatewayId"`
}

type GETDeleteVpnGatewayHeaders struct {
	XAmzAlgorithm     *string `header:"style=simple,explode=false,name=X-Amz-Algorithm"`
	XAmzContentSha256 *string `header:"style=simple,explode=false,name=X-Amz-Content-Sha256"`
	XAmzCredential    *string `header:"style=simple,explode=false,name=X-Amz-Credential"`
	XAmzDate          *string `header:"style=simple,explode=false,name=X-Amz-Date"`
	XAmzSecurityToken *string `header:"style=simple,explode=false,name=X-Amz-Security-Token"`
	XAmzSignature     *string `header:"style=simple,explode=false,name=X-Amz-Signature"`
	XAmzSignedHeaders *string `header:"style=simple,explode=false,name=X-Amz-SignedHeaders"`
}

type GETDeleteVpnGatewayRequest struct {
	QueryParams GETDeleteVpnGatewayQueryParams
	Headers     GETDeleteVpnGatewayHeaders
}

type GETDeleteVpnGatewayResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
