// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// POSTDescribeInstanceTypesActionEnum
type POSTDescribeInstanceTypesActionEnum string

const (
	POSTDescribeInstanceTypesActionEnumDescribeInstanceTypes POSTDescribeInstanceTypesActionEnum = "DescribeInstanceTypes"
)

func (e *POSTDescribeInstanceTypesActionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "DescribeInstanceTypes":
		*e = POSTDescribeInstanceTypesActionEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for POSTDescribeInstanceTypesActionEnum: %s", s)
	}
}

// POSTDescribeInstanceTypesVersionEnum
type POSTDescribeInstanceTypesVersionEnum string

const (
	POSTDescribeInstanceTypesVersionEnumTwoThousandAndSixteen1115 POSTDescribeInstanceTypesVersionEnum = "2016-11-15"
)

func (e *POSTDescribeInstanceTypesVersionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "2016-11-15":
		*e = POSTDescribeInstanceTypesVersionEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for POSTDescribeInstanceTypesVersionEnum: %s", s)
	}
}

type POSTDescribeInstanceTypesRequest struct {
	Action POSTDescribeInstanceTypesActionEnum `queryParam:"style=form,explode=true,name=Action"`
	// Pagination limit
	MaxResults *string `queryParam:"style=form,explode=true,name=MaxResults"`
	// Pagination token
	NextToken         *string                              `queryParam:"style=form,explode=true,name=NextToken"`
	RequestBody       []byte                               `request:"mediaType=text/xml"`
	Version           POSTDescribeInstanceTypesVersionEnum `queryParam:"style=form,explode=true,name=Version"`
	XAmzAlgorithm     *string                              `header:"style=simple,explode=false,name=X-Amz-Algorithm"`
	XAmzContentSha256 *string                              `header:"style=simple,explode=false,name=X-Amz-Content-Sha256"`
	XAmzCredential    *string                              `header:"style=simple,explode=false,name=X-Amz-Credential"`
	XAmzDate          *string                              `header:"style=simple,explode=false,name=X-Amz-Date"`
	XAmzSecurityToken *string                              `header:"style=simple,explode=false,name=X-Amz-Security-Token"`
	XAmzSignature     *string                              `header:"style=simple,explode=false,name=X-Amz-Signature"`
	XAmzSignedHeaders *string                              `header:"style=simple,explode=false,name=X-Amz-SignedHeaders"`
}

type POSTDescribeInstanceTypesResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
