/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class ListAssociatedGroupsRequest {
    
    public ListAssociatedGroupsPathParams pathParams;
    public ListAssociatedGroupsRequest withPathParams(ListAssociatedGroupsPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
    
    public ListAssociatedGroupsQueryParams queryParams;
    public ListAssociatedGroupsRequest withQueryParams(ListAssociatedGroupsQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    
    public ListAssociatedGroupsHeaders headers;
    public ListAssociatedGroupsRequest withHeaders(ListAssociatedGroupsHeaders headers) {
        this.headers = headers;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ListAssociatedGroupsRequestBody request;
    public ListAssociatedGroupsRequest withRequest(ListAssociatedGroupsRequestBody request) {
        this.request = request;
        return this;
    }
    
}
