/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EdgePackagingJobStatusEnum } from "./edgepackagingjobstatusenum";
import { ListEdgePackagingJobsSortByEnum } from "./listedgepackagingjobssortbyenum";
import { SortOrderEnum } from "./sortorderenum";
import { Expose, Transform } from "class-transformer";

export class ListEdgePackagingJobsRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "CreationTimeAfter" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  creationTimeAfter?: Date;

  @SpeakeasyMetadata()
  @Expose({ name: "CreationTimeBefore" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  creationTimeBefore?: Date;

  @SpeakeasyMetadata()
  @Expose({ name: "LastModifiedTimeAfter" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  lastModifiedTimeAfter?: Date;

  @SpeakeasyMetadata()
  @Expose({ name: "LastModifiedTimeBefore" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  lastModifiedTimeBefore?: Date;

  @SpeakeasyMetadata()
  @Expose({ name: "MaxResults" })
  maxResults?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "ModelNameContains" })
  modelNameContains?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "NameContains" })
  nameContains?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "NextToken" })
  nextToken?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "SortBy" })
  sortBy?: ListEdgePackagingJobsSortByEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "SortOrder" })
  sortOrder?: SortOrderEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "StatusEquals" })
  statusEquals?: EdgePackagingJobStatusEnum;
}
