// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PurchaseReservedNodeOfferingResult - Success
type PurchaseReservedNodeOfferingResult struct {
	// Describes a reserved node. You can call the <a>DescribeReservedNodeOfferings</a> API to obtain the available reserved node offerings.
	ReservedNode *ReservedNode
}
