<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


enum S3InputFileTypeEnum: string
{
    case CSV = 'CSV';
    case JSON = 'JSON';
}
