package openapisdk.models.shared;


public enum NotificationSettingNotificationTypesEnum {
    NOTIFICATION_TYPE_UNSPECIFIED("NOTIFICATION_TYPE_UNSPECIFIED"),
    GOOGLE_UPDATE("GOOGLE_UPDATE"),
    NEW_REVIEW("NEW_REVIEW"),
    UPDATED_REVIEW("UPDATED_REVIEW"),
    NEW_CUSTOMER_MEDIA("NEW_CUSTOMER_MEDIA"),
    NEW_QUESTION("NEW_QUESTION"),
    UPDATED_QUESTION("UPDATED_QUESTION"),
    NEW_ANSWER("NEW_ANSWER"),
    UPDATED_ANSWER("UPDATED_ANSWER"),
    DUPLICATE_LOCATION("DUPLICATE_LOCATION"),
    LOSS_OF_VOICE_OF_MERCHANT("LOSS_OF_VOICE_OF_MERCHANT"),
    VOICE_OF_MERCHANT_UPDATED("VOICE_OF_MERCHANT_UPDATED");

    public final String value;

    private NotificationSettingNotificationTypesEnum(String value) {
        this.value = value;
    }
}
