/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OrdersCustomBatchRequestEntryShipLineItemsShipmentInfo } from "./orderscustombatchrequestentryshiplineitemsshipmentinfo";
import { OrderShipmentLineItemShipment } from "./ordershipmentlineitemshipment";
import { Expose, Type } from "class-transformer";

export class OrdersShipLineItemsRequest extends SpeakeasyBase {
  /**
   * Line items to ship.
   */
  @SpeakeasyMetadata({ elemType: OrderShipmentLineItemShipment })
  @Expose({ name: "lineItems" })
  @Type(() => OrderShipmentLineItemShipment)
  lineItems?: OrderShipmentLineItemShipment[];

  /**
   * The ID of the operation. Unique across all operations for a given order.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "operationId" })
  operationId?: string;

  /**
   * ID of the shipment group. Required for orders that use the orderinvoices service.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "shipmentGroupId" })
  shipmentGroupId?: string;

  /**
   * Shipment information. This field is repeated because a single line item can be shipped in several packages (and have several tracking IDs).
   */
  @SpeakeasyMetadata({
    elemType: OrdersCustomBatchRequestEntryShipLineItemsShipmentInfo,
  })
  @Expose({ name: "shipmentInfos" })
  @Type(() => OrdersCustomBatchRequestEntryShipLineItemsShipmentInfo)
  shipmentInfos?: OrdersCustomBatchRequestEntryShipLineItemsShipmentInfo[];
}
