<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/** Indicates the ranking importance given to property when it is matched during retrieval. Once set, the token importance of a property cannot be changed. */
enum RetrievalImportanceImportanceEnum: string
{
    case DEFAULT = 'DEFAULT';
    case HIGHEST = 'HIGHEST';
    case HIGH = 'HIGH';
    case LOW = 'LOW';
    case NONE = 'NONE';
}
