/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NewTransitVirtualInterface - Information about a transit virtual interface.
 */
public class NewTransitVirtualInterface {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addressFamily")
    public AddressFamilyEnum addressFamily;

    public NewTransitVirtualInterface withAddressFamily(AddressFamilyEnum addressFamily) {
        this.addressFamily = addressFamily;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amazonAddress")
    public String amazonAddress;

    public NewTransitVirtualInterface withAmazonAddress(String amazonAddress) {
        this.amazonAddress = amazonAddress;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("asn")
    public Long asn;

    public NewTransitVirtualInterface withAsn(Long asn) {
        this.asn = asn;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authKey")
    public String authKey;

    public NewTransitVirtualInterface withAuthKey(String authKey) {
        this.authKey = authKey;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customerAddress")
    public String customerAddress;

    public NewTransitVirtualInterface withCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("directConnectGatewayId")
    public String directConnectGatewayId;

    public NewTransitVirtualInterface withDirectConnectGatewayId(String directConnectGatewayId) {
        this.directConnectGatewayId = directConnectGatewayId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("enableSiteLink")
    public Boolean enableSiteLink;

    public NewTransitVirtualInterface withEnableSiteLink(Boolean enableSiteLink) {
        this.enableSiteLink = enableSiteLink;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mtu")
    public Long mtu;

    public NewTransitVirtualInterface withMtu(Long mtu) {
        this.mtu = mtu;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    public Tag[] tags;

    public NewTransitVirtualInterface withTags(Tag[] tags) {
        this.tags = tags;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("virtualInterfaceName")
    public String virtualInterfaceName;

    public NewTransitVirtualInterface withVirtualInterfaceName(String virtualInterfaceName) {
        this.virtualInterfaceName = virtualInterfaceName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vlan")
    public Long vlan;

    public NewTransitVirtualInterface withVlan(Long vlan) {
        this.vlan = vlan;
        return this;
    }
    
    public NewTransitVirtualInterface(){}
}
