/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class RepoMirrorSyncPathParams {
    /**
     * owner of the repo to sync
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=owner")
    public String owner;
    public RepoMirrorSyncPathParams withOwner(String owner) {
        this.owner = owner;
        return this;
    }
    
    /**
     * name of the repo to sync
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=repo")
    public String repo;
    public RepoMirrorSyncPathParams withRepo(String repo) {
        this.repo = repo;
        return this;
    }
    
}
