/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class RepoGetTagRequest {
    
    public RepoGetTagPathParams pathParams;
    public RepoGetTagRequest withPathParams(RepoGetTagPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
