// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GETGenesByKeywordUsingGETPathParams struct {
	// Search keyword
	Keyword string `pathParam:"style=simple,explode=false,name=keyword"`
	// Species type key.  A list of species type keys can be found in the lookup service
	SpeciesTypeKey int `pathParam:"style=simple,explode=false,name=speciesTypeKey"`
}

type GETGenesByKeywordUsingGETRequest struct {
	PathParams GETGenesByKeywordUsingGETPathParams
}

type GETGenesByKeywordUsingGETResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
