from .getdistrictevents import *
from .getdistricteventskeys import *
from .getdistricteventssimple import *
from .getdistrictrankings import *
from .getdistrictsbyyear import *
from .getdistrictteams import *
from .getdistrictteamskeys import *
from .getdistrictteamssimple import *
from .getevent import *
from .geteventalliances import *
from .geteventawards import *
from .geteventdistrictpoints import *
from .geteventinsights import *
from .geteventmatches import *
from .geteventmatcheskeys import *
from .geteventmatchessimple import *
from .geteventmatchtimeseries import *
from .geteventoprs import *
from .geteventpredictions import *
from .geteventrankings import *
from .geteventsbyyear import *
from .geteventsbyyearkeys import *
from .geteventsbyyearsimple import *
from .geteventsimple import *
from .geteventteams import *
from .geteventteamskeys import *
from .geteventteamssimple import *
from .geteventteamsstatuses import *
from .getmatch import *
from .getmatchsimple import *
from .getmatchtimeseries import *
from .getmatchzebra import *
from .getstatus import *
from .getteam import *
from .getteamawards import *
from .getteamawardsbyyear import *
from .getteamdistricts import *
from .getteameventawards import *
from .getteameventmatches import *
from .getteameventmatcheskeys import *
from .getteameventmatchessimple import *
from .getteamevents import *
from .getteameventsbyyear import *
from .getteameventsbyyearkeys import *
from .getteameventsbyyearsimple import *
from .getteameventskeys import *
from .getteameventssimple import *
from .getteameventsstatusesbyyear import *
from .getteameventstatus import *
from .getteammatchesbyyear import *
from .getteammatchesbyyearkeys import *
from .getteammatchesbyyearsimple import *
from .getteammediabytag import *
from .getteammediabytagyear import *
from .getteammediabyyear import *
from .getteamrobots import *
from .getteams import *
from .getteamsbyyear import *
from .getteamsbyyearkeys import *
from .getteamsbyyearsimple import *
from .getteamsimple import *
from .getteamskeys import *
from .getteamsocialmedia import *
from .getteamssimple import *
from .getteamyearsparticipated import *

__all__ = ["GetDistrictEventsPathParams","GetDistrictEventsHeaders","GetDistrictEventsSecurity","GetDistrictEventsRequest","GetDistrictEventsResponse","GetDistrictEventsKeysPathParams","GetDistrictEventsKeysHeaders","GetDistrictEventsKeysSecurity","GetDistrictEventsKeysRequest","GetDistrictEventsKeysResponse","GetDistrictEventsSimplePathParams","GetDistrictEventsSimpleHeaders","GetDistrictEventsSimpleSecurity","GetDistrictEventsSimpleRequest","GetDistrictEventsSimpleResponse","GetDistrictRankingsPathParams","GetDistrictRankingsHeaders","GetDistrictRankingsSecurity","GetDistrictRankingsRequest","GetDistrictRankingsResponse","GetDistrictsByYearPathParams","GetDistrictsByYearHeaders","GetDistrictsByYearSecurity","GetDistrictsByYearRequest","GetDistrictsByYearResponse","GetDistrictTeamsPathParams","GetDistrictTeamsHeaders","GetDistrictTeamsSecurity","GetDistrictTeamsRequest","GetDistrictTeamsResponse","GetDistrictTeamsKeysPathParams","GetDistrictTeamsKeysHeaders","GetDistrictTeamsKeysSecurity","GetDistrictTeamsKeysRequest","GetDistrictTeamsKeysResponse","GetDistrictTeamsSimplePathParams","GetDistrictTeamsSimpleHeaders","GetDistrictTeamsSimpleSecurity","GetDistrictTeamsSimpleRequest","GetDistrictTeamsSimpleResponse","GetEventPathParams","GetEventHeaders","GetEventSecurity","GetEventRequest","GetEventResponse","GetEventAlliancesPathParams","GetEventAlliancesHeaders","GetEventAlliancesSecurity","GetEventAlliancesRequest","GetEventAlliancesResponse","GetEventAwardsPathParams","GetEventAwardsHeaders","GetEventAwardsSecurity","GetEventAwardsRequest","GetEventAwardsResponse","GetEventDistrictPointsPathParams","GetEventDistrictPointsHeaders","GetEventDistrictPointsSecurity","GetEventDistrictPointsRequest","GetEventDistrictPointsResponse","GetEventInsightsPathParams","GetEventInsightsHeaders","GetEventInsightsSecurity","GetEventInsightsRequest","GetEventInsightsResponse","GetEventMatchesPathParams","GetEventMatchesHeaders","GetEventMatchesSecurity","GetEventMatchesRequest","GetEventMatchesResponse","GetEventMatchesKeysPathParams","GetEventMatchesKeysHeaders","GetEventMatchesKeysSecurity","GetEventMatchesKeysRequest","GetEventMatchesKeysResponse","GetEventMatchesSimplePathParams","GetEventMatchesSimpleHeaders","GetEventMatchesSimpleSecurity","GetEventMatchesSimpleRequest","GetEventMatchesSimpleResponse","GetEventMatchTimeseriesPathParams","GetEventMatchTimeseriesHeaders","GetEventMatchTimeseriesSecurity","GetEventMatchTimeseriesRequest","GetEventMatchTimeseriesResponse","GetEventOpRsPathParams","GetEventOpRsHeaders","GetEventOpRsSecurity","GetEventOpRsRequest","GetEventOpRsResponse","GetEventPredictionsPathParams","GetEventPredictionsHeaders","GetEventPredictionsSecurity","GetEventPredictionsRequest","GetEventPredictionsResponse","GetEventRankingsPathParams","GetEventRankingsHeaders","GetEventRankingsSecurity","GetEventRankingsRequest","GetEventRankingsResponse","GetEventsByYearPathParams","GetEventsByYearHeaders","GetEventsByYearSecurity","GetEventsByYearRequest","GetEventsByYearResponse","GetEventsByYearKeysPathParams","GetEventsByYearKeysHeaders","GetEventsByYearKeysSecurity","GetEventsByYearKeysRequest","GetEventsByYearKeysResponse","GetEventsByYearSimplePathParams","GetEventsByYearSimpleHeaders","GetEventsByYearSimpleSecurity","GetEventsByYearSimpleRequest","GetEventsByYearSimpleResponse","GetEventSimplePathParams","GetEventSimpleHeaders","GetEventSimpleSecurity","GetEventSimpleRequest","GetEventSimpleResponse","GetEventTeamsPathParams","GetEventTeamsHeaders","GetEventTeamsSecurity","GetEventTeamsRequest","GetEventTeamsResponse","GetEventTeamsKeysPathParams","GetEventTeamsKeysHeaders","GetEventTeamsKeysSecurity","GetEventTeamsKeysRequest","GetEventTeamsKeysResponse","GetEventTeamsSimplePathParams","GetEventTeamsSimpleHeaders","GetEventTeamsSimpleSecurity","GetEventTeamsSimpleRequest","GetEventTeamsSimpleResponse","GetEventTeamsStatusesPathParams","GetEventTeamsStatusesHeaders","GetEventTeamsStatusesSecurity","GetEventTeamsStatusesRequest","GetEventTeamsStatusesResponse","GetMatchPathParams","GetMatchHeaders","GetMatchSecurity","GetMatchRequest","GetMatchResponse","GetMatchSimplePathParams","GetMatchSimpleHeaders","GetMatchSimpleSecurity","GetMatchSimpleRequest","GetMatchSimpleResponse","GetMatchTimeseriesPathParams","GetMatchTimeseriesHeaders","GetMatchTimeseriesSecurity","GetMatchTimeseriesRequest","GetMatchTimeseriesResponse","GetMatchZebraPathParams","GetMatchZebraHeaders","GetMatchZebraSecurity","GetMatchZebraRequest","GetMatchZebraResponse","GetStatusHeaders","GetStatusSecurity","GetStatusRequest","GetStatusResponse","GetTeamPathParams","GetTeamHeaders","GetTeamSecurity","GetTeamRequest","GetTeamResponse","GetTeamAwardsPathParams","GetTeamAwardsHeaders","GetTeamAwardsSecurity","GetTeamAwardsRequest","GetTeamAwardsResponse","GetTeamAwardsByYearPathParams","GetTeamAwardsByYearHeaders","GetTeamAwardsByYearSecurity","GetTeamAwardsByYearRequest","GetTeamAwardsByYearResponse","GetTeamDistrictsPathParams","GetTeamDistrictsHeaders","GetTeamDistrictsSecurity","GetTeamDistrictsRequest","GetTeamDistrictsResponse","GetTeamEventAwardsPathParams","GetTeamEventAwardsHeaders","GetTeamEventAwardsSecurity","GetTeamEventAwardsRequest","GetTeamEventAwardsResponse","GetTeamEventMatchesPathParams","GetTeamEventMatchesHeaders","GetTeamEventMatchesSecurity","GetTeamEventMatchesRequest","GetTeamEventMatchesResponse","GetTeamEventMatchesKeysPathParams","GetTeamEventMatchesKeysHeaders","GetTeamEventMatchesKeysSecurity","GetTeamEventMatchesKeysRequest","GetTeamEventMatchesKeysResponse","GetTeamEventMatchesSimplePathParams","GetTeamEventMatchesSimpleHeaders","GetTeamEventMatchesSimpleSecurity","GetTeamEventMatchesSimpleRequest","GetTeamEventMatchesSimpleResponse","GetTeamEventsPathParams","GetTeamEventsHeaders","GetTeamEventsSecurity","GetTeamEventsRequest","GetTeamEventsResponse","GetTeamEventsByYearPathParams","GetTeamEventsByYearHeaders","GetTeamEventsByYearSecurity","GetTeamEventsByYearRequest","GetTeamEventsByYearResponse","GetTeamEventsByYearKeysPathParams","GetTeamEventsByYearKeysHeaders","GetTeamEventsByYearKeysSecurity","GetTeamEventsByYearKeysRequest","GetTeamEventsByYearKeysResponse","GetTeamEventsByYearSimplePathParams","GetTeamEventsByYearSimpleHeaders","GetTeamEventsByYearSimpleSecurity","GetTeamEventsByYearSimpleRequest","GetTeamEventsByYearSimpleResponse","GetTeamEventsKeysPathParams","GetTeamEventsKeysHeaders","GetTeamEventsKeysSecurity","GetTeamEventsKeysRequest","GetTeamEventsKeysResponse","GetTeamEventsSimplePathParams","GetTeamEventsSimpleHeaders","GetTeamEventsSimpleSecurity","GetTeamEventsSimpleRequest","GetTeamEventsSimpleResponse","GetTeamEventsStatusesByYearPathParams","GetTeamEventsStatusesByYearHeaders","GetTeamEventsStatusesByYearSecurity","GetTeamEventsStatusesByYearRequest","GetTeamEventsStatusesByYearResponse","GetTeamEventStatusPathParams","GetTeamEventStatusHeaders","GetTeamEventStatusSecurity","GetTeamEventStatusRequest","GetTeamEventStatusResponse","GetTeamMatchesByYearPathParams","GetTeamMatchesByYearHeaders","GetTeamMatchesByYearSecurity","GetTeamMatchesByYearRequest","GetTeamMatchesByYearResponse","GetTeamMatchesByYearKeysPathParams","GetTeamMatchesByYearKeysHeaders","GetTeamMatchesByYearKeysSecurity","GetTeamMatchesByYearKeysRequest","GetTeamMatchesByYearKeysResponse","GetTeamMatchesByYearSimplePathParams","GetTeamMatchesByYearSimpleHeaders","GetTeamMatchesByYearSimpleSecurity","GetTeamMatchesByYearSimpleRequest","GetTeamMatchesByYearSimpleResponse","GetTeamMediaByTagPathParams","GetTeamMediaByTagHeaders","GetTeamMediaByTagSecurity","GetTeamMediaByTagRequest","GetTeamMediaByTagResponse","GetTeamMediaByTagYearPathParams","GetTeamMediaByTagYearHeaders","GetTeamMediaByTagYearSecurity","GetTeamMediaByTagYearRequest","GetTeamMediaByTagYearResponse","GetTeamMediaByYearPathParams","GetTeamMediaByYearHeaders","GetTeamMediaByYearSecurity","GetTeamMediaByYearRequest","GetTeamMediaByYearResponse","GetTeamRobotsPathParams","GetTeamRobotsHeaders","GetTeamRobotsSecurity","GetTeamRobotsRequest","GetTeamRobotsResponse","GetTeamsPathParams","GetTeamsHeaders","GetTeamsSecurity","GetTeamsRequest","GetTeamsResponse","GetTeamsByYearPathParams","GetTeamsByYearHeaders","GetTeamsByYearSecurity","GetTeamsByYearRequest","GetTeamsByYearResponse","GetTeamsByYearKeysPathParams","GetTeamsByYearKeysHeaders","GetTeamsByYearKeysSecurity","GetTeamsByYearKeysRequest","GetTeamsByYearKeysResponse","GetTeamsByYearSimplePathParams","GetTeamsByYearSimpleHeaders","GetTeamsByYearSimpleSecurity","GetTeamsByYearSimpleRequest","GetTeamsByYearSimpleResponse","GetTeamSimplePathParams","GetTeamSimpleHeaders","GetTeamSimpleSecurity","GetTeamSimpleRequest","GetTeamSimpleResponse","GetTeamsKeysPathParams","GetTeamsKeysHeaders","GetTeamsKeysSecurity","GetTeamsKeysRequest","GetTeamsKeysResponse","GetTeamSocialMediaPathParams","GetTeamSocialMediaHeaders","GetTeamSocialMediaSecurity","GetTeamSocialMediaRequest","GetTeamSocialMediaResponse","GetTeamsSimplePathParams","GetTeamsSimpleHeaders","GetTeamsSimpleSecurity","GetTeamsSimpleRequest","GetTeamsSimpleResponse","GetTeamYearsParticipatedPathParams","GetTeamYearsParticipatedHeaders","GetTeamYearsParticipatedSecurity","GetTeamYearsParticipatedRequest","GetTeamYearsParticipatedResponse"]