package shared

type ChannelCatalogMarketplaceSettingDiscriminatorTypeEnum string

const (
	ChannelCatalogMarketplaceSettingDiscriminatorTypeEnumChannelCatalogMarketplaceStringSetting  ChannelCatalogMarketplaceSettingDiscriminatorTypeEnum = "channelCatalogMarketplaceStringSetting"
	ChannelCatalogMarketplaceSettingDiscriminatorTypeEnumChannelCatalogMarketplaceIntegerSetting ChannelCatalogMarketplaceSettingDiscriminatorTypeEnum = "channelCatalogMarketplaceIntegerSetting"
	ChannelCatalogMarketplaceSettingDiscriminatorTypeEnumChannelCatalogMarketplaceBooleanSetting ChannelCatalogMarketplaceSettingDiscriminatorTypeEnum = "channelCatalogMarketplaceBooleanSetting"
	ChannelCatalogMarketplaceSettingDiscriminatorTypeEnumChannelCatalogMarketplaceNumberSetting  ChannelCatalogMarketplaceSettingDiscriminatorTypeEnum = "channelCatalogMarketplaceNumberSetting"
)
