package shared

type OptimisationActionNameGeneralParametersEnum string

const (
	OptimisationActionNameGeneralParametersEnumReenable OptimisationActionNameGeneralParametersEnum = "reenable"
	OptimisationActionNameGeneralParametersEnumDisable  OptimisationActionNameGeneralParametersEnum = "disable"
)
