package openapisdk.models.shared;


public enum DomainVerificationDetailStatusEnum {
    COMPLETED("COMPLETED"),
    FAILED_VERIFICATION("FAILED_VERIFICATION"),
    VERIFIED_POSSIBLE_FRAUD("VERIFIED_POSSIBLE_FRAUD"),
    DROPPED("DROPPED"),
    DROPPED_CERTIFICATE_AUTHORITY_AUTHORIZATION("DROPPED_CERTIFICATE_AUTHORITY_AUTHORIZATION"),
    DROPPED_GOOGLE_SAFE_BROWSING("DROPPED_GOOGLE_SAFE_BROWSING"),
    INVALID("INVALID"),
    AWAITING("AWAITING"),
    PENDING_POSSIBLE_FRAUD("PENDING_POSSIBLE_FRAUD"),
    REVOKED_CERTIFICATE("REVOKED_CERTIFICATE");

    public final String value;

    private DomainVerificationDetailStatusEnum(String value) {
        this.value = value;
    }
}
