<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use \OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class GetGetUserByOrcidRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=format')]
    public ?GetGetUserByOrcidFormatEnum $format = null;
    
    /**
     * string
     * 
     * @var string $orcid
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=orcid')]
    public string $orcid;
    
	public function __construct()
	{
		$this->format = null;
		$this->orcid = "";
	}
}
