// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateSubscriptionsToEventBridgeMessage - <p/>
type UpdateSubscriptionsToEventBridgeMessage struct {
	ForceMove *bool `json:"ForceMove,omitempty"`
}
