from .texttospeech_projects_locations_voices_synthesizelongaudio import *
from .texttospeech_text_synthesize import *
from .texttospeech_voices_list import *

__all__ = ["TexttospeechProjectsLocationsVoicesSynthesizeLongAudioPathParams","TexttospeechProjectsLocationsVoicesSynthesizeLongAudioQueryParams","TexttospeechProjectsLocationsVoicesSynthesizeLongAudioSecurity","TexttospeechProjectsLocationsVoicesSynthesizeLongAudioRequest","TexttospeechProjectsLocationsVoicesSynthesizeLongAudioResponse","TexttospeechTextSynthesizeQueryParams","TexttospeechTextSynthesizeSecurity","TexttospeechTextSynthesizeRequest","TexttospeechTextSynthesizeResponse","TexttospeechVoicesListQueryParams","TexttospeechVoicesListSecurity","TexttospeechVoicesListRequest","TexttospeechVoicesListResponse"]