/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.openapis.openapi.utils.SpeakeasyMetadata;

public class PaymentLinkApiUriRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=id")
    public Integer id;

    public PaymentLinkApiUriRequest withId(Integer id) {
        this.id = id;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-auth-key")
    public String xAuthKey;

    public PaymentLinkApiUriRequest withXAuthKey(String xAuthKey) {
        this.xAuthKey = xAuthKey;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-auth-secret")
    public String xAuthSecret;

    public PaymentLinkApiUriRequest withXAuthSecret(String xAuthSecret) {
        this.xAuthSecret = xAuthSecret;
        return this;
    }
    
    public PaymentLinkApiUriRequest(@JsonProperty("id") Integer id, @JsonProperty("x-auth-key") String xAuthKey, @JsonProperty("x-auth-secret") String xAuthSecret) {
        this.id = id;
        this.xAuthKey = xAuthKey;
        this.xAuthSecret = xAuthSecret;
  }
}
