/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FailoverConfig } from "./failoverconfig";
import { Expose, Type } from "class-transformer";

/**
 * The routing configuration of the endpoint.
 */
export class RoutingConfig extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "FailoverConfig" })
  @Type(() => FailoverConfig)
  failoverConfig: FailoverConfig;
}
