/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExecutorConfiguration } from "./executorconfiguration";
import { ExecutorTypeEnum } from "./executortypeenum";
import { Expose, Type } from "class-transformer";

/**
 * The action engine, or executor, for an action type created for a provider, where the action is to be used by customers of the provider. The action engine is associated with the model used to create and update the action, such as the Lambda integration model.
 */
export class ActionTypeExecutor extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "configuration" })
  @Type(() => ExecutorConfiguration)
  configuration: ExecutorConfiguration;

  @SpeakeasyMetadata()
  @Expose({ name: "jobTimeout" })
  jobTimeout?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "policyStatementsTemplate" })
  policyStatementsTemplate?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: ExecutorTypeEnum;
}
