<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;


/** The way to sort the results. */
enum GetChannelVideosSortEnum: string
{
    case ADDED = 'added';
    case ALPHABETICAL = 'alphabetical';
    case COMMENTS = 'comments';
    case DATE = 'date';
    case DEFAULT = 'default';
    case DURATION = 'duration';
    case LIKES = 'likes';
    case MANUAL = 'manual';
    case MODIFIED_TIME = 'modified_time';
    case PLAYS = 'plays';
}
