/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class POSTListTagsForResourceQueryParams {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Action")
    public POSTListTagsForResourceActionEnum action;
    public POSTListTagsForResourceQueryParams withAction(POSTListTagsForResourceActionEnum action) {
        this.action = action;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Version")
    public POSTListTagsForResourceVersionEnum version;
    public POSTListTagsForResourceQueryParams withVersion(POSTListTagsForResourceVersionEnum version) {
        this.version = version;
        return this;
    }
    
}
