"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import invoicepaymentstatus_enum as shared_invoicepaymentstatus_enum
from dataclasses_json import Undefined, dataclass_json
from datetime import date
from marshmallow import fields
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Invoice:
    
    amount: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount') }})
    r"""The amount of your invoice"""  
    amount_to_be_paid: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amountToBePaid') }})
    r"""The remaining amount to be paid for this invoice"""  
    contract_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('contractId') }})
    r"""Your contract identifier"""  
    currency_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('currencyCode') }})
    r"""The currency code <a href=\\"https://en.wikipedia.org/wiki/ISO_4217\\">(ISO 4217)</a>"""  
    due_date: date = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dueDate'), 'encoder': utils.dateisoformat(False), 'decoder': utils.datefromisoformat, 'mm_field': fields.DateTime(format='iso') }})  
    invoice_date: date = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('invoiceDate'), 'encoder': utils.dateisoformat(False), 'decoder': utils.datefromisoformat, 'mm_field': fields.DateTime(format='iso') }})
    r"""The invoice date"""  
    invoice_number: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('invoiceNumber') }})
    r"""Your invoice number"""  
    payment_status: shared_invoicepaymentstatus_enum.InvoicePaymentStatusEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('paymentStatus') }})
    r"""The payment status"""  
    invoice_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('invoiceUrl'), 'exclude': lambda f: f is None }})
    r"""The url of the invoice document"""  
    