package openapisdk.models.operations;


public enum AdsenseAccountsReportsGenerateCsvDimensionsEnum {
    DIMENSION_UNSPECIFIED("DIMENSION_UNSPECIFIED"),
    DATE("DATE"),
    WEEK("WEEK"),
    MONTH("MONTH"),
    ACCOUNT_NAME("ACCOUNT_NAME"),
    AD_CLIENT_ID("AD_CLIENT_ID"),
    HOSTED_AD_CLIENT_ID("HOSTED_AD_CLIENT_ID"),
    PRODUCT_NAME("PRODUCT_NAME"),
    PRODUCT_CODE("PRODUCT_CODE"),
    AD_UNIT_NAME("AD_UNIT_NAME"),
    AD_UNIT_ID("AD_UNIT_ID"),
    AD_UNIT_SIZE_NAME("AD_UNIT_SIZE_NAME"),
    AD_UNIT_SIZE_CODE("AD_UNIT_SIZE_CODE"),
    CUSTOM_CHANNEL_NAME("CUSTOM_CHANNEL_NAME"),
    CUSTOM_CHANNEL_ID("CUSTOM_CHANNEL_ID"),
    OWNED_SITE_DOMAIN_NAME("OWNED_SITE_DOMAIN_NAME"),
    OWNED_SITE_ID("OWNED_SITE_ID"),
    URL_CHANNEL_NAME("URL_CHANNEL_NAME"),
    URL_CHANNEL_ID("URL_CHANNEL_ID"),
    BUYER_NETWORK_NAME("BUYER_NETWORK_NAME"),
    BUYER_NETWORK_ID("BUYER_NETWORK_ID"),
    BID_TYPE_NAME("BID_TYPE_NAME"),
    BID_TYPE_CODE("BID_TYPE_CODE"),
    CREATIVE_SIZE_NAME("CREATIVE_SIZE_NAME"),
    CREATIVE_SIZE_CODE("CREATIVE_SIZE_CODE"),
    DOMAIN_NAME("DOMAIN_NAME"),
    DOMAIN_CODE("DOMAIN_CODE"),
    COUNTRY_NAME("COUNTRY_NAME"),
    COUNTRY_CODE("COUNTRY_CODE"),
    PLATFORM_TYPE_NAME("PLATFORM_TYPE_NAME"),
    PLATFORM_TYPE_CODE("PLATFORM_TYPE_CODE"),
    TARGETING_TYPE_NAME("TARGETING_TYPE_NAME"),
    TARGETING_TYPE_CODE("TARGETING_TYPE_CODE"),
    CONTENT_PLATFORM_NAME("CONTENT_PLATFORM_NAME"),
    CONTENT_PLATFORM_CODE("CONTENT_PLATFORM_CODE"),
    AD_PLACEMENT_NAME("AD_PLACEMENT_NAME"),
    AD_PLACEMENT_CODE("AD_PLACEMENT_CODE"),
    REQUESTED_AD_TYPE_NAME("REQUESTED_AD_TYPE_NAME"),
    REQUESTED_AD_TYPE_CODE("REQUESTED_AD_TYPE_CODE"),
    SERVED_AD_TYPE_NAME("SERVED_AD_TYPE_NAME"),
    SERVED_AD_TYPE_CODE("SERVED_AD_TYPE_CODE"),
    AD_FORMAT_NAME("AD_FORMAT_NAME"),
    AD_FORMAT_CODE("AD_FORMAT_CODE"),
    CUSTOM_SEARCH_STYLE_NAME("CUSTOM_SEARCH_STYLE_NAME"),
    CUSTOM_SEARCH_STYLE_ID("CUSTOM_SEARCH_STYLE_ID"),
    DOMAIN_REGISTRANT("DOMAIN_REGISTRANT"),
    WEBSEARCH_QUERY_STRING("WEBSEARCH_QUERY_STRING");

    public final String value;

    private AdsenseAccountsReportsGenerateCsvDimensionsEnum(String value) {
        this.value = value;
    }
}
