<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * InterconnectDiagnosticsARPEntry - Describing the ARP neighbor entries seen on this link
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class InterconnectDiagnosticsARPEntry
{
    /**
     * The IP address of this ARP neighbor.
     * 
     * @var ?string $ipAddress
     */
	#[\JMS\Serializer\Annotation\SerializedName('ipAddress')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ipAddress = null;
    
    /**
     * The MAC address of this ARP neighbor.
     * 
     * @var ?string $macAddress
     */
	#[\JMS\Serializer\Annotation\SerializedName('macAddress')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $macAddress = null;
    
	public function __construct()
	{
		$this->ipAddress = null;
		$this->macAddress = null;
	}
}
