/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateRepositoryXAmzTargetEnum
 */
public enum CreateRepositoryXAmzTargetEnum {
    SPENCER_FRONTEND_SERVICE_CREATE_REPOSITORY("SpencerFrontendService.CreateRepository");

    @JsonValue
    public final String value;

    private CreateRepositoryXAmzTargetEnum(String value) {
        this.value = value;
    }
}
