/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class DirectoryUsersWatchRequest {
    /**
     * V1 error format.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$.xgafv")
    public org.openapis.openapi.models.shared.XgafvEnum dollarXgafv;
    public DirectoryUsersWatchRequest withDollarXgafv(org.openapis.openapi.models.shared.XgafvEnum dollarXgafv) {
        this.dollarXgafv = dollarXgafv;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public org.openapis.openapi.models.shared.Channel channel;
    public DirectoryUsersWatchRequest withChannel(org.openapis.openapi.models.shared.Channel channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * OAuth access token.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=access_token")
    public String accessToken;
    public DirectoryUsersWatchRequest withAccessToken(String accessToken) {
        this.accessToken = accessToken;
        return this;
    }
    
    /**
     * Data format for response.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=alt")
    public org.openapis.openapi.models.shared.AltEnum alt;
    public DirectoryUsersWatchRequest withAlt(org.openapis.openapi.models.shared.AltEnum alt) {
        this.alt = alt;
        return this;
    }
    
    /**
     * JSONP
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=callback")
    public String callback;
    public DirectoryUsersWatchRequest withCallback(String callback) {
        this.callback = callback;
        return this;
    }
    
    /**
     * Comma-separated list of schema names. All fields from these schemas are fetched. This should only be set when projection=custom.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=customFieldMask")
    public String customFieldMask;
    public DirectoryUsersWatchRequest withCustomFieldMask(String customFieldMask) {
        this.customFieldMask = customFieldMask;
        return this;
    }
    
    /**
     * Immutable ID of the Google Workspace account. In case of multi-domain, to fetch all users for a customer, fill this field instead of domain.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=customer")
    public String customer;
    public DirectoryUsersWatchRequest withCustomer(String customer) {
        this.customer = customer;
        return this;
    }
    
    /**
     * Name of the domain. Fill this field to get users from only this domain. To return all users in a multi-domain fill customer field instead."
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=domain")
    public String domain;
    public DirectoryUsersWatchRequest withDomain(String domain) {
        this.domain = domain;
        return this;
    }
    
    /**
     * Events to watch for.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=event")
    public DirectoryUsersWatchEventEnum event;
    public DirectoryUsersWatchRequest withEvent(DirectoryUsersWatchEventEnum event) {
        this.event = event;
        return this;
    }
    
    /**
     * Selector specifying which fields to include in a partial response.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=fields")
    public String fields;
    public DirectoryUsersWatchRequest withFields(String fields) {
        this.fields = fields;
        return this;
    }
    
    /**
     * API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=key")
    public String key;
    public DirectoryUsersWatchRequest withKey(String key) {
        this.key = key;
        return this;
    }
    
    /**
     * Maximum number of results to return.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=maxResults")
    public Long maxResults;
    public DirectoryUsersWatchRequest withMaxResults(Long maxResults) {
        this.maxResults = maxResults;
        return this;
    }
    
    /**
     * OAuth 2.0 token for the current user.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=oauth_token")
    public String oauthToken;
    public DirectoryUsersWatchRequest withOauthToken(String oauthToken) {
        this.oauthToken = oauthToken;
        return this;
    }
    
    /**
     * Column to use for sorting results
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderBy")
    public DirectoryUsersWatchOrderByEnum orderBy;
    public DirectoryUsersWatchRequest withOrderBy(DirectoryUsersWatchOrderByEnum orderBy) {
        this.orderBy = orderBy;
        return this;
    }
    
    /**
     * Token to specify next page in the list
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageToken")
    public String pageToken;
    public DirectoryUsersWatchRequest withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }
    
    /**
     * Returns response with indentations and line breaks.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=prettyPrint")
    public Boolean prettyPrint;
    public DirectoryUsersWatchRequest withPrettyPrint(Boolean prettyPrint) {
        this.prettyPrint = prettyPrint;
        return this;
    }
    
    /**
     * What subset of fields to fetch for this user.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=projection")
    public DirectoryUsersWatchProjectionEnum projection;
    public DirectoryUsersWatchRequest withProjection(DirectoryUsersWatchProjectionEnum projection) {
        this.projection = projection;
        return this;
    }
    
    /**
     * Query string search. Should be of the form "". Complete documentation is at https: //developers.google.com/admin-sdk/directory/v1/guides/search-users
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=query")
    public String query;
    public DirectoryUsersWatchRequest withQuery(String query) {
        this.query = query;
        return this;
    }
    
    /**
     * Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=quotaUser")
    public String quotaUser;
    public DirectoryUsersWatchRequest withQuotaUser(String quotaUser) {
        this.quotaUser = quotaUser;
        return this;
    }
    
    /**
     * If set to true, retrieves the list of deleted users. (Default: false)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=showDeleted")
    public String showDeleted;
    public DirectoryUsersWatchRequest withShowDeleted(String showDeleted) {
        this.showDeleted = showDeleted;
        return this;
    }
    
    /**
     * Whether to return results in ascending or descending order.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sortOrder")
    public DirectoryUsersWatchSortOrderEnum sortOrder;
    public DirectoryUsersWatchRequest withSortOrder(DirectoryUsersWatchSortOrderEnum sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }
    
    /**
     * Legacy upload protocol for media (e.g. "media", "multipart").
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=uploadType")
    public String uploadType;
    public DirectoryUsersWatchRequest withUploadType(String uploadType) {
        this.uploadType = uploadType;
        return this;
    }
    
    /**
     * Upload protocol for media (e.g. "raw", "multipart").
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=upload_protocol")
    public String uploadProtocol;
    public DirectoryUsersWatchRequest withUploadProtocol(String uploadProtocol) {
        this.uploadProtocol = uploadProtocol;
        return this;
    }
    
    /**
     * Whether to fetch the administrator-only or domain-wide public view of the user. For more information, see [Retrieve a user as a non-administrator](/admin-sdk/directory/v1/guides/manage-users#retrieve_users_non_admin).
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=viewType")
    public DirectoryUsersWatchViewTypeEnum viewType;
    public DirectoryUsersWatchRequest withViewType(DirectoryUsersWatchViewTypeEnum viewType) {
        this.viewType = viewType;
        return this;
    }
    
}
