<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * ConfigurationErrorDetails - Contains the details of an IoT SiteWise configuration error.
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class ConfigurationErrorDetails
{
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('enum<OpenAPI\OpenAPI\Models\Shared\ErrorCodeEnum>')]
    public ErrorCodeEnum $code;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	public function __construct()
	{
		$this->code = \OpenAPI\OpenAPI\Models\Shared\ErrorCodeEnum::VALIDATION_ERROR;
		$this->message = "";
	}
}
