/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PodocRequestBodyCertificateParameters {
    /**
     * Full name
     */
    @JsonProperty("FullName")
    public String fullName;
    public PodocRequestBodyCertificateParameters withFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }
    
    /**
     * Policy number
     */
    @JsonProperty("PolicyNumber")
    public String policyNumber;
    public PodocRequestBodyCertificateParameters withPolicyNumber(String policyNumber) {
        this.policyNumber = policyNumber;
        return this;
    }
    
}
