/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MediaSourceConfig - The configuration details that consist of the credentials required (&lt;code&gt;MediaUriSecretArn&lt;/code&gt; and &lt;code&gt;MediaUriType&lt;/code&gt;) to access the media files that are streamed to the camera.
 */
public class MediaSourceConfig {
    @JsonProperty("MediaUriSecretArn")
    public String mediaUriSecretArn;

    public MediaSourceConfig withMediaUriSecretArn(String mediaUriSecretArn) {
        this.mediaUriSecretArn = mediaUriSecretArn;
        return this;
    }
    
    @JsonProperty("MediaUriType")
    public MediaUriTypeEnum mediaUriType;

    public MediaSourceConfig withMediaUriType(MediaUriTypeEnum mediaUriType) {
        this.mediaUriType = mediaUriType;
        return this;
    }
    
    public MediaSourceConfig(@JsonProperty("MediaUriSecretArn") String mediaUriSecretArn, @JsonProperty("MediaUriType") MediaUriTypeEnum mediaUriType) {
        this.mediaUriSecretArn = mediaUriSecretArn;
        this.mediaUriType = mediaUriType;
  }
}
