package shared

type Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum string

const (
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumTesla      Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "TESLA"
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumBmw        Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "BMW"
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumAudi       Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "AUDI"
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumVolkswagen Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "VOLKSWAGEN"
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumHyundai    Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "HYUNDAI"
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumPeugeot    Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "PEUGEOT"
	Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnumNissan     Oneme1vendors1Percent7BvendorPercent7DDeleteParameters0SchemaEnum = "NISSAN"
)
