package shared

type Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum string

const (
	Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnumBatteryLevel      Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum = "BATTERY_LEVEL"
	Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnumRange             Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum = "RANGE"
	Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnumIsPluggedIn       Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum = "IS_PLUGGED_IN"
	Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnumIsCharging        Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum = "IS_CHARGING"
	Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnumIsChargingReasons Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum = "IS_CHARGING_REASONS"
	Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnumLocation          Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum = "LOCATION"
)

type Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchema struct {
	Properties *Onevehicles1Percent7BvehicleIDPercent7D1watchPostRequestBodyContentApplication1jsonSchemaPropertiesEnum `json:"properties,omitempty"`
}
