/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;



public class GETCreateDomainRequest {
    
    public GETCreateDomainQueryParams queryParams;
    public GETCreateDomainRequest withQueryParams(GETCreateDomainQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    
    public GETCreateDomainHeaders headers;
    public GETCreateDomainRequest withHeaders(GETCreateDomainHeaders headers) {
        this.headers = headers;
        return this;
    }
    
}
