/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import org.openapis.openapi.utils.SpeakeasyMetadata;

public class GETDescribeExpressionsQueryParams {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Action")
    public GETDescribeExpressionsActionEnum action;
    public GETDescribeExpressionsQueryParams withAction(GETDescribeExpressionsActionEnum action) {
        this.action = action;
        return this;
    }
    
    /**
     * Whether to display the deployed configuration (&lt;code&gt;true&lt;/code&gt;) or include any pending changes (&lt;code&gt;false&lt;/code&gt;). Defaults to &lt;code&gt;false&lt;/code&gt;.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Deployed")
    public Boolean deployed;
    public GETDescribeExpressionsQueryParams withDeployed(Boolean deployed) {
        this.deployed = deployed;
        return this;
    }
    
    /**
     * The name of the domain you want to describe.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=DomainName")
    public String domainName;
    public GETDescribeExpressionsQueryParams withDomainName(String domainName) {
        this.domainName = domainName;
        return this;
    }
    
    /**
     * Limits the &lt;code&gt;&lt;a&gt;DescribeExpressions&lt;/a&gt;&lt;/code&gt; response to the specified expressions. If not specified, all expressions are shown.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ExpressionNames")
    public String[] expressionNames;
    public GETDescribeExpressionsQueryParams withExpressionNames(String[] expressionNames) {
        this.expressionNames = expressionNames;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Version")
    public GETDescribeExpressionsVersionEnum version;
    public GETDescribeExpressionsQueryParams withVersion(GETDescribeExpressionsVersionEnum version) {
        this.version = version;
        return this;
    }
    
}
