<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Shared;


/**
 * RepositoryCollaboratorPermission - Repository Collaborator Permission
 * 
 * @package OpenAPI\OpenAPI\Models\Shared
 * @access public
 */
class RepositoryCollaboratorPermission
{
	#[\JMS\Serializer\Annotation\SerializedName('permission')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $permission;
    
    /**
     * Collaborator
     * 
     * @var \OpenAPI\OpenAPI\Models\Shared\NullableCollaborator $user
     */
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('OpenAPI\OpenAPI\Models\Shared\NullableCollaborator')]
    public NullableCollaborator $user;
    
	public function __construct()
	{
		$this->permission = "";
		$this->user = new \OpenAPI\OpenAPI\Models\Shared\NullableCollaborator();
	}
}
