package openapisdk.models.shared;


public enum AutoRenewingBasePlanTypeProrationModeEnum {
    SUBSCRIPTION_PRORATION_MODE_UNSPECIFIED("SUBSCRIPTION_PRORATION_MODE_UNSPECIFIED"),
    SUBSCRIPTION_PRORATION_MODE_CHARGE_ON_NEXT_BILLING_DATE("SUBSCRIPTION_PRORATION_MODE_CHARGE_ON_NEXT_BILLING_DATE"),
    SUBSCRIPTION_PRORATION_MODE_CHARGE_FULL_PRICE_IMMEDIATELY("SUBSCRIPTION_PRORATION_MODE_CHARGE_FULL_PRICE_IMMEDIATELY");

    public final String value;

    private AutoRenewingBasePlanTypeProrationModeEnum(String value) {
        this.value = value;
    }
}
