package openapisdk.models.shared;


public enum UserDeveloperAccountPermissionsEnum {
    DEVELOPER_LEVEL_PERMISSION_UNSPECIFIED("DEVELOPER_LEVEL_PERMISSION_UNSPECIFIED"),
    CAN_SEE_ALL_APPS("CAN_SEE_ALL_APPS"),
    CAN_VIEW_FINANCIAL_DATA_GLOBAL("CAN_VIEW_FINANCIAL_DATA_GLOBAL"),
    CAN_MANAGE_PERMISSIONS_GLOBAL("CAN_MANAGE_PERMISSIONS_GLOBAL"),
    CAN_EDIT_GAMES_GLOBAL("CAN_EDIT_GAMES_GLOBAL"),
    CAN_PUBLISH_GAMES_GLOBAL("CAN_PUBLISH_GAMES_GLOBAL"),
    CAN_REPLY_TO_REVIEWS_GLOBAL("CAN_REPLY_TO_REVIEWS_GLOBAL"),
    CAN_MANAGE_PUBLIC_APKS_GLOBAL("CAN_MANAGE_PUBLIC_APKS_GLOBAL"),
    CAN_MANAGE_TRACK_APKS_GLOBAL("CAN_MANAGE_TRACK_APKS_GLOBAL"),
    CAN_MANAGE_TRACK_USERS_GLOBAL("CAN_MANAGE_TRACK_USERS_GLOBAL"),
    CAN_MANAGE_PUBLIC_LISTING_GLOBAL("CAN_MANAGE_PUBLIC_LISTING_GLOBAL"),
    CAN_MANAGE_DRAFT_APPS_GLOBAL("CAN_MANAGE_DRAFT_APPS_GLOBAL"),
    CAN_CREATE_MANAGED_PLAY_APPS_GLOBAL("CAN_CREATE_MANAGED_PLAY_APPS_GLOBAL"),
    CAN_CHANGE_MANAGED_PLAY_SETTING_GLOBAL("CAN_CHANGE_MANAGED_PLAY_SETTING_GLOBAL"),
    CAN_MANAGE_ORDERS_GLOBAL("CAN_MANAGE_ORDERS_GLOBAL");

    public final String value;

    private UserDeveloperAccountPermissionsEnum(String value) {
        this.value = value;
    }
}
