// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RestoreFromSnapshotRequest - An object representing the inputs for the <a>RestoreFromSnapshot</a> operation.
type RestoreFromSnapshotRequest struct {
	SnapshotID string `json:"SnapshotId"`
}
