from .createapp import *
from .createcampaign import *
from .createemailtemplate import *
from .createexportjob import *
from .createimportjob import *
from .createinapptemplate import *
from .createjourney import *
from .createpushtemplate import *
from .createrecommenderconfiguration import *
from .createsegment import *
from .createsmstemplate import *
from .createvoicetemplate import *
from .deleteadmchannel import *
from .deleteapnschannel import *
from .deleteapnssandboxchannel import *
from .deleteapnsvoipchannel import *
from .deleteapnsvoipsandboxchannel import *
from .deleteapp import *
from .deletebaiduchannel import *
from .deletecampaign import *
from .deleteemailchannel import *
from .deleteemailtemplate import *
from .deleteendpoint import *
from .deleteeventstream import *
from .deletegcmchannel import *
from .deleteinapptemplate import *
from .deletejourney import *
from .deletepushtemplate import *
from .deleterecommenderconfiguration import *
from .deletesegment import *
from .deletesmschannel import *
from .deletesmstemplate import *
from .deleteuserendpoints import *
from .deletevoicechannel import *
from .deletevoicetemplate import *
from .getadmchannel import *
from .getapnschannel import *
from .getapnssandboxchannel import *
from .getapnsvoipchannel import *
from .getapnsvoipsandboxchannel import *
from .getapp import *
from .getapplicationdaterangekpi import *
from .getapplicationsettings import *
from .getapps import *
from .getbaiduchannel import *
from .getcampaign import *
from .getcampaignactivities import *
from .getcampaigndaterangekpi import *
from .getcampaigns import *
from .getcampaignversion import *
from .getcampaignversions import *
from .getchannels import *
from .getemailchannel import *
from .getemailtemplate import *
from .getendpoint import *
from .geteventstream import *
from .getexportjob import *
from .getexportjobs import *
from .getgcmchannel import *
from .getimportjob import *
from .getimportjobs import *
from .getinappmessages import *
from .getinapptemplate import *
from .getjourney import *
from .getjourneydaterangekpi import *
from .getjourneyexecutionactivitymetrics import *
from .getjourneyexecutionmetrics import *
from .getpushtemplate import *
from .getrecommenderconfiguration import *
from .getrecommenderconfigurations import *
from .getsegment import *
from .getsegmentexportjobs import *
from .getsegmentimportjobs import *
from .getsegments import *
from .getsegmentversion import *
from .getsegmentversions import *
from .getsmschannel import *
from .getsmstemplate import *
from .getuserendpoints import *
from .getvoicechannel import *
from .getvoicetemplate import *
from .listjourneys import *
from .listtagsforresource import *
from .listtemplates import *
from .listtemplateversions import *
from .phonenumbervalidate import *
from .putevents import *
from .puteventstream import *
from .removeattributes import *
from .sendmessages import *
from .sendusersmessages import *
from .tagresource import *
from .untagresource import *
from .updateadmchannel import *
from .updateapnschannel import *
from .updateapnssandboxchannel import *
from .updateapnsvoipchannel import *
from .updateapnsvoipsandboxchannel import *
from .updateapplicationsettings import *
from .updatebaiduchannel import *
from .updatecampaign import *
from .updateemailchannel import *
from .updateemailtemplate import *
from .updateendpoint import *
from .updateendpointsbatch import *
from .updategcmchannel import *
from .updateinapptemplate import *
from .updatejourney import *
from .updatejourneystate import *
from .updatepushtemplate import *
from .updaterecommenderconfiguration import *
from .updatesegment import *
from .updatesmschannel import *
from .updatesmstemplate import *
from .updatetemplateactiveversion import *
from .updatevoicechannel import *
from .updatevoicetemplate import *

__all__ = ["CreateAppHeaders","CreateAppRequestBodyCreateApplicationRequest","CreateAppRequestBody","CreateAppRequest","CreateAppResponse","CreateCampaignPathParams","CreateCampaignHeaders","CreateCampaignRequestBodyWriteCampaignRequest","CreateCampaignRequestBody","CreateCampaignRequest","CreateCampaignResponse","CreateEmailTemplatePathParams","CreateEmailTemplateHeaders","CreateEmailTemplateRequestBodyEmailTemplateRequest","CreateEmailTemplateRequestBody","CreateEmailTemplateRequest","CreateEmailTemplateResponse","CreateExportJobPathParams","CreateExportJobHeaders","CreateExportJobRequestBodyExportJobRequest","CreateExportJobRequestBody","CreateExportJobRequest","CreateExportJobResponse","CreateImportJobPathParams","CreateImportJobHeaders","CreateImportJobRequestBodyImportJobRequest","CreateImportJobRequestBody","CreateImportJobRequest","CreateImportJobResponse","CreateInAppTemplatePathParams","CreateInAppTemplateHeaders","CreateInAppTemplateRequestBodyInAppTemplateRequest","CreateInAppTemplateRequestBody","CreateInAppTemplateRequest","CreateInAppTemplateResponse","CreateJourneyPathParams","CreateJourneyHeaders","CreateJourneyRequestBodyWriteJourneyRequest","CreateJourneyRequestBody","CreateJourneyRequest","CreateJourneyResponse","CreatePushTemplatePathParams","CreatePushTemplateHeaders","CreatePushTemplateRequestBodyPushNotificationTemplateRequest","CreatePushTemplateRequestBody","CreatePushTemplateRequest","CreatePushTemplateResponse","CreateRecommenderConfigurationHeaders","CreateRecommenderConfigurationRequestBodyCreateRecommenderConfiguration","CreateRecommenderConfigurationRequestBody","CreateRecommenderConfigurationRequest","CreateRecommenderConfigurationResponse","CreateSegmentPathParams","CreateSegmentHeaders","CreateSegmentRequestBodyWriteSegmentRequest","CreateSegmentRequestBody","CreateSegmentRequest","CreateSegmentResponse","CreateSmsTemplatePathParams","CreateSmsTemplateHeaders","CreateSmsTemplateRequestBodySmsTemplateRequest","CreateSmsTemplateRequestBody","CreateSmsTemplateRequest","CreateSmsTemplateResponse","CreateVoiceTemplatePathParams","CreateVoiceTemplateHeaders","CreateVoiceTemplateRequestBodyVoiceTemplateRequest","CreateVoiceTemplateRequestBody","CreateVoiceTemplateRequest","CreateVoiceTemplateResponse","DeleteAdmChannelPathParams","DeleteAdmChannelHeaders","DeleteAdmChannelRequest","DeleteAdmChannelResponse","DeleteApnsChannelPathParams","DeleteApnsChannelHeaders","DeleteApnsChannelRequest","DeleteApnsChannelResponse","DeleteApnsSandboxChannelPathParams","DeleteApnsSandboxChannelHeaders","DeleteApnsSandboxChannelRequest","DeleteApnsSandboxChannelResponse","DeleteApnsVoipChannelPathParams","DeleteApnsVoipChannelHeaders","DeleteApnsVoipChannelRequest","DeleteApnsVoipChannelResponse","DeleteApnsVoipSandboxChannelPathParams","DeleteApnsVoipSandboxChannelHeaders","DeleteApnsVoipSandboxChannelRequest","DeleteApnsVoipSandboxChannelResponse","DeleteAppPathParams","DeleteAppHeaders","DeleteAppRequest","DeleteAppResponse","DeleteBaiduChannelPathParams","DeleteBaiduChannelHeaders","DeleteBaiduChannelRequest","DeleteBaiduChannelResponse","DeleteCampaignPathParams","DeleteCampaignHeaders","DeleteCampaignRequest","DeleteCampaignResponse","DeleteEmailChannelPathParams","DeleteEmailChannelHeaders","DeleteEmailChannelRequest","DeleteEmailChannelResponse","DeleteEmailTemplatePathParams","DeleteEmailTemplateQueryParams","DeleteEmailTemplateHeaders","DeleteEmailTemplateRequest","DeleteEmailTemplateResponse","DeleteEndpointPathParams","DeleteEndpointHeaders","DeleteEndpointRequest","DeleteEndpointResponse","DeleteEventStreamPathParams","DeleteEventStreamHeaders","DeleteEventStreamRequest","DeleteEventStreamResponse","DeleteGcmChannelPathParams","DeleteGcmChannelHeaders","DeleteGcmChannelRequest","DeleteGcmChannelResponse","DeleteInAppTemplatePathParams","DeleteInAppTemplateQueryParams","DeleteInAppTemplateHeaders","DeleteInAppTemplateRequest","DeleteInAppTemplateResponse","DeleteJourneyPathParams","DeleteJourneyHeaders","DeleteJourneyRequest","DeleteJourneyResponse","DeletePushTemplatePathParams","DeletePushTemplateQueryParams","DeletePushTemplateHeaders","DeletePushTemplateRequest","DeletePushTemplateResponse","DeleteRecommenderConfigurationPathParams","DeleteRecommenderConfigurationHeaders","DeleteRecommenderConfigurationRequest","DeleteRecommenderConfigurationResponse","DeleteSegmentPathParams","DeleteSegmentHeaders","DeleteSegmentRequest","DeleteSegmentResponse","DeleteSmsChannelPathParams","DeleteSmsChannelHeaders","DeleteSmsChannelRequest","DeleteSmsChannelResponse","DeleteSmsTemplatePathParams","DeleteSmsTemplateQueryParams","DeleteSmsTemplateHeaders","DeleteSmsTemplateRequest","DeleteSmsTemplateResponse","DeleteUserEndpointsPathParams","DeleteUserEndpointsHeaders","DeleteUserEndpointsRequest","DeleteUserEndpointsResponse","DeleteVoiceChannelPathParams","DeleteVoiceChannelHeaders","DeleteVoiceChannelRequest","DeleteVoiceChannelResponse","DeleteVoiceTemplatePathParams","DeleteVoiceTemplateQueryParams","DeleteVoiceTemplateHeaders","DeleteVoiceTemplateRequest","DeleteVoiceTemplateResponse","GetAdmChannelPathParams","GetAdmChannelHeaders","GetAdmChannelRequest","GetAdmChannelResponse","GetApnsChannelPathParams","GetApnsChannelHeaders","GetApnsChannelRequest","GetApnsChannelResponse","GetApnsSandboxChannelPathParams","GetApnsSandboxChannelHeaders","GetApnsSandboxChannelRequest","GetApnsSandboxChannelResponse","GetApnsVoipChannelPathParams","GetApnsVoipChannelHeaders","GetApnsVoipChannelRequest","GetApnsVoipChannelResponse","GetApnsVoipSandboxChannelPathParams","GetApnsVoipSandboxChannelHeaders","GetApnsVoipSandboxChannelRequest","GetApnsVoipSandboxChannelResponse","GetAppPathParams","GetAppHeaders","GetAppRequest","GetAppResponse","GetApplicationDateRangeKpiPathParams","GetApplicationDateRangeKpiQueryParams","GetApplicationDateRangeKpiHeaders","GetApplicationDateRangeKpiRequest","GetApplicationDateRangeKpiResponse","GetApplicationSettingsPathParams","GetApplicationSettingsHeaders","GetApplicationSettingsRequest","GetApplicationSettingsResponse","GetAppsQueryParams","GetAppsHeaders","GetAppsRequest","GetAppsResponse","GetBaiduChannelPathParams","GetBaiduChannelHeaders","GetBaiduChannelRequest","GetBaiduChannelResponse","GetCampaignPathParams","GetCampaignHeaders","GetCampaignRequest","GetCampaignResponse","GetCampaignActivitiesPathParams","GetCampaignActivitiesQueryParams","GetCampaignActivitiesHeaders","GetCampaignActivitiesRequest","GetCampaignActivitiesResponse","GetCampaignDateRangeKpiPathParams","GetCampaignDateRangeKpiQueryParams","GetCampaignDateRangeKpiHeaders","GetCampaignDateRangeKpiRequest","GetCampaignDateRangeKpiResponse","GetCampaignsPathParams","GetCampaignsQueryParams","GetCampaignsHeaders","GetCampaignsRequest","GetCampaignsResponse","GetCampaignVersionPathParams","GetCampaignVersionHeaders","GetCampaignVersionRequest","GetCampaignVersionResponse","GetCampaignVersionsPathParams","GetCampaignVersionsQueryParams","GetCampaignVersionsHeaders","GetCampaignVersionsRequest","GetCampaignVersionsResponse","GetChannelsPathParams","GetChannelsHeaders","GetChannelsRequest","GetChannelsResponse","GetEmailChannelPathParams","GetEmailChannelHeaders","GetEmailChannelRequest","GetEmailChannelResponse","GetEmailTemplatePathParams","GetEmailTemplateQueryParams","GetEmailTemplateHeaders","GetEmailTemplateRequest","GetEmailTemplateResponse","GetEndpointPathParams","GetEndpointHeaders","GetEndpointRequest","GetEndpointResponse","GetEventStreamPathParams","GetEventStreamHeaders","GetEventStreamRequest","GetEventStreamResponse","GetExportJobPathParams","GetExportJobHeaders","GetExportJobRequest","GetExportJobResponse","GetExportJobsPathParams","GetExportJobsQueryParams","GetExportJobsHeaders","GetExportJobsRequest","GetExportJobsResponse","GetGcmChannelPathParams","GetGcmChannelHeaders","GetGcmChannelRequest","GetGcmChannelResponse","GetImportJobPathParams","GetImportJobHeaders","GetImportJobRequest","GetImportJobResponse","GetImportJobsPathParams","GetImportJobsQueryParams","GetImportJobsHeaders","GetImportJobsRequest","GetImportJobsResponse","GetInAppMessagesPathParams","GetInAppMessagesHeaders","GetInAppMessagesRequest","GetInAppMessagesResponse","GetInAppTemplatePathParams","GetInAppTemplateQueryParams","GetInAppTemplateHeaders","GetInAppTemplateRequest","GetInAppTemplateResponse","GetJourneyPathParams","GetJourneyHeaders","GetJourneyRequest","GetJourneyResponse","GetJourneyDateRangeKpiPathParams","GetJourneyDateRangeKpiQueryParams","GetJourneyDateRangeKpiHeaders","GetJourneyDateRangeKpiRequest","GetJourneyDateRangeKpiResponse","GetJourneyExecutionActivityMetricsPathParams","GetJourneyExecutionActivityMetricsQueryParams","GetJourneyExecutionActivityMetricsHeaders","GetJourneyExecutionActivityMetricsRequest","GetJourneyExecutionActivityMetricsResponse","GetJourneyExecutionMetricsPathParams","GetJourneyExecutionMetricsQueryParams","GetJourneyExecutionMetricsHeaders","GetJourneyExecutionMetricsRequest","GetJourneyExecutionMetricsResponse","GetPushTemplatePathParams","GetPushTemplateQueryParams","GetPushTemplateHeaders","GetPushTemplateRequest","GetPushTemplateResponse","GetRecommenderConfigurationPathParams","GetRecommenderConfigurationHeaders","GetRecommenderConfigurationRequest","GetRecommenderConfigurationResponse","GetRecommenderConfigurationsQueryParams","GetRecommenderConfigurationsHeaders","GetRecommenderConfigurationsRequest","GetRecommenderConfigurationsResponse","GetSegmentPathParams","GetSegmentHeaders","GetSegmentRequest","GetSegmentResponse","GetSegmentExportJobsPathParams","GetSegmentExportJobsQueryParams","GetSegmentExportJobsHeaders","GetSegmentExportJobsRequest","GetSegmentExportJobsResponse","GetSegmentImportJobsPathParams","GetSegmentImportJobsQueryParams","GetSegmentImportJobsHeaders","GetSegmentImportJobsRequest","GetSegmentImportJobsResponse","GetSegmentsPathParams","GetSegmentsQueryParams","GetSegmentsHeaders","GetSegmentsRequest","GetSegmentsResponse","GetSegmentVersionPathParams","GetSegmentVersionHeaders","GetSegmentVersionRequest","GetSegmentVersionResponse","GetSegmentVersionsPathParams","GetSegmentVersionsQueryParams","GetSegmentVersionsHeaders","GetSegmentVersionsRequest","GetSegmentVersionsResponse","GetSmsChannelPathParams","GetSmsChannelHeaders","GetSmsChannelRequest","GetSmsChannelResponse","GetSmsTemplatePathParams","GetSmsTemplateQueryParams","GetSmsTemplateHeaders","GetSmsTemplateRequest","GetSmsTemplateResponse","GetUserEndpointsPathParams","GetUserEndpointsHeaders","GetUserEndpointsRequest","GetUserEndpointsResponse","GetVoiceChannelPathParams","GetVoiceChannelHeaders","GetVoiceChannelRequest","GetVoiceChannelResponse","GetVoiceTemplatePathParams","GetVoiceTemplateQueryParams","GetVoiceTemplateHeaders","GetVoiceTemplateRequest","GetVoiceTemplateResponse","ListJourneysPathParams","ListJourneysQueryParams","ListJourneysHeaders","ListJourneysRequest","ListJourneysResponse","ListTagsForResourcePathParams","ListTagsForResourceHeaders","ListTagsForResourceRequest","ListTagsForResourceResponse","ListTemplatesQueryParams","ListTemplatesHeaders","ListTemplatesRequest","ListTemplatesResponse","ListTemplateVersionsPathParams","ListTemplateVersionsQueryParams","ListTemplateVersionsHeaders","ListTemplateVersionsRequest","ListTemplateVersionsResponse","PhoneNumberValidateHeaders","PhoneNumberValidateRequestBodyNumberValidateRequest","PhoneNumberValidateRequestBody","PhoneNumberValidateRequest","PhoneNumberValidateResponse","PutEventsPathParams","PutEventsHeaders","PutEventsRequestBodyEventsRequest","PutEventsRequestBody","PutEventsRequest","PutEventsResponse","PutEventStreamPathParams","PutEventStreamHeaders","PutEventStreamRequestBodyWriteEventStream","PutEventStreamRequestBody","PutEventStreamRequest","PutEventStreamResponse","RemoveAttributesPathParams","RemoveAttributesHeaders","RemoveAttributesRequestBodyUpdateAttributesRequest","RemoveAttributesRequestBody","RemoveAttributesRequest","RemoveAttributesResponse","SendMessagesPathParams","SendMessagesHeaders","SendMessagesRequestBodyMessageRequest","SendMessagesRequestBody","SendMessagesRequest","SendMessagesResponse","SendUsersMessagesPathParams","SendUsersMessagesHeaders","SendUsersMessagesRequestBodySendUsersMessageRequest","SendUsersMessagesRequestBody","SendUsersMessagesRequest","SendUsersMessagesResponse","TagResourcePathParams","TagResourceHeaders","TagResourceRequestBodyTagsModel","TagResourceRequestBody","TagResourceRequest","TagResourceResponse","UntagResourcePathParams","UntagResourceQueryParams","UntagResourceHeaders","UntagResourceRequest","UntagResourceResponse","UpdateAdmChannelPathParams","UpdateAdmChannelHeaders","UpdateAdmChannelRequestBodyAdmChannelRequest","UpdateAdmChannelRequestBody","UpdateAdmChannelRequest","UpdateAdmChannelResponse","UpdateApnsChannelPathParams","UpdateApnsChannelHeaders","UpdateApnsChannelRequestBodyApnsChannelRequest","UpdateApnsChannelRequestBody","UpdateApnsChannelRequest","UpdateApnsChannelResponse","UpdateApnsSandboxChannelPathParams","UpdateApnsSandboxChannelHeaders","UpdateApnsSandboxChannelRequestBodyApnsSandboxChannelRequest","UpdateApnsSandboxChannelRequestBody","UpdateApnsSandboxChannelRequest","UpdateApnsSandboxChannelResponse","UpdateApnsVoipChannelPathParams","UpdateApnsVoipChannelHeaders","UpdateApnsVoipChannelRequestBodyApnsVoipChannelRequest","UpdateApnsVoipChannelRequestBody","UpdateApnsVoipChannelRequest","UpdateApnsVoipChannelResponse","UpdateApnsVoipSandboxChannelPathParams","UpdateApnsVoipSandboxChannelHeaders","UpdateApnsVoipSandboxChannelRequestBodyApnsVoipSandboxChannelRequest","UpdateApnsVoipSandboxChannelRequestBody","UpdateApnsVoipSandboxChannelRequest","UpdateApnsVoipSandboxChannelResponse","UpdateApplicationSettingsPathParams","UpdateApplicationSettingsHeaders","UpdateApplicationSettingsRequestBodyWriteApplicationSettingsRequest","UpdateApplicationSettingsRequestBody","UpdateApplicationSettingsRequest","UpdateApplicationSettingsResponse","UpdateBaiduChannelPathParams","UpdateBaiduChannelHeaders","UpdateBaiduChannelRequestBodyBaiduChannelRequest","UpdateBaiduChannelRequestBody","UpdateBaiduChannelRequest","UpdateBaiduChannelResponse","UpdateCampaignPathParams","UpdateCampaignHeaders","UpdateCampaignRequestBodyWriteCampaignRequest","UpdateCampaignRequestBody","UpdateCampaignRequest","UpdateCampaignResponse","UpdateEmailChannelPathParams","UpdateEmailChannelHeaders","UpdateEmailChannelRequestBodyEmailChannelRequest","UpdateEmailChannelRequestBody","UpdateEmailChannelRequest","UpdateEmailChannelResponse","UpdateEmailTemplatePathParams","UpdateEmailTemplateQueryParams","UpdateEmailTemplateHeaders","UpdateEmailTemplateRequestBodyEmailTemplateRequest","UpdateEmailTemplateRequestBody","UpdateEmailTemplateRequest","UpdateEmailTemplateResponse","UpdateEndpointPathParams","UpdateEndpointHeaders","UpdateEndpointRequestBodyEndpointRequest","UpdateEndpointRequestBody","UpdateEndpointRequest","UpdateEndpointResponse","UpdateEndpointsBatchPathParams","UpdateEndpointsBatchHeaders","UpdateEndpointsBatchRequestBodyEndpointBatchRequest","UpdateEndpointsBatchRequestBody","UpdateEndpointsBatchRequest","UpdateEndpointsBatchResponse","UpdateGcmChannelPathParams","UpdateGcmChannelHeaders","UpdateGcmChannelRequestBodyGcmChannelRequest","UpdateGcmChannelRequestBody","UpdateGcmChannelRequest","UpdateGcmChannelResponse","UpdateInAppTemplatePathParams","UpdateInAppTemplateQueryParams","UpdateInAppTemplateHeaders","UpdateInAppTemplateRequestBodyInAppTemplateRequest","UpdateInAppTemplateRequestBody","UpdateInAppTemplateRequest","UpdateInAppTemplateResponse","UpdateJourneyPathParams","UpdateJourneyHeaders","UpdateJourneyRequestBodyWriteJourneyRequest","UpdateJourneyRequestBody","UpdateJourneyRequest","UpdateJourneyResponse","UpdateJourneyStatePathParams","UpdateJourneyStateHeaders","UpdateJourneyStateRequestBodyJourneyStateRequest","UpdateJourneyStateRequestBody","UpdateJourneyStateRequest","UpdateJourneyStateResponse","UpdatePushTemplatePathParams","UpdatePushTemplateQueryParams","UpdatePushTemplateHeaders","UpdatePushTemplateRequestBodyPushNotificationTemplateRequest","UpdatePushTemplateRequestBody","UpdatePushTemplateRequest","UpdatePushTemplateResponse","UpdateRecommenderConfigurationPathParams","UpdateRecommenderConfigurationHeaders","UpdateRecommenderConfigurationRequestBodyUpdateRecommenderConfiguration","UpdateRecommenderConfigurationRequestBody","UpdateRecommenderConfigurationRequest","UpdateRecommenderConfigurationResponse","UpdateSegmentPathParams","UpdateSegmentHeaders","UpdateSegmentRequestBodyWriteSegmentRequest","UpdateSegmentRequestBody","UpdateSegmentRequest","UpdateSegmentResponse","UpdateSmsChannelPathParams","UpdateSmsChannelHeaders","UpdateSmsChannelRequestBodySmsChannelRequest","UpdateSmsChannelRequestBody","UpdateSmsChannelRequest","UpdateSmsChannelResponse","UpdateSmsTemplatePathParams","UpdateSmsTemplateQueryParams","UpdateSmsTemplateHeaders","UpdateSmsTemplateRequestBodySmsTemplateRequest","UpdateSmsTemplateRequestBody","UpdateSmsTemplateRequest","UpdateSmsTemplateResponse","UpdateTemplateActiveVersionPathParams","UpdateTemplateActiveVersionHeaders","UpdateTemplateActiveVersionRequestBodyTemplateActiveVersionRequest","UpdateTemplateActiveVersionRequestBody","UpdateTemplateActiveVersionRequest","UpdateTemplateActiveVersionResponse","UpdateVoiceChannelPathParams","UpdateVoiceChannelHeaders","UpdateVoiceChannelRequestBodyVoiceChannelRequest","UpdateVoiceChannelRequestBody","UpdateVoiceChannelRequest","UpdateVoiceChannelResponse","UpdateVoiceTemplatePathParams","UpdateVoiceTemplateQueryParams","UpdateVoiceTemplateHeaders","UpdateVoiceTemplateRequestBodyVoiceTemplateRequest","UpdateVoiceTemplateRequestBody","UpdateVoiceTemplateRequest","UpdateVoiceTemplateResponse"]