from .assignment import *
from .assignmentcopy import *
from .assignmentcreation import *
from .assignmentsubmission import *
from .assignmentsubmissioncomment import *
from .assignmentsubmissioncommentcreation import *
from .assignmentsubmissionhistory import *
from .assignmentsubmissionstate_enum import *
from .assignmentsubmissionupdate import *
from .assignmenttype_enum import *
from .classattachmentcreation import *
from .classcreation import *
from .classdetails import *
from .classroles_enum import *
from .classstate_enum import *
from .classupdate import *
from .collection import *
from .collectioncreation import *
from .collectionmodification import *
from .collectionprivacy_enum import *
from .collectiontype_enum import *
from .flaterrorresponse import *
from .flatlocales_enum import *
from .googleclassroomcoursework import *
from .googleclassroomsubmission import *
from .group import *
from .groupdetails import *
from .grouptype_enum import *
from .licensemode_enum import *
from .licensesources_enum import *
from .lmsname_enum import *
from .lticredentials import *
from .lticredentialscreation import *
from .mediaattachment import *
from .mediascoresharingmode_enum import *
from .microsoftgraphassignment import *
from .microsoftgraphsubmission import *
from .organizationinvitation import *
from .organizationinvitationcreation import *
from .organizationroles_enum import *
from .resourcecollaborator import *
from .resourcecollaboratorcreation import *
from .resourcerights import *
from .role_enum import *
from .scorecomment import *
from .scorecommentcontext import *
from .scorecommentcreation import *
from .scorecommentscounts import *
from .scorecommentupdate import *
from .scorecreation import *
from .scorecreationtype_enum import *
from .scoredetails import *
from .scorefork import *
from .scorelicense_enum import *
from .scorelikescounts import *
from .scoremodification import *
from .scoreplayscounts import *
from .scoreprivacy_enum import *
from .scorerevision import *
from .scorerevisioncreation import *
from .scorerevisionstatistics import *
from .scoresource import *
from .scoretrack import *
from .scoretrackcreation import *
from .scoretrackpoint import *
from .scoretrackstate_enum import *
from .scoretracktype_enum import *
from .scoretrackupdate import *
from .scoreviewscounts import *
from .security import *
from .sortdirection_enum import *
from .useradminupdate import *
from .usercreation import *
from .userdetails import *
from .userdetailsadmin import *
from .userpublic import *
from .userpublicsummary import *

__all__ = ["AssignmentCanvas","AssignmentLti","AssignmentMfc","AssignmentStateEnum","Assignment","AssignmentCopy","AssignmentCreationAssigneeModeEnum","AssignmentCreationGoogleClassroom","AssignmentCreationMicrosoftGraph","AssignmentCreationStateEnum","AssignmentCreation","AssignmentSubmission","AssignmentSubmissionComment","AssignmentSubmissionCommentCreation","AssignmentSubmissionHistoryAttachment","AssignmentSubmissionHistory","AssignmentSubmissionStateEnum","AssignmentSubmissionUpdateComments","AssignmentSubmissionUpdate","AssignmentTypeEnum","ClassAttachmentCreationTypeEnum","ClassAttachmentCreation","ClassCreation","ClassDetailsCanvas","ClassDetailsCleverSubjectEnum","ClassDetailsClever","ClassDetailsGoogleClassroom","ClassDetailsGoogleDrive","ClassDetailsIssuesSyncReasonEnum","ClassDetailsIssuesSync","ClassDetailsIssues","ClassDetailsLti","ClassDetailsMfc","ClassDetailsMicrosoftGraph","ClassDetails","ClassRolesEnum","ClassStateEnum","ClassUpdate","CollectionCapabilities","Collection","CollectionCreation","CollectionModification","CollectionPrivacyEnum","CollectionTypeEnum","FlatErrorResponse","FlatLocalesEnum","GoogleClassroomCoursework","GoogleClassroomSubmission","Group","GroupDetails","GroupTypeEnum","LicenseModeEnum","LicenseSourcesEnum","LmsNameEnum","LtiCredentials","LtiCredentialsCreation","MediaAttachmentTypeEnum","MediaAttachment","MediaScoreSharingModeEnum","MicrosoftGraphAssignment","MicrosoftGraphSubmission","OrganizationInvitation","OrganizationInvitationCreation","OrganizationRolesEnum","ResourceCollaborator","ResourceCollaboratorCreation","ResourceRights","RoleEnum","ScoreCommentTypeEnum","ScoreComment","ScoreCommentContext","ScoreCommentCreation","ScoreCommentsCounts","ScoreCommentUpdate","ScoreCreationDataEncodingEnum","ScoreCreation","ScoreCreationTypeEnum","ScoreDetails","ScoreFork","ScoreLicenseEnum","ScoreLikesCounts","ScoreModification","ScorePlaysCounts","ScorePrivacyEnum","ScoreRevision","ScoreRevisionCreationDataEncodingEnum","ScoreRevisionCreation","ScoreRevisionStatistics","ScoreSource","ScoreTrack","ScoreTrackCreation","ScoreTrackPointTypeEnum","ScoreTrackPoint","ScoreTrackStateEnum","ScoreTrackTypeEnum","ScoreTrackUpdate","ScoreViewsCounts","SchemeOAuth2","SortDirectionEnum","UserAdminUpdate","UserCreation","UserDetailsTypeEnum","UserDetails","UserDetailsAdminLicense","UserDetailsAdminTypeEnum","UserDetailsAdmin","UserPublicTypeEnum","UserPublic","UserPublicSummaryTypeEnum","UserPublicSummary"]