// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type Creditcardnumber1Response struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Creditcardnumber1200WildcardString *string
}
