package openapisdk.models.shared;


public enum VersionInboundServicesEnum {
    INBOUND_SERVICE_UNSPECIFIED("INBOUND_SERVICE_UNSPECIFIED"),
    INBOUND_SERVICE_MAIL("INBOUND_SERVICE_MAIL"),
    INBOUND_SERVICE_MAIL_BOUNCE("INBOUND_SERVICE_MAIL_BOUNCE"),
    INBOUND_SERVICE_XMPP_ERROR("INBOUND_SERVICE_XMPP_ERROR"),
    INBOUND_SERVICE_XMPP_MESSAGE("INBOUND_SERVICE_XMPP_MESSAGE"),
    INBOUND_SERVICE_XMPP_SUBSCRIBE("INBOUND_SERVICE_XMPP_SUBSCRIBE"),
    INBOUND_SERVICE_XMPP_PRESENCE("INBOUND_SERVICE_XMPP_PRESENCE"),
    INBOUND_SERVICE_CHANNEL_PRESENCE("INBOUND_SERVICE_CHANNEL_PRESENCE"),
    INBOUND_SERVICE_WARMUP("INBOUND_SERVICE_WARMUP");

    public final String value;

    private VersionInboundServicesEnum(String value) {
        this.value = value;
    }
}
